libraries/achartengine/achartengine/build.xml

Replace it with mapviewbaloons's build.xml

Gut achartengine build.xml

---

app/src/org/commcare/android/database/user/CommCareUserOpenHelper.java
app/src/org/commcare/android/database/user/UserDatabaseUpgrader.java
app/src/org/commcare/android/database/user/models/ACasePreV6Model.java
app/src/org/commcare/android/tasks/DataPullTask.java

Updated database migration for users to support case index relationships.
Added profiling information to support testing purge impact.
Initial profiling indicates that the new algorithm doesn't significantly affect purge times, which are strongly IO/serialization bound.
X-Requested: JavaRosa, CommCare, CommCareAndroid

Extension cases

---

app/src/org/odk/collect/android/widgets/SelectMultiWidget.java

Apply https://github.com/dimagi/opendatakit.collect/pull/51/files to this repo.

Multi select fix

---

app/res/xml/preferences_developer.xml
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
app/src/org/commcare/dalvik/preferences/DeveloperPreferences.java

Not ready for prime-time but  usable for testing

Introduced developer flagged auto-refresh. 

---

app/src/org/commcare/android/cases/AndroidCaseInstanceTreeElement.java
app/src/org/commcare/android/util/AndroidUtil.java
app/src/org/commcare/dalvik/application/CommCareApplication.java

Bugfix for serious predicate evaluation issue where in some circumstances predicates in external instances would merge subsequent predicates rather than perform a union/filter
X-Requested with:
https://github.com/dimagi/javarosa/pull/43

Predicate bugfix

---

app/src/org/commcare/dalvik/activities/MenuGrid.java
app/src/org/commcare/dalvik/activities/MenuList.java

http://manage.dimagi.com/default.asp?157945#878277
Slightly concerned that I'm opening up a can of worms with this, but I don't have a good argument against swiping being equivalent to "back" in as many places as possible.

Make swiping backwards on a list of forms take you to the previous screen

---

app/.classpath
app/project.properties

Addendum to https://github.com/dimagi/commcare-odk/pull/150

Fix build (graphing)

---

app/src/org/commcare/android/framework/CommCareActivity.java

http://manage.dimagi.com/default.asp?157953
Not sure why I limited this to KitKat+ in the first place - looked over the original PR's changes and didn't find anything that's not in API level 14.

Allow swiping on all Android versions

---

app/AndroidManifest.xml

Removed duplicate ODK provider declaritons

Fix for overlapping ODK and CC installs

---

app/src/org/commcare/android/tasks/EntityLoaderTask.java

Improved error reporting when xpath issues are found in filters on entity lists.

Improved error reporting 

---

app/src/org/commcare/android/logic/DetailCalloutListenerDefaultImpl.java
app/src/org/commcare/android/util/DetailCalloutListener.java
app/src/org/commcare/dalvik/activities/EntityDetailActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java

Fix for [159503](http://manage.dimagi.com/default.asp?159503#887208), which crashes in devices that split the screen in the dial activity ("awesome mode").

"Awesome mode" callout crash

---

app/src/org/commcare/android/view/EntityView.java

Small refactoring of the commit [ed59fd7fddc244d05ff31c3a0bbe96e45d66635e](https://github.com/dimagi/commcare-odk/commit/ed59fd7fddc244d05ff31c3a0bbe96e45d66635e), using the utility method to get the stacktrace as a string.

Refactor: Using ExceptionReportTask.getStackTrace utility method

---

app/res/values/colors.xml

Added values for colors based on the new color palette for HQ

names for the colors in the new palette

---

app/src/org/commcare/android/adapters/MenuAdapter.java

Adds a `relevant` attribute to `<menu>` elements in suite.xml

Module filtering

---

app/src/org/commcare/android/util/StringUtils.java

Re-introduced removal of diacritics and case standardization

Fix for string normalization during fuzzy search. 

---

.android_studio_settings/README
.android_studio_settings/codestyles/CommCare Coding Style.xml
.android_studio_settings/inspection/CommCare Inpsection Profile.xml

Setting up project coding style and lint settings for Android Studio.
Fairly confident this is the right approach, but please try it on your local machine before accepting. 
Setup details found in the README or at https://confluence.dimagi.com/display/MD/Code+Conventions

Coding style and insp setttings

---

app/src/org/odk/collect/android/tasks/FormLoaderTask.java

Fixes an issue where when our caching optimization fails and it crashes the app
http://manage.dimagi.com/default.asp?161629#898010

Bugfix: Form Serialization Crash

---

app/src/org/commcare/android/adapters/EntityListAdapter.java
app/src/org/commcare/android/models/Entity.java

Solving [CommCare-161205](http://manage.dimagi.com/default.asp?161205), in which data was not getting sorted correctly.

Making sort by feature work when sortData is null

---

app/src/org/commcare/android/view/EntityDetailView.java
app/src/org/commcare/android/view/EntityView.java
app/src/org/commcare/android/view/GraphView.java

Display an error message instead of crashing on bad data.

Graph error handling

---

app/src/org/odk/collect/android/widgets/StringNumberWidget.java

ticket: http://manage.dimagi.com/default.asp?156920

Fix StringNumberWidget keyboard action

---

app/src/org/commcare/android/view/GraphView.java

Make issues like http://manage.dimagi.com/default.asp?162426 FM-diagnosable

Trap error when data conains NaN

---

app/src/org/odk/collect/android/widgets/QuestionWidget.java

Reapply https://github.com/dimagi/opendatakit.collect/pull/42

Fix for FB#144824

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/widgets/QuestionWidget.java

Reapply https://github.com/dimagi/opendatakit.collect/pull/44

Reapply multiple validation error handling

---

app/src/org/commcare/android/view/GraphView.java

http://manage.dimagi.com/default.asp?156948
Caused by https://github.com/dimagi/commcare-odk/pull/93

Case list graphs getting pushed offscreen

---

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java

Shot in the dark at fixing http://manage.dimagi.com/default.asp?163638

Differentiate between invalidateOptionsMenu & supportInvalidateOptionsMenu

---

app/src/org/commcare/android/adapters/MenuAdapter.java
app/src/org/commcare/android/models/AndroidSessionWrapper.java

Depends on https://github.com/dimagi/commcare/pull/62
Includes menu command ID with Evaluation Context request when filtering modules

Module filter fix

---

app/src/org/commcare/android/cases/AndroidCaseInstanceTreeElement.java
app/src/org/commcare/android/database/SqlStorage.java
unit-tests/src/org/commcare/android/tests/processing/ProcessingTest.java
unit-tests/src/org/commcare/android/tests/queries/CaseDbQueryTest.java
unit-tests/src/org/commcare/android/util/TestUtils.java

Changes to permit tests for case queries that are backed by the sqlstorage shadows.
Tests include
https://github.com/dimagi/commcare/pull/65
So will be broken until it is pulled

Tests for Case instance backed XPath queries

---

app/src/org/commcare/android/adapters/MenuAdapter.java
app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
app/src/org/odk/collect/android/activities/FormEntryActivity.java

Reconcile build

---

app/src/org/commcare/dalvik/activities/InstallArchiveActivity.java
app/src/org/commcare/dalvik/activities/MultimediaInflaterActivity.java
app/src/org/commcare/dalvik/utils/UriToFilePath.java

Tested on 5.1, 4.4.2, 4.2, 2.3.3

Lollipop File Chooser Fix

---

app/src/org/commcare/android/tasks/DataPullTask.java
app/src/org/commcare/android/tasks/ManageKeyRecordTask.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/LoginActivity.java
app/src/org/commcare/dalvik/application/CommCareApplication.java
app/src/org/commcare/dalvik/odk/provider/FormsProvider.java
app/src/org/commcare/dalvik/odk/provider/InstanceProvider.java
app/src/org/commcare/dalvik/services/CommCareSessionService.java
app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/listeners/FormSaveCallback.java

Logging in for the first time fails silently and requires a second login.
This PR fixes that.

First login automatically logs the user out

---

app/src/org/commcare/android/view/TabbedDetailView.java

http://manage.dimagi.com/default.asp?167434

case detail crash fix

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/provider/FormsProvider.java
app/src/org/odk/collect/android/provider/FormsProviderAPI.java
app/src/org/odk/collect/android/provider/InstanceProvider.java
app/src/org/odk/collect/android/provider/InstanceProviderAPI.java
app/src/org/odk/collect/android/tasks/SaveToDiskTask.java

Reverts dimagi/commcare-odk#269

Revert "Removed old odk provider files"

---

app/res/layout/activity_report_problem.xml
app/src/org/commcare/android/models/AndroidSessionWrapper.java
app/src/org/commcare/android/tasks/DataPullTask.java
app/src/org/commcare/android/tasks/ManageKeyRecordTask.java
app/src/org/commcare/android/view/TabbedDetailView.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
app/src/org/commcare/dalvik/activities/LoginActivity.java
app/src/org/commcare/dalvik/application/CommCareApplication.java
app/src/org/commcare/dalvik/odk/provider/FormsProvider.java
app/src/org/commcare/dalvik/odk/provider/InstanceProvider.java
app/src/org/commcare/dalvik/preferences/CommCarePreferences.java
app/src/org/commcare/dalvik/services/CommCareSessionService.java
app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/jr/extensions/IntentCallout.java
app/src/org/odk/collect/android/listeners/FormSaveCallback.java
app/src/org/odk/collect/android/widgets/DecimalWidget.java
app/src/org/odk/collect/android/widgets/IntegerWidget.java
app/src/org/odk/collect/android/widgets/StringNumberWidget.java
app/src/org/odk/collect/android/widgets/StringWidget.java

Figured I'd merge all the 2.21 fixes into master, even though the release isn't done.
Cross-requested with
https://github.com/dimagi/commcare/pull/80
https://github.com/dimagi/javarosa/pull/93

Merging 2.21 into master

---

app/src/org/odk/collect/android/widgets/AudioWidget.java
app/src/org/odk/collect/android/widgets/BarcodeWidget.java
app/src/org/odk/collect/android/widgets/ImageWidget.java
app/src/org/odk/collect/android/widgets/IntentWidget.java
app/src/org/odk/collect/android/widgets/SignatureWidget.java
app/src/org/odk/collect/android/widgets/VideoWidget.java

Removing some code duplication in Button setup for widgets.
Taking the opportunity to lint the Widget classes too.
Doesn't seems to conflict with the restyling branch any more than the master branch.

Widget button setup refactor

---

app/src/org/commcare/android/tasks/ResourceEngineTask.java
app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java

Cleaning up ResourceEngineTask before I work on a feature

Resource engine refactor

---

app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/android/view/EntityView.java
app/src/org/commcare/android/view/GridEntityView.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/views/media/AudioButton.java
app/src/org/odk/collect/android/views/media/AudioController.java
app/src/org/odk/collect/android/widgets/AudioWidget.java

Make audio stop playing during form entry when the user advances to next view.
Also includes two null pointer exception fixes having to do with FormRecordListActivity.

Stop audio from playing on slide to next screen

---

app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
app/src/org/odk/collect/android/activities/FormEntryActivity.java

http://manage.dimagi.com/default.asp?168200

Catch missing fixture

---

app/src/org/commcare/android/view/GraphView.java

Depends on https://github.com/dimagi/commcare/pull/83

Graphing: support legends

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java

Fixing a hard to reproduce Null Pointer Exception

FormEntryActivity Null Pointer Exception fix

---

app/res/layout/component_entity_detail_item.xml
app/src/org/commcare/android/view/AspectRatioLayout.java
app/src/org/commcare/android/view/EntityDetailView.java
app/src/org/commcare/android/view/GraphView.java

Quick implementation of bar graphs to better support mobile UCR.

Bar graphs

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java

Saving on session expiration currently crashes the app if the form being edited violates constraints. This PR just aborts the save if constraints aren't met. We could also attempt to clear violating values and resave, should this be done?
[ticket](http://manage.dimagi.com/default.asp?168163#939208)

Save on session expiration when constraints are violated

---

app/src/org/commcare/android/tasks/DataPullTask.java
app/src/org/commcare/android/tasks/ProcessAndSendTask.java
app/src/org/commcare/dalvik/services/CommCareSessionService.java

Following up on a comment @wpride made on another PR of mine.

Better lock name and a task sequentialization note

---

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java

Pressing the sync button could cause a crash because the session might expire while in an un-wrapped call to checkAndStartUnsentTask.
Fix that.
I wasn't able to reproduce this crash, but the stack trace is found here
http://manage.dimagi.com/default.asp?168135

Wrap a form sync call in try/catch for session expiration check

---

app/src/org/odk/collect/android/views/ODKView.java
app/src/org/odk/collect/android/widgets/QuestionWidget.java
app/src/org/odk/collect/android/widgets/TriggerWidget.java
app/src/org/odk/collect/android/widgets/WidgetFactory.java

Make label text selectable (for copying) during form entry.
[ticket](http://manage.dimagi.com/default.asp?169335)

Make labels copyable

---

app/src/org/commcare/android/view/EntityView.java
app/src/org/commcare/dalvik/geo/EntityOverlayItemFactory.java

http://manage.dimagi.com/default.asp?169125

Support pixel-based case list column widths

---

app/res/layout/connection_diagnostic.xml
app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
app/src/org/commcare/dalvik/activities/FormRecordListActivity.java

Also centering the logo in connection_diagnostic screen.

Adding missing code in FormRecordListActivity (incomplete forms search)

---

app/src/org/odk/collect/android/widgets/IntentWidget.java

Same as https://github.com/dimagi/commcare-odk/pull/332, but for the oldui branch.

Intent layout fix oldui

---

app/src/org/commcare/dalvik/activities/FormRecordListActivity.java

Solving bug [171246](http://manage.dimagi.com/default.asp?171246) in the new UI.

Incomplete forms loading its elements on every refreshView()

---

app/src/org/odk/collect/android/views/media/AudioButton.java
app/src/org/odk/collect/android/views/media/MediaLayout.java
app/src/org/odk/collect/android/widgets/AudioWidget.java

Register onClick with AudioButton so that when it is clicked, the audio playback is triggered.
Also lint and styling changes.

Audio playback button not registered

---

app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/dalvik/activities/CommCareFormDumpActivity.java
app/src/org/commcare/dalvik/activities/CommCareWiFiDirectActivity.java
app/src/org/commcare/dalvik/activities/ConnectionDiagnosticActivity.java
app/src/org/commcare/dalvik/activities/InstallArchiveActivity.java
app/src/org/commcare/dalvik/activities/MultimediaInflaterActivity.java
app/src/org/odk/collect/android/views/media/AudioButton.java

Refactor that mostly removes unused code from CommCareActivity.
Other changes:
- simplification of conditional logic
- rename method to not start with capital letter
- use StringBuilder inside of loop instead of String concatenation

Cleaning up CommCareActivity

---

app/src/org/commcare/xml/CommCareTransactionParserFactory.java
app/src/org/commcare/xml/FormInstanceXmlParser.java

- Comments
- Variable renaming
- Removed unneeded method params
- Change namespace Hashtable to unmodifiableMap 
- Collapse multiple catches with same body into one catch

Minimal FormInstanceXmlParser refactor 

---

app/src/org/odk/collect/android/widgets/TriggerWidget.java
app/src/org/odk/collect/android/widgets/WidgetFactory.java

2.22 version of https://github.com/dimagi/commcare-odk/pull/345

(2.22) Trigger text selectable only when 'appearance' hint is set to 'selectable'

---

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java

I was getting a null pointer exception sometimes upon login. This makes sure the syncButton isn't null before having it invoke methods.
Any ideas as to why it is null sometimes?

On login, check if sync button is null before invoking it.

---

app/src/org/commcare/dalvik/activities/CallLogActivity.java
app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/preferences/PreferencesActivity.java

Same as #339 in the new UI 2.22 branch.

2.22 new UI - Changing managedQuery to CursorLoader

---

app/src/org/commcare/dalvik/activities/CallLogActivity.java
app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/preferences/PreferencesActivity.java

Same as #339 in the old UI 2.22 branch.

2.22 old UI - Changing managedQuery to CursorLoader

---

app/ant.properties

Specifying Java 1.7 in ant.properties

---

app/src/org/commcare/android/view/EntityView.java

Changes added in https://github.com/dimagi/commcare-odk/pull/314 are causing the following bugs:
http://manage.dimagi.com/default.asp?171241
http://manage.dimagi.com/default.asp?171345
Revert just enough of that PR to fix these issues. Not fully reverting because it crosses all three repos and I'm aiming to get this fixed correctly for 2.23.

don't allow pixel-based case list column widths

---

app/src/org/commcare/android/models/AndroidSessionWrapper.java

This is untested, but pretty sure it does the right thing.

AndroidSessionWrapper: Make string equality tests use .equals

---

app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
app/src/org/commcare/dalvik/activities/FormRecordListActivity.java
app/src/org/commcare/dalvik/preferences/CommCarePreferences.java

Restoring query string in search bar for case search screens.

Restore query in case search

---

app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java

2.22 version of https://github.com/dimagi/commcare-odk/pull/378

Ensure reference is valid before continuing install (2.22)

---

app/AndroidManifest.xml

Follow up to https://github.com/dimagi/commcare-odk/pull/381 after realizing that perm already occured

Remove unneeded duplicate permissions

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java

Fixing http://manage.dimagi.com/default.asp?174626.
See also #386.

Long press crash fix

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java

New UI - Long press crash fix

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java

https://github.com/dimagi/commcare-odk/pull/390 for oldui 2.22
cross-requested with newui branch: https://github.com/dimagi/commcare-odk/pull/392

Replace managedQuery/CursorLoader with getContentResolver().query

---

app/src/org/commcare/android/fragments/SetupEnterURLFragment.java

remove URL prep - 2.22

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/views/ODKView.java

Allows labels in repeats, field lists, groups to have markdown formatting
http://manage.dimagi.com/default.asp?174085

markdown for groups, repeats, lists

---

app/src/org/odk/collect/android/widgets/IntentWidget.java

X-Branch fix of https://github.com/dimagi/commcare-odk/pull/395

Fix for Intent Widget duplicate Callout

---

app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java

Fix for the sortby menu not being available again after the adapter loaded.
FogBugz
http://manage.dimagi.com/default.asp?171354#973976

[CommCare 2.22] Fix for Sort By menu

---

unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
unit-tests/src/org/commcare/android/tests/processing/KeyRecordTest.java
unit-tests/src/org/commcare/android/tests/processing/ProcessingTest.java
unit-tests/src/org/commcare/android/util/TestUtils.java
unit-tests/src/resources/forms/placeholder.xml
unit-tests/src/resources/inputs/key_record_create.xml

Regression tests for bugs caught during 2.22 QA

Text Form Bug Regressions

---

app/src/org/commcare/dalvik/activities/EntitySelectActivity.java

Missed a file from previous commit
Fix for
http://manage.dimagi.com/default.asp?171354
Already fixed on newui

[CommCare 2.22] Fix for Sort Issues (again)

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/android/view/EntityDetailView.java

Old UI version of https://github.com/dimagi/commcare-odk/pull/406
...although this isn't exactly a bug, so maybe not necessary, but the PR is created, so what's the harm?

Add translation

---

app/src/org/commcare/android/references/JavaHttpRoot.java
app/src/org/commcare/android/util/AndroidCommCarePlatform.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
app/src/org/commcare/dalvik/application/CommCareApp.java

Misc cleanup of platform and app classes, plus a few other small changes.
Mostly dead code removal and linting.

CommCarePlatform and CommCareApp refactor

---

app/src/org/commcare/android/tasks/VerificationTask.java
app/src/org/commcare/dalvik/activities/CommCareVerificationActivity.java

Just basic linting for activity and task that do user requested media validation

Verification Activity and Task refactor

---

app/src/org/commcare/android/view/EntityView.java

Revert https://github.com/dimagi/commcare-odk/pull/352, which was itself a revert, and fix the actual bug.
@ctsims

Fix case list dimensions

---

app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java

Fixing bug [175330](http://manage.dimagi.com/default.asp?175330).

Fixing install bug when rotating right after scanning a barcode

---

app/res/layout-land/mainnew.xml

Fixing overlap in version string (bug [17006](http://manage.dimagi.com/default.asp?176006)).

Fixing str_version issue

---

app/src/org/odk/collect/android/tasks/FormLoaderTask.java

Close an un-closed cursor, make nested class static, and squash similar catch bodies

FormLoaderTask refactor

---

app/res/layout-land/mainnew.xml

Fixing the second problem mentioned in bug [176006](http://manage.dimagi.com/default.asp?176006).

Adding ScrollView to avoid buttons being cut off from the home screen

---

app/src/org/commcare/xml/AndroidCaseXmlParser.java

Fixed missing storage abstraction for case processing unit tests.

Case unit test fix

---

app/src/org/commcare/android/view/GraphView.java

TDH request. Allow user to specify whether bars should be displayed horizontally (default) or vertically.

Graph orientation

---

app/src/org/commcare/android/view/SquareButtonWithNotification.java
app/src/org/commcare/android/view/SquareButtonWithText.java

To give feedback to users when they click the buttons in the home screen, SquareButtonWithText now shows a bluish color when pressed.

Adding on click effects to SquareButtonWithText

---

build.gradle
settings.gradle

Updated gradle settings to include commcare as a separate project
X-Requested with
https://github.com/dimagi/commcare/pull/105

CommCare Gradle settings

---

app/AndroidManifest.xml
app/proguard.cfg
app/res/layout-land/mainnew_modern.xml
app/res/layout/mainnew_modern.xml
app/res/layout/square_button_notification.xml
app/res/layout/square_button_text.xml
app/src/org/commcare/android/view/SquareButton.java
app/src/org/commcare/android/view/SquareButtonWithNotification.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
build.gradle
debug/org/odk/collect/android/utilities/StethoInitializer.java
release/org/odk/collect/android/utilities/StethoInitializer.java

SquareButton: Fixing issues with the home screen buttons
build.gradle: Specifying proguard config files.
proguard.cfg: Adding configs to keep custom view constructors
AndroidManifest.xml: Removing unnecessary sections
StethoInitializer: Logging which version is currently running (debug/release)

Multiple fixes for the gradle build

---

app/src/org/commcare/android/view/SquareButton.java

Non-stretched buttons in the install screens.

Fixing install screen button issue

---

settings.gradle

Cross-requested with https://github.com/dimagi/javarosa/pull/131

Update gradle settings to work with javarosa harness

---

app/src/org/odk/collect/android/widgets/BarcodeWidget.java

Re: http://manage.dimagi.com/default.asp?178126

fix barcode widget

---

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java

Follow-up to https://github.com/dimagi/commcare-odk/pull/477 that fixes build error

Remove code that references old ui layouts

---

app/AndroidManifest.xml

Fixing bug [177774](http://manage.dimagi.com/default.asp?177774).

Adding READ_CALL_LOG permission in AndroidManifest.xml

---

app/src/org/commcare/android/framework/BreadcrumbBarFragment.java

Solving issue [174033](http://manage.dimagi.com/default.asp?174033).

Including Incomplete/Saved forms in title

---

app/res/layout/fragment_setup_install.xml
app/res/layout/fragment_setup_keepinstall.xml

Wrapping the layouts in ScrollViews so they assume their correct positions in the screen.
Fixes bug [173829](http://manage.dimagi.com/default.asp?173829).

Fixing layout problems in install screens

---

app/AndroidManifest.xml

Solving bug [173822](http://manage.dimagi.com/default.asp?173822).

Preventing login text boxes from getting cut off

---

app/src/org/commcare/dalvik/activities/CommCareFormDumpActivity.java

Solves [174130](http://manage.dimagi.com/default.asp?174130).

Persisting error message across orientation changes in Dump Forms screen

---

app/AndroidManifest.xml
app/res/layout/connection_diagnostic.xml

Fixing [173826](http://manage.dimagi.com/default.asp?173826#991198) by adding a ScrollView to the Activity and setting its windowSoftInputMode to adjustResize.

Small fixes to Connection Test

---

app/src/org/commcare/android/view/GraphView.java

http://manage.dimagi.com/default.asp?178653

Limit pan & zoom to full-screen graphs

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/dalvik/activities/CommCareVerificationActivity.java

Solving [178563](http://manage.dimagi.com/default.asp?178563#991207).

Adding user feedback when multimedia files are validated without errors

---

libraries/achartengine/achartengine/AndroidManifest.xml

Fixing bug [178773](http://manage.dimagi.com/default.asp?178773).

Ensuring achartengine demo won't be installed with ODK

---

app/src/org/commcare/android/tasks/FormRecordCleanupTask.java

Incomplete forms were being saved as complete and not showing up in the incomplete forms listing.
Introduced by me in https://github.com/dimagi/commcare-odk/pull/316

Incomplete forms were being saved as complete

---

app/src/org/commcare/android/models/AndroidSessionWrapper.java

Updated processing to reflect new unified session process from commcare core libs
X-Requested with
https://github.com/dimagi/commcare/pull/130

Updated Processing Code Paths

---

app/src/org/commcare/android/models/AndroidSessionWrapper.java

Applied change from master to oldui branch

Migrated Session Change to Old UI

---

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/LoginActivity.java

Solving bug [178853](http://manage.dimagi.com/default.asp?178853#993131).

Unconditional exit method to CommCareHomeActivity

---

app/res/drawable/divider_case_list_modern.xml
app/res/layout/entity_select_layout.xml
app/res/values-land/dimens.xml
app/res/values/dimens.xml
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java

Solving http://manage.dimagi.com/default.asp?179028.

Dynamic case tiles

---

app/src/org/commcare/dalvik/activities/ReportProblemActivity.java
app/src/org/odk/collect/android/views/media/MediaLayout.java

Fix for http://manage.dimagi.com/default.asp?178867

Fix image resizing bug

---

app/AndroidManifest.xml

http://manage.dimagi.com/default.asp?179320
@dcluna this was removed in https://github.com/dimagi/commcare-odk/pull/453 - why?

Put GraphicalActivity back in manifest

---

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java

Copying over essential changes from: https://github.com/dimagi/commcare-odk/pull/535

using session object's setComputedDatum method

---

app/src/org/commcare/android/database/user/UserSandboxUtils.java
app/src/org/commcare/android/framework/FileServerFragment.java
app/src/org/commcare/android/tasks/SendTask.java
app/src/org/commcare/android/util/FileUtil.java
app/src/org/commcare/dalvik/activities/CommCareWiFiDirectActivity.java

-There were 2 methods in FileUtil.java doing the same thing (deleting a file or directory), and one was slightly wrong because it was not recursive. Consolidate into one method that is recursive and returns a boolean indicating success.
-Fix over-indentation of most of the methods in FileUtil

Consolidate and improve delete method in FileUtil

---

app/src/org/commcare/android/view/GraphView.java

part of http://manage.dimagi.com/default.asp?179685
Multiple people have complained about this, so just increase the default rather than making this configurable.

graphing UI tweaks: thicken lines

---

app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/LoginActivity.java

Custom logos now work again and play nice with screen sizes.

Fix for Custom Logos in New UI

---

app/src/org/commcare/dalvik/activities/LoginActivity.java

Linting & remove need for ```LoginBoxesStatus``` enum

Small LoginActivity refactor

---

app/res/values/dimens.xml
app/src/org/commcare/android/view/GraphView.java
libraries/achartengine/achartengine/src/org/achartengine/chart/AbstractChart.java

Band-aid fix for overlap issue described in http://manage.dimagi.com/default.asp?179685
Before: 
http://manage.dimagi.com/default.asp?pg=pgDownload&pgType=pgFile&ixBugEvent=999788&ixAttachment=44278&sTicket=&sFileName=Screenshot_2015-08-23-10-57-54.png
After:

Fix legend overlapping x labels

---

libraries/achartengine/achartengine/src/org/achartengine/GraphicalActivity.java

Another part of http://manage.dimagi.com/default.asp?179685 - enabling the "back" icon in the action bar.
Code is stolen from CommCareActivity; I don't think a cleaner solution is worth the trouble right now.

Enable back icon & action on full-screen graphs

---

app/src/org/commcare/android/view/GraphView.java

Let's make this function marginally nicer.
@phillipm

if => switch

---

app/src/org/commcare/android/util/CommCareInstanceInitializer.java

Fix typo from https://github.com/dimagi/commcare-odk/pull/560

Fix extends typo in case template PR

---

.gitmodules
app/res/layout-land/mainnew_modern.xml
app/res/layout-land/mainnew_modern_v10.xml
build.gradle
gradlew
gradlew.bat
settings.gradle

Moved Etsy Gridview to be a submodule dependency, due to the published library being fundamentally broken in landscape and applied a fix to the overscroll. 
Also updated gradle config to include the gradlew as recommended by gradle best practices

Fix for Gridview Overscroll

---

app/src/org/commcare/android/util/CommCareInstanceInitializer.java
app/src/org/commcare/android/util/CommCareUtil.java
app/src/org/commcare/dalvik/application/CommCareApplication.java
unit-tests/src/org/commcare/android/util/TestUtils.java

OldUI version of https://github.com/dimagi/commcare-odk/pull/560

OldUI version of "Use a hardcoded template for casedb instances"

---

app/src/org/commcare/android/util/CommCareUtil.java

Add missing TAG field used in changes from https://github.com/dimagi/commcare-odk/pull/586

OldUI: Add missing TAG field

---

build.gradle

OldUI version of https://github.com/dimagi/commcare-odk/pull/595

OldUI: Remove javarosa/commcare android build settings

---

app/res/values/external_strings.xml
app/src/org/commcare/dalvik/application/CommCareApplication.java
build.gradle

2.23 old ui version of https://github.com/dimagi/commcare-odk/pull/592

OldUI 2.23: Make gradle set version number and date

---

app/res/values/external_strings.xml
app/src/org/commcare/dalvik/application/CommCareApplication.java
build.gradle

OldUI version of https://github.com/dimagi/commcare-odk/pull/592

OldUI: Make gradle set version number and date 

---

app/src/org/commcare/android/view/GraphView.java

R&D feature + probably only affecting TDH = don't care about replicating this on the old ui

Parameters incorrect for getTimeChartIntent

---

app/src/org/odk/collect/android/utilities/FileUtils.java

oldui version of https://github.com/dimagi/commcare-odk/pull/608

fix getBitmapScaledToDisplay to never causes OutOfMemory error

---

app/AndroidManifest.xml

Fix for http://manage.dimagi.com/default.asp?181435#1009632

add call log permissions to oldui manifest

---

app/src/org/odk/collect/android/widgets/DateWidget.java

Old UI implementation of 
https://github.com/dimagi/commcare-odk/pull/602

Alternate fix for date issues which stays within Jodatime

---

app/src/org/commcare/android/javarosa/DeviceReportWriter.java
app/src/org/commcare/android/tasks/ExceptionReportTask.java
app/src/org/commcare/android/tasks/LogSubmissionTask.java

Large methods make me sad.
Linting, code reformatting, breaking large methods into a series of smaller helper methods.
Review commit-by-commit

Refactor for LogSubmissionTask and a few other similar files

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/dalvik/activities/EntityDetailActivity.java

http://manage.dimagi.com/default.asp?179685
reviewing without whitespace will hide the AS changes

Translate 'Done' on view-only case list

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/dalvik/activities/EntityDetailActivity.java

Old UI version of https://github.com/dimagi/commcare-odk/pull/621

Translate 'Done' button on case list

---

app/AndroidManifest.xml
build.gradle
libraries/achartengine/build.gradle
settings.gradle

http://manage.dimagi.com/default.asp?181952
Setting achartengine as library (moving https://github.com/dimagi/commcare-odk/commit/6e256b275a62624cf1b91ffee8b818e9559e481c?w=1 to the old ui branch) fixes this.

Update achartengine-related build settings

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/dalvik/activities/EntityDetailActivity.java
app/src/org/odk/collect/android/widgets/DateWidget.java

Merging 2.23 into master again

Merge 2.23

---

app/src/org/commcare/dalvik/application/CommCareApplication.java

Same as https://github.com/dimagi/commcare-odk/pull/633

Fix app initialization logic error, name method better

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/android/view/EntityView.java

this was originally:
https://github.com/dimagi/commcare-odk/pull/287
I'm unclear how this got removed from the code

localizable search highlight colors

---

app/res/layout/mainnew.xml

fix for missing buttons on home screen

---

app/res/values/strings.xml

Adding an attribute under a fake namespace to strings.xml, in order to indicate which strings are translatable

add translatable attribute to strings.xml

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/activities/components/FormNavigationUI.java

http://manage.dimagi.com/default.asp?182741#1018579

Fix issue where user was allowed to swipe past the last question

---

app/AndroidManifest.xml

Mirror the change that is going into 2.23.1 https://github.com/dimagi/commcare-odk/pull/660

Add NFC permission

---

app/AndroidManifest.xml

2.23.1 new ui version of https://github.com/dimagi/commcare-odk/pull/664

Add export attribute to providers

---

app/AndroidManifest.xml

2.23.1 old ui version of https://github.com/dimagi/commcare-odk/pull/664

fix for exported default change

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/activities/FormHierarchyActivity.java
app/src/org/odk/collect/android/adapters/HierarchyListAdapter.java
app/src/org/odk/collect/android/logic/FormHierarchyBuilder.java
app/src/org/odk/collect/android/logic/HierarchyElement.java
app/src/org/odk/collect/android/logic/HierarchyEntryType.java
app/src/org/odk/collect/android/views/HierarchyElementView.java

Includes changes from https://github.com/dimagi/commcare-odk/pull/640 and https://github.com/dimagi/commcare-odk/pull/648
Cross-requested with https://github.com/dimagi/javarosa/pull/166

2.23.1 hotfix: Form hierarchy background color and repeat listing

---

app/src/org/commcare/android/models/AndroidSessionWrapper.java

Small constructor calling changes needed by https://github.com/dimagi/javarosa/pull/168

Support JavaRosa PR for overriding hashCode whenever equals is overridden

---

app/src/org/commcare/android/view/GraphView.java

Played around with this a few weeks ago. Turns out TDH actually wants it released, ideally for 2.24.
Has some formatting changes mixed it, but `?w=1` cleans them up.

Stacked bar graphs

---

app/src/org/odk/collect/android/views/ResizingImageView.java

Release notes: Fix image scaling for "half" resize option
http://manage.dimagi.com/default.asp?179788

Fix half resizing image

---

app/src/org/commcare/dalvik/application/CommCareApplication.java
app/src/org/odk/collect/android/logic/ArchivedFormManagement.java

2.23.2 old ui hotfix version of https://github.com/dimagi/commcare-odk/pull/675
Doesn't include the tests of https://github.com/dimagi/commcare-odk/pull/675, but I manually verified that purge checks work correctly.

2.23.2 old ui hotfix: Saved forms are being purged at incorrect times

---

app/src/org/commcare/dalvik/application/CommCareApplication.java
app/src/org/odk/collect/android/logic/ArchivedFormManagement.java

2.23.2 beta hotfix version of https://github.com/dimagi/commcare-odk/pull/675
Doesn't include the tests of https://github.com/dimagi/commcare-odk/pull/675, but I manually verified that purge checks work correctly.

2.23.2 beta hotfix: Saved forms are being purged at incorrect times

---

app/res/values/strings.xml

Latest odk build isn't allowing installation of 2.24 apps

bump strings.xml to 2.24

---

app/src/org/commcare/android/view/GraphView.java

http://manage.dimagi.com/default.asp?183803
`w=1`

Enlarge graph points

---

app/src/org/commcare/android/models/NodeEntityFactory.java
app/src/org/commcare/android/tasks/DataPullTask.java

Unifies code where variables are loaded. Depends on (one-way, the 175 PR won't break Android without this, it's just for code de-deduplication
https://github.com/dimagi/commcare/pull/175
and also (since I screwed up my branching order)
on 
https://github.com/dimagi/commcare-odk/pull/682
which is much more important, so review that first if you're only gonna do one anyway!

CLI consistency update

---

build.gradle

Linting build.gradle :)
This will require you to launch your sdk manager and downloaded the corresponding updates, but it shouldn't be a big download.

Use the latest support libs

---

build.gradle

Reverts dimagi/commcare-odk#684
Broke the build

Revert "Use the latest support libs"

---

app/assets/locales/messages_ccodk_default.txt
app/res/layout/screen_login.xml
app/src/org/commcare/dalvik/activities/LoginActivity.java

Login screen was always showing "Welcome back! Please log in." even if the user wasn't using an English locale. Expose the string to the translation framework.
Also format XML and remove duplicate login button variable
http://manage.dimagi.com/default.asp?184140

Localize the login welcome message

---

app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java

https://github.com/dimagi/commcare-odk/pull/654 had a bug that was crashing commcare when trying to install a new app. This fixes that.

Fix sms query that limits to date range of messages

---

app/src/org/commcare/android/framework/BreadcrumbBarFragment.java

Fixes issues with persisted case tiles not showing

Fix for case tiles when there are computed datums

---

app/res/layout/grid_menu_layout.xml
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/MenuList.java

Depends on
https://github.com/dimagi/commcare/pull/177

Enabled the grid view menus when requested by the suite file

---

app/src/org/commcare/android/view/GridEntityView.java

Vertical gravity flags on text would overwrite horizontal ones

Grid Text Gravity Bugfix

---

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
app/src/org/odk/collect/android/activities/FormEntryActivity.java

Round II of https://github.com/dimagi/commcare-odk/pull/687
Wrap and show XPathTypeMismatchExceptions to the user for the following crashes:
- https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/3577a187d82959385a56efa8ad896f73 and https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/0bd89ca6c1ee59c8bd156b77f167a947
- https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/4b1244c91dca92cf4f30f7932eebb1e4
- https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/1df2a34b161bab95b0ec777fbe07c587 and https://commcare-acralyzer.cloudant.com/acralyzer/_design/acr …

Show user XPathTypeMismatchExceptions

---

app/AndroidManifest.xml
app/src/org/commcare/android/javarosa/AndroidLogger.java
app/src/org/commcare/android/tasks/ZipTask.java
app/src/org/commcare/dalvik/activities/CommCareFormDumpActivity.java
app/src/org/commcare/dalvik/activities/CommCareWiFiDirectActivity.java

Just some added logging for SD Card Dump and Wifi Direct so we can track/verify if we're losing files anywhere

Sd logging

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/activities/components/ImageCaptureProcessing.java

Copying https://github.com/dimagi/commcare-odk/pull/721 over to 2.24

prevent null pointer exception if getCurrentWidget() returns null

---

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java

See https://github.com/dimagi/commcare-odk/pull/730

Fix where we were never dismissing the alert dialog

---

app/res/layout/custom_alert_dialog.xml

http://manage.dimagi.com/default.asp?185212
Put the buttons inside the scrollable area because I had issues with them disappearing when the ScrollView only contained the TextView. Open to looking at it more if anyone thinks that's important, but i don't think it's a big deal.

Make alert dialog scroll long messages

---

app/src/org/odk/collect/android/activities/FormEntryActivity.java

Form entry font wasn't being updated after returning from preferences menu. This ensures that.
http://manage.dimagi.com/default.asp?184657

Form entry update font size after returning from prefs

---

app/res/layout/custom_alert_dialog.xml

Fix for: http://manage.dimagi.com/default.asp?184634
Increasing the weight given to buttons so they don't get cut off, even in landscape.

Fix for button getting cut-off in dialog

---

app/src/org/commcare/android/framework/CommCareActivity.java

Tested this, and it looks like the lines I've removed (probably) aren't needed. @amstone326 Can you verify?

Refactor: remove unneeded dialog set during onPause

---

app/src/org/commcare/android/net/HttpRequestGenerator.java

2.24 version of https://github.com/dimagi/commcare-odk/pull/770
fix for http://manage.dimagi.com/default.asp?184606

2.24: Allow redirects from http to https

---

app/src/org/commcare/dalvik/activities/EntityDetailActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java

https://github.com/dimagi/commcare-odk/pull/720 but leave in all the text to speech code.

Round 2: Surface refactoring of entity detail and select activities 

---

app/src/org/odk/collect/android/widgets/ImageWidget.java

minor typo introduced by https://github.com/dimagi/commcare-odk/pull/724

ImageWidget typo: use class field, not constructor arg

---

app/src/org/odk/collect/android/widgets/StringWidget.java

See https://github.com/dimagi/commcare-odk/pull/784

Don't allow keyboard suggestions

---

app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/widgets/StringWidget.java

doesn't include disabling of case-list search caching

Merge 2.24.1 changes into master

---

app/src/org/odk/collect/android/widgets/QuestionWidget.java
app/src/org/odk/collect/android/widgets/SelectMultiWidget.java
app/src/org/odk/collect/android/widgets/SelectOneAutoAdvanceWidget.java
app/src/org/odk/collect/android/widgets/SelectOneWidget.java

See 186542
Also removed a function we weren't using
cross https://github.com/dimagi/javarosa/pull/194

Properly respect markdown in select choices, refactor

---

app/src/org/commcare/dalvik/dialogs/PinnedNotificationWithProgress.java

Fix for https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/0e377dddbedd490256bf462c1230b5f7

Array nullity check on pinned notification bar

---

app/assets/graphing/graph.css
app/assets/graphing/graph.js
app/src/org/commcare/android/view/GraphView.java

support chart titles

---

app/AndroidManifest.xml
app/src/org/commcare/dalvik/activities/DeviceDensityActivity.java

Going to use in a CC app I'm building that users can download to help them do image sizing.

Callout for computing a user's device density

---

app/res/layout/entity_item_image.xml

This reverts commit 0ce7f8179489d6aaa7b4a75845c323ecaccae02d.

Revert "Center crop alignment"

---

app/src/org/commcare/android/view/EntityView.java

re: http://manage.dimagi.com/default.asp?187233

move super call below image sizing

---

app/res/xml/preferences_developer.xml
app/src/org/commcare/android/util/MediaUtil.java
app/src/org/commcare/dalvik/preferences/CommCarePreferences.java
app/src/org/commcare/dalvik/preferences/DeveloperPreferences.java
app/src/org/odk/collect/android/views/media/MediaLayout.java

Switch new image inflation setting to being enabled from HQ instead of Developer Preferences

Switch image inflation setting to being enabled from HQ

---

app/assets/graphing/graph.js
app/src/org/commcare/android/view/GraphView.java
app/src/org/commcare/android/view/c3/AxisConfiguration.java
app/src/org/commcare/android/view/c3/Configuration.java
app/src/org/commcare/android/view/c3/DataConfiguration.java

Support graphs that use datetimes for x values.

Time graphs

---

app/assets/graphing/errors.js
app/assets/graphing/graph.css
app/assets/graphing/graph.js
app/src/org/commcare/android/view/GraphView.java

Users shouldn't see this, but it'll make the weird world of developing-javascript-on-android a little easier for developers.

Display js errors

---

app/src/org/commcare/android/framework/EntityDetailFragment.java
app/src/org/commcare/android/framework/EntitySubnodeDetailFragment.java

Move https://github.com/dimagi/commcare-odk/pull/757 to master

Propagate parent detail variables to all child details

---

libraries/mapballoons/android-mapviewballoons/AndroidManifest.xml

Hopefully this allows users who don't have mapping android libs to install our app.
http://manage.dimagi.com/default.asp?182975

Remove map lib dependency

---

app/assets/graphing/graph.js
app/src/org/commcare/android/view/GraphView.java
app/src/org/commcare/android/view/c3/DataConfiguration.java
app/src/org/commcare/dalvik/activities/EntityDetailActivity.java

See https://github.com/dimagi/commcare/pull/202
The legend in the screenshot looks wonky because `line-color` wasn't set - because `bar-color` is point-specific, not series-specific, I don't know what color to draw the legend unless `line-color` is also specified, and C3 doesn't know anything about the bar-specific colors, so it gives the legend an arbitrary color.

Support for bar-color

---

app/assets/graphing/graph.js
app/src/org/commcare/android/view/c3/AxisConfiguration.java
app/src/org/commcare/android/view/c3/Configuration.java
app/src/org/commcare/android/view/c3/DataConfiguration.java

http://manage.dimagi.com/default.asp?186271
Time-based graphs should accept any of these formats:
- YYYY-MM-DD
- YYYY-MM-DD HH:MM:SS
- double representing number of days since the epoch

Graphing: Be more forgiving about time formats

---

app/res/layout/menu_list_item_modern.xml

Center menu list entries

---

app/assets/graphing/graph.js
app/res/anim/grow_shrink.xml
app/res/layout/menu_list_item_modern.xml
app/res/layout/screen_form_entry.xml
app/res/values/colors.xml
app/res/xml/preferences_developer.xml
app/src/org/commcare/android/tasks/ProcessAndSendTask.java
app/src/org/commcare/android/tasks/templates/CommCareTask.java
app/src/org/commcare/android/view/c3/AxisConfiguration.java
app/src/org/commcare/android/view/c3/Configuration.java
app/src/org/commcare/android/view/c3/DataConfiguration.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/RecoveryActivity.java
app/src/org/commcare/dalvik/activities/UpdateUIState.java
app/src/org/odk/collect/android/activities/FormEntryActivity.java
app/src/org/odk/collect/android/activities/components/FormNavigationUI.java

Merge 2.25 changes from last week into master

2.25 back merge

---

app/assets/graphing/graph.js
app/src/org/commcare/android/view/GraphView.java

Stop requiring javascript variable names to be globally unique. Now they only need to be unique within their Configuration class.

Namespace graph vars

---

app/src/org/commcare/android/models/notifications/ProcessIssues.java
app/src/org/commcare/android/tasks/DumpTask.java
app/src/org/commcare/android/tasks/ProcessAndSendTask.java
app/src/org/commcare/android/tasks/SendTask.java
app/src/org/commcare/android/tasks/ZipTask.java

Redoing https://github.com/dimagi/commcare-odk/pull/855 because the merge conflicts were too bad.

Refactor: ProcessAndSendTask

---

app/src/org/commcare/dalvik/activities/LoginActivity.java

http://manage.dimagi.com/default.asp?188508#1053899

persist entered text across rotation on login screen 

---

app/src/org/commcare/android/adapters/ListItemViewStriper.java

http://manage.dimagi.com/default.asp?188505

Have ListItemViewStriper fully implement Parcelable

---

app/src/org/commcare/android/view/c3/DataConfiguration.java

http://manage.dimagi.com/default.asp?188636

Graphing: deprecate bar-sort

---

app/src/org/commcare/android/view/c3/DataConfiguration.java

Courtesy to mWellcare, make it slightly easier for their graphs to transition 2.24 => 2.25

Accept either "triangle" or "triangle-up"

---

app/src/org/commcare/android/view/c3/DataConfiguration.java

http://manage.dimagi.com/default.asp?188911
Before:
After:

Fix boundary series

---

app/src/org/commcare/android/view/c3/AxisConfiguration.java

http://manage.dimagi.com/default.asp?188934
Before:
After:

fix cut off labels for time graphs

---

app/res/layout/choice_dialog_view.xml
app/res/layout/single_dialog_choice_view.xml
app/res/values/dimens.xml

-ListView selector wasn't working; add a selector to the individual buttons instead
-Make target area larger (had to do this with padding because the single_dialog_choice_view wasn't respecting its layout_height parameter; still not sure why)

Small choice dialog fixes

---

app/src/org/odk/collect/android/views/media/MediaLayout.java

QR codes weren't working in field lists. Fix necessary for ICDS
http://manage.dimagi.com/default.asp?188629#1057494

Fix for QR Codes in Field Lists

---

app/src/org/commcare/android/models/logic/FormRecordProcessor.java
app/src/org/commcare/android/view/c3/AxisConfiguration.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
app/src/org/odk/collect/android/widgets/DateWidget.java

cross-requested with https://github.com/dimagi/javarosa/pull/213

2.25 backmerge

---

app/src/org/commcare/android/models/logic/FormRecordProcessor.java

Issue: http://manage.dimagi.com/default.asp?189759
Regression test in PR that targets master: https://github.com/dimagi/commcare-odk/pull/927
Caused by https://github.com/dimagi/commcare-odk/pull/913

Hotfix 2.25.1: Form record process parse failure

---

app/src/org/odk/collect/android/activities/DrawActivity.java

Signature widget was crashing on my phone upon launch. Not sure what was causing it because it looks like it wasn't crashing on 2.25. Regardless this PR addresses the crash.

Signature widget crashing on Android 6

---

app/src/org/commcare/dalvik/activities/FormRecordListActivity.java

fixing build error caused by https://github.com/dimagi/commcare-odk/pull/920/files#diff-42cb099301a39024a6bb5076f457a72fL79

remove useless catch block

---

app/src/org/commcare/android/adapters/MenuAdapter.java
app/src/org/commcare/dalvik/activities/GraphActivity.java

fixes build error caused by https://github.com/dimagi/commcare-odk/pull/920

Post-refactor build fix: remove final qualifier & unneeded catch statement

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/dalvik/activities/CommCareWiFiDirectActivity.java

Strings needed by Carla for new Wi-Fi direct project

add wifi direct strings

---

README.md

Just set up the mobile dev env with @benrudolph today and am updating the docs with some relevant info.

Update setup and test docs in README

---

app/assets/graphing/graph.js
app/src/org/commcare/android/view/c3/DataConfiguration.java

Remove redundant point-style code

---

app/src/org/commcare/android/framework/CommCareActivity.java

Fix for http://manage.dimagi.com/default.asp?190442, which was introduced by https://github.com/dimagi/commcare-odk/pull/932. 
1st commit contains the fix, 2nd commit is just clarifying existing code.

Fix dialog rotation bug

---

app/src/org/commcare/android/adapters/EntityDetailAdapter.java
app/src/org/commcare/android/adapters/EntityListAdapter.java
app/src/org/commcare/android/adapters/EntitySubnodeDetailAdapter.java
app/src/org/commcare/android/framework/BreadcrumbBarFragment.java
app/src/org/commcare/android/framework/EntitySubnodeDetailFragment.java
app/src/org/commcare/android/models/NodeEntityFactory.java
app/src/org/commcare/android/view/EntityDetailView.java
app/src/org/commcare/android/view/EntityView.java
app/src/org/commcare/android/view/TabbedDetailView.java
app/src/org/commcare/dalvik/activities/EntityDetailActivity.java
app/src/org/commcare/dalvik/activities/EntitySelectActivity.java

Ready to review, but need to test a persistent case tile related refactor before it can be merged.
Easiest to review commit-by-commit

Refactor Entity related code

---

app/src/org/commcare/android/database/user/models/AUser.java
app/src/org/odk/collect/android/jr/extensions/CalendaredDateFormatHandler.java

Cross-requested with https://github.com/dimagi/javarosa/pull/224

Remove unused javarosa level methods and classes

---

app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/android/framework/CommCareActivityUIController.java
app/src/org/commcare/android/framework/ManagedUiFramework.java
app/src/org/commcare/android/framework/WithUIController.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/FormAndDataSyncer.java
app/src/org/commcare/dalvik/activities/HomeActivityUIController.java
app/src/org/commcare/dalvik/activities/LoginActivity.java
app/src/org/commcare/dalvik/activities/LoginActivityUIController.java
app/src/org/commcare/dalvik/activities/UpdateActivity.java
app/src/org/commcare/dalvik/activities/UpdateUIController.java

Pre-factoring for PIN password work -- 2 major changes:
1. A CommCareActivity can now utilize *both* the @ManagedUI framework and a UIController. This involved making a CommCareActivityUIController interface, and adjusting the util methods in ManagedUiFramework.java 
2. LoginActivity now uses a ui controller (along with the @ManagedUI annotation that it was already using)

UI controllers work with @ManagedUI + UI controller for login activity

---

app/src/org/odk/collect/android/widgets/LabelWidget.java
app/src/org/odk/collect/android/widgets/ListMultiWidget.java
app/src/org/odk/collect/android/widgets/ListWidget.java
app/src/org/odk/collect/android/widgets/QuestionWidget.java

Fix for http://manage.dimagi.com/default.asp?190325#1069642
Never got markdown support in for this ListWidget type class because I didn't know it existed:
https://confluence.dimagi.com/display/commcarepublic/Advanced+CommCare+ODK+Formatting#AdvancedCommCareODKFormatting-GridView
Ideally these three classes would probably be refactored to share some common ancestor like "AbstractSelectWidget" that would have these helper functions. Not sure that's worthwhile considering how little used they are, for now QuestionWidget is the common ancestor

add markdown to list widgets

---

app/src/org/commcare/android/framework/CommCareActivity.java
app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
app/src/org/commcare/dalvik/activities/HomeActivityUIController.java

When you changed languages in the settings menu the home screen buttons didn't update immediately.
Fix for http://manage.dimagi.com/default.asp?191090

Refresh home buttons when language is changed

---

app/src/org/commcare/android/storage/framework/Persisted.java

Hoping this will help track down a strange reflection crash on ACRA
cross-requested w/ https://github.com/dimagi/javarosa/pull/232

Throw DeserializationException that preserves cause

---

app/src/org/commcare/dalvik/activities/DispatchActivity.java

Complete extra enum serialization change that I started in https://github.com/dimagi/commcare-odk/commit/78fafb1b78e7b72ec6bc0e307d947dc7aab0685c

Store lastLoginMode as LoginMode, not String

---

app/src/org/commcare/android/tasks/DataPullTask.java

cross: https://github.com/dimagi/commcare/pull/245

Report missing and removed cases during sync to device logs

---

app/res/values/strings.xml
app/src/org/commcare/android/fragments/SetupEnterURLFragment.java

Bit.ly install was broken by labeling refactor

fix bitly install

---

app/assets/locales/messages_ccodk_default.txt
app/res/layout/file_server.xml
app/src/org/commcare/android/adapters/WiFiDirectAdapter.java
app/src/org/commcare/dalvik/activities/CommCareWiFiDirectActivity.java

Fixes for:
http://manage.dimagi.com/default.asp?215795
http://manage.dimagi.com/default.asp?215799
http://manage.dimagi.com/default.asp?215938
http://manage.dimagi.com/default.asp?215796

Wifi direct fix

---

app/src/org/commcare/dalvik/activities/CommCareGraphActivity.java
app/src/org/commcare/graph/activities/GraphActivity.java
app/src/org/commcare/graph/activities/GraphActivityStateHandler.java

https://github.com/dimagi/commcare-odk/commit/eb9b482e8882c61e5b501d898b7155422a1286fc#commitcomment-15746250
good point @phillipm

Update method name

---

app/src/org/odk/collect/android/views/media/MediaLayout.java

Fix for http://manage.dimagi.com/default.asp?216180
We need to allow this ImageView to resize itself according to the new scaling rules

setAdjustViewBounds true

---

build.gradle

Just ran into this issue https://github.com/ACRA/acra/issues/354
Looks like ACRA 4.8.1 was released yesterday and addresses it.

ACRA 4.81 has a crucial android 4.4.4 bug fix

---

build.gradle

Get maps loading again.
This only took me 5 hours to figure out :sob: 
http://manage.dimagi.com/default.asp?215939

Don't wrap map api key in quotes

---

app/src/org/commcare/android/view/c3/AxisConfiguration.java

http://manage.dimagi.com/default.asp?216662

Graphing: round decimal label counts

---

app/src/org/commcare/dalvik/activities/EntitySelectActivity.java

Fix for "View on Map" menu entry for location enabled case lists disappearing on screen rotation.
http://manage.dimagi.com/default.asp?217057

Remember map view menu entry

---

app/assets/graphing/graph.js

Error in https://github.com/dimagi/commcare-odk/pull/1064
`setTimeout` will only execute the function once; I want to execute it repeatedly, until the body has size.

setInterval, not setTimeout

---

app/assets/graphing/graph.js

http://manage.dimagi.com/default.asp?217064
Introduced, inadvertently, in https://github.com/dimagi/commcare-odk/pull/1064

Fix graphs getting cut off

---

app/assets/locales/messages_ccodk_default.txt
app/res/layout/wifi_manager.xml

Simple text update to reflect current state of code

simple text update

---

app/src/org/odk/collect/android/views/media/MediaLayout.java

See:
http://manage.dimagi.com/default.asp?217530
http://manage.dimagi.com/default.asp?218317

resize fix

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/dalvik/activities/CallOutActivity.java
app/src/org/odk/collect/android/views/media/MediaLayout.java

2.26.1 PR: https://github.com/dimagi/commcare-odk/pull/1091
2.26.2 PR: https://github.com/dimagi/commcare-odk/pull/1093

Backmerging 2.26.1 and 2.26.2

---

app/res/layout/component_entity_detail_item.xml

http://manage.dimagi.com/default.asp?217336
Not clear why this was only affecting Hindi text.

Fix Hindi text failing to wrap

---

app/src/org/commcare/activities/CommCareHomeActivity.java
app/src/org/commcare/preferences/CommCarePreferences.java
app/src/org/commcare/preferences/DeveloperPreferences.java

See http://manage.dimagi.com/default.asp?220695
cross https://github.com/dimagi/commcare-hq/pull/10683
cc @amstone326 to confirm analytics stuff is moved correctly
cc @amsagoff

Move GridMenu dev preferences to main preferences

---

app/src/org/commcare/views/widgets/GeoPointWidget.java

Form progress wasn't getting updated when location questions were being answered.
http://manage.dimagi.com/default.asp?218955

Update form progress on location question answering

---

app/src/org/commcare/views/widgets/IntentWidget.java

Small refactor and fix for IntentWidget no longer respecting the button-label attribute in the <intent> block

Small refactor, make Widget respect button-label attribute

---

app/res/xml/preferences_developer.xml
app/res/xml/server_preferences.xml

Addresses NPE crash that occurs when the main settings menu is entered.
Follow up to https://github.com/dimagi/commcare-odk/pull/1120

Move grid pref entry to main settings

---

app/src/org/commcare/logging/analytics/GoogleAnalyticsUtils.java

Contains all commits from https://github.com/dimagi/commcare-odk/pull/1069 because it uses a util method that was moved in that PR, so don't merge until that one is. 
The actual changes in this PR are just the most recent commit.

Add project space ID to GA

---

app/src/org/commcare/utils/NepaliDateUtilities.java
unit-tests/src/org/commcare/utils/NepaliDateUtilitiesTests.java

Fix for the problem described in https://github.com/dimagi/commcare-odk/pull/1129

Fix Nepali date casting to account for current timezone

---

app/src/org/commcare/engine/cases/CaseUtils.java
app/src/org/commcare/models/database/user/models/CaseIndexTable.java

Fix for http://manage.dimagi.com/default.asp?221463
Our autopurge was not appropriately cleaning up when an index was removed because a case was removed in an index relationship.

Ensure Case Index table is purged

---

app/src/org/commcare/tasks/DataPullTask.java

Looks like the last sync time wasn't getting stored on successful recovery syncs
Fix for http://manage.dimagi.com/default.asp?209452

Update last sync time on successful recovery

---

app/res/layout/wifi_direct_main.xml

Minor wifi direct fix. Probably just the result of an awkward merge.
Ticket: http://manage.dimagi.com/default.asp?221824#1114479

Wifi Direct Crash

---

app/src/org/commcare/adapters/IncompleteFormListAdapter.java

Fix for incomplete form display when traversing views
ticket:
http://manage.dimagi.com/default.asp?221833

Incomplete Forms Crash Fix

---

app/src/org/commcare/activities/FormEntryActivity.java

Fix crash when user swipes next on a screen which never had more than one question
Ticket: http://manage.dimagi.com/default.asp?222347

Fix for swipe crash on tiny form.

---

app/src/org/commcare/activities/FormEntryActivity.java

ticket: http://manage.dimagi.com/default.asp?222536
needed after this change: https://github.com/dimagi/commcare-odk/pull/1107

Ignore constraints on incomplete save

---

app/src/org/commcare/tasks/DataPullTask.java

Includes commits from https://github.com/dimagi/commcare-odk/pull/1153

light refactoring of DataPullTask

---

app/src/org/commcare/android/nsd/MicroNode.java
app/src/org/commcare/models/database/HybridFileBackedSqlStorage.java
app/src/org/commcare/utils/AndroidStreamUtil.java

Use buffered input stream reading approach. 
Doing so cuts 1mb file load time from 500ms to 250ms on a Nexus 5x.
cross-request: https://github.com/dimagi/javarosa/pull/277

Use buffer for reading input stream to byte array

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/views/QuestionsView.java

fix for http://manage.dimagi.com/default.asp?217534
undoes https://github.com/dimagi/commcare-odk/pull/1080 since this was more appropriately fixed at the QuestionView level

Group name fix

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/views/QuestionsView.java

See https://github.com/dimagi/commcare-odk/pull/1182

227 group fix

---

app/assets/locales/messages_ccodk_default.txt
app/res/drawable/apply_update.xml
app/res/drawable/install_start.xml
app/res/layout-land/update_activity.xml
app/res/layout/update_activity.xml
app/res/xml/preferences_developer.xml
app/src/org/commcare/activities/EntityDetailActivity.java
app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/FormRecordListActivity.java
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/android/logging/ForceCloseLogger.java
app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java
app/src/org/commcare/logging/analytics/GoogleAnalyticsUtils.java
app/src/org/commcare/network/HttpRequestGenerator.java
app/src/org/commcare/preferences/DeveloperPreferences.java
app/src/org/commcare/tasks/LogSubmissionTask.java
app/src/org/commcare/utils/FormUploadUtil.java
app/src/org/commcare/views/EntityView.java
app/src/org/commcare/views/notifications/NotificationMessageFactory.java

Had some conflicts so worth a closer look-over.
Conflicts were in https://github.com/dimagi/commcare-odk/pull/1171 and https://github.com/dimagi/commcare-odk/pull/1181
I checked the relevant files over and everything looks fine

2.27 backmerge

---

app/src/org/commcare/activities/FormAndDataSyncer.java
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
app/src/org/commcare/provider/ExternalApiReceiver.java
app/src/org/commcare/tasks/DataPullTask.java
app/src/org/commcare/tasks/ResultAndError.java
app/src/org/commcare/tasks/SaveToDiskTask.java

Follow-up to request by @wpride : https://github.com/dimagi/commcare-odk/pull/1159#discussion_r58723208

Use ResultAndError to store task results that have error messages

---

app/src/org/commcare/activities/FormAndDataSyncer.java
app/src/org/commcare/activities/RecoveryActivity.java
app/src/org/commcare/network/DataSubmissionEntity.java
app/src/org/commcare/network/EncryptedFileBody.java
app/src/org/commcare/tasks/ProcessAndSendTask.java
app/src/org/commcare/utils/AndroidStreamUtil.java
build.gradle

Re-apply changes from https://github.com/dimagi/commcare-odk/pull/1179 because we accidentally reverted it.

Be less agressive in notifying http submission progress (round II)

---

app/src/org/commcare/models/AndroidSessionWrapper.java
app/src/org/commcare/tasks/FormRecordLoaderTask.java

Move mega-method to the one place it is used.
Make it safer by getting rid of sketch manipulation of current session.
cross-request: https://github.com/dimagi/commcare/pull/279

Move form loader task helper

---

app/src/org/commcare/utils/CommCareExceptionHandler.java

2.27 version of https://github.com/dimagi/commcare-odk/pull/1201

2.27 fix for localization exception notifier

---

app/src/org/commcare/activities/CommCareHomeActivity.java
app/src/org/commcare/activities/EntityMapActivity.java
app/src/org/commcare/activities/EntitySelectActivity.java
app/src/org/commcare/adapters/MenuAdapter.java
app/src/org/commcare/fragments/BreadcrumbBarFragment.java
app/src/org/commcare/models/AndroidSessionWrapper.java
app/src/org/commcare/tasks/FormRecordLoaderTask.java
app/src/org/commcare/utils/EntityDetailUtils.java
build.gradle

cross-request: https://github.com/dimagi/commcare/pull/282

Represent datum data using OO

---

app/src/org/odk/collect/android/jr/extensions/IntentCallout.java

I meant to log these to the server

Log intent callouts to server

---

app/src/org/commcare/activities/MenuGrid.java
app/src/org/commcare/adapters/MenuAdapter.java

fixes issues with using views on grid menus

Fix for places where FormEntry objects should have been marked as Entry objects

---

app/src/org/commcare/activities/MenuList.java
app/src/org/commcare/adapters/MenuAdapter.java

follow up to https://github.com/dimagi/commcare-odk/pull/1222
Fixing some mistakes in this refactor: https://github.com/dimagi/commcare-odk/pull/975

Round II : Fix for places where FormEntry objects should have been marked as Entry objects

---

app/AndroidManifest.xml
app/src/org/commcare/activities/CommCareActivity.java
app/src/org/commcare/activities/CommCareHomeActivity.java
app/src/org/commcare/activities/FormAndDataSyncer.java
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/activities/components/FormNavigationUI.java
app/src/org/commcare/fragments/TaskConnectorFragment.java
app/src/org/commcare/network/HttpRequestGenerator.java
app/src/org/commcare/tasks/DataPullTask.java
app/src/org/commcare/tasks/templates/CommCareTask.java
app/src/org/commcare/views/dialogs/CustomProgressDialog.java

merges 27.1 changes into master

CommCare 2.27.1 Backmerge

---

app/src/org/commcare/views/widgets/GridWidget.java

Fix for http://manage.dimagi.com/default.asp?223603. 
This definitely fixes the problem, but I'm a little concerned by what it might break, since I can't figure out what the reason for having that code in there was in the first place. I don't think this was actually written by any of us, so I'm inclined to make the change unless anyone knows its purpose. 
Before: 
After:

Fix grid widget warning msg being off-screen

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/views/media/MediaLayout.java

Fix for http://manage.dimagi.com/default.asp?224767

Resume inline video where it left off after rotation

---

app/src/org/commcare/activities/components/FormNavigationUI.java

Fix for http://manage.dimagi.com/default.asp?225318
Release Note: Make markdown available in floating labels

Use markdown for floating labels when available

---

app/src/org/commcare/CommCareApplication.java

This will need to make it into whatever apk ICDS uses, so maybe in the next 2.27 hotfix or the 'CommCare Conservative' build
Completes the work started in https://github.com/dimagi/commcare-odk/pull/1205

Launch auto-update using parallel thread pool

---

app/src/org/commcare/CommCareApplication.java
build.gradle
templates/google-services.json

2.27.2 LTS build for ICDS 
Includes following changes applied to a branch made from the `commcaer_2.27.2` tag:
https://github.com/dimagi/commcare-odk/pull/1247
https://github.com/dimagi/commcare-odk/pull/1245
Once merged, I will create a `commcare_2.27.2_lts` tag, make a new 2.27 build off it, verify  it all works, and upload the LTS apk to the play store as a new CommCare LTS app

2.27 LTS fixes

---

app/src/org/commcare/activities/MenuGrid.java
app/src/org/commcare/adapters/GridMenuAdapter.java
app/src/org/commcare/adapters/MenuAdapter.java

Refactor: MenuAdapter

---

scripts/consumer_apps_builder.py

Consumer apps build script update #2

---

app/src/org/commcare/adapters/EntityListAdapter.java
app/src/org/commcare/views/EntityView.java

Fix null pointers introduced by https://github.com/dimagi/commcare-odk/pull/1119.
@phillipm I'm gonna have someone merge this now because I need master to not be crashing in order to work on consumer apps stuff, but want to make sure with you that this is an OK resolution of this.

Checking if detail callout is null before using

---

app/src/org/commcare/views/EntityView.java

Follow up to https://github.com/dimagi/commcare-odk/pull/1267

Log when trying to set extra case list data w/o display info

---

app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/activities/CommCareVerificationActivity.java
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/activities/UpdateActivity.java
app/src/org/commcare/engine/resource/installers/SingleAppInstallation.java
app/src/org/commcare/utils/ConsumerAppsUtil.java
scripts/consumer_apps_builder.py

Consumer apps tweaks

---

scripts/consumer_apps_builder.py

@phillipm Last of the consumer apps-related PRs for now! 😄

Use python util libs for file/dir manipulation in build script

---

app/src/org/commcare/activities/CreatePinActivity.java
app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java
app/src/org/commcare/logging/analytics/GoogleAnalyticsUtils.java
app/src/org/commcare/models/database/user/DemoUserBuilder.java

Add analytics category + util method for reporting usage of specific features, and start with reporting a couple (demo user, PIN creation).

GA method for reporting usage of specific features

---

app/src/org/commcare/graph/view/GraphView.java
app/src/org/commcare/views/EntityDetailView.java

https://github.com/dimagi/commcare-odk/pull/1277/files/7a5e307a32af5bc318f4b83153c818b03cb84c46#r64393918
@phillipm

Split out graphing helper methods

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/components/FormLayoutHelpers.java

Refactor of https://github.com/dimagi/commcare-odk/pull/787 and bug fix for http://manage.dimagi.com/default.asp?227683
🐟 🐟 🐟 review commit-by-commit 🐟 🐟 🐟

Fix group label not restoring after being hidden

---

app/src/org/commcare/activities/CommCareHomeActivity.java
app/src/org/commcare/tasks/FormRecordLoaderTask.java
unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml

cross-request: https://github.com/dimagi/commcare/pull/302

Add relevancy condition to post request

---

app/res/layout/menu_list_item_modern.xml
app/res/values/attrs.xml
app/src/org/commcare/views/ShrinkingLinearLayout.java

Hotfix Branch for CommCare 2.27.3
merges https://github.com/dimagi/commcare-odk/pull/1271 into the LTS revision. Will also include Phillip's background update (automatically, as it was part of the short-lived 2.27.2_lts_only build)

Commcare 2.27.3 menu hotfix

---

app/src/org/commcare/activities/CommCareHomeActivity.java
app/src/org/commcare/activities/MenuBase.java
app/src/org/commcare/activities/MenuGrid.java
app/src/org/commcare/activities/MenuList.java
app/src/org/commcare/android/logging/ForceCloseLogger.java
app/src/org/commcare/logging/XPathErrorLogger.java
app/src/org/commcare/models/AsyncEntity.java
app/src/org/commcare/tasks/SaveToDiskTask.java
app/src/org/commcare/tasks/templates/CommCareTask.java

- Address a logging TODO
- Remove unused imports / class fields
- Move code shared between `MenuGrid` and `MenuList` to a common super class (`MenuBase`)

Make MenuGrid / MenuList subclass same class

---

app/src/org/commcare/activities/AppManagerActivity.java
app/src/org/commcare/activities/CommCareHomeActivity.java
app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/activities/SingleAppManagerActivity.java
app/src/org/commcare/activities/components/ImageCaptureProcessing.java
app/src/org/commcare/adapters/EntityListAdapter.java
app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java
app/src/org/commcare/logging/analytics/GoogleAnalyticsUtils.java
app/src/org/commcare/tasks/TemplatePrinterTask.java
app/src/org/commcare/utils/FileUtil.java
app/src/org/commcare/utils/MediaUtil.java

cross-request: https://github.com/dimagi/commcare/pull/304

Add analytics for features

---

app/src/org/commcare/android/storage/framework/Persisted.java

Refactor Persisted

---

app/src/org/commcare/utils/AndroidUtil.java
unit-tests/src/org/commcare/utils/StaticInjectionTests.java

Hotfix version of https://github.com/dimagi/commcare-odk/pull/1320
cross-request: https://github.com/dimagi/commcare/pull/310
cross-request: https://github.com/dimagi/javarosa/pull/311

2.27.5 hotfix

---

app/src/org/commcare/views/widgets/SpinnerWidget.java

Changed single-select multiple choice widget. 
New behavior: 
-Selected text is empty when widget is first displayed. Submitting answer from this view results in null submission
-On dropdown user can select from all of the options specified in formbuilder
In response to http://manage.dimagi.com/default.asp?229724

Fixed singleselect multi choice widget

---

build.gradle
settings.gradle
unit-tests/src/org/commcare/CommCareTestApplication.java

cross-request: https://github.com/dimagi/commcare/pull/313

Move JavaRosa code into commcare repository

---

app/src/org/commcare/utils/GeoUtils.java

Correctly localize gps dialog strings.
http://manage.dimagi.com/default.asp?230392

Localize odk gps string

---

app/src/org/commcare/models/database/user/UserSandboxUtils.java
app/src/org/commcare/tasks/ManageKeyRecordTask.java

Reviewing is easiest commit-by-commit.

Refactor: make UserKeyRecord migration code use helper methods

---

app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java
app/src/org/commcare/utils/AndroidUtil.java
unit-tests/src/org/commcare/utils/AndroidUtilTest.java

cross-request: https://github.com/dimagi/commcare-core/pull/321

Union is intersection

---

app/src/org/commcare/views/widgets/ListMultiWidget.java
app/src/org/commcare/views/widgets/ListWidget.java
app/src/org/commcare/views/widgets/SelectMultiWidget.java
app/src/org/commcare/views/widgets/SelectOneAutoAdvanceWidget.java
app/src/org/commcare/views/widgets/SelectOneWidget.java

cross-request: https://github.com/dimagi/commcare-j2me/pull/314

Use normal FormIndex.hashCode in widget id computation

---

app/src/org/commcare/activities/AdvancedActionsActivity.java
app/src/org/commcare/activities/CommCareFormDumpActivity.java
app/src/org/commcare/activities/CommCareHomeActivity.java
app/src/org/commcare/activities/CommCareWiFiDirectActivity.java

Fix for http://manage.dimagi.com/default.asp?231306 and http://manage.dimagi.com/default.asp?231600, which were the same bug. Comments in-line as to what fixed the issue

Fix bugs related to showing message after successful form dump or send

---

app/src/org/commcare/tasks/FormRecordCleanupTask.java
app/src/org/commcare/xml/AndroidCaseXmlParser.java
app/src/org/commcare/xml/AndroidTransactionParserFactory.java
app/src/org/commcare/xml/FormInstanceXmlParser.java
app/src/org/commcare/xml/MetaDataXmlParser.java

cross-request: https://github.com/dimagi/commcare-core/pull/328

Refactor: CaseXmlParser

---

app/src/org/commcare/activities/EntitySelectActivity.java

Allow case list to perform a callout when it launches.
Possible Health project wants to test out enabling this feature.
cross-request: https://github.com/dimagi/commcare-core/pull/334

Allow case list to auto-launch search callout

---

app/proguard.cfg

Fix issue that was preventing me from building

keep and dont warn about javax annotations

---

app/src/org/commcare/utils/MediaUtil.java

No functional changes, just refactoring to make this more readable. (There is a suite of tests for this functionality in `ImageInflationTest.java` that is still passing)

Clean up image inflation code

---

app/src/org/commcare/tasks/PurgeStaleArchivedFormsTask.java

Ticket: http://manage.dimagi.com/default.asp?232372
Removes 2.26.4 hotfix to resubmit data

Removed temporary form re-send hotfix code

---

app/src/org/commcare/activities/CommCareHomeActivity.java

Lots of 2.28 ACRA crashes with this one
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.commcare.dalvik/org.commcare.activities.CommCareHomeActivity}: org.commcare.utils.SessionUnavailableException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2790)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
at android.app.ActivityThread.access$900(ActivityThread.java:181)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6117)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at …
```

Handle session expiring when setting up home activity menu

---

app/src/org/commcare/tasks/FormLoaderTask.java

cross-request: https://github.com/dimagi/commcare-core/pull/331

Remove unused locale change and element state change alerts

---

app/src/org/commcare/activities/CommCareActivity.java
app/src/org/commcare/adapters/EntityListAdapter.java

cross-request: https://github.com/dimagi/commcare-core/pull/340

Load text/callout query info from pre-form navigation into session instance

---

app/src/org/commcare/activities/DispatchActivity.java

We've added logic to handle the login redirection bug so we don't need to soft assert it anymore

Remove login redirect soft assert

---

app/src/org/commcare/activities/CommCareHomeActivity.java
app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/HomeActivityUIController.java

2.28 versions of the following PRs:
- https://github.com/dimagi/commcare-android/pull/1405
- https://github.com/dimagi/commcare-android/pull/1403
- https://github.com/dimagi/commcare-android/pull/1408

Hotfix 2.28.4 (Part I): Small fixes for some ACRA crashes & signature widget

---

app/AndroidManifest.xml
app/src/org/commcare/activities/DispatchActivity.java
app/src/org/commcare/activities/UnrecoverableErrorActivity.java

Storage is Corrupt dialog wasn't being shown

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/activities/SyncUIHandling.java
app/src/org/commcare/network/HttpRequestGenerator.java
app/src/org/commcare/tasks/AsyncRestoreHelper.java
app/src/org/commcare/views/dialogs/CustomProgressDialog.java

Reviewing commit-by-commit will explain everything I did.

Small fixes/tweaks to async restore

---

app/src/org/commcare/android/logging/ReportingUtils.java

Merged https://github.com/dimagi/commcare-android/pull/1422 when the test runner was broken. Turns out it broke some tests.

Fix analytics NPE

---

unit-tests/resources/inputs/case_test_db_optimizations.xml
unit-tests/src/org/commcare/android/tests/queries/CaseDbQueryTest.java

Tests for CommCare Core Fix
cross-request: https://github.com/dimagi/commcare-core/pull/351

Tests for Storage Backed Predicate Fix

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/activities/LoginActivity.java

Addresses http://manage.dimagi.com/default.asp?183184 
(screenshots below)

 Improve UX of incorrect pw with existing username when offline

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/views/widgets/GregorianDateWidget.java

- add missing localization keys
- clear month when 'clear' button is pressed
- lint and format calendar prototype code
follow-up to calendar prototype added by https://github.com/dimagi/commcare-android/pull/1289

Calendar prototype fixes

---

app/src/org/commcare/views/widgets/AudioWidget.java
app/src/org/commcare/views/widgets/CommCareAudioWidget.java
app/src/org/commcare/views/widgets/ImageWidget.java
app/src/org/commcare/views/widgets/RecordingFragment.java
app/src/org/commcare/views/widgets/VideoWidget.java
app/src/org/commcare/views/widgets/WidgetFactory.java

Also only make audio widget prototype show up if the string `"prototype"` is part of the appearance attribute.
format and lint audio widget related code
fix for http://manage.dimagi.com/default.asp?234161

Fix audio widget prototype NPE & linting

---

app/src/org/commcare/android/javarosa/PollSensorController.java

Fix for http://manage.dimagi.com/default.asp?234163

Reset location manager if it was unset due to empty providers

---

app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/android/javarosa/PollSensorController.java
app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java
app/src/org/commcare/logging/analytics/GoogleAnalyticsUtils.java
app/src/org/commcare/views/widgets/AudioWidget.java
app/src/org/commcare/views/widgets/CommCareAudioWidget.java
app/src/org/commcare/views/widgets/GregorianDateWidget.java
app/src/org/commcare/views/widgets/ImageWidget.java
app/src/org/commcare/views/widgets/RecordingFragment.java
app/src/org/commcare/views/widgets/VideoWidget.java
app/src/org/commcare/views/widgets/WidgetFactory.java

cross-request: https://github.com/dimagi/commcare-core/pull/357

2.29 backmerge

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/FormEntryActivityUIController.java

Move most UI logic out of `FormEntryActivity` as a means to cut down on the max line count.

UI Controller for FormEntryActivity

---

app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
app/src/org/commcare/android/resource/installers/FileSystemUtils.java
app/src/org/commcare/android/resource/installers/MediaFileAndroidInstaller.java
app/src/org/commcare/engine/references/ArchiveFileReference.java
app/src/org/commcare/engine/references/AssetFileReference.java
app/src/org/commcare/engine/references/JavaFileReference.java
app/src/org/commcare/engine/references/JavaHttpReference.java
app/src/org/commcare/logic/FileReference.java
app/src/org/commcare/models/encryption/ByteEncrypter.java
build.gradle
unit-tests/resources/commcare-apps/update_tests/base_app/profile.ccpr
unit-tests/resources/commcare-apps/update_tests/invalid_update/profile.ccpr
unit-tests/resources/commcare-apps/update_tests/invalid_version/profile.ccpr
unit-tests/resources/commcare-apps/update_tests/update_with_suite_fixture/profile.ccpr
unit-tests/resources/commcare-apps/update_tests/valid_update/profile.ccpr
unit-tests/resources/commcare-apps/update_tests/valid_update_with_multimedia_present/profile.ccpr
unit-tests/resources/commcare-apps/update_tests/valid_update_without_multimedia_present/profile.ccpr
unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.java
unit-tests/src/org/commcare/android/tests/caselist/EntityListCalloutDataTest.java
unit-tests/src/org/commcare/android/util/CaseLoadUtils.java
unit-tests/src/org/commcare/android/util/UpdateUtils.java

Moving refactors from https://github.com/dimagi/commcare-android/pull/1438 into a clean PR.
cross-request: https://github.com/dimagi/commcare-core/pull/375
Lib update changes:
- Android support `24.1.0` -> `24.1.1` https://developers.google.com/android/guides/releases#august_1_-_v94
- Play services `9.2.1` -> `9.4.0` https://developer.android.com/topic/libraries/support-library/revisions.html

Refactoring before demo user work

---

app/src/org/commcare/utils/MediaUtil.java
app/src/org/commcare/views/EntityActionViewUtils.java
unit-tests/src/org/commcare/android/tests/ImageInflationTest.java

Hotfix version of https://github.com/dimagi/commcare-android/pull/1459, pared down to include only the fix for the case list action item images

2.29 respect bounds exactly fix

---

app/src/org/commcare/android/javarosa/IntentCallout.java

Allows callouts to video players to work per http://manage.dimagi.com/default.asp?233491

add hack for playing video in callout

---

app/src/org/commcare/utils/ConnectivityStatus.java

Updates connectivity status check to match best practice from
https://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html#DetermineType

Fix for Connectivity status check

---

app/src/org/commcare/activities/QueryRequestActivity.java
build.gradle
unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java

cross-request: https://github.com/dimagi/commcare-core/pull/379

Keep ordering info on case search user query prompts

---

app/src/org/commcare/activities/EntitySelectActivity.java
app/src/org/commcare/adapters/EntityListAdapter.java

cross-request: https://github.com/dimagi/commcare-core/pull/381

Extend case list actions to allow for relevancy condition

---

app/res/xml/preferences_developer.xml
app/src/org/commcare/activities/UpdateActivity.java
app/src/org/commcare/preferences/DeveloperPreferences.java

@ctsims Proposed solution for offline update security concerns - only show the offline update option if we are logged in, or in debug mode

Change accessibility to offline update

---

app/src/org/commcare/provider/InstanceProvider.java

see https://github.com/dimagi/commcare-core/pull/393

remove invalid storage structure reference

---

app/src/org/commcare/tasks/ProcessAndSendTask.java

fixes http://manage.dimagi.com/default.asp?236251

Purge form records that update a non-existant case

---

app/src/org/commcare/activities/UpdateActivity.java

Never actually tested this without a connection :(

Make update from .ccz actually work without network connection

---

app/res/xml/commcare_preferences.xml
app/res/xml/preferences_developer.xml
app/src/org/commcare/activities/EntitySelectActivity.java
app/src/org/commcare/activities/UpdateActivity.java
app/src/org/commcare/engine/resource/ResourceInstallUtils.java
app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java
app/src/org/commcare/preferences/CommCarePreferences.java
app/src/org/commcare/preferences/DeveloperPreferences.java
app/src/org/commcare/provider/RefreshToLatestBuildReceiver.java
app/src/org/commcare/tasks/ProcessAndSendTask.java

cross-request: https://github.com/dimagi/commcare-core/pull/400

Backmerge 2.30

---

app/src/org/commcare/activities/EntitySelectActivity.java
app/src/org/commcare/fragments/EntitySubnodeDetailFragment.java
app/src/org/commcare/models/Entity.java
app/src/org/commcare/models/NodeEntityFactory.java
app/src/org/commcare/tasks/EntityLoaderListener.java
app/src/org/commcare/tasks/EntityLoaderTask.java

cross-request: https://github.com/dimagi/commcare-core/pull/397
@ctsims This is currently targeting 2.30, but if it seems like a little bit much to add last minute, we can leave the existing implementation for now, and put this into master. Just let me know.

Use detail's <focus> element to set focus in entity list

---

app/src/org/commcare/logic/FormController.java
app/src/org/commcare/views/QuestionsView.java

Needed for live preview
cross-request: https://github.com/dimagi/commcare-core/pull/410

Move getQuestionPrompts into FormEntryController

---

build.gradle
unit-tests/resources/robolectric.properties
unit-tests/src/org/commcare/android/CommCareTestRunner.java

Android Studio 2.2 was released and is full of lots of good stuff.
Not sure if this will require us all to be on Android Studio 2.2 or not.
I think this will require you to install set Java 8 as your default version of java
Update to Android 7: https://developer.android.com/about/versions/nougat/android-7.0.html
Update Robolectric to use Android SDK 23
Update Zxing: https://github.com/zxing/zxing/releases/tag/zxing-3.3.0
Update SQLCipher: https://discuss.zetetic.net/t/sqlcipher-for-android-3-5-4-release/1676
Update play services: https://developers.google.com/android/guides/releases
Update google support library: https://developer.android.com/topic/libraries/support-library/revisions.html

Update to Android Studio 2.2

---

app/src/org/commcare/utils/FileUtil.java
app/src/org/commcare/views/widgets/ImageWidget.java
app/src/org/commcare/views/widgets/QuestionWidget.java

Fix for http://manage.dimagi.com/default.asp?238084

Call checkFileSize on the correct image

---

app/res/layout/http_request_layout.xml

Fix display of claim query error messages

---

app/res/layout/app_title_view.xml

Fix for http://manage.dimagi.com/default.asp?238031

Fix justification of long titles in app manager

---

app/src/org/commcare/activities/CreatePinActivity.java

Follow-up fix to changes made in https://github.com/dimagi/commcare-android/pull/1519

Don't hide pin keyboard

---

app/src/org/commcare/activities/FormAndDataSyncer.java
app/src/org/commcare/activities/LoginActivity.java

cross-request: https://github.com/dimagi/commcare-core/pull/436

Use same password for all ccz demo users

---

app/assets/locales/android_startup_strings.txt
app/assets/locales/android_translatable_strings.txt
app/assets/locales/messages_ccodk_default.txt
app/src/org/commcare/CommCareApplication.java

Addresses http://manage.dimagi.com/default.asp?239390
First commit is just clean-up of `CommCareApplication`

Create not translatable strings file

---

app/src/org/commcare/tasks/DataPullTask.java

This reverts commit 6d4059e6a98b330aa85978f61e80316a7bbc7e36.

Revert "add back method required by implementing interface"

---

app/res/layout/geo_progress.xml
app/src/org/commcare/activities/GeoPointActivity.java
app/src/org/commcare/views/dialogs/GeoProgressDialog.java

The dialog for location capture in forms was still using the old dialog style. If anyone knows of other lingering instances of this, let me know please! It's so ugly 😬 
Old:
New:

Modernize style of location capture dialog

---

app/src/org/commcare/models/AsyncNodeEntityFactory.java
unit-tests/src/org/commcare/CommCareTestApplication.java
unit-tests/src/org/commcare/android/tests/caselist/EntityListCacheIndexTest.java

Contains https://github.com/dimagi/commcare-android/pull/1547, will split out if that isn't merged soon
Updates the CommCareTestApplication to check that all asynchronous activities have not crashed. RoboElectric would fail silently if an exception occurred off the main thread.

RoboElectric catch async exceptions

---

app/assets/locales/messages_ccodk_default.txt
app/res/layout/screen_login.xml
app/res/values/strings.xml
app/src/org/commcare/activities/LoginActivityUIController.java
app/src/org/commcare/preferences/CommCarePreferences.java
app/src/org/commcare/views/PasswordShow.java

LTS version of https://github.com/dimagi/commcare-android/pull/1569

Feature flag to allow showing password text (CommCare LTS 2.27)

---

app/src/org/commcare/utils/DummyResourceTable.java

cross-request: https://github.com/dimagi/commcare-core/pull/464

Provide more specific app upgrade failure stacktraces

---

app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java
app/src/org/commcare/engine/cases/AndroidLedgerInstanceTreeElement.java

cross-request: https://github.com/dimagi/commcare-core/pull/471

Don't confuse union with intersection... again

---

app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/network/HttpRequestGenerator.java

Version of https://github.com/dimagi/commcare-android/pull/1567 for CommCare LTS 2.27

Include IMEI in key fetch URL (CommCare 2.27 LTS)

---

app/assets/locales/android_startup_strings.txt
app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/tasks/RetrieveParseVerifyMessageTask.java

Changes requested by UW: https://trello.com/c/xXyqeTuW/174-uw-change-sms-install-workflow
Also change install text generally to remove the notion of "app resources"

SMS install refactor

---

app/src/org/commcare/activities/SyncCapableCommCareActivity.java

@wpride The simplification I tried to make here after talking with you actually doesn't work for all cases, so need to revert. I can explain more in person if you want, it's a little hard to write out.

Go back to checking for all possible ProcessAndSendTask ids

---

app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/activities/UpdateActivity.java
app/src/org/commcare/android/nsd/MicroNode.java
app/src/org/commcare/fragments/SelectInstallModeFragment.java

Lets users do an offline update against a local micronode, but only if they manually trigger it in the activity for now for safety/security reasons

Enable manual updates to new app versions from locally hosted micronodes

---

app/src/org/commcare/adapters/GridMenuAdapter.java

Assume that if the badge text evaluates to 0, we don't want to show the badge at all

Don't show badge if text evaluates to 0

---

app/res/layout/action_card.xml

Fix for http://manage.dimagi.com/default.asp?243657
**Before:**
**After (if text stays on 1 line):**
**After (if text goes onto 2nd line):**

Fix text overlapping button on action view card

---

build.gradle

run with ./gradlew downloadLicenses

Add license reporting plugin

---

app/src/org/commcare/android/logging/ReportingUtils.java

Should help us figure out http://manage.dimagi.com/default.asp?244099

Never crash hard if we can't get the appId

---

app/src/org/commcare/activities/FormEntryActivityUIController.java
app/src/org/commcare/activities/FormHierarchyActivity.java
app/src/org/commcare/activities/HomeScreenBaseActivity.java
app/src/org/commcare/activities/components/ImageCaptureProcessing.java
app/src/org/commcare/adapters/IncompleteFormListAdapter.java
app/src/org/commcare/adapters/SquareButtonAdapter.java
app/src/org/commcare/engine/resource/installers/SingleAppInstallation.java
app/src/org/commcare/interfaces/FormSaveCallback.java
app/src/org/commcare/interfaces/RuntimePermissionRequester.java
app/src/org/commcare/logic/FormHierarchyBuilder.java
app/src/org/commcare/models/database/HybridFileBackedSqlStorage.java
app/src/org/commcare/models/database/HybridFileBackedStorageIterator.java
app/src/org/commcare/models/database/user/models/CaseIndexTable.java
app/src/org/commcare/network/SimpleGetRequest.java
app/src/org/commcare/tasks/FormRecordLoadListener.java
app/src/org/commcare/tasks/FormRecordLoaderTask.java
app/src/org/commcare/tasks/ManageKeyRecordTask.java
app/src/org/commcare/utils/EntityDetailUtils.java
app/src/org/commcare/utils/EntitySelectRefreshTimer.java
app/src/org/commcare/utils/UriToFilePath.java
app/src/org/commcare/views/CustomButtonWithText.java
app/src/org/commcare/views/widgets/GeoPointWidget.java
app/src/org/commcare/views/widgets/ListMultiWidget.java
unit-tests/src/org/commcare/android/tests/DataPullTaskTest.java

Get rid of some of the TODOs I've added over time that nobody is ever going find useful going forward

Remove unneeded TODOs and add some class-level comments

---

app/res/layout/menu_grid_item.xml
app/res/layout/menu_list_item_modern.xml
app/res/values/dimens.xml
app/res/values/styles.xml
app/src/org/commcare/activities/FormAndDataSyncer.java
app/src/org/commcare/activities/RecoveryActivity.java
app/src/org/commcare/activities/SyncCapableCommCareActivity.java
app/src/org/commcare/adapters/GridMenuAdapter.java
app/src/org/commcare/adapters/MenuAdapter.java
app/src/org/commcare/interfaces/UiLoadedListener.java
app/src/org/commcare/provider/ExternalApiReceiver.java
app/src/org/commcare/tasks/FormSubmissionProgressBarListener.java
app/src/org/commcare/tasks/ProcessAndSendTask.java
app/src/org/commcare/views/EntityActionViewUtils.java

This PR ties up 2 loose ends that were left after my first round of dev work for the Pluscare UI changes:
1. Make the form submission progress bar and the sync animations persist on rotation
2. Make module badges show in list mode as well as grid (fyi @ctsims on the screenshot):

Pluscare tech debt

---

app/src/org/commcare/activities/components/FormEntryInstanceState.java
app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java
app/src/org/commcare/models/database/user/models/CaseIndexTable.java
app/unit-tests/src/org/commcare/android/tests/queries/CaseDbQueryTest.java
app/unit-tests/src/org/commcare/android/util/TestUtils.java

cross-request: https://github.com/dimagi/commcare-core/pull/508

Implementaiton of selected() optimizations on android for index queries

---

app/build.gradle

...Taking up the mantle from Phillip with these.

Update robolectric, acra, and google play services libs

---

app/unit-tests/src/org/commcare/models/database/StoreFixturesOnFilesystemTests.java

cross-request: https://github.com/dimagi/commcare-core/pull/510

Merge IStorageUtility with IStorageUtilityIndexed

---

app/src/org/commcare/adapters/ComboboxAdapter.java

Fix for http://manage.dimagi.com/default.asp?246453

2.33 Combobox fix

---

app/src/org/commcare/activities/GeoPointActivity.java
app/src/org/commcare/activities/components/FormEntryInstanceState.java
app/src/org/commcare/adapters/ComboboxAdapter.java
app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java
app/src/org/commcare/models/database/user/models/CaseIndexTable.java
app/unit-tests/src/org/commcare/android/tests/queries/CaseDbQueryTest.java
app/unit-tests/src/org/commcare/android/util/TestUtils.java

cross-request: https://github.com/dimagi/commcare-core/pull/513

Backmerge commcare 2.33

---

app/src/org/commcare/activities/HomeScreenBaseActivity.java

Fixes http://manage.dimagi.com/default.asp?246479

Fix for session state sticking around after error

---

app/src/org/commcare/utils/DummyResourceTable.java

cross-request: https://github.com/dimagi/commcare-core/pull/514
The CommCareInstance interface was only being implemented by CommCarePlatform, YAGNI

remove commcareinstance

---

app/assets/locales/android_translatable_strings.txt
app/res/values/strings.xml

remove 'NEW' text from latest saved state option

---

app/AndroidManifest.xml

Force full-screen graphs to landscape mode

---

app/src/org/commcare/logging/AndroidLogger.java
app/src/org/commcare/provider/InstanceProvider.java
app/src/org/commcare/tasks/ProcessAndSendTask.java
app/src/org/commcare/utils/FormUploadUtil.java
app/src/org/commcare/utils/StorageUtils.java

Re: http://manage.dimagi.com/default.asp?247810#1289890
cc @snopoke

Better logging around form submission and completion

---

app/src/org/commcare/views/widgets/GregorianDateWidget.java

@ctsims updated here. Confirmed this still fixes the initial error reported by Cory but not clear what these setFocuses are meant to address - let me know if there's a specific condition I should be checking.

re-add setFocus to invalid conditions

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/components/FormEntryDialogs.java

Fix for http://manage.dimagi.com/default.asp?247973

Dismiss keyboard when user exists form entry

---

app/src/org/commcare/views/Combobox.java
app/src/org/commcare/views/widgets/ComboboxWidget.java

Reverts commit 08dc3c52fe4c7d44e7b137fbd29afa92a09e9cec. Fix for https://manage.dimagi.com/default.asp?248507

Revert change to fillInPreviousAnswerChoice() for Combobox

---

app/res/layout/menu_list_item_modern.xml

Fixes https://manage.dimagi.com/default.asp?248138
I *think* this will always do the right thing, still reasoning out all the logic

match_parent

---

app/AndroidManifest.xml
app/src/org/commcare/graph/activities/GraphActivity.java

https://github.com/dimagi/commcare-android/commit/893a77df3add42e6038265f79d3e816982bbe0ae#commitcomment-21165119
@amstone326

Move full screen graph orientation into code

---

app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
app/src/org/commcare/engine/resource/AndroidResourceManager.java
app/src/org/commcare/engine/resource/AndroidResourceTable.java
app/src/org/commcare/tasks/ResourceEngineTask.java
app/src/org/commcare/tasks/UpdateTask.java
app/src/org/commcare/tasks/VerificationTask.java
app/src/org/commcare/utils/AndroidCommCarePlatform.java
app/src/org/commcare/utils/DummyResourceTable.java

Backports https://github.com/dimagi/commcare-android/pull/1309 From 2.28 to CommCare LTS on 2.27
cross-request: https://github.com/dimagi/commcare-core/pull/532

Lts backport installer update

---

app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/activities/ConnectionDiagnosticActivity.java
app/src/org/commcare/preferences/CommCareServerPreferences.java
app/src/org/commcare/tasks/LogSubmissionTask.java
app/src/org/commcare/utils/CommCareUtil.java

https://manage.dimagi.com/default.asp?249286

Allow app to submit to a separate logging endpoint

---

app/src/org/commcare/activities/UpdateActivity.java

Prompted by https://manage.dimagi.com/default.asp?248119, where Ray was requesting to be able to see when users have updated to new app versions via the device logs. Seemed harmless to add it so just went for it.

Log all app updates 

---

app/res/xml/preferences_developer.xml
app/src/org/commcare/models/AndroidClassHasher.java
app/src/org/commcare/models/database/AndroidTableBuilder.java
app/src/org/commcare/models/database/SqlStorage.java
app/src/org/commcare/models/database/user/models/AndroidCaseIndexTable.java
app/src/org/commcare/models/database/user/models/EntityStorageCache.java
app/src/org/commcare/preferences/DeveloperPreferences.java
app/src/org/commcare/xml/AndroidBulkCaseXmlParser.java
app/src/org/commcare/xml/AndroidTransactionParserFactory.java
app/unit-tests/src/org/commcare/android/tests/queries/CaseDbQueryTest.java
app/unit-tests/src/org/commcare/android/util/TestUtils.java

reduces amount of time to process 20k transactions on my phone from around 3 minutes to about 30 seconds.
cross-request: https://github.com/dimagi/commcare-core/pull/537

Enable Bulk Processing Restore Data

---

app/res/xml/preferences_developer.xml
app/src/org/commcare/network/HttpRequestGenerator.java
app/src/org/commcare/preferences/DeveloperPreferences.java
app/src/org/commcare/utils/CredentialUtil.java
app/unit-tests/src/org/commcare/utils/CredentialUtilTest.java

minor change to add capacity to wrap plaintext to obfuscate as requested externally.

PW Obfuscation

---

app/src/org/commcare/activities/FormAndDataSyncer.java
app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
app/src/org/commcare/network/DataPullRequester.java
app/src/org/commcare/network/DataPullResponseFactory.java
app/src/org/commcare/network/HttpRequestGenerator.java
app/src/org/commcare/network/LocalReferencePullResponseFactory.java
app/src/org/commcare/network/mocks/LocalFilePullResponseFactory.java
app/src/org/commcare/provider/ExternalApiReceiver.java
app/src/org/commcare/tasks/DataPullTask.java
app/unit-tests/src/org/commcare/android/tests/DataPullTaskTest.java

As requested by: http://manage.dimagi.com/default.asp?248247#1299915 gives additional metadata to HQ to use when fulfilling sync requests.

Submit User ID and device ID with sync requests

---

app/src/org/commcare/suite/model/graph/Graph.java
app/src/org/commcare/suite/model/graph/XYSeries.java

Fixes https://manage.dimagi.com/default.asp?248652 and another bug where bar graphs with no entries would not appear
@orangejenny one proposed solution

Graphing Fix

---

app/src/org/commcare/suite/model/graph/Graph.java

fix for when graph Y is null

---

app/AndroidManifest.xml
app/res/xml/preferences_developer.xml
app/src/org/commcare/activities/CommCareHomeActivity.java
app/src/org/commcare/preferences/DeveloperPreferences.java

LTS Point Release Request from Saket - allow hiding the report issue button

allow apps to hide the 'report issue' button

---

app/src/org/commcare/graph/view/c3/DataConfiguration.java
app/unit-tests/src/org/commcare/android/tests/queries/LedgerDbQueryTest.java

Back-merges the changes made in 2.35.1 and 2.35.2 (2.35.3 was already in master before we did the hotfix)
cross-request: https://github.com/dimagi/commcare-core/pull/555

Backmerge 2.35 hotfixes

---

app/src/org/commcare/activities/CommCareGraphActivity.java
app/src/org/commcare/google/services/analytics/GoogleAnalyticsFields.java
app/src/org/commcare/google/services/analytics/GoogleAnalyticsUtils.java
app/src/org/commcare/graph/activities/GraphActivityStateHandler.java
app/src/org/commcare/graph/view/GraphView.java

For Neal, Rashmi, et. al.'s mobile performance graphing push

Add Google Analytics to graph usage

---

app/src/org/commcare/preferences/DeveloperPreferences.java

This is what you get for not testing small changes... Iterating through the indices doesn't work because as you remove them, the indices of the remaining ones change.

Fix prefs hiding

---

app/res/xml/provider_paths.xml
app/src/org/commcare/utils/FileUtil.java
app/src/org/commcare/views/media/MediaLayout.java

Fixes https://manage.dimagi.com/default.asp?252781

Prevent crash on callout to video player in Android N

---

app/AndroidManifest.xml
app/assets/locales/android_translatable_strings.txt
app/build.gradle
app/src/org/commcare/activities/EntitySelectActivity.java
app/src/org/commcare/activities/components/EntitySelectCalloutSetup.java
app/src/org/commcare/android/javarosa/IntentCallout.java
app/src/org/commcare/views/widgets/IntentWidget.java
app/unit-tests/resources/commcare-apps/case_list_lookup/suite.xml
app/unit-tests/src/org/commcare/android/tests/caselist/EntityListCalloutDataTest.java

cross-request: https://github.com/dimagi/commcare-core/pull/559

Simprints updates

---

app/assets/locales/android_startup_strings.txt
app/res/layout/user_get_available_apps.xml
app/res/values/strings.xml
app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/activities/InstallFromListActivity.java

Added "(NEW!)" to the option in the options menu, and added prompt text to the auth screen.

Make Install-from-list slightly more discoverable

---

app/src/org/commcare/activities/EntityDetailActivity.java

cross-request: https://github.com/dimagi/commcare-core/pull/561

Don't derive print template twice

---

app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/activities/InstallFromListActivity.java

- Start app install automatically after an app is selected from the list
- Check for connectivity before making the request, and show a useful error message if not

More install-from-list improvements

---

app/AndroidManifest.xml
app/res/values/strings.xml

cross-request: https://github.com/dimagi/commcare-core/pull/562

bump version to 2.37

---

app/assets/locales/android_startup_strings.txt
app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/activities/AppManagerAdvancedSettings.java
app/src/org/commcare/preferences/DeveloperPreferences.java

Addresses https://manage.dimagi.com/default.asp?253960

Add mobile privilege claiming to developer prefs options menu

---

app/res/layout/user_get_available_apps.xml
app/src/org/commcare/activities/InstallFromListActivity.java

Fixes https://manage.dimagi.com/default.asp?254505 and https://manage.dimagi.com/default.asp?254502, plus a few other improvements:
- use a scroll view for the auth view so that everything can be seen when in landscape mode
- scroll to the error message when it pops up
- clear any entered text from the auth fields when returning from list view

2.36 install from list ui fixes

---

app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/activities/FormAndDataSyncer.java

Show a dialog for all classes of form send errors, and make the error messages more specific to each type of failure.

Improve form send error dialogs

---

app/src/org/commcare/adapters/EntityDetailPagerAdapter.java
app/src/org/commcare/fragments/EntityDetailFragment.java
app/src/org/commcare/fragments/EntitySubnodeDetailFragment.java

cross-request: https://github.com/dimagi/commcare-core/pull/590

Display conditions for case detail tabs

---

app/src/org/commcare/activities/CommCareGraphActivity.java
app/src/org/commcare/graph/view/GraphView.java
app/src/org/commcare/logging/AndroidLogger.java

For Neal and Rashmi's CHW Performance Graphing analysis

Log Graphing actions

---

app/src/org/commcare/adapters/GridMenuAdapter.java
app/src/org/commcare/adapters/MenuAdapter.java

Addresses https://manage.dimagi.com/default.asp?255735

Display any errors encountered while loading module badges

---

app/src/org/commcare/engine/resource/ResourceInstallUtils.java

This will allow @calellowitz to include the username in the build comment that gets added to builds triggered by requests to updated to the latest saved app version.
HQ ticket: http://manage.dimagi.com/default.asp?256796

Add username as url query param for updates

---

app/src/org/commcare/views/EntityDetailView.java

Case url: https://manage.dimagi.com/default.asp?255261#1352893
Added setUpMarkdown function to support Markdown templates.  Also extracted out the code for simple text template in a different function called setUpText for better modularity.

Add support for markdown templates in case detail

---

app/src/org/commcare/activities/SyncCapableCommCareActivity.java
app/src/org/commcare/tasks/ProcessAndSendTask.java

Case url : https://manage.dimagi.com/default.asp?252457#1355469
- Add Stop button to send forms dialog
- Checks while sending forms if task is cancelled, if yes throws the TaskCancelledException to return FormUploadResult.FAILURE as result

Add stop feature to upload sync

---

app/src/org/commcare/models/database/IndexedFixturePathUtils.java
app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

cross-request: https://github.com/dimagi/commcare-core/pull/594

Db Migration for INDDEX work

---

app/src/org/commcare/activities/CommCarePreferenceActivity.java

Case url: https://manage.dimagi.com/default.asp?258182
- Adds a check for fragment == null before adding it.

Fixes Preferences Dialog crash on rotation

---

app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java
app/src/org/commcare/models/database/SqlStorage.java

Minor changes to support shifting elements into core code.
cross-request: https://github.com/dimagi/commcare-core/pull/607

Performance: Allow bulk lookups with indexed fixtures

---

app/build.gradle
app/proguard.cfg
app/src/org/commcare/activities/MenuActivity.java
app/src/org/commcare/activities/RootMenuHomeActivity.java
app/src/org/commcare/activities/components/MenuList.java
app/src/org/commcare/adapters/MenuAdapter.java
build.gradle

Case url: https://manage.dimagi.com/default.asp?257029#1355558
cross-request: https://github.com/dimagi/commcare-core/pull/605
- Adds RxAndroid to the project
- Adds Java8 Compatibility options and retrolambda plugin to support lambda expressions
- Moves BadgeView to do calculations asynchronously and then update the UI on main thread by using Rx Observable subscriber pattern.

Make module badge calculations asynchronous

---

app/src/org/commcare/network/HttpRequestGenerator.java

Update our openrosa request version to 2.1 to ensure that HQ can feel comfortable sending us multiple indexed fixtures.

Update Request Version

---

app/unit-tests/resources/inputs/case_test_model_query_fallbacks.xml
app/unit-tests/src/org/commcare/android/tests/queries/CaseDbQueryTest.java

Tests for:
https://github.com/dimagi/commcare-core/pull/618
Can't be fully set up right now due to lack of instrumentation, but should guarantee execution of all codepaths. 
cross-request: https://github.com/dimagi/commcare-core/pull/618

Query Fallback Tests

---

app/src/org/commcare/utils/FormUploadUtil.java

Add logging around form attachments

---

app/src/org/commcare/adapters/EntityStringFilterer.java

Introduced by transactions refactor code.

Fix for crash in case filter/search cancel 

---

app/src/org/commcare/tasks/AsyncRestoreHelper.java

@ctsims After looking at this a bit more, it seems to me that there are 2 possible causes for the "Non-positive period" issue:
1. HQ is actually returning a negative value for the retry period. This PR makes it so that if this is in fact what is happening, a special `InvalidWaitTimeException` will be thrown, whose message will communicate what the returned retry-after value was 
2. The interval of time that passes between when the retry-after value is parsed, and when `startReportingServerProgress()` is called, is somehow longer than the duration of the retry-after value itself. It occurred to me that this is vaguely possible now that HQ changed the retry-after period from 30 seconds to 5 seconds. It still seems unlikely to me that it could take CommCare 5 seconds to go through that …

Logging and better handling for negative period value

---

app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java

I didn't properly bump this when the 2.37.1 hotfix got backmerged

Fix DB Version for Master

---

app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java
app/src/org/commcare/models/database/SqlStorage.java

Release Note: "Improvements to performance for apps that make use of large location trees"
cross-request: https://github.com/dimagi/commcare-core/pull/626

Improve performance of DB model builds

---

app/build.gradle
build.gradle

Potentially fixes Jenkins workspace issue cc @amstone326

Update to latest build tools

---

app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java
app/src/org/commcare/models/database/SqlStorage.java

Backport https://github.com/dimagi/commcare-android/pull/1786 to 2.37 for a hotfix
cross-request: https://github.com/dimagi/commcare-core/pull/632

Backport iterator fix to 2.37

---

app/src/org/commcare/preferences/DeveloperPreferences.java

Case: https://manage.dimagi.com/default.asp?260395#1381083

Fixes Developer Preferences options menu

---

app/src/org/commcare/adapters/GridMenuAdapter.java
app/src/org/commcare/adapters/MenuAdapter.java
app/src/org/commcare/views/media/AudioPlaybackButtonBase.java

Case: https://manage.dimagi.com/default.asp?261071#1386375
* Refactors MenuAdapter to use view holder pattern
*  implement cache for badges so that we don't end up doing repeated calculation on listview scrolling. 
cross-request: https://github.com/dimagi/commcare-core/pull/637

Async Badges fix

---

app/AndroidManifest.xml
app/res/layout/activity_uitest_info.xml
app/src/org/commcare/activities/UITestInfoActivity.java
app/src/org/commcare/services/CommCareSessionService.java
app/src/org/commcare/tasks/LogSubmissionTask.java

* Adds `UITestInfoActivity` to test non UI components using Calabash
* Adds the ability to show logSubmission last run result in `UITestInfoActivity` 
Corresponding UI test - https://github.com/dimagi/commcare-ui-tests/pull/91

Debug Activity for Non UI Components

---

app/src/org/commcare/activities/HomeScreenBaseActivity.java
app/src/org/commcare/activities/UpdateActivity.java

- Only trigger a sync after update if the update was OTA
- Don't trigger sync after update if we're in demo mode

Tweaks for sync after update

---

app/src/org/commcare/adapters/MenuAdapter.java

The badge text processor wasn't processing what instances were needed for displaying menus, which was causing delays in loading menus for un-needed data sources.
cross-request: https://github.com/dimagi/commcare-core/pull/644

Fix for Badge Processing Erroneously loading Instances

---

app/build.gradle
app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/activities/CommCareActivity.java
app/src/org/commcare/activities/MenuActivity.java
app/src/org/commcare/activities/RecoveryActivity.java
app/src/org/commcare/activities/RootMenuHomeActivity.java
app/src/org/commcare/activities/components/MenuList.java
app/src/org/commcare/adapters/MenuAdapter.java
app/src/org/commcare/android/database/user/models/FormRecord.java
app/src/org/commcare/android/logging/ForceCloseLogger.java
app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java
app/src/org/commcare/models/database/SqlStorage.java
app/src/org/commcare/tasks/ProcessAndSendTask.java
app/unit-tests/src/org/commcare/android/tests/database/SqlStorageBaseTests.java
app/unit-tests/src/org/commcare/android/util/TestUtils.java

Backmerge 2.39 bug fixes into master
cross-request: https://github.com/dimagi/commcare-core/pull/650

Preliminary 2.39 Backmerge

---

app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/activities/CreatePinActivity.java
app/src/org/commcare/activities/PinAuthenticationActivity.java

Fix for https://manage.dimagi.com/default.asp?262413

Check for pin length when keyboard action buttons are used

---

app/res/layout/edit_text_question_widget_compact.xml
app/src/org/commcare/views/widgets/DecimalWidget.java
app/src/org/commcare/views/widgets/IntegerWidget.java

Fixes both https://manage.dimagi.com/default.asp?261622 and https://manage.dimagi.com/default.asp?261623#1394803

Fixes scroll of compact editText Content

---

app/src/org/commcare/activities/EntityDetailActivity.java
app/src/org/commcare/print/TemplatePrinterActivity.java
app/src/org/commcare/print/TemplatePrinterTask.java

Ali requested that printing get added as a log tag so that mlabour can track how often it's being used.
cross-request: https://github.com/dimagi/commcare-core/pull/652

Log print actions

---

app/src/org/commcare/models/database/SqlStorage.java

Android requirements for the cross-request
cross-request: https://github.com/dimagi/commcare-core/pull/654

Killable Queries 

---

app/assets/locales/android_translatable_strings.txt
app/res/xml/preferences_developer_access_code.xml
app/res/xml/preferences_developer_pin.xml
app/src/org/commcare/preferences/CommCarePreferences.java
app/src/org/commcare/preferences/DeveloperPreferences.java

Addresses concerns raised in https://manage.dimagi.com/default.asp?262779

2.36.3 - Set up ability to require PIN for dev options access

---

app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

Fixes tests after 
https://github.com/dimagi/commcare-core/pull/653

Fix for missing action class in deserialization

---

app/build.gradle

https://manage.dimagi.com/default.asp?262521

Adds widget shortcut for LTS

---

app/src/org/commcare/models/database/SqlStorage.java

cross-request: https://github.com/dimagi/commcare-core/pull/642

In Progress: Partial Load Optimizations

---

app/src/org/commcare/preferences/DeveloperPreferences.java

Fixes https://manage.dimagi.com/default.asp?264206

Check if pref is present before trying to remove it

---

app/src/org/commcare/views/widgets/AudioWidget.java
app/src/org/commcare/views/widgets/VideoWidget.java

Re-create https://github.com/dimagi/commcare-android/pull/1868 into 2.40

Commcare 2.40 file fix

---

app/src/org/commcare/xml/AndroidBulkCaseXmlParser.java
app/src/org/commcare/xml/AndroidTransactionParserFactory.java
app/unit-tests/src/org/commcare/android/util/TestUtils.java

* Removes unused `CommcareRequestEndpoints` from `AndroidBulkCaseXmlParser`

No-Op Minor Cleanup

---

app/src/org/commcare/utils/MediaUtil.java

Should fix https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59ca8f31be077a4dcc497578?time=last-seven-days

Use safe image inflation with cache retreival

---

app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

Adds new class from 
https://github.com/dimagi/commcare-core/pull/676
to tests

Add distinct-values xpath function to Externalize list

---

app/src/org/commcare/models/database/IndexedFixturePathUtils.java
app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java

hotfix version of https://github.com/dimagi/commcare-android/pull/1889

Go back to getting fixture names as a set for the migration

---

app/src/org/commcare/engine/resource/AndroidResourceManager.java

cross-request: https://github.com/dimagi/commcare-core/pull/685
fixes build failure from: https://github.com/dimagi/commcare-core/pull/684/files

Lock on platform variable

---

app/src/org/commcare/heartbeat/HeartbeatRequester.java

Send last sync time parameter for heartbeat in ISO8601 format

---

app/src/org/commcare/activities/EntitySelectActivity.java

Based upon the weirdness of this code and a comment that existed in a previous iteration (https://github.com/dimagi/commcare-android/blame/3cf36feaa69e24530665022dd8148428948f6d50/app/src/org/commcare/dalvik/activities/EntitySelectActivity.java#L193-L197), I'm pretty certain that we should be finishing this activity in `onResume` if we have no session command when starting up.
Should fix https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59ff5fae61b02d480dd5cbc2?time=last-thirty-days

If session has no command in EntitySelectActivity, finish

---

app/src/org/commcare/tasks/ProcessAndSendTask.java

**Product Note**: CommCare will try to submit any pending device log reports after every successful form submission process, in order to ensure that we are sending these more frequently and at a time when the device is most likely to have good connectivity.
@ctsims I tested out the functionality of the on-login trigger for log submission a few times, and it seemed to be working as expected, so I'm not sure what to make of the delay I've been noticing for my own logs, though admittedly that was anecdotal. I'll try to keep an eye on it.

Start sending logs after every successful ProcessAndSendTask

---

app/src/org/commcare/models/database/SqlStorage.java
app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

android side of a core refactor
cross-request: https://github.com/dimagi/commcare-core/pull/689

Move request abandonment to be based on simple thread interruption

---

app/unit-tests/resources/indexed_fixture_with_index_over_nonhomo_entry.xml
app/unit-tests/src/org/commcare/android/tests/processing/IndexedFixtureLoadingTest.java

Tests for index fixture bug
cross-request: https://github.com/dimagi/commcare-core/pull/696

Tests for indexed fixture changes

---

app/src/org/commcare/utils/FileUtil.java

Fixes https://manage.dimagi.com/default.asp?266884
Seems like an odd edge case (that has been in here forever) but I can see how it'd happen

Fix for deleteFileOrDir of empty dir

---

app/src/org/commcare/activities/SyncCapableCommCareActivity.java

fixes: https://manage.dimagi.com/default.asp?264086

Never show numerator larger than denominator in progress update

---

app/src/org/commcare/activities/EntitySelectActivity.java
app/src/org/commcare/utils/AndroidHereFunctionHandler.java

In order to unify support of the here() function between Android and formplayer, I've moved some logic that was previously in Android-only to some base classes in core.
cross-request: https://github.com/dimagi/commcare-core/pull/706

here() handling refactor 

---

app/src/org/commcare/tasks/ProcessAndSendTask.java

Exception reported by Derek, log it better.

Log exception during form submission better

---

app/assets/locales/android_translatable_strings.txt
app/res/layout/custom_alert_dialog.xml
app/res/values/strings.xml
app/src/org/commcare/activities/HomeScreenBaseActivity.java
app/src/org/commcare/views/dialogs/StandardAlertDialog.java

Addresses https://manage.dimagi.com/default.asp?267357

Stronger warning message when entering practice mode

---

gradle.properties

Reverts dimagi/commcare-android#1932

Revert "gradle.properties changes for build speed"

---

app/src/org/commcare/activities/CommCareActivity.java
app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/activities/FormHierarchyActivity.java
app/src/org/commcare/activities/MenuActivity.java

https://manage.dimagi.com/default.asp?263214
This is not going to eliminate the crash completely but should reduce the frequency of these crashes.

Adds activitiy is Finishing checks to avoid illegalStateExceptions

---

app/src/org/commcare/adapters/IncompleteFormListAdapter.java

Prompted by an email from Derek, I realized that we had never updated the saved forms list to sort records by their submission ordering number where possible.
**Product Note:** On the Saved Forms page, sort Completed (Unsent + Saved) forms by their submission ordering number rather than their last modified date

Sort completed forms in form record list by submission ordering number

---

app/src/org/commcare/activities/components/ImageCaptureProcessing.java

Case: https://manage.dimagi.com/default.asp?270156#1456886
When we are moving files internally to original path to final path, they were not getting deleted from gallery. So user was able to see 2 files in gallery one belonging to old original path and one for the new final path and when user clicks on the old one  it results in an error since the file doesn't really exist outside of gallery. 
Product Note: Fixes a bug where user receives an error "Can't find the downloaded file" on choosing an image from gallery for Image Capture Question .

Explicitly Deleting deleted files from gallery

---

app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/provider/InstanceProvider.java

Adding some crashes that were getting left out to Crashlytics.

More Crashes

---

app/src/org/commcare/adapters/IncompleteFormListAdapter.java

This reverts commit 9f0e8aba9472e5e9d722c60cc97de77086d3d33b.

2.42.1 hotfix -- Revert sorting the saved forms list by submission ordering number

---

app/src/org/commcare/adapters/EntityStringFilterer.java

Crash: https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5aa268088cb3c2fa63a75788/sessions/5AA44BF800E40001275D784C70E54F29_DNE_0_v2?select_key=user
I am not able to repro this though this seems to happen intermittently on device farm causing @CaseListSearch to fail.

Removes stranded setTransactionSuccesful

---

app/src/org/commcare/models/AndroidSessionWrapper.java

cross-request: https://github.com/dimagi/commcare-core/pull/778/

Method name changed

---

app/assets/locales/android_translatable_strings.txt
app/res/layout/layout_note_msg.xml
app/res/layout/screen_messages.xml
app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
app/src/org/commcare/engine/resource/AppInstallStatus.java
app/src/org/commcare/engine/resource/installers/LocalStorageUnavailableException.java
app/src/org/commcare/engine/resource/installers/SingleAppInstallation.java
app/src/org/commcare/tasks/ResourceEngineListener.java
app/src/org/commcare/tasks/ResourceEngineTask.java
app/src/org/commcare/utils/FormUploadUtil.java

Spec: https://docs.google.com/document/d/13GBlrrSQ2qu8u8sOeE4-kz3rydnyZiWfOaXMB31NqXA/edit
Screenshots for Error Screens:
Product Note: Adds a check on mobile to not allow apps targeting LTS to be installed on non LTS Commcare flavour and vice versa.( See the spec linked above for detail)
cross-request: https://github.com/dimagi/commcare-core/pull/768

Target Specific CommCare Flavor

---

app/src/org/commcare/activities/StandardHomeActivity.java
app/unit-tests/src/org/commcare/android/tests/DemoUserRestoreTest.java

Did this as an one off build earlier. Though since it's now a permanent requirement for ICDS, PRing it to master. 
Product Note: Adds ability to change language in Practice mode.

Enables Change Language Option in Practice Mode

---

app/src/org/commcare/activities/HomeScreenBaseActivity.java

Fixes https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5a7d3b208cb3c2fa63a264dc?time=last-seven-days and https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5a881a928cb3c2fa633cb3df?time=last-seven-days

Fix 2 NPEs from crashlytics

---

app/src/org/commcare/activities/EntitySelectActivity.java

Fix for https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5a86cf1e8cb3c2fa632a2729?time=last-thirty-days and https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5a38f3be8cb3c2fa6335fb68?time=last-thirty-days

Null checks

---

app/src/org/commcare/models/database/AndroidSandbox.java

cross-request: https://github.com/dimagi/commcare-core/pull/787

Add implementation of fail fast method

---

app/assets/locales/android_startup_strings.txt

This feature isn't really new anymore, so can remove the 'NEW' prompt

2.43 - remove 'NEW' text

---

app/unit-tests/src/org/commcare/CommCareTestApplication.java
app/unit-tests/src/org/commcare/android/CommCareTestRunner.java
app/unit-tests/src/org/commcare/android/tests/activities/FormRecordListActivityTest.java
app/unit-tests/src/org/commcare/android/tests/formentry/FormIntentTests.java
app/unit-tests/src/org/commcare/android/tests/formentry/IntentCalloutTests.java
app/unit-tests/src/org/commcare/android/tests/formnav/CalendarLocaleTest.java
app/unit-tests/src/org/commcare/android/tests/formnav/EndOfFormTest.java
app/unit-tests/src/org/commcare/android/tests/formsave/FormRecordProcessingTest.java
app/unit-tests/src/org/commcare/logging/DataChangeLoggerTest.java

* Adds JUnit tests for `DataChangeLogger`

Adds test for DataChangeLogger

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/components/FormEntryInstanceState.java
app/src/org/commcare/android/database/user/models/FormRecord.java
app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
app/src/org/commcare/provider/InstanceProviderAPI.java
app/src/org/commcare/tasks/FormRecordCleanupTask.java
app/src/org/commcare/tasks/SaveToDiskTask.java
app/src/org/commcare/xml/FormInstanceXmlParser.java

This is a stale concept, and one we don't want/need to continue supporting. Once a form is marked as completed, it is never again editable.
cross-request: https://github.com/dimagi/commcare-core/pull/804

Remove concept of being able to edit a form after it's completed

---

app/build.gradle

Ran into this crash [stack at bottom] while investigating a Calabash test failure. Error occurred after selecting a new font size from form entry settings, looks like its coming from the native animation class. SO turned up [this](https://stackoverflow.com/questions/42987363/java-lang-noclassdeffounderror-failed-resolution-of-landroid-support-v4-animat) answer which suggested updating the Android support libraries; this resolved the crash. 
```
05-21 18:40:32.826 12789 13908 D ForceCloseLogger:       <msg>java.lang.NoClassDefFoundError: android.support.v4.animation.AnimatorCompatHelper
05-21 18:40:32.826 12789 13908 D ForceCloseLogger: 	at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
05-21 18:40:32.826 12789 13908 D ForceCloseLogger: 	at …
```

Update android.support libs to 27.1.1

---

app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/CommCareApp.java
app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
app/src/org/commcare/android/resource/installers/LocaleAndroidInstaller.java
app/src/org/commcare/android/resource/installers/MediaFileAndroidInstaller.java
app/src/org/commcare/android/resource/installers/OfflineUserRestoreAndroidInstaller.java
app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
app/src/org/commcare/android/resource/installers/XFormAndroidInstallerV1.java
app/src/org/commcare/android/resource/installers/XFormUpdateInfoInstaller.java
app/src/org/commcare/engine/resource/AppInstallStatus.java
app/src/org/commcare/heartbeat/HeartbeatLifecycleManager.java
app/src/org/commcare/tasks/InstallStagedUpdateTask.java
app/src/org/commcare/utils/AndroidCommCarePlatform.java
app/src/org/commcare/utils/DummyResourceTable.java

cross-request: https://github.com/dimagi/commcare-core/pull/809

Initializing a CommCareApp should fail if a resource fails to initialize

---

app/src/org/commcare/models/AndroidSessionWrapper.java

Adds more debugging info for https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59e2076c61b02d480d8ee18e

Adds crash log for Unique form id constraint failure

---

app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
app/src/org/commcare/heartbeat/HeartbeatRequester.java
app/src/org/commcare/tasks/FormLoaderTask.java

- Closes streams which were previouly left opened. 
cross_request: https://github.com/dimagi/commcare-core/pull/818

Closes several streams

---

app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java

Closes Suite Stream

---

app/assets/locales/android_translatable_strings.txt

https://manage.dimagi.com/default.asp?282108

Change Pop up message for Clear data confirmation

---

app/src/org/commcare/CommCareNoficationManager.java

LTS port for PR - https://github.com/dimagi/commcare-android/pull/2050

[lts port] Oreo notification  changes

---

app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/network/CommcareRequestGenerator.java
app/src/org/commcare/tasks/ModernHttpTask.java
app/unit-tests/src/org/commcare/CommCareTestApplication.java

cross-request: https://github.com/dimagi/commcare-core/pull/832

Disable Retries for Post requests

---

app/src/org/commcare/activities/FormAndDataSyncer.java
app/src/org/commcare/engine/references/ArchiveFileReference.java
app/src/org/commcare/tasks/ProcessAndSendTask.java
app/src/org/commcare/utils/FormUploadResult.java
app/src/org/commcare/utils/FormUploadUtil.java

Jira: https://dimagi-dev.atlassian.net/projects/MOB/issues/MOB-47
Passes through HQ error messages to user in case of actionable failures (406) during form upload.

Error Message Improvement for Form Uploads for 406 reesponse code

---

app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/activities/SyncCapableCommCareActivity.java
app/src/org/commcare/android/database/user/models/FormRecord.java
app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
app/src/org/commcare/tasks/DataPullTask.java
app/src/org/commcare/views/notifications/NotificationMessageFactory.java

- Shows a better error in case restore url is set to empty (https://dimagi-dev.atlassian.net/projects/MOB/issues/MOB-61) 
- Makes Form Instance Id more visible in logs and Integrity Scan Result

Error Improvements Plus Logging

---

app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/tasks/LogSubmissionTask.java

In case logging is disabled for a project 
- Clears Logger instance
- Dont send any http requests for log
cross-request: https://github.com/dimagi/commcare-core/pull/838

Disable log submission requests in case logging is disabled

---

app/assets/locales/android_translatable_strings.txt
app/res/values/strings.xml
app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
app/src/org/commcare/engine/references/ArchiveFileReference.java

Jira: https://dimagi-dev.atlassian.net/browse/MOB-45
cross-request: https://github.com/dimagi/commcare-core/pull/834

Throws better error on resource file not found during install

---

app/src/org/commcare/activities/LoginActivity.java

Picking up on the simplest MLE feedback. 
Product Note: Removes Up (<) button from CommCare Login Screen

Removes Up button from Login Screen

---

app/res/layout/menu_list_header.xml
app/src/org/commcare/activities/components/MenuList.java

This makes the menu list header to right align when in RTL settings.

Fixes alignment for Menu List Header

---

app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java

https://dimagi-dev.atlassian.net/browse/QA-179
App update is breaking since I forgot to bump the db version.

Corrects APP DB version

---

app/src/org/commcare/models/database/SqlStorage.java

Jira: Jira: https://dimagi-dev.atlassian.net/browse/REACH-102
Refer core PR for context. 
cross-request: https://github.com/dimagi/commcare-core/pull/843

Protects wipeTable call with a tableExists check

---

app/templates/google-services.json

Adds LTS debug in google services template to be able to install LTS debug locally.

Adds LTS debug in google services template

---

app/build.gradle
app/src/org/commcare/activities/EntitySelectActivity.java

Added click filter on Entity list.
Jira ticket: https://dimagi-dev.atlassian.net/browse/MOB-77

added rxBindings; added rx item click listener;

---

app/build.gradle
app/src/org/commcare/views/media/MediaLayout.java

Product Note: Added support for animated images (GIFs)
Jira ticket https://dimagi-dev.atlassian.net/browse/MOB-75

added glide for GIF image loading

---

app/src/org/commcare/adapters/IncompleteFormListAdapter.java
app/src/org/commcare/utils/StorageUtils.java

Product note: When unsent filter selected on saved forms screen, forms are listed in submission order.
Jira task https://dimagi-dev.atlassian.net/browse/MOB-74

added sorting for unsaved forms

---

app/src/org/commcare/activities/FormEntryActivityUIController.java

Product note: "If there is no last question on the form, only hidden value, submit and exit the form will be triggered"
Jira issue: https://dimagi-dev.atlassian.net/browse/MOB-99

Added check: if there is no question on the screen, save form and exit

---

app/res/values-es/strings.xml
app/res/values-fr/strings.xml
app/res/values-lt/strings.xml
app/res/values-no/strings.xml
app/res/values-pt/strings.xml
app/res/values-sw/strings.xml
app/res/values/strings.xml
app/src/org/commcare/views/widgets/ImageWidget.java

-Product note: Added cancel option on image question to remove taken image.
Jira task: https://dimagi-dev.atlassian.net/browse/PF-310
When there is selected there is remove button
When there is no selected image, remove button is hidden.

Added discard button to image widget

---

app/build.gradle
app/res/values/strings.xml
app/src/org/commcare/android/database/global/models/ApplicationRecord.java
app/src/org/commcare/fragments/BreadcrumbBarFragment.java

Updated action bar to display correct application name depending on different build variant.
Task on Jira: https://dimagi-dev.atlassian.net/browse/MOB-82
Screen Shots

Updated app name in action bar.

---

app/src/org/commcare/adapters/MenuAdapter.java
app/src/org/commcare/fragments/BreadcrumbBarFragment.java
app/src/org/commcare/models/AndroidSessionWrapper.java

Jira: https://dimagi-dev.atlassian.net/browse/MOB-105
cross-request: https://github.com/dimagi/commcare-core/pull/854

Adds support to use instance variables in Menu text xpath

---

app/src/org/commcare/engine/cases/AndroidIndexedFixtureInstanceTreeElement.java
app/unit-tests/src/org/commcare/android/tests/processing/IndexedFixtureLoadingTest.java

cross-request: https://github.com/dimagi/commcare-core/pull/858

Moves Indexed Fixture attribute lookup methods to core

---

app/src/org/commcare/activities/EntitySelectActivity.java
app/src/org/commcare/activities/FormEntryActivity.java

CL: https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5c87e77ff8b88c2963d987c8?time=last-ninety-days
https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59dcde5cbe077a4dcc0ef624?time=last-ninety-days
Instead of crashing on a XPathException, Catches the XpathException and shows the error to the user.

Catches Xpath error in onEntitySelected

---

app/unit-tests/src/org/commcare/android/tests/processing/IndexedFixtureLoadingTest.java

Test for: https://github.com/dimagi/commcare-core/pull/866

Adds test for accessing missing attribute in indexed Fixtures

---

app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/activities/EntitySelectActivity.java

1st part of https://dimagi-dev.atlassian.net/browse/MOB-126

Localizes Case List Settings Text

---

app/AndroidManifest.xml
app/build.gradle

Turned out quite small in the end. I tested some main workflows on an emulator and they are running fine. 
Product Note: Adds full support for Android 9 devices.

Targets Android Pie

---

app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/activities/SyncCapableCommCareActivity.java
app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
app/src/org/commcare/tasks/DataPullTask.java
app/src/org/commcare/views/notifications/NotificationMessageFactory.java
app/unit-tests/src/org/commcare/android/tests/DataPullTaskTest.java

Jira: https://dimagi-dev.atlassian.net/browse/ICDS-902
There was some discussion on Jira regarding wordings for this error. I am starting with being transparent first and open to iterations if we don't really wanna mention "servers unavailable/busy" to users encountering rate limiting errors. 
Product Note: Error message improvements for rate limiting errors encountered on login or sync.

Error message improvements for 503 (Rate limiting) error

---

app/src/org/commcare/android/javarosa/IntentCallout.java

Fabric: https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5a0cbe1d61b02d480d8329c3?time=last-ninety-days

Handle null values in callout response keys

---

app/src/org/commcare/CommCareApp.java
app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/StandardHomeActivity.java
app/src/org/commcare/activities/SyncCapableCommCareActivity.java
app/src/org/commcare/android/logging/ReportingUtils.java
app/src/org/commcare/engine/resource/AndroidResourceManager.java
app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
app/src/org/commcare/google/services/analytics/FormAnalyticsHelper.kt
app/src/org/commcare/logging/analytics/UpdateStats.java
app/src/org/commcare/logic/AndroidFormController.java
app/src/org/commcare/tasks/UpdateTask.java
app/src/org/commcare/utils/FileUtil.java
app/src/org/commcare/views/media/MediaLayout.java

Implements analytics changes from the spec -  https://docs.google.com/document/d/1TRYNvofE_2mA5sVAkSUiIfLFOn_elRSSnmhcfwS3KdI

Adds Video Usage analytics

---

app/res/values-pt/strings.xml

https://dimagi-dev.atlassian.net/browse/MOB-126
This PR will add Portugese translation for 3 buttons viz. Uninstall, Archive and Update

Add Portugese translation for buttons in App Management Screen

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/views/QuestionsView.java
app/src/org/commcare/views/widgets/QuestionWidget.java

https://dimagi-dev.atlassian.net/browse/MOB-121
This PR will show popup dialog box with the XPathTypeMismatchException message while fetching question hint. 
cross-request: https://github.com/dimagi/commcare-core/pull/874

Show error popup when hint text gets type mismatch exception 

---

app/src/org/commcare/activities/LoginActivityUIController.java
app/src/org/commcare/adapters/HomeScreenAdapter.java
app/src/org/commcare/views/CustomBanner.java

https://dimagi-dev.atlassian.net/browse/MOB-136
This PR will use the downsampled banner image to prevent OOM Exceptions.

Use downsampled banner to prevent OOM Exceptions

---

app/src/org/commcare/views/widgets/TriggerWidget.java

Reverts dimagi/commcare-android#2162

Revert "Return empty string as answer instead of OK for a label"

---

app/src/org/commcare/network/CommcareRequestGenerator.java
app/src/org/commcare/utils/SyncDetailCalculations.java
app/unit-tests/src/org/commcare/utils/DateUtilTest.java

Hotfix version of 
https://github.com/dimagi/commcare-android/pull/2169

[Hotfix] Add days since last sync param to sync requests

---

app/assets/locales/android_translatable_strings.txt
app/res/layout/pin_screen_buttons.xml
app/src/org/commcare/activities/CreatePinActivity.java

https://dimagi-dev.atlassian.net/browse/ICDS-1235

Adds translation key for cancel button on Pin Screen

---

app/src/org/commcare/activities/FormRecordListActivity.java
app/src/org/commcare/views/IncompleteFormRecordView.java

This'll make forms with status COMPLETE and UNSENT appear same to the user.

Add forms with status complete to the unsent filter

---

app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
app/src/org/commcare/engine/resource/AndroidResourceManager.java
app/src/org/commcare/preferences/HiddenPreferences.java

Jira: https://dimagi-dev.atlassian.net/browse/QA-1120

Sets Pre update Sync needed from the staged update

---

app/src/org/commcare/activities/GeoPointMapActivity.java
app/src/org/commcare/views/widgets/GeoPointWidget.java

https://forum.dimagi.com/t/alternative-method-to-capture-gps-location/7373/1

GPS Maps: Focuses on last selected location

---

app/res/drawable-anydpi/ic_layers.xml
app/res/layout/geopoint_layout.xml
app/res/values/colors.xml
app/res/values/dimens.xml
app/src/org/commcare/activities/GeoPointMapActivity.java
app/src/org/commcare/preferences/HiddenPreferences.java
app/src/org/commcare/utils/GeoUtils.java
app/src/org/commcare/utils/MapLayer.java

Adds a button to switch between layers on Google Maps
UX - https://drive.google.com/file/d/1VFv39Rn_UkowWpvMzj61s74hf5Qb4QXA/view?usp=sharing
@ctsims  Let me know if the UX doesn't make sense, though that seems to be more of a standard way to implement a very simple layer switching UI.

GPS Maps: Adds Layer change Button

---

app/src/org/commcare/utils/AndroidCommCarePlatform.java

[Crash Trace](https://console.firebase.google.com/u/1/project/commcare-a57e4/crashlytics/app/android:org.commcare.lts/issues/4337c9ddc534f7eb6281f642f91edf72?time=last-seven-days&sessionId=)

Fix for NPE while De-regestering Form

---

app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/activities/SyncCapableCommCareActivity.java
app/src/org/commcare/engine/resource/AppInstallStatus.java
app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
app/src/org/commcare/network/HttpCalloutTask.java
app/src/org/commcare/tasks/DataPullTask.java
app/src/org/commcare/tasks/ManageKeyRecordTask.java
app/src/org/commcare/tasks/ProcessAndSendTask.java
app/src/org/commcare/tasks/ResourceEngineTask.java
app/src/org/commcare/utils/FormUploadResult.java
app/src/org/commcare/utils/FormUploadUtil.java
app/src/org/commcare/views/notifications/NotificationMessageFactory.java

cross-request: https://github.com/dimagi/commcare-core/pull/889

Show detailed error for captive portal presense

---

app/src/org/commcare/preferences/HiddenPreferences.java
app/src/org/commcare/views/widgets/QuestionWidget.java

Jira: https://dimagi-dev.atlassian.net/browse/ICDS-344
Product Note: Implements a custom property `cc-label-required-questions-with-asterisk` to show a red asterisk to denote mandatory questions in a form

Label required questions with a red asterisk

---

app/src/org/commcare/views/widgets/SpinnerWidget.java

Jira: https://dimagi-dev.atlassian.net/browse/SAAS-10759
Fix a bug which removes spinner validation error UI when spinner question is the last question of the form.

Fix unwanted onItemSelected callback in spinner

---

app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

Updates externalizables list to incorporate https://github.com/dimagi/commcare-core/pull/891

Fixes testAllExternalizablesInPrototypeFactory

---

app/assets/locales/android_translatable_strings.txt
app/res/xml/advanced_actions.xml
app/src/org/commcare/activities/FormAndDataSyncer.java
app/src/org/commcare/activities/RecoveryActivity.java
app/src/org/commcare/activities/SyncCapableCommCareActivity.java
app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
app/src/org/commcare/preferences/AdvancedActionsPreferences.java
app/src/org/commcare/preferences/HiddenPreferences.java
app/src/org/commcare/sync/FormSubmissionHelper.java
app/src/org/commcare/tasks/DataPullTask.java
app/src/org/commcare/utils/FormUploadUtil.java

Will merge after this https://github.com/dimagi/commcare-android/pull/2195. Since the rate limit message assumes that commcare will automatically retry the form submission. 
Jira: https://dimagi-dev.atlassian.net/browse/SAAS-10719
Includes 429 response code for rate-limiting error.

Rate limit error message improvement

---

app/src/org/commcare/activities/PromptApkUpdateActivity.java
app/src/org/commcare/appupdate/AppUpdateControllerFactory.java

Addressing https://github.com/dimagi/commcare-android/pull/2227#issuecomment-619797150

Use normal update instead of forced for version mismatch exception

---

app/src/org/commcare/utils/FileUtil.java

[Stack Trace](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/63a588d184f917b8ebd951fa21cd10c9?time=last-seven-days&sessionId=5EB227F4037F000154DA55FBFC0619BB_DNE_0_v2)

Fix npe in deleting files inside directory

---

app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.java

Left out a test failure in [this PR](https://github.com/dimagi/commcare-android/pull/2244)
cross-request: https://github.com/dimagi/commcare-core/pull/902

Fixes testUpdateToAppMissingMultimedia

---

app/res/values/strings.xml
app/src/org/commcare/CommCareApp.java
app/src/org/commcare/utils/AndroidCommCarePlatform.java
app/unit-tests/src/org/commcare/android/database/user/models/SessionStateDescriptorTests.java

Jira: https://dimagi-dev.atlassian.net/browse/ICDS-1490
Product Note: Updates Required version comparison to include the minimal app version
cross-request: https://github.com/dimagi/commcare-core/pull/907

Adds minimal platform version

---

app/assets/locales/android_translatable_strings.txt
app/res/drawable/blue_outlined_view.xml
app/res/layout/blue_outlined_button.xml
app/src/org/commcare/views/widgets/SelectOneWidget.java

JIRA: https://dimagi-dev.atlassian.net/browse/SAAS-10936
Product Note: Added a button to clear choices in single-select questions.

Add a button to clear radio button selection. 

---

app/res/layout/activity_drawing_boundary.xml
app/src/org/commcare/gis/DrawingBoundaryActivity.kt
app/src/org/commcare/gis/DrawingBoundaryActivityUIController.kt

* Only show start button once the map has loaded
* Updates Area display from input coordinates ([JIRA](https://dimagi-dev.atlassian.net/browse/QA-1363))
* Sets area precision to 4 decimal places in result

Draw boundary fixes

---

app/src/org/commcare/activities/UpdateUIController.java

JIRA: https://dimagi-dev.atlassian.net/browse/SAAS-10938

Keep update check button enabled all the time

---

app/src/org/commcare/android/logging/ReportingUtils.java
app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java

This adds the ability to seggregrate analytics events per app profile. 
cross-request: https://github.com/dimagi/commcare-core/pull/871/

Adds the build profile Id as an user property for analytics

---

app/src/org/commcare/engine/resource/AndroidResourceManager.java
app/src/org/commcare/engine/resource/AppInstallStatus.java
app/src/org/commcare/logging/analytics/UpdateStats.java

Ports https://github.com/dimagi/commcare-android/pull/2307 for LTS

Update fixes Port for LTS [2.48.10 hotfix]

---

app/src/org/commcare/update/UpdateWorker.kt

Found a mistake made by me where the auto update retry logic was written inversely to what is should be.

[2.49.6] Fixes Auto update retries

---

app/proguard.cfg

Jira: https://dimagi-dev.atlassian.net/browse/QA-1892
A Fix for `NoSuchAlgorithmException: no such algorithm: SHA256withRSA/PSS for provider BC`

Replace spongycastle to bouncycastle in proguard

---

app/src/org/commcare/views/widgets/SelectOneAutoAdvanceWidget.java

A fix for: https://dimagi-dev.atlassian.net/browse/QA-1900

Fix radio button visibility

---

app/src/org/commcare/gis/EntityMapboxActivity.kt

Jira: https://dimagi-dev.atlassian.net/browse/QA-1914

Fix info visibility when markers are too close

---

app/build.gradle
app/res/layout/media_layout.xml
app/res/layout/missing_media_view.xml
app/src/org/commcare/views/media/MediaLayout.java

This PR reverts #2355 and uses a RelativeLayout instead of ConstraintLayout.

Use RelativeLayout instead of ConstraintLayout for mediaview

---

app/AndroidManifest.xml

Fix for [CL](https://console.firebase.google.com/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/ff6c880478ae84ef9866bad1b6c008ae?time=last-seven-days&versions=2.50.0%20(463781)&sessionEventKey=5F752CE6020400016D2BB1FCA44F7F95_1456899003590486482)

Remove KujakuNetworkChangeReceiver

---

app/src/org/commcare/android/database/user/models/FormRecord.java

cross-request: https://github.com/dimagi/commcare-core/pull/933

include original exception as cause

---

app/assets/locales/android_translatable_strings.txt
app/src/org/commcare/activities/PinAuthenticationActivity.java

Pin reset screen was missing label on the cancel button.

Adds label to cancel button In Reset Pin UI

---

app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/DiskUtils.kt
app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
app/src/org/commcare/tasks/CleanRawMedia.kt
app/src/org/commcare/utils/StorageUtils.java

* Deletes raw folder for saved forms to conserve space for LTS users
* Report free disk available as a user property to Analytics events

[2.48.11] Delete raw images from Saved Forms 

---

app/instrumentation-tests/src/org/commcare/androidTests/AppPreferenceSettingsTest.kt
app/instrumentation-tests/src/org/commcare/androidTests/DialogTests.kt
app/instrumentation-tests/src/org/commcare/androidTests/LanguagesTest.kt
app/instrumentation-tests/src/org/commcare/androidTests/MenuTests.kt
app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt

Add dialog tests

---

app/res/values/strings.xml
app/src/org/commcare/CommCareApplication.java

Jira: https://dimagi-dev.atlassian.net/browse/SAAS-11499

Remove duplicate commcareVersion from strings.xml

---

app/res/xml/main_preferences.xml
app/src/org/commcare/activities/FormRecordListActivity.java
app/src/org/commcare/activities/GlobalPrivilegeClaimingActivity.java
app/src/org/commcare/activities/QueryRequestActivity.java
app/src/org/commcare/activities/components/EntitySelectCalloutSetup.java
app/src/org/commcare/fragments/SelectInstallModeFragment.java
app/src/org/commcare/preferences/MainConfigurablePreferences.java
app/src/org/commcare/views/widgets/BarcodeWidget.java
app/src/org/commcare/views/widgets/WidgetUtils.java

#2377 
Product Note: Added a setting to allow users to use custom applications for scanning barcodes. 
[Video](https://drive.google.com/drive/folders/1cnVOzjFcycAM0mD1VwfkPr51HkVoGEqf?usp=sharing)

Allow use of custom barcode scanner apps

---

app/assets/locales/android_translatable_strings.txt

Added new translation for the title of "Case Claim." 
Just confirming there no syntax/other things I need to be aware of.
Relates to this [PR](https://github.com/dimagi/commcare-core/pull/958)

Added new translation

---

app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/activities/QueryRequestActivity.java
app/unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml
app/unit-tests/resources/commcare-apps/case_search_and_claim/user_restore.xml
app/unit-tests/src/org/commcare/CommCareTestApplication.java
app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java

Android level tests for
https://github.com/dimagi/commcare-core/pull/959
Requires that PR to be pulled first. 
cross-request: https://github.com/dimagi/commcare-core/pull/959

Android App Tests for New Query Prompt Defaults

---

app/instrumentation-tests/src/org/commcare/androidTests/DeletedUserTest.kt
app/instrumentation-tests/src/org/commcare/utils/HQApi.java
app/instrumentation-tests/src/org/commcare/utils/InstrumentationUtility.kt

#2341 
CC core changes::
```
@Streaming
@DELETE
Call<ResponseBody> makeDeleteRequest(@Url String url, @QueryMap Map<String, String> params,
@HeaderMap Map<String, String> headers);
```
Waiting for [this](https://dimagi-dev.atlassian.net/browse/SAAS-11198)
cross-request: https://github.com/dimagi/commcare-core/pull/969

Add delete user test

---

app/src/org/commcare/heartbeat/HeartbeatLifecycleManager.java
app/src/org/commcare/heartbeat/HeartbeatWorker.kt
app/src/org/commcare/services/CommCareSessionService.java
app/unit-tests/src/org/commcare/android/tests/HeartbeatAndPromptedUpdateTests.java

Product Note: Improved heartbeat periodicity and reliability.

Move hearbeat to use android worker

---

app/assets/locales/android_translatable_strings.txt
app/res/values/strings.xml
app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/components/ImageCaptureProcessing.java
app/src/org/commcare/preferences/FilePreferenceDialogFragmentCompat.java
app/src/org/commcare/utils/FileUtil.java
app/src/org/commcare/views/widgets/MediaWidget.java

Jira: https://dimagi-dev.atlassian.net/browse/SAAS-11633
Product Note: Show an error dialog when file of size more than 15 MB is selected by the user.

Discard image when file limit exceeds. 

---

app/src/org/commcare/utils/FileUtil.java

Jira: https://dimagi-dev.atlassian.net/browse/QA-2443

Use sdfat format for SD card availability check

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/GeoPointActivity.java
app/src/org/commcare/android/javarosa/PollSensorController.java
app/src/org/commcare/location/CommCareFusedLocationController.kt
app/src/org/commcare/location/CommCareLocationController.kt
app/src/org/commcare/location/CommCareProviderLocationController.kt
app/src/org/commcare/tts/TextToSpeechConverter.kt
app/src/org/commcare/utils/TimeoutTimer.java

There has been an increase in the OOMs with CommCare 2.51. This PR targets to remove some memory leaks so as to avoid those OOMs.

Fix Memory leaks

---

app/src/org/commcare/views/widgets/LabelWidget.java
app/src/org/commcare/views/widgets/ListMultiWidget.java
app/src/org/commcare/views/widgets/ListWidget.java

Product Note: Remove bold text style from likert format list. 
Screenshots:

Remove bold styling from list with radio selection

---

app/res/layout/http_request_layout.xml

https://dimagi-dev.atlassian.net/browse/QA-2695?focusedCommentId=127010

Bug fix: Case query Button slides off screen

---

app/build.gradle

Addresses https://github.com/dimagi/commcare-android/issues/2426

Use bouncycastle jdk15to18 1.68

---

app/src/org/commcare/activities/QueryRequestActivity.java

cross-request: https://github.com/dimagi/commcare-core/pull/984

Changes to support Core Api Changes for Formplayer

---

app/AndroidManifest.xml
app/res/values/strings.xml
app/src/org/commcare/provider/CommCareLogoutReceiver.java
app/src/org/commcare/provider/ExternalApiReceiver.java

Apps using the receiver will need to request for `org.commcare.dalvik.permission.COMMCARE_LOGOUT`

Adds receiver to logout CC user

---

app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
app/src/org/commcare/engine/references/JavaHttpReference.java
app/src/org/commcare/engine/resource/ResourceInstallUtils.java
app/src/org/commcare/tasks/ResourceEngineTask.java

Jira https://dimagi-dev.atlassian.net/browse/SAAS-12107
Detect captive portals during app installs and provide a better error message to the user.
cross-request: https://github.com/dimagi/commcare-core/pull/994

[SAAS-12107] Handle captive portal in app installs

---

app/build.gradle

https://github.com/dimagi/commcare-android/issues/2473

Shifts Kujaku to download from maven central

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/components/ImageCaptureProcessing.java
app/src/org/commcare/utils/FileUtil.java
app/src/org/commcare/utils/FormUploadUtil.java

Jira: https://dimagi-dev.atlassian.net/browse/SAAS-12272
While analyzing the logs, I found another case of missing attachments on HQ. The issue was happening because the selected image was not supported by commcare. More details in the ticket. 
**Product Note: Improved check for supported multimedia files.**

[SAAS-12272] Show error if selected image is not supported by commcare 

---

scripts/browserstack.py

Sometimes when we retry the BS test, it gives an error `No Test Run` even though all the tests run successfully. 
This PR will fix it.

[SAAS-12293] Fix No Test Run error in BS

---

app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/utils/StringExtensionImpl.java

Reference: https://c3js.org/samples/axes_x_tick_rotate.html
cross-request: https://github.com/dimagi/commcare-core/pull/999
Product Note: Large graph labels will be rotated by 75 degrees.
Screenshot:

Rotate large x axis labels on UCRs

---

.github/pull_request_template.md
ISSUE_TEMPLATE/bug_report.md
ISSUE_TEMPLATE/feature_request.md

Adding HQ's PR template here with slight modifications. Improvements welcomed. 
Should we add it for commcare-core as well ?

PR template

---

app/AndroidManifest.xml
app/build.gradle
app/res/drawable/ic_current_location.xml
app/res/layout/activity_mapbox_location_picker.xml
app/res/values/strings.xml
app/src/org/commcare/activities/GeoPointMapActivity.java
app/src/org/commcare/activities/components/FormEntryDialogs.java
app/src/org/commcare/gis/BaseMapboxActivity.kt
app/src/org/commcare/gis/MapboxLocationPickerActivity.kt
app/src/org/commcare/gis/MapboxLocationPickerViewModel.kt
app/src/org/commcare/utils/GeoUtils.java
app/src/org/commcare/views/widgets/GeoPointWidget.java
build.gradle

Jira: https://dimagi-dev.atlassian.net/browse/SAAS-11688
Video here:
https://user-images.githubusercontent.com/29516995/118972956-c665ff80-b98e-11eb-8b6a-1376712b6df9.mp4
Product Note: We'll use MapBox style map for GPS capture questions with appearance attribute `map` when the app is using `cc-use-mapbox-map` setting.

[SAAS-11688] Use mapbox map with capturing location

---

scripts/browserstack.py

Prints BS api json response to jenkins job console.

Log json response for BS apis

---

app/src/org/commcare/android/database/user/models/ACasePreV28Model.java
app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
scripts/browserstack.py

https://dimagi-dev.atlassian.net/browse/QA-3228
None
Mostly relying on QA update tests due to which we were able to find out this issue during QA itself.

Fixes case db migration

---

app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java

Fix for https://dimagi-dev.atlassian.net/browse/QA-3228

Fix db update crash for FormRecord

---

app/build.gradle

Adds leak-canary to detect leaks. https://square.github.io/leakcanary/getting_started/
We've seen OOM issues in the last release due to leaks so adding the library would be really useful.

Add leak canary to debug builds

---

app/build.gradle

Addresses https://github.com/dimagi/commcare-android/issues/2426#issuecomment-883125639

Update bouncy castle to 1.69

---

app/AndroidManifest.xml

Backmerge Commcare 2.52.1

---

app/assets/graphing/graph.max.js

Fixes `characterLimit is undefined` error. Formplayer doesn't provide `characterLimit` variable to `graph.js` so it's undefined there and breaks.

Fix characterLimit is undefined error

---

app/src/org/commcare/models/FormRecordProcessor.java
app/src/org/commcare/sync/ExternalDataUpdateHelper.java
app/src/org/commcare/tasks/DataPullTask.java

Send an update to Reminders app after sync

Fixes reminders update on sync

---

app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

https://github.com/dimagi/commcare-core/pull/1088

fixes test for decrypt-string

---

app/instrumentation-tests/src/org/commcare/androidTests/DateWidgetsTests.kt

… 
Made below changes to the DateWidgetsTests.kt file:
1. added one missing month in the listOfEthiopianMonths  
2. updated the format of long date format from "EE, MMM dd, yyyy" to "EE, MMM d, yyyy"
Changes are made to the DateWidgetsTests.kt file
Executed the tests on my local AVD and they got executed successfully.

added one missing month in the listOfEthiopianMonths and also updated the format of long date format from EE, MMM dd, yyyy to EE, MMM d, yyyy

---

app/src/org/commcare/tasks/DumpTask.java

This PR decrypts media files so they can be dumped in the SD card in their original form. The main reason for transferring files in this format is due to the lack of a secure channel to share the secret key with the device that is going to submit the forms.
- [x ] I have confidence that this PR will not introduce a regression for the reasons below

Remove media encryption before dumping files in SD card

---

app/src/org/commcare/activities/HomeScreenBaseActivity.java
app/src/org/commcare/activities/PostRequestActivity.java
app/unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml
app/unit-tests/resources/commcare-apps/case_search_and_claim/user_restore.xml
app/unit-tests/src/org/commcare/android/tests/activities/PostRequestActivityTest.java
app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

Some final edits for `formplayer - master` convergence. Mostly test fixes along with some Multimap handling I missed in https://github.com/dimagi/commcare-android/pull/2584
All of these changes are motivated by test failures in first place, so we do have the relevant coverage on all of these changes.
cross-request: https://github.com/dimagi/commcare-core/pull/1162

Some last fixes for formplayer -> Master Merge

---

.github/workflows/commcare-android-pr-workflow.yml

This PR enables Github Actions for commcare-android PRs.

Setup Github actions for commcare-android PRs

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

This PR is to Update Gradle to version 7.5.

Update to Gradle 7.5

---

.github/workflows/commcare-android-pr-workflow.yml

Improvements to the commcare-android PR CI workflow.

GitHub Actions CI workflow improvements

---

app/src/org/commcare/tasks/FormRecordCleanupTask.java
app/src/org/commcare/xml/AndroidCaseXmlParser.java
app/unit-tests/src/org/commcare/android/util/TestUtils.java

Changes for https://github.com/dimagi/commcare-core/pull/1271
cross-request: https://github.com/dimagi/commcare-core/pull/1271

[No Op] Change constant references

---

.github/linters/checkstyle.xml
.github/workflows/linter.yml

Trying out [Super Linter](https://github.com/super-linter/super-linter) for PRs. The checkstyle file is copied from [commcare-core](https://github.com/dimagi/commcare-core/blob/master/config/checkstyle/checkstyle.xml)

Adds SuperLinter

---

app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

Fixes test by adding the new core model to the test
cross-request: https://github.com/dimagi/commcare-core/pull/1303

Adds detailGroup to completeHistoryOfExternalizableClasses

---

app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

Test fix
cross-request: https://github.com/dimagi/commcare-core/pull/1360/files

Adds model class in test

---

app/build.gradle

New cccStaging build flavor in order to support Connect production and staging versions.

Added cccStaging build flavor

---

app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

Skipping PR template as only a unit test change. 
cross-request: https://github.com/dimagi/commcare-core/pull/1392

Adds query Group model to test

---

app/res/layout/fragment_connect_delivery_details.xml
app/res/layout/fragment_connect_results_summary_list.xml
app/res/values/strings.xml
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
app/src/org/commcare/android/database/connect/models/ConnectPaymentUnitRecord.java
app/src/org/commcare/connect/ConnectDatabaseHelper.java
app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
app/src/org/commcare/fragments/connect/ConnectDeliveryProgressDeliveryFragment.java
app/src/org/commcare/fragments/connect/ConnectResultsSummaryListFragment.java
app/src/org/commcare/models/database/connect/ConnectDatabaseUpgrader.java
app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

Added new DB table to store payment units, and DB upgrade code. UI changes to Job Details and Delivery Progress pages to show multi-visit breakdowns.

Multi-visit info in Connect pages

---

app/src/org/commcare/engine/resource/ResourceInstallUtils.java
app/src/org/commcare/tasks/ResourceEngineTask.java
app/src/org/commcare/update/UpdateWorker.kt

https://dimagi.atlassian.net/browse/SC-3786
Logs Unknown Errors while App install and Update
NA
Exception Logs only

Logs Unknown Errors while App install and Update

---

app/AndroidManifest.xml

Adds ability to query [Biometric App](https://github.com/dimagi/biometric-android/blob/master/app/build.gradle#L9) to be able to add it as an [App depndency](https://dimagi.atlassian.net/wiki/spaces/GS/pages/2374238277/Set+Android+app+dependencies+that+must+be+installed+before+using+a+CommCare+app). 
NA
NA

Add biometric app as dependency

---

app/src/org/commcare/CommCareApplication.java

https://dimagi.atlassian.net/browse/CCCT-340

Add CCC job ID to analytics message

---

app/src/org/commcare/android/database/connect/models/ConnectJobAssessmentRecord.java
app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
app/src/org/commcare/services/CommCareFirebaseMessagingService.java

https://dimagi.atlassian.net/browse/CCCT-357

CCCT-357 || Learn Assessment Score

---

app/res/values/strings.xml
app/src/org/commcare/activities/connect/ConnectIdMessageActivity.java
app/src/org/commcare/activities/connect/ConnectIdPinActivity.java
app/src/org/commcare/connect/ConnectConstants.java
app/src/org/commcare/connect/ConnectIdWorkflows.java
app/src/org/commcare/connect/ConnectManager.java
app/src/org/commcare/connect/ConnectTask.java

Redirection to verify alternate number on wrong pin entered
https://dimagi.atlassian.net/browse/CCCT-354?atlOrigin=eyJpIjoiMGM2MmM4MDNmMDczNDE1ODk1NjcxNDg0YzA4YTU3OWYiLCJwIjoiaiJ9

CCCT-354-bug fix of wrong attempt redirection

---

app/build.gradle
app/src/org/commcare/activities/connect/ConnectIdPhoneActivity.java
app/src/org/commcare/activities/connect/ConnectIdRecoveryDecisionActivity.java
app/src/org/commcare/activities/connect/ConnectIdRecoveryDecisionActivityUiController.java
app/src/org/commcare/connect/ConnectConstants.java
app/src/org/commcare/utils/PhoneNumberHelper.java

https://dimagi.atlassian.net/browse/CCCT-366

PM_CCCt_366- pr upgrade

---

app/res/drawable/baseline_menu_24.xml
app/res/drawable/ic_list_alt.xml
app/res/drawable/ic_notifications_24.xml
app/res/layout/connectid_title_bar.xml

PM- common title bar

---

app/AndroidManifest.xml
app/res/layout/screen_connect.xml
app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/activities/HomeScreenBaseActivity.java
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/activities/StandardHomeActivity.java
app/src/org/commcare/activities/connect/ConnectActivity.java
app/src/org/commcare/activities/connect/ConnectIdActivity.java
app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
app/src/org/commcare/android/database/connect/models/ConnectJobRecordV4.java
app/src/org/commcare/android/database/connect/models/ConnectJobRecordV7.java
app/src/org/commcare/android/database/connect/models/ConnectLinkedAppRecord.java
app/src/org/commcare/android/database/connect/models/ConnectLinkedAppRecordV3.java
app/src/org/commcare/android/database/connect/models/ConnectLinkedAppRecordV9.java
app/src/org/commcare/connect/ConnectConstants.java
app/src/org/commcare/connect/ConnectManager.java
app/src/org/commcare/connect/network/ApiConnect.java
app/src/org/commcare/fragments/connect/ConnectJobsListsFragment.java
app/src/org/commcare/models/database/connect/ConnectDatabaseUpgrader.java
app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
app/src/org/commcare/utils/BiometricsHelper.java
app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java

Added a field to the ConnectLinkeddAppRecord table so we can track the last time an app was accessed (i.e. logged in to). This will be used for ordering in the new app list (also under development).
This PR also contains some fixes to functionality that was broken after the refactor to use the Navigation component for ConnectID.

Tracking app last accessed date

---

app/res/drawable/connect_edit_text_bg.xml
app/res/drawable/connect_side_icon_bg.xml
app/res/layout/fragment_phone.xml
app/res/layout/fragment_phone_available_bottom_sheet.xml
app/res/layout/fragment_recovery_code.xml
app/res/layout/fragment_secondary_phone_number.xml
app/res/layout/screen_connect_message.xml
app/res/layout/screen_connect_password_verify.xml
app/res/layout/screen_connect_phone_verify.xml
app/res/layout/screen_connect_primary_phone.xml
app/res/layout/screen_connect_verify.xml
app/res/layout/select_install_mode_fragment.xml
app/src/org/commcare/fragments/connectId/ConnectIDSecondaryPhoneNumber.java
app/src/org/commcare/fragments/connectId/ConnectIDSignupFragment.java
app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
app/src/org/commcare/fragments/connectId/ConnectIdMessageFragment.java
app/src/org/commcare/fragments/connectId/ConnectIdPasswordVerificationFragment.java
app/src/org/commcare/fragments/connectId/ConnectIdPhoneAvailableBottomSheet.java
app/src/org/commcare/fragments/connectId/ConnectIdPhoneFragment.java
app/src/org/commcare/fragments/connectId/ConnectIdPhoneVerificationFragmnet.java
app/src/org/commcare/fragments/connectId/ConnectIdPinFragment.java
app/src/org/commcare/views/CustomButtonWithText.java
app/src/org/commcare/views/connect/RoundedButton.java

Refactor ConnectId Flow Screen UI

---

app/res/values/strings.xml
app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
app/src/org/commcare/fragments/connectId/ConnectIDSignupFragment.java

Changed the titles for a few Connect pages to match the designs in Figma.

Updated Connect page titles

---

app/src/org/commcare/fragments/connect/ConnectDeliveryProgressDeliveryFragment.java

Issue Delivery Progress Sync Button

---

.github/pull_request_template.md

Adds a PR checklist item for Release Notes

---

app/res/drawable/ic_connect_close.xml
app/res/drawable/rounded_top_corners.xml
app/res/layout/fragment_connect_job_detail_bottom_sheet_dialog.xml
app/res/navigation/nav_graph_connect.xml
app/res/values-ti/strings.xml
app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
app/src/org/commcare/fragments/connect/ConnectJobDetailBottomSheetDialogFragment.java
app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java

Set bottom sheet for job details
https://dimagi.atlassian.net/browse/CCCT-563

CCCT-563 || Delivery Detail Bottom Sheet

---

app/res/navigation/nav_graph_connectid.xml
app/src/org/commcare/connect/ConnectConstants.java
app/src/org/commcare/fragments/connectId/ConnectIdMessageFragment.java
app/src/org/commcare/fragments/connectId/ConnectIdPasswordVerificationFragment.java
app/src/org/commcare/fragments/connectId/ConnectIdPhoneFragment.java
app/src/org/commcare/fragments/connectId/ConnectIdPhoneVerificationFragmnet.java

Solved recovery bugs
https://dimagi.atlassian.net/browse/QA-7294
https://dimagi.atlassian.net/browse/QA-7295
https://dimagi.atlassian.net/browse/QA-7296
https://dimagi.atlassian.net/browse/QA-7297

CCCT-7297 || Solved recovery bugs

---

app/res/layout/fragment_recovery_code.xml
app/res/layout/fragment_secondary_phone_number.xml

Solved translation issue
https://dimagi.atlassian.net/browse/QA-7293

QA-7293 || Solved translation issue

---

app/res/layout/fragment_channel_list.xml
app/res/layout/item_channel.xml
app/src/org/commcare/activities/StandardHomeActivity.java
app/src/org/commcare/activities/connect/ConnectMessagingActivity.java
app/src/org/commcare/adapters/ChannelAdapter.java
app/src/org/commcare/fragments/connect/ConnectJobsListsFragment.java
app/src/org/commcare/fragments/connectMessaging/ConnectMessageChannelConsentBottomSheet.java
app/src/org/commcare/fragments/connectMessaging/ConnectMessageChannelListFragment.java
app/src/org/commcare/fragments/connectMessaging/ConnectMessageFragment.java

Bug fix and polling implementation of messaging

Pm messaging

---

app/res/drawable/ic_connect_arrow_forward_24px.xml
app/res/layout-land/home_screen.xml
app/res/layout/dialog_payment_confirmation.xml
app/res/layout/fragment_connect_delivery_details.xml
app/res/layout/fragment_connect_delivery_progress.xml
app/res/layout/fragment_connect_job_intro.xml
app/res/layout/fragment_connect_learning_progress.xml
app/res/layout/fragment_connect_progress_delivery.xml
app/res/layout/fragment_phone_available_bottom_sheet.xml
app/res/layout/fragment_recovery_code.xml
app/res/layout/fragment_secondary_phone_number.xml
app/res/layout/fragment_signup.xml
app/res/layout/home_screen.xml
app/res/layout/screen_connect_message.xml
app/res/layout/screen_connect_password_verify.xml
app/res/layout/screen_connect_phone_verify.xml
app/res/layout/screen_connect_primary_phone.xml
app/res/layout/screen_connect_user_deactivate_otp_verify.xml
app/res/layout/screen_connect_verify.xml
app/res/layout/screen_login.xml
app/res/layout/select_install_mode_fragment.xml
app/res/layout/temp_login.xml
app/res/values/strings.xml
app/src/org/commcare/activities/LoginActivityUiController.java
app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
app/src/org/commcare/fragments/connect/ConnectDeliveryProgressDeliveryFragment.java
app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java

Rounded button changes only for the initial branch for release

Pm round button

---

app/src/org/commcare/activities/FormEntryActivity.java
app/src/org/commcare/activities/FormEntryActivityUIController.java
app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java

- Adds form schema to Form analytics Event
- Adds a new event for form entry
NA
PR mostly Adds a fails safe method  and report to Analytics.

Small modifications to Form analytics 

---

app/res/layout/fragment_connect_progress_delivery.xml

Corrected Delivery Progress Sync button UI
Before:
After:
https://dimagi.atlassian.net/browse/CCCT-735
It is UI bug fix
Manual review of Delivery Progress Sync button

Corrected Delivery Progress Sync button UI

---

app/src/org/commcare/CommCareApplication.java
app/src/org/commcare/logging/analytics/TimedStatsTracker.java
app/src/org/commcare/tasks/DataPullTask.java
app/src/org/commcare/tasks/ManageKeyRecordTask.java

Logging to troubleshoot https://dimagi.atlassian.net/browse/QA-7555
This is a temporary addition and will need to be reverted before release.

Additional logging to troubleshoot the repeated login issue

---

app/src/org/commcare/engine/resource/ResourceInstallUtils.java

Logs an exception to firebase in case of SSL errors.

Logs SSL exception when trying to download app

---

app/src/org/commcare/activities/StandardHomeActivityUIController.java

Now, display short description in home screen for logged in app 
https://dimagi.atlassian.net/browse/CCCT-709
Fix
Confirm the UI changes
Now, app should display short description

Display short description at home screen for logged in app

---

app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/android/database/connect/models/ConnectAppRecord.java
app/src/org/commcare/connect/ConnectIDManager.java
app/src/org/commcare/connect/database/ConnectAppDatabaseUtil.java
app/src/org/commcare/connect/database/ConnectDatabaseHelper.java
app/src/org/commcare/connect/network/ConnectSsoHelper.java

Small corrections with `checkConnectIdLink` method used to link and unlink a CommCare app to connect. 
Please refer to individual commits for details. (Review commit by commit)
The only user visible changes that this  PR should cause The navigation to connect home/ jobs screen should work better in different scenarios if it was not earlier. 
Changes are not tested by me but are done as part of phase2 review and will need to be tested further when backmerging these into main connect branch. 
Should be tested along with phase 2 merge changes

Fixes for check connect link Method

---

app/res/menu/menu_app_home.xml
app/src/org/commcare/activities/StandardHomeActivity.java
app/unit-tests/src/org/commcare/android/tests/DemoUserRestoreTest.java

No visible change to user
Changed the menu in StandardHomeActivity to use an XML resource.
This change sets up menu enhancements in the Connect branch.
None
Tested locally, no expected change to app behavior
None
Test the menu in the app home page and verify that it behaves exactly as it did before.

App home menu using XML resource

---

app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/activities/LoginActivityUIController.java
app/src/org/commcare/connect/ConnectConstants.java
app/src/org/commcare/connect/ConnectIDManager.java
app/src/org/commcare/connect/database/ConnectAppDatabaseUtil.java
app/src/org/commcare/connect/database/ConnectJobUtils.java
app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt
app/src/org/commcare/fragments/SelectInstallModeFragment.java
app/src/org/commcare/utils/CrashUtil.java
app/src/org/commcare/utils/EncryptionKeyAndTransform.java

Updated the missing code from the qa branch and change the request code
Managed the signup button for normal commcare user

-update the missing code, and change the request code value

---

app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java

No visible change
Added a user property to all analytics events containing our uniquely generated CommCare device ID.
None
Simple change to logging
None
None

Added device_id to analytics in user properties.

---

app/res/layout/fragment_recovery_code.xml
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
app/src/org/commcare/connect/ConnectIDManager.java
app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
app/src/org/commcare/utils/JsonExtensions.kt
app/src/org/commcare/views/connect/CustomOtpView.java

Bug fixes for qa regression testing of beta

Pm qa 7730

---

app/src/org/commcare/connect/ConnectManager.java
app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
app/src/org/commcare/fragments/connect/ConnectJobsListsFragment.java
app/src/org/commcare/fragments/connect/ConnectUnlockFragment.java

These changes got left out in https://github.com/dimagi/commcare-android/pull/3075 and is now breaking the build for connect.

Correct method name

---

app/src/org/commcare/android/database/connect/models/ConnectDeliveryDetails.java
app/src/org/commcare/fragments/connect/ConnectDeliveryProgressDeliveryFragment.java

Minor refactor to utilize constructor correctly. 
Motivated by https://github.com/dimagi/commcare-android/pull/3084/files#r2079052133

Use constructor for delivery details

---

app/src/org/commcare/connect/database/ConnectJobUtils.java

https://dimagi.atlassian.net/browse/QA-7739
[Crash](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/1cf5805b5f8de40f5e8676e8cee97112?time=last-hour&types=crash&versions=2.57%20(472005)&sessionEventKey=681DCAEA009A000156075EBA0EE8BAD3_2080821954707560445)
````
Fatal Exception: java.lang.IllegalStateException: Cannot call beginTransaction between calling setTransactionSuccessful and endTransaction
at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListenerInternal(SQLiteDatabase.java:3040)
at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:777)
at net.sqlcipher.database.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:748)
at …
```

fixed Crash on clicking delivery app

---

app/build.gradle

Removed Duplicate depedencies
There will be no impact on any feature

- removed duplicate dependencies

---

app/src/org/commcare/connect/network/ApiPersonalId.java
app/src/org/commcare/connect/network/PersonalIdApiErrorHandler.java
app/src/org/commcare/connect/network/PersonalIdApiHandler.java
app/src/org/commcare/connect/network/connectId/ApiEndPoints.java
app/src/org/commcare/connect/network/connectId/ApiService.java
app/src/org/commcare/connect/network/parser/AddOrVerifyNameParser.java
app/src/org/commcare/connect/network/parser/JsonToSessionDataParser.java
app/src/org/commcare/connect/network/parser/PersonalIdApiResponseParser.java
app/src/org/commcare/connect/network/parser/StartConfigurationResponseParser.java
app/src/org/commcare/fragments/personalId/PersonalIdNameFragment.java
app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java

Call New api end point to check_name in PersonalIdNameFragment
https://dimagi.atlassian.net/browse/CCCT-1221

call api for check_name

---

app/src/org/commcare/connect/network/ApiPersonalId.java
app/src/org/commcare/fragments/personalId/PersonalIdBiometricConfigFragment.java

A couple fixes based on testing the new workflow today

Small Device Configuration Workflow Fixes

---

README.md

Adds info on Google Cloud Project

---

app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java

Integrity token issue solved

---

app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
app/src/org/commcare/utils/AppMetaDataUtil.kt

https://dimagi.atlassian.net/browse/CCCT-1296

Adding app meta data as per https://dimagi.atlassian.net/browse/CCCT-1296

---

app/src/org/commcare/connect/network/ApiPersonalId.java
app/src/org/commcare/connect/network/PersonalIdApiHandler.java
app/src/org/commcare/connect/network/connectId/ApiService.java
app/src/org/commcare/fragments/personalId/PersonalIdNameFragment.java

Two fixes:
1. Retrieving session data from view model when Name fragment starts
2. Added token auth to the check_name call

Configuration workflow fixes

---

app/templates/google-services.json

Updates google services to latest from firebase

Update template google services

---

app/AndroidManifest.xml
app/src/org/commcare/activities/LoginActivityUIController.java
app/src/org/commcare/fragments/SelectInstallModeFragment.java

Hide the go to connect menu button till phase 4 merge is complete from login screen , install fragment

hide go to connect menu button

---

app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java

https://dimagi.atlassian.net/browse/QA-7824

Backup code error when not matching criteria

---

app/res/values-fr/strings.xml
app/res/values-pt/strings.xml
app/res/values-sw/strings.xml
app/res/values-ti/strings.xml

Compile issue solved due to string not present in default locale

---

app/AndroidManifest.xml
app/src/org/commcare/connect/SMSBroadcastReceiver.java
app/src/org/commcare/connect/SMSListener.java
app/src/org/commcare/fragments/personalId/PersonalIdPhoneVerificationFragment.java

https://dimagi.atlassian.net/browse/CCCT-1307
Fixed otp autofill in phone verification using User Consent API Method 
https://github.com/user-attachments/assets/f8f81825-809f-4fad-bb5d-b9f8796a96ea

 fixed otp autofill

---

app/src/org/commcare/activities/CommCareSetupActivity.java
app/src/org/commcare/activities/LoginActivity.java
app/src/org/commcare/connect/PersonalIdManager.java
app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java
app/src/org/commcare/fragments/personalId/PersonalIdBiometricConfigFragment.java
app/src/org/commcare/fragments/personalId/PersonalIdPhotoCaptureFragment.java
app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
app/src/org/commcare/utils/GlobalErrorUtil.java

Corrects logging of personal ID events.

Fixes some incorrect analytics logging + rename events to make them more clear what they represent

---

app/build.gradle
app/proguard.cfg
app/res/layout/screen_connect.xml
app/res/navigation/nav_graph_connect.xml
app/src/org/commcare/activities/connect/ConnectActivity.java

Copy of Pm_qa_7909
https://dimagi.atlassian.net/browse/QA-7909
Issue:- Nav host JobListFragment is calling the api and retuning the result after it got detached and the LearningProgress is up thats why it was crashing 
Stacktrace
````
Process: org.commcare.dalvik.debug, PID: 4732
java.lang.IllegalStateException: Fragment ConnectJobsListsFragment{93ac5ec} (54dfe6c0-d31b-4827-bc56-69918d041811) not attached to an activity.
at androidx.fragment.app.Fragment.requireActivity(Fragment.java:1000)
at org.commcare.fragments.connect.ConnectJobsListsFragment.processJobRecords(ConnectJobsListsFragment.java:347)
at org.commcare.fragments.connect.ConnectJobsListsFragment.createJobModel(ConnectJobsListsFragment.java:315)
at org.commcare.fragments.connect.ConnectJobsListsFragment.setJobListData(ConnectJob …
```

- fixed view jib status click issue

---

app/res/layout/connect_delivery_item.xml
app/res/layout/fragment_connect_delivery_list.xml
app/src/org/commcare/adapters/ConnectDeliveryProgressReportAdapter.java
app/src/org/commcare/fragments/connect/ConnectDeliveryListFragment.java
app/src/org/commcare/fragments/connect/ConnectDeliveryProgressDeliveryFragment.java

Resolved phase 4 comments 
https://github.com/dimagi/commcare-android/pull/3108#discussion_r2205403731
https://github.com/dimagi/commcare-android/pull/3108#discussion_r2205394625
https://github.com/dimagi/commcare-android/pull/3108#discussion_r2205372517

Pm phase4 merge comments

---

app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java

https://dimagi.atlassian.net/browse/CCCT-1472

Adds build number to analytics

---

app/src/org/commcare/connect/network/ApiPersonalId.java
app/src/org/commcare/connect/network/ApiService.java
app/src/org/commcare/connect/network/ConnectSsoHelper.java
app/src/org/commcare/connect/network/base/BaseApiCallback.kt
app/src/org/commcare/connect/network/base/BaseApiHandler.kt
app/src/org/commcare/connect/network/connectId/PersonalIdApiHandler.java
app/src/org/commcare/connect/network/connectId/parser/ConnectTokenResponseParser.kt
app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt

https://dimagi.atlassian.net/browse/CCCT-1409
Check the connect complete cycle

Retrofit applied to connectId token and connect heart beat

---

app/src/org/commcare/activities/CommCareSetupActivity.java

Crashlytics issue: https://console.firebase.google.com/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/7f24c229a2dfd2918fbdd7fc8981f50d
Ticket: https://dimagi.atlassian.net/browse/CI-21

Fix NPE during CommCareSetupActivity menu preparation

---

app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt

Duplicating change made to master for 2.59.1 hotfix

fix issue with connect hearbeat due to incorrect sequencing

---

app/src/org/commcare/activities/connect/viewmodel/PersonalIdCredentialViewModel.kt
app/src/org/commcare/connect/network/ApiPersonalId.java
app/src/org/commcare/connect/network/connectId/PersonalIdApiHandler.java

Updated `credential` api to use userId instead of userName

Updated credential api to user userId
