app/res/layout/fragment_progress_dialog.xml, app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java, app/src/org/commcare/dalvik/activities/CommCareVerificationActivity.java, app/src/org/commcare/dalvik/activities/LoginActivity.java, app/src/org/commcare/dalvik/dialogs/CustomProgressDialog.java, app/src/org/commcare/dalvik/dialogs/DialogController.java
This came up in conversation and sounded like an easy win.
The one rough edge is that some tasks only need a progress bar some of the time, e.g., during login, an empty progress bar shows while the message says "Communicating with server" so that it can be used when the message switches to "Processing server data: X/Y."
=> Add progress bar to CustomProgressDialog

app/src/org/commcare/android/view/ViewUtil.java
Fixes issues where some menu options can have optional prefixes which aren't cleared out, making them have leading/trailing ${0} stringargs
=> Automatically Clear Arguments

app/src/org/odk/collect/android/widgets/StringWidget.java
Fixes a bug that replaced the value of anything entered into a "secret" field with all asterisks if the user navigated back and forth
=> "Secret" input fix

app/src/org/commcare/android/adapters/EntityListAdapter.java
Fixes a bug introduced with background searching when double management is enabled for non-async entity selects
=> Double Management Fix

app/src/org/commcare/android/database/user/UserDatabaseUpgrader.java, app/src/org/commcare/android/database/user/models/CaseIndexTable.java, app/src/org/commcare/dalvik/application/CommCareApplication.java
Fixes for:
A) The Case upgrader timing out on very large caseloads (NOTE: User experience still isn't good, but at least the user can log in)
B) bug in 5->6 upgrade path causing deadlock between the session and the upgrader
=> Fixes for in-place DB Migrations/Upgrades

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/dalvik/activities/CallOutActivity.java
Fix for callout failures, as described in [157429 - CommCare Doesn't Handle Failed Phone Dialer Intent Callout failure gracefully] (http://manage.dimagi.com/default.asp?157429#883355).
In case of failure (when there is no dialer/SMS app installed), the chooser displays an error toast instead of crashing the app.
=> Handling dialer/sms app failures gracefully

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
Fix for the bug [159047](http://manage.dimagi.com/default.asp?159047), in which the home screen dropdown would not be refreshed automatically when settings changed.
=> Refreshing home screen dropdown on locale change

app/src/org/commcare/dalvik/activities/CallOutActivity.java
Fixing bug [156775](http://manage.dimagi.com/default.asp?156775#885522), in which the dialer app is called but returns to a blank screen instead of back to the details screen.
=> 156775 - Commcare - Clicking on Phone Number on Case List Takes You to Form List

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
Solving bug [159047](http://manage.dimagi.com/default.asp?159047), follow-up to [166](https://github.com/dimagi/commcare-odk/pull/166), to solve localization issues after an app install with an international default locale.
=> Rebuilding 'settings' dropdown on clean install

app/src/org/commcare/android/tasks/VerificationTask.java, app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
When in [superuser mode] (https://github.com/dimagi/commcare-odk/blob/d6a7df6f546caffc3b0ba44461aaf3725fa762c8/app/src/org/commcare/dalvik/preferences/DeveloperPreferences.java#L65), ignores the multimedia validation step result, always returning success. 
Useful if installing an app just for development/testing purposes.
=> Ignoring multimedia validation when superuser

.gitignore
these files showed up as untracked after importing a freshly pulled repo into Android Studio.
=> add android studio generated files to gitignore

app/src/org/commcare/android/tasks/ExceptionReportTask.java, app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java
When returning from FormEntryActivity after a form error occurs, the result code in CommCareHomeActivitiy.onActivityResult was always RESULT_OK, so exception handling never happened. I hence removed the code that tried to do that handling and just logged the form errors when they occurred.
=> Remove dead error-handling code in CommCareHomeActivitiy.onActivityResult

app/src/org/commcare/android/adapters/IncompleteFormListAdapter.java, app/src/org/commcare/android/tasks/FormRecordLoaderTask.java, app/src/org/commcare/dalvik/activities/FormRecordListActivity.java
When filtering over saved forms and changing the form status to list, the filtering method would crash because it tried to filter data before it was loaded. This commit  ensures that filtering only occurs after FormRecord text data has been loaded.
The biggest change is that IncompleteFormListAdapter extends FormRecordLoadListener and adds itself to the listeners to be called when FormRecordLoaderTask finishes loading data, in order to filterValues at the proper time.
Fixes [bug 161420](http://manage.dimagi.com/default.asp?161420)
=> Drop down search crash

app/src/org/commcare/android/cases/AndroidCaseInstanceTreeElement.java
Introduced a small bullet test for optimizing case index lookups heuristically.
Should only affect people who are performing operations where they retrieve bulk data like graphing, but should really speed up anywhere where those ops are performed repeatedly.
=> Relative index lookup caching

app/src/org/commcare/android/view/GraphView.java
Parto's horizontal grid lines weren't showing because apparently using custom labels means grid lines are controlled by a different function.
=> Show grid even when using custom labels

app/src/org/commcare/android/models/NodeEntityFactory.java
Fields with XPath errors have been getting dropped altogether from case details.
Testing for relevancy can itself cause XPath errors, so just display fields with errors without checking for relevancy.
=> Silent XPath errors

app/src/org/commcare/dalvik/activities/EntityDetailActivity.java, app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
Prevent EntityDetailActivity's "Continue" button from being displayed while in landscape mode
Also fix code that rotates from landscape to portrait with an entity selected and launches EntityDetailActivity with that selection.
[Bug 163637](http://manage.dimagi.com/default.asp?163637)
=> Don't show next button during view + landscape mode

app/src/org/commcare/android/adapters/MenuAdapter.java
Partial fix for http://manage.dimagi.com/default.asp?164631
Evaluation context was created using the first module with a relevancy condition, which could cause later modules with relevancy conditions to fail.
=> Don't cache EvaluationContext

app/src/org/commcare/dalvik/preferences/CommCarePreferences.java, app/src/org/commcare/dalvik/services/CommCareSessionService.java
To test apps we need to be able to set session expiration lengths to be on the order of seconds/minutes, so changed this app preference to be in terms of seconds instead of hours.
=> Change login duration setting to be represent seconds not hours

app/res/values-es/strings.xml, app/res/values-fr/strings.xml, app/res/values-lt/strings.xml, app/res/values-no/strings.xml, app/res/values-pt/strings.xml, app/res/values-sw/strings.xml, app/res/values/strings.xml, app/src/org/odk/collect/android/activities/FormEntryActivity.java
Remove form entry options to clear an answer or delete a repeat entry, except for in the case of select one/select multiple question types. These options pop up when you long-press question entry areas, which often blocks availability of normal android paste/select functionality.
=> Remove 'delete repeat/clear answer' long-tap option

app/src/org/odk/collect/android/jr/extensions/PollSensorExtensionParser.java, app/src/org/odk/collect/android/logic/FormController.java
IDataReference (from javarosa) was an unused abstraction, causing a bunch of unneeded indirection in the code
Cross-requested with https://github.com/dimagi/javarosa/pull/73
=> Remove IDataReference (from javarosa)

app/src/org/odk/collect/android/widgets/AudioWidget.java, app/src/org/odk/collect/android/widgets/VideoWidget.java
Audio and Video widgets use an out of date method for converting URIs into filepaths.
This PR changes them to use the 4.4+ compatible version.
=> Android 4.4+ compat process to convert URI->filepath

app/src/org/commcare/dalvik/preferences/CommCarePreferences.java
Change the default app session length from 8 hrs (28800 seconds) to 24 hrs (86400 seconds)
=> Change default session length from 8 to 24 hrs

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java
When returning from FormEntryActivity to the CommCareHomeActivity, forms weren't correctly being synced. This PR fixes that by adding and extra to the intent returned from FormEntryActivity that signals if the form that was being processed was an archive or a newly saved form.
[ticket](http://manage.dimagi.com/default.asp?167352#932439)
=> Home activity detects if form entry was processing archive or new form

app/src/org/commcare/android/models/AndroidSessionWrapper.java
Saw the following trace in the device log details and figured the null check in this PR would be a good idea
java.lang.NullPointerException at org.commcare.android.models.AndroidSessionWrapper.commitRecordTransaction(AndroidSessionWrapper.java:172) at org.commcare.dalvik.odk.provider.InstanceProvider.linkToSessionFormRecord(InstanceProvider.java:488) at org.commcare.dalvik.odk.provider.InstanceProvider.update(InstanceProvider.java:398) at android.content.ContentProvider$Transport.update(ContentProvider.java:287) at android.content.ContentResolver.update(ContentResolver.java:1321) at org.odk.collect.android.tasks.SaveToDiskTask.updateInstanceDatabase(SaveToDiskTask.java:154) at org.odk.collect.android.tasks.SaveToDiskTask.exportData(SaveToDiskTask.java:217) at …
=> Null check to try to fix NPE

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
When the user launches the media validator manually, and media validation fails, then when they press the back button, the app shouldn't exit (current behavior) but rather the user should be returned to the home screen.
=> Manual launch of media validation shouldn't exit app on failure

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
Erroring-out of form entry took the user back to the module selection screen, whereas it should take one back to the form selection screen. 
[ticket](http://manage.dimagi.com/default.asp?167803#935571)
=> Form cancel should redirect to form selection

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/application/CommCareApplication.java, app/src/org/commcare/dalvik/preferences/CommCarePreferences.java
@wspride in commit f8928c70076b9b1a9dafb79eef17420815820647 , you added the following logic that I am now asking to be removed. That commit edited some preferences but never committed them by calling '.commit()'. This means that AUTO_TRIGGER_UPDATE was always set to false, making the statements removed in the PR no-ops.
I initially added '.commit()' back in but it broke things, so I decided to remove the code, since it is unclear what the intent of the logic was.
=> Remove pref edits that were never committed

app/src/org/commcare/dalvik/activities/CommCareFormDumpActivity.java, app/src/org/commcare/dalvik/activities/ConnectionDiagnosticActivity.java
Removing unused class fields that caused a crash when CommCareActivity tried to load them when screen orientation changes.
[ticket](http://manage.dimagi.com/default.asp?167532#939390)
=> Removed unused fields that cause crash on 4.2.2

app/src/org/odk/collect/android/activities/FormEntryActivity.java
- If the session expires while the form is loading, don't try to save it.
- Don't relaunch form save task if it is already running
=> Don't save unloaded forms on session expiration

app/src/org/commcare/dalvik/services/CommCareSessionService.java
When the session expires and a form tries to save, there is a timeout period, which when reached the form saving is aborted. Increase this timeout to 90 seconds because who knows how long it might take to save some huge form on a slow phone.
=> Increase form save logout timeout to 90 secs

app/src/org/commcare/android/api/ExternalApiReceiver.java, app/src/org/commcare/android/tasks/DataPullTask.java, app/src/org/commcare/android/tasks/LogSubmissionTask.java, app/src/org/commcare/android/tasks/SendTask.java, app/src/org/commcare/android/util/CommCareUtil.java, app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/activities/ConnectionDiagnosticActivity.java, app/src/org/commcare/dalvik/activities/EntityDetailActivity.java, app/src/org/commcare/dalvik/activities/FormRecordListActivity.java, app/src/org/commcare/dalvik/activities/RecoveryActivity.java, app/src/org/commcare/dalvik/application/CommCareApplication.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java
Many places call getSession (the CommCareSessionService one, not the one with unfortunately the same name found in AndroidSessionWrapper). These calls usually occur when a task, that accesses the user database, is getting ready to spin up. 
This PR wraps almost all calls to getSession in a try/catch to handle when the session has expired and is no longer available. In most cases such failed calls to getSession will result in tasks not getting launched.
=> Wrap getSession calls in try/catch

app/src/org/commcare/android/tasks/EntityLoaderTask.java, app/src/org/commcare/android/tasks/FormRecordLoaderTask.java, app/src/org/commcare/android/tasks/templates/CommCareTask.java, app/src/org/commcare/android/tasks/templates/CommCareTaskConnector.java, app/src/org/commcare/android/tasks/templates/ManagedAsyncTask.java, app/src/org/commcare/dalvik/services/CommCareSessionService.java
Was experiencing a crash in EntityLoaderTask, where if the database closed when it was running, it would crash commcare. Fix this by canceling the task when the db is closed.
- Create ManageAsyncTask to keep track of running tasks.
- ManageAsyncTask.cancelTasks calls cancel on all the running tasks; call on session expiration
- have CommCareTask extend it ManageAsyncTask
=> ManageAsyncTasks; enabling task cancellation on session expiration

app/src/org/commcare/android/tasks/DataPullTask.java, app/src/org/commcare/android/tasks/ProcessAndSendTask.java, app/src/org/commcare/dalvik/services/CommCareSessionService.java
Make ProcessAndSendTask and DataPullTask background tasks acquire a session logout lock so that the session can't close down when they are running.
Eventually when the task finishes then the session will be able to grab the lock and close down.
=> Make session only expire if syncing isn't occurring

app/src/org/odk/collect/android/views/ODKView.java
QA is experiencing a strange crash when session expiration tries to save a form that has questions that violate constraints.
I was unable to reproduce the bug, but worked off of the stack trace, found at http://manage.dimagi.com/default.asp?168163#945195
=> Check array size before removing questions and dividers

app/src/org/commcare/android/models/logic/FormRecordProcessor.java, app/src/org/commcare/android/tasks/FormRecordCleanupTask.java, app/src/org/commcare/android/tasks/ManageKeyRecordTask.java, app/src/org/commcare/xml/CommCareTransactionParserFactory.java, app/src/org/commcare/xml/FormInstanceXmlParser.java, app/src/org/commcare/xml/KeyRecordParser.java, app/src/org/commcare/xml/MetaDataXmlParser.java, app/src/org/commcare/xml/UserXmlParser.java
Since TransactionParser and its extensions didn't use the following, remove them:
-  'parses' method
- 'name' and 'namespace' fields
Change TransactionParserFactory's getParser to not take in a name or namespace field. These were rarely used, and in the cases that they were, the name/namespace values were obtained from the parser argument, and hence were redundant.
Cross requested with https://github.com/dimagi/commcare/pull/84
=> Remove TransactionParser's name & namespace fields

app/src/org/commcare/android/adapters/IncompleteFormListAdapter.java, app/src/org/commcare/android/tasks/FormRecordLoadListener.java, app/src/org/commcare/android/tasks/FormRecordLoaderTask.java, app/src/org/commcare/dalvik/activities/FormRecordListActivity.java
The 'Saved Form Listing' view was trying to load saved forms more than once and only showing results once everything had loaded. 
This PR makes sure forms loading doesn't occur more than once per view entry and enables incremental results to be displayed.
Hopefully helpful for this [ticket](http://manage.dimagi.com/default.asp?167729)
=> Display saved forms incrementally; only call load once.

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
When autosyncs were triggered, it was possible for them to occur before submissions were fired off, which could dangerously leave the phone in a bad state.
Fix for
http://manage.dimagi.com/default.asp?170109
=> Fix for autosync jumping in before submission

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
When there are large submissions this prevents a period of nonmodal behavior
=> Usability fix for sync fix

app/src/org/odk/collect/android/tasks/FormLoaderTask.java
Formdef deserialziation wasn't buffered before and its run through a complex process, so this makes a massive difference on large forms.
=> [Minor] Buffer formdef deserialization for major improvement in load times

app/src/org/commcare/dalvik/activities/FormRecordListActivity.java
Solving bug [171246](http://manage.dimagi.com/default.asp?171246), in which the incomplete forms screen would not show any elements.
=> Incomplete forms loading its elements on every refreshView()

app/src/org/commcare/dalvik/activities/CallLogActivity.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/preferences/PreferencesActivity.java
Solving bug [172119](http://manage.dimagi.com/default.asp?172119) in the new UI, caused by using the deprecated method managedQuery() in APIs greater than Honeycomb.
See also https://github.com/dimagi/commcare-odk/pull/339.
=> NewUI - Changing managedQuery to CursorLoader

app/src/org/commcare/dalvik/activities/CallLogActivity.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/preferences/PreferencesActivity.java
Solving bug [172119](http://manage.dimagi.com/default.asp?172119), caused by using the deprecated method managedQuery() in APIs greater than Honeycomb.
Now using the recommended CursorLoader class instead.
See also https://github.com/dimagi/commcare-odk/pull/340
=> Changing managedQuery to CursorLoader

app/src/org/odk/collect/android/widgets/TriggerWidget.java, app/src/org/odk/collect/android/widgets/WidgetFactory.java
In https://github.com/dimagi/commcare-odk/pull/313 I made all text in trigger widgets (output labels in form builder) selectable. Clayton & Amelia then decided that it would be bad to make text selectable since non-tech-savy users might get confused after long-pressing text on accident.
This PR makes trigger widget text only selectable if you set the appearance field (found under the Advanced tab) to 'selectable' in the form builder.
=> Trigger text selectable only when 'appearance' hint is set to 'selectable'

app/src/org/commcare/android/util/CommCareInstanceInitializer.java, app/src/org/odk/collect/android/views/ResizingImageView.java
Relates to this ticket:
http://manage.dimagi.com/default.asp?171248
Basically our old algorithm would not resize UP a very small image unless the getMinimumHeight() method of the parent view suggested it. This seems to go against the feature definition of full/half/width resizing which suggests that the image will be stretched to take up that amount of the screen.
I think this change does the correct thing (just use the max width/height of the screen for calculation baselines). However, the image resizing is tricky (figuring our how much screen real estate you actually have esp. given nav bar, keyboard, variable widget sizes, etc) so I don't know if there's a completely "correct" way to do this. Happy to hear comment.
=> fix image resizing

app/src/org/commcare/android/models/AndroidSessionWrapper.java
mockEasiestRoute, which is used to create a SessionStateDescriptor for a form instance that is manually being loaded onto the phone from an external source, had the following bug:
instead of creating a descriptor of this nature
"COMMAND_ID m0 COMMAND_ID m0-f0 CASE_ID case_id_new_pregnancy_0 ..."
the module id 'm0' was being replaced by the entry id 'm0-f0'
"COMMAND_ID m0-f0 COMMAND_ID m0-f0 CASE_ID case_id_new_pregnancy_0 ..."
This PR fixes this by calling a method that find the module id for an entry.
Cross requested with https://github.com/dimagi/commcare/pull/88
=> Correctly register the module id in mockEasiestRoute

app/ant.properties
Jenkins build is broken without this configuration.
=> Specifying Java 1.7 in ant.properties

app/src/org/odk/collect/android/activities/FormEntryActivity.java
NewUI fix for [this ticket](http://manage.dimagi.com/default.asp?174380)
How to reproduce the crash (thanks to Clark):
- Open a form to edit
- save your progress using the right-hand settings menu.
- In the same settings menu, click "Go to prompt" and then "Go to beginning" or "Go to end"
- Experience the wondrous crash
Cross-requested with old ui: https://github.com/dimagi/commcare-odk/pull/364
=> Remove deprecated use of startManagingCursor

app/src/org/odk/collect/android/activities/FormEntryActivity.java
OldUI fix for [this ticket](http://manage.dimagi.com/default.asp?174380)
How to reproduce the crash (thanks to Clark):
- Open a form to edit
- save your progress using the right-hand settings menu.
- In the same settings menu, click "Go to prompt" and then "Go to beginning" or "Go to end"
- Experience the wondrous crash
Cross-requested with new ui: https://github.com/dimagi/commcare-odk/pull/355
=> Remove deprecated use of startManagingCursor (old ui)

app/src/org/commcare/android/net/HttpRequestGenerator.java, app/src/org/commcare/android/tasks/SendTask.java, app/src/org/commcare/android/util/FormUploadUtil.java, app/src/org/commcare/dalvik/activities/CommCareFormDumpActivity.java, app/src/org/commcare/dalvik/activities/CommCareWiFiDirectActivity.java, app/src/org/odk/collect/android/widgets/AudioWidget.java
Fix for [this ticket](http://manage.dimagi.com/default.asp?173209)
NewUi version of this PR: https://github.com/dimagi/commcare-odk/pull/358
There was a bug where the sync process wasn't sending certain case audio attachments up to HQ. The problem was that only a handful of hard coded filetypes were accepted as valid.
This PR allows for all files that have an audio, video, or image mimetype to be uploaded as case attachments to HQ.
Note: currently if a case is uploaded to HQ that expects an attachment but the phone didn't include that attachment, the only info HQ returns is a 500 error.
Also includes:
- made AudioWidget stop adding double backslashes to filepaths
- removed unneeded platform parameter from SendTask constructor
- Refactored FormUploadUtil to use helper methods
- make …
=> Allow uploading of all audio, image, and video filetypes to HQ (newui version)

app/src/org/commcare/android/net/HttpRequestGenerator.java, app/src/org/commcare/android/tasks/SendTask.java, app/src/org/commcare/android/util/FormUploadUtil.java, app/src/org/commcare/dalvik/activities/CommCareFormDumpActivity.java, app/src/org/commcare/dalvik/activities/CommCareWiFiDirectActivity.java, app/src/org/odk/collect/android/widgets/AudioWidget.java
Fix for [this ticket](http://manage.dimagi.com/default.asp?173209)
OldUi version of this PR: https://github.com/dimagi/commcare-odk/pull/357
There was a bug where the sync process wasn't sending certain case audio attachments up to HQ. The problem was that only a handful of hard coded filetypes were accepted as valid.
This PR allows for all files that have an audio, video, or image mimetype to be uploaded as case attachments to HQ.
Note: currently if a case is uploaded to HQ that expects an attachment but the phone didn't include that attachment, the only info HQ returns is a 500 error.
Also includes:
- made AudioWidget stop adding double backslashes to filepaths
- removed unneeded platform parameter from SendTask constructor
- Refactored FormUploadUtil to use helper methods
- make …
=> Allow uploading of all audio, image, and video filetypes to HQ (oldui version)

app/src/org/odk/collect/android/activities/FormEntryActivity.java
2.21 hotfix for [this ticket](http://manage.dimagi.com/default.asp?174380)
Ran this on a 2.21.0 build, verifying that the bug is present and fixed by this PR
How to reproduce the crash (thanks to Clark):
- Open a form to edit
- save your progress using the right-hand settings menu.
- In the same settings menu, click "Go to prompt" and then "Go to beginning" or "Go to end"
- Experience the wondrous crash
Fix has already gone into 2.22 https://github.com/dimagi/commcare-odk/pull/355
=> startManagingCursor 2.21 hotfix

app/src/org/commcare/dalvik/activities/CallLogActivity.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/preferences/PreferencesActivity.java
Found a managed cursor bug that is fixed by this PR, so I figured I'd include it in the 2.21 hotfix.
to reproduce:
- save incomplete form
- re-open form
- click save in the top right settings
- click go to prompt, and go to start
- crash!
@dcluna PR comments for these changes:
Solving bug [172119](http://manage.dimagi.com/default.asp?172119), caused by using the deprecated method managedQuery() in APIs greater than Honeycomb.
Now using the recommended CursorLoader class instead.
See also https://github.com/dimagi/commcare-odk/pull/340
=> Changing managedQuery to CursorLoader (2.21 hotfix)

app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
The UI refactors took out some error handling:
https://github.com/dimagi/commcare-odk/commit/07c1c36ad4af256e63b30758c7d569c8f8fc0773#diff-8ceab6edefa7a1717265df3ea8d93ffaL496
This PR restores the error handling that re-asks for the install reference if CommCare has trouble processing the reference.
=> Ensure reference is valid before continuing install

unit-tests/src/org/commcare/android/util/TestUtils.java
The TransactionParserFactory.getParser interface changed a while ago. This PR updates the unit test to match that new interface.
=> Update unit test to correctly override getParser

app/AndroidManifest.xml
Correct spelling error in "android.permission.ACESS_NETWORK_STATE"
Not sure how this error in this ticket came up though:
http://manage.dimagi.com/default.asp?175355
=> Spelling error in permission of Android Manifest

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Proposing a 2.21.2 hotfix because:
The issues persist with http://manage.dimagi.com/default.asp?171001#971103
Now getting something like:
```
java.lang.RuntimeException: Unable to resume activity {org.commcare.dalvik/org.odk.collect.android.activities.FormEntryActivity}: java.lang.IllegalStateException: database /data/data/org.commcare.dalvik/databases/instances.db already closed
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2139)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:966)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3714)
at …
```
=> Replace managedQuery/CursorLoader with getContentResolver().query

app/AndroidManifest.xml
For the [2.21.2 hotfix](https://github.com/dimagi/commcare-odk/pull/390) build
=> hotfix 2.21.2 version bump

app/assets/locales/messages_ccodk_default.txt, app/res/values/strings.xml, app/src/org/commcare/android/util/FormUploadUtil.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/views/ODKView.java, app/src/org/odk/collect/android/widgets/AudioWidget.java, app/src/org/odk/collect/android/widgets/ImageWidget.java, app/src/org/odk/collect/android/widgets/QuestionWidget.java, app/src/org/odk/collect/android/widgets/VideoWidget.java
Don't let user select multimedia files of invalid type during form entry.
Currently, when the user chooses a non-supported file for the audio/video/image widget during form entry, no warning is shown. Then the form fails to be uploaded to the server because of it.
This PR shows an error message and clears the user's file choice if they try to use a file that isn't supported for audio/video/image widget.
Fix for [this ticket](http://manage.dimagi.com/default.asp?173209)
oldui version of this: https://github.com/dimagi/commcare-odk/pull/400
=> Check multimedia file extension during form entry

app/assets/locales/messages_ccodk_default.txt, app/res/values/strings.xml, app/src/org/commcare/android/util/FormUploadUtil.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/views/ODKView.java, app/src/org/odk/collect/android/widgets/AudioWidget.java, app/src/org/odk/collect/android/widgets/ImageWidget.java, app/src/org/odk/collect/android/widgets/QuestionWidget.java, app/src/org/odk/collect/android/widgets/VideoWidget.java
The old ui version of https://github.com/dimagi/commcare-odk/pull/399
Don't let user select multimedia files of invalid type during form entry.
Currently, when the user chooses a non-supported file for the audio/video/image widget during form entry, no warning is shown. Then the form fails to be uploaded to the server because of it.
This PR shows an error message and clears the user's file choice if they try to use a file that isn't supported for audio/video/image widget.
Fix for [this ticket](http://manage.dimagi.com/default.asp?173209)
=> Check multimedia file extension during form entry (oldui)

app/src/org/commcare/android/fragments/SetupEnterURLFragment.java
Autofilling the default location when user chooses 'Raw' prefix and automatically handling URLs without a :// prefix.
This complements #388.
=> Fixing autocomplete issues with 'Raw' prefix

app/src/org/commcare/android/view/EntityView.java
Make calculateDetailWidths better handle cases where the requested column widths don't fit well into the available screen width.
Putting in master rather than 2.22 because HQ shouldn't actually be generating problem layouts unless you're using very large icons in case details. Which is possible, since previously HQ would scale any large icons down to 13%, but pretty edge-casey.
=> Better handle edge cases in case list widths

app/src/org/commcare/android/tasks/ConnectionDiagnosticTask.java, app/src/org/commcare/android/tasks/DataPullTask.java, app/src/org/commcare/android/tasks/FormTransferTask.java, app/src/org/commcare/android/tasks/ResourceEngineTask.java, app/src/org/commcare/android/tasks/UnzipTask.java, app/src/org/commcare/android/tasks/templates/CommCareTask.java, app/src/org/commcare/android/tasks/templates/HttpCalloutTask.java, app/src/org/commcare/dalvik/activities/LoginActivity.java
Don't try to switch on a null value, which occurs when the DataPullTask launched by LoginActivity errors out. Noticed this when looking at this crash from the play store crash reports: 
```
java.lang.NullPointerException
at org.commcare.dalvik.activities.LoginActivity$3.deliverResult(LoginActivity.java:181)
at org.commcare.dalvik.activities.LoginActivity$3.deliverResult(LoginActivity.java:173)
at org.commcare.android.tasks.templates.CommCareTask.onPostExecute(CommCareTask.java:83)
at android.os.AsyncTask.finish(AsyncTask.java:417)
at android.os.AsyncTask.access$300(AsyncTask.java:127)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at …
```
=> Fix app crash in LoginActivity & persistently log any task crashes

app/src/org/odk/collect/android/logic/FormController.java, app/src/org/odk/collect/android/tasks/FormLoaderTask.java
The FormDef parameter was unused in TreeElement.populate, so remove it.
Cross-request: https://github.com/dimagi/javarosa/pull/123
=> TreeElement.populate remove unused method argument

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
Linting of CommCareHomeActivity.
I did remove several throw/catches for SessionUnavailableException that weren't relevant. Those blocks are really throwing SessionStateUninitException. It should be possible to refactor the code to avoid needing to ever throw SessionStateUninitException; I will leave this to a future PR.
Easiest to review commit by commit.
=> Refactor CommCareHomeActivity

app/src/org/commcare/android/util/ACRAUtil.java, app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/activities/LoginActivity.java, app/src/org/commcare/dalvik/activities/ReportProblemActivity.java, app/src/org/commcare/dalvik/application/CommCareApplication.java
ACRA crashes and blocks stack traces when it isn't setup correctly.
This PR disables ACRA if the submission url isn't a valid url.
=> Disable acra if submission url isn't valid

app/res/drawable/circle_button.xml
Small UI fix: making the case drawer detail button's background transparent.
=> Fixing black background circle in case detail drawer

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
Migrating to gradle broke the CommCare home screen buttons.
Until we identify the issue, this PR reverts back to the old ui, so that we can continue development in other parts of the code base.
This is a messy PR: I didn't test if all the homescreen button text functionality works. Should be ok, since it is meant to be reverted in the future.
=> Revert to OldUI homescreen buttons temporarily

build.gradle
After pull https://github.com/dimagi/commcare-odk/pull/453 I was experiencing some build issues.
The first error I got was multiple dex files error. I fixed that by disabling incremental dexing.
The second error I got was stlport_shared.so missing, fixed that by setting the jniLibs dirs.
=> Gradle: Set jni dir instead of using native lib task

app/src/org/commcare/android/adapters/HomeScreenAdapter.java, app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
@dcluna, while reviewing your UI refactor I asked you about the code in HomeScreenAdapter that did resource lookup based on resource id. I forgot what your reasoning was, so maybe this PR is moot. 
Regardless, I noticed that the lookupID parameter is always false, so I removed all the code that depends on it being set to true. If it was in fact being used we can close this PR.
=> Remove button lookup via resource id from HomeScreenAdapter

app/src/org/commcare/android/view/EntityView.java
When rows in case list have no icons, they currently have a white background - the correct behavior is to show nothing (transparent background).
=> Fixing bug where rows in case list with no icon had a white background

app/src/org/commcare/android/tasks/ResourceEngineListener.java, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
I kept confusing the very similar updateProgress interfaces found in ResourceEngineListener and DialogController.
This PR renames ResourceEngineListener one to updateResourceProgress
=> Rename ResourceEngineListener.updateProgress to not conflict w/ DialogController.updateProgress

app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/dalvik/activities/EntityMapActivity.java, app/src/org/commcare/dalvik/activities/EntitySelectActivity.java, app/src/org/commcare/dalvik/activities/FormRecordListActivity.java
CommCareActivity.onStop overrides the protected onStop method in Activity, making it public, which is an accepted pattern. That said, there doesn't seem to be a reason for doing this (at least in the current state of the code base). Once the public modifier is changed to protected the overriding method just calls super, so we can safely remove it.
=> CommCareActivity.onStop shouldn't be public or even there

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Noticed some logic surrounding mErrorMessage in FormEntryActivity, which was never being written (other than in onSaveInstanceState)
=> Removed unused error logic from FormEntryActivity

app/res/layout/screen_login.xml
Noticed that the login screen was behaving in a weird way in devices with small screens (such as my 2.3.7 emulated phone), so this PR fixes that.
Changes:
Added scrolling capabilities to the login screen.
Ensuring the 'Log In' box has the minimum padding top and bottom.
=> Small fixes to the login screen

app/src/org/commcare/android/framework/CommCareActivity.java
activityPaused is set to false in onPause, so we should set it to true in onResume, not onCreate.
=> Set activityPaused flag in onResume, not onCreate

app/src/org/commcare/android/framework/CommCareActivity.java
Fix for a problem with https://github.com/dimagi/commcare-odk/pull/420 
Since we now stop connecting to progress dialog in CommCareActivity while it is paused, we want to always reconnect to dialog upon resume.
=> Always store progress dialog id & restore dialog in onResume

app/src/org/odk/collect/android/activities/FormEntryActivity.java
In old Android versions, the progress bar in form entry does not appear. This PR fixes that.
=> Fixing invisible progressbar in old devices

app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/android/framework/SessionAwareCommCareActivity.java, app/src/org/commcare/dalvik/activities/CommCareFormDumpActivity.java, app/src/org/commcare/dalvik/activities/CommCareWiFiDirectActivity.java, app/src/org/commcare/dalvik/activities/ConnectionDiagnosticActivity.java, app/src/org/commcare/dalvik/activities/EntityDetailActivity.java, app/src/org/commcare/dalvik/activities/EntitySelectActivity.java, app/src/org/commcare/dalvik/activities/FormRecordListActivity.java, app/src/org/commcare/dalvik/activities/MenuGrid.java, app/src/org/commcare/dalvik/activities/MenuList.java, app/src/org/commcare/dalvik/activities/MultimediaInflaterActivity.java, app/src/org/commcare/dalvik/activities/RecoveryActivity.java, app/src/org/commcare/dalvik/activities/ReportProblemActivity.java, app/src/org/commcare/dalvik/application/CommCareApplication.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java
Some activities need to extend CommCareActivity but not be session aware.
Make SessionAwareCommCareActivity extend CommCareActivity instead of having CommCareActivity extend SessionAwareFragmentActivity.
FormEntryActivity is the one activity that needs to be session aware but not extend CommCareActivity, hence we manually add in the session un/registration handlers into onPause/onResume
=> Make session aware class extend CommCareActivity

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
Checking if build version is Honeycomb or greater before calling refreshActionBar().
=> Fixing crash in older Android versions

app/src/org/commcare/android/framework/BreadcrumbBarFragment.java
With multiple apps, it is now possible to end up in CommCareSetupActivity while an app is seated, which causes the action bar to show an app name in that activity. This is confusing since CommCareSetupActivity should be an app-agnostic activity, so ensure that the action bar just always says "CommCare" for this activity.
=> Make action bar in CCSetupActivity app-agnostic

app/src/org/commcare/android/view/GridEntityView.java, build.gradle
GridEntityView was extending the stock GridLayout, thus crashing in old devices. This PR fixes that.
=> Using compatibility library to avoid crashes in pre-HoneycombM2 devices

app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
CCSetupActivity should never redirect back to CCHomeActivity in onResume if it is in upgrade mode
=> Fix for update bug after multiple apps merge

app/AndroidManifest.xml, build.gradle, libraries/achartengine/build.gradle, settings.gradle
achartengine is now a library project, which makes 'go to source' and other AS functions work as intended.
This solves bug [177777](http://manage.dimagi.com/default.asp?177777#990599).
=> achartengine as a library

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/android/models/notifications/NotificationMessageFactory.java, app/src/org/commcare/dalvik/odk/provider/InstanceProvider.java
Raise runtime exception when forms have trouble saving. This ensures the user sees that there was a problem saving the form.
This exception will be caught and reraised as a SQLException in InstanceProvider.update/insert
User should see "Sorry, form save failed!"  toast pop-up message and be left on the current screen.
A pinned notification will also be created with the title: _Form Saving Failed_
and the body _The following error occrued while saving the form:_ and then the error message, which might look something like:
```Invalid XML Structure(START_TAG <{http://commcarehq.org/case/transaction/v2}n0:update>@1:1006 in java.io.InputStreamReader@d058c15): No case found for update. Skipping ID: ```
Problem mentioned in http://manage.dimagi.com/default.asp?178655
=> Raise runtime exception on form save error

app/src/org/commcare/android/view/GraphView.java
http://manage.dimagi.com/default.asp?178650
This was changed from DEFAULT to STACKED, presumably unintentionally, in https://github.com/dimagi/commcare-odk/commit/f58e39b9fdbe41b9c0302c5e9911c5869fbb68c0 which was otherwise a whitespace-cleanup commit on the original bar graphs PR (https://github.com/dimagi/commcare-odk/pull/293).
=> Fix bar graph type

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java
Register form save callback, which is called on session expiration, only on form loading and if the current form isn't read only.
Also make use of FormEntryActivity constants in CommCareHomeActivity.
=> Don't register form save callback for archived forms

app/src/org/odk/collect/android/activities/FormEntryActivity.java
When navigating an archived form and press the green arrow at the end, it currently tries to save the form. 
This PR checks if the form is archived and doesn't trigger form saving if that is the case.
=> Don't save on reaching form end if readonly

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/activities/CommCareVerificationActivity.java
Don't redirect away from CCVerificationActivity if explicitly brought there from the home activity settings menu.
=> MMVerificationActivity redirection fix

app/src/org/commcare/dalvik/application/CommCareApplication.java
Fix for CommCareApplication not having the correct AndroidSessionWrapper for the currently-seated app.
=> Initialize AndroidSessionWrapper when an app is seated

app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
If entry into CommCareSetupActivity came from an external application (such as a bit.ly url entered into a browser), do not redirect in onResume.
=> Enable install requests from external applications with multiple apps

app/res/layout/entity_detail.xml, app/res/layout/tabbed_detail_view.xml, app/src/org/commcare/android/view/TabbedDetailView.java
* Restyled 'Continue' button - now it's green. 
* 'Continue' button is now pinned to top of view.
* Tab name strip ('cases') won't appear unless there's more than one tab
=> Case detail fix

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
This was loading the wrong version of the home screen in devices with API level between 10 and 12.
=> Min build version for Etsy's gridview should be 10, not 12

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
-move logic for handling and setting a computed datum entirely into CommCareSession, passing the necessary evaluation context
-get evaluation context in the proper way
Cross: https://github.com/dimagi/commcare/pull/140
=> Refactor setting computed datum

app/src/org/commcare/dalvik/services/CommCareSessionService.java
Small refactor that uses NotificationBuilder to avoid deprecated API calls.
Also fixes small bug where clicking the "Click here to log back into your session" pinned notification while already on the login screen adds an additional activity to the backstack.
=> Use NotificationBuilder to avoid deprecated API calls

build.gradle
- Lift build types out of java source set closure and use a default config.
- Bump some library version numbers 
- Use incremental dexing (we can turn this off if it creates dex errors)
=> Simplify build types by using default config

app/src/org/commcare/android/framework/SessionActivityRegistration.java, app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/services/CommCareSessionService.java
Fix bug where every once in a while logging in puts the whole app into the background.
Caused by something (I don't know what) launching the LoginActivity twice combined with me not correctly using FLAG_ACTIVITY_CLEAR_TOP. Shoulda read the [whole entry in the docs](https://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_CLEAR_TOP)...
=> Fix app closing intermittently on login

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/android/tasks/ResourceEngineTask.java, app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
Currently if you try to install an app without an internet connection, you get a very very unhelpful "Couldn't locate part of your app" message. This does a check for connectivity before an install is actually attempted, and if there's no connection and it's not an offline install, raises an explicit "no internet connection" error right away.
While I was at it, discovered a couple of fields in CommCareSetupActivity related to multiple apps stuff that I hadn't been saving in onSavedInstanceState() as they should be, so added that in
=> Better error message if no connection during install

app/src/org/commcare/android/view/GraphView.java, libraries/achartengine/achartengine/src/org/achartengine/GraphicalView.java, libraries/achartengine/achartengine/src/org/achartengine/renderer/DefaultRenderer.java
More from http://manage.dimagi.com/default.asp?179685
Allow zoom controls to be placed in different corners of graph instead of always bottom right, and make it a little less obtrusive. No way to do this without fiddling with AChartEngine. Increasingly considering switching chart libraries.
Most changes are AS reformatting AChartEngine code.
Before:
After:
=> Configure zoom placement & tweak aesthetics

app/src/org/odk/collect/android/logic/FormController.java
Java will statically ensure that you actually implement the methods in an interface when you use the ```implements``` keyword. Regardless, override annotations are important for code readability and to ensure that you are actually overriding something when you think you are.
=> Add @Override annotation to interface implementation

build.gradle
The sdk version settings for javarosa/commcare shouldn't be needed and make it easier to config odk jenkins builds.
Will require updating the odk jenkins build.
=> Remove javarosa/commcare android build settings

app/res/values/external_strings.xml, app/src/org/commcare/dalvik/application/CommCareApplication.java, build.gradle
When we migrated to gradle we forgot to update the logic that sets the app's version number and build date.
=> Make gradle set version number and date

app/src/org/commcare/android/view/GridEntityView.java
Fix for there being a maximum boundary on row size scaling, causing odd gridview grids on XXHigh res screens
On my Galaxy S5 this fixes a bug where the tiles would have a ton of empty space below the content.
=> GridView Row Density Fix

app/res/drawable/divider_case_list_modern.xml, app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
Tile separators weren't appearing on Android 5.0 devices (and possibly some 4.0 devices), and did not meet the colors and spacing in the spec.
=> Fix for Tile Separators

app/src/org/commcare/android/fragments/SetupEnterURLFragment.java, app/src/org/commcare/android/fragments/SetupInstallFragment.java, app/src/org/commcare/android/fragments/SetupKeepInstallFragment.java, app/src/org/commcare/android/view/SquareButtonWithNotification.java, app/src/org/commcare/android/view/SquareButtonWithText.java
The `@ManagedUi` and `@UiElement` annotations that flag ui elements to inflate automatically in CommCareActivity are useless when present in classes that don't extend `CommCareActivity`. Remove them.
Also lint, code style, method order, and other minor refactors. __Review commit-by-commit__
=> ManagedUi and UiElement annotations are useless outside of CommCareActivity

app/src/org/commcare/android/adapters/EntityListAdapter.java, app/src/org/commcare/android/util/StringUtils.java, app/src/org/commcare/android/view/EntityView.java
Fixes issues where the algorithm was being triggered with too little data, and the order of arguments was being provided backwards.
Fix for http://manage.dimagi.com/default.asp?181239
=> Fix order of arguments for edit distance match

app/src/org/odk/collect/android/utilities/FileUtils.java
Fix for http://manage.dimagi.com/default.asp?181327#1009226
=> fix getBitmapScaledToDisplay() to never cause OutOfMemory error

app/src/org/commcare/android/framework/BreadcrumbBarFragment.java
Fix for bug where persistent tiles would show affordance for dropdown when there was no inline detail
=> Fix for persistent tiles showing dropdown icon

app/src/org/odk/collect/android/widgets/DateWidget.java
Alternate fix for
http://manage.dimagi.com/default.asp?180595
which stays within the jodatime framework, but works with dates that are on edges (since it doesn't force setting a specific time)
=> Alternate fix for date issues which stays within Jodatime

app/assets/locales/messages_ccodk_default.txt
@dimagi/product @wspride 
Quick text change for the error that appears when you mistype your installation URL on ODK.
=> Update error text when mistyping URL

build.gradle
Tried to use robolectric 3.1 snapshot to see if it would fix the linking error that requires `-noverify` compiler flag. It didn't, so let's use the stable version, 3, instead of 3.1
=> Use stable robolectric version over 3.1 snapshot

app/res/layout/mainnew.xml
Fix for the version string and last sync message on the home screen overlapping on some device screens (reported in Value Labs' latest response on this ticket http://manage.dimagi.com/default.asp?181690).
This is the commit where the diff is just wrong. The actual change that I made is just the following to the LinearLayout with id 'main_center_pane':
-android:layout_above="@id/home.logout"
+android:layout_above="@id/str_version"
ALL of the other additions it's showing are actually lines that were already in this file on oldui/commcare_2.23 (I double-triple-quadruple checked this because I feel like I'm going crazy). Decided I'm ok with just merging this anyway because the actual resulting change is still only what I said above. If anyone has any objections though, or any thoughts on what …
=> stop version string and last sync message from overlapping

app/src/org/commcare/dalvik/application/CommCareApplication.java
Fix bug where missing else statement caused CCApplication to always initialize the first installed app in the db, instead of being smart about it.
=> Fix app initialization logic error, name method better

app/src/org/commcare/dalvik/activities/LoginActivity.java
When seating an app in the login screen, text entry focus should be set to the username field if there isn't a last logged in user entry in the preferences.
=> Login username text field focus when seating app w/o LAST_LOGGED_IN_USER field

app/src/org/commcare/dalvik/activities/EntityDetailActivity.java
TDH requested that for entity details that don't go anywhere (namely, mobile UCR reports), the icon on the continue button be reversed. Chatted with @biyeun and decided to drop the icon altogether in that case.
=> Drop chevron from read-only entity detail

app/src/org/odk/collect/android/activities/FormHierarchyActivity.java, app/src/org/odk/collect/android/adapters/HierarchyListAdapter.java, app/src/org/odk/collect/android/logic/HierarchyElement.java, app/src/org/odk/collect/android/views/HierarchyElementView.java
In the form hierarchy view for an incomplete form instance, which shows a forms questions in a list view, the back button redirects to editing the incomplete form if you are in a nested entry. The back button should really traverse back up the form hierarchy. E.g. if you enter a repeat entry, the form hierarchy drills down into that repeat entry, at which point the back button should return you to the top level hierarchy view.
Also, correctly set the background color of form question entries in this view.
Before:
After:
Includes linting and code reformatting. I've marked the actually bug fixes with github comments.
=> FormHierarchyActivity fixes: entry background color, back button in nested entry

app/src/org/odk/collect/android/activities/FormEntryActivity.java
View creation should never happen for an end of form event. Throw a soft assert in and move the user back one step if this occurs.
=> Soft assert when showing view at end of form

app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
Fixes infinite loop that is entered in CommCareSetupActivity while trying to install an app. The loop was caused by the sms message query cursor not being advanced.
Also only looks 100 messages back in search of a sms message with a valid commcare install link. I added this 100 message limit in case searching through all the incoming texts on a phone takes a long time. It doesn't on my phone because it is new and doesn't have many texts, but we should test this on an older phone that has thousands of texts. If we do want to search through all texts, it should be done on a background thread that is non-UI blocking.
=> Advance sms message cursor when looking for app install link

app/src/org/commcare/android/view/CustomButtonWithText.java
Fix for bug introduced in https://github.com/dimagi/commcare-odk/pull/599, in which I broke the functionality where the background color of CustomButtonWithText instances changes when you press them.
=> Fix button press background color change

app/AndroidManifest.xml
Add NFC permission to the beta to make migrating from old to new ui require user intervention
=> 2.23.1 Hotfix: Add NFC permission to trigger manual new ui update

app/AndroidManifest.xml
Apparently our content providers are broken because at some point this attribute stopped being "true" by default. I can't find a lot of great information about when/what caused this
=> Add export attribute to providers

app/src/org/commcare/android/framework/SessionActivityRegistration.java
Fix crash being seen on ACRA where, in onPause, unregistering the session expiration receiver that wasn't previously registered causes force close. Not sure how this could ever happen, because it should always be registered in onResume, but might as well not fail hard when this happens.
https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/524bbfea0dcd4c2ba3c645f0bb97e485
=> Don't crash unregistering a receiver that wasn't previously registered

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/android/database/global/models/ApplicationRecord.java, app/src/org/commcare/dalvik/services/CommCareSessionService.java
In response to: http://manage.dimagi.com/default.asp?183315#1021983
Release Note: If more than one app is installed, the logged in notification will include the display name of the current app.
=> Logged in notification text change for multiple apps

app/src/org/odk/collect/android/views/ResizingImageView.java
Fix for typo that caused image scaling to be broken, but only for the "Half" resize option
Possibly hot fixable... 
http://manage.dimagi.com/default.asp?179788
=> Fix half resizing image

app/src/org/odk/collect/android/jr/extensions/AndroidXFormExtensions.java, app/src/org/odk/collect/android/jr/extensions/IntentCallout.java, app/src/org/odk/collect/android/jr/extensions/IntentExtensionParser.java, build.gradle, unit-tests/resources/forms/intent_callout_serialization_test.xml, unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Add missing empty constructor for IntentCallout serialization because it was causing form deserialization to fail.
=> Add missing empty constructor for IntentCallout serialization

app/src/org/commcare/dalvik/activities/EntityDetailActivity.java, app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
In https://github.com/dimagi/commcare-odk/pull/645 I forgot to also make the change for the horizontal entity select+detail screen.
=> Drop chevron from read-only entity detail (horizontal view)

app/src/org/commcare/android/tasks/DataPullTask.java
Fixed issue where the user couldn't see the fixture message because we weren't failing fast on parse errors. Note: Will also affect apps where an individual case record is broken, but I think that'-s something we should be doing-
=> Fix for new Fixture Size error not being shown to the user

app/src/org/commcare/android/view/EntityView.java, app/src/org/odk/collect/android/activities/components/ImageCaptureProcessing.java, app/src/org/odk/collect/android/utilities/FileUtils.java
Fix for: http://manage.dimagi.com/default.asp?183486
Images embedded in the case list were not being scaled down from their original size at all, causing OOM errors very quickly if the original images were at all large.
=> Scale down images in the case list 

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/android/framework/StateFragment.java, app/src/org/commcare/android/tasks/PurgeStaleArchivedFormsTask.java, app/src/org/commcare/android/tasks/TaskListener.java, app/src/org/commcare/android/tasks/TaskListenerRegistrationException.java, app/src/org/commcare/android/tasks/templates/CommCareTask.java, app/src/org/commcare/dalvik/activities/FormRecordListActivity.java, app/src/org/commcare/dalvik/application/CommCareApplication.java, unit-tests/src/org/commcare/android/tests/processing/ArchivedFormPurgeTest.java
Users were reporting lag upon login that was probably associated with slow archived form purging. Do this in the background. Also block users from accessing the saved forms list while the purging task is running. 
Includes some linting/small refactors to the task connector framework even though I ended up not using task connectors. Instead I chose to use the framework I created in the background update PR (https://github.com/dimagi/commcare-odk/pull/507) because they both have the same pattern of launching singleton tasks in one place that need to be connected to specific activities when they are launched. I will generalize this framework when background update PR gets merged.
Can't figure out how to get the created `CustomProgressDialog` to not cancel when the back button is pressed. …
=> Perform purging of invalid archived forms in backgroud

build.gradle
Retrying https://github.com/dimagi/commcare-odk/pull/684, but this time verified it builds on jenkins http://jenkins.dimagi.com/job/test-odk-build/1/console
=> Use the latest support libs | Round 2

app/src/org/commcare/android/view/GridEntityView.java
IMPORTANT NOTE: For the material diff, look at the 1st commit only. The 2nd commit is just reformatting (somehow this file got missed out on our conversion from tabs to spaces) but it makes basically the whole file have a diff, so you can't see the meaningful changes from looking at the overall diff.
Explanation: For both REC and Parto (the 2 main apps using case tiles for their case lists), on the new UI there is currently an awkward amount of extra spacing between lines of content in each case tile. Since the spacing of the tile contents are dependent on the tile sizes, which are in turn dependent upon how many tiles the device tries to show per screen, the solution was to increase the default number of grid tiles that are shown per screen (from 5 to 7). Screenshots included below for …
=> Fix for unnecessary spacing in custom case lists on new UI

app/src/org/commcare/dalvik/activities/HomeActivityUIController.java
Fix for: http://manage.dimagi.com/default.asp?183983. The logout button notification text and the saved forms button text were both just not getting refreshed properly.
=> refresh logout notification text and saved forms button text properly

app/src/org/odk/collect/android/views/ResizingImageView.java
Fix for http://manage.dimagi.com/default.asp?179788
Basically with half image resizing we were previously calculating the "Ideal" image size (based on the drawable and screen size), THEN rescaling to half that width/height. What we actually want is to say that only half the screen width/height is available to begin with and calculate the ideal image size from there.
=> We should scale the max image size before calculations

build.gradle, unit-tests/resources/robolectric.properties, unit-tests/src/org/commcare/android/shadows/CommCareShadowLog.java
Enable the ability to show only CommCare specific logs when running Robolectric tests.
Unfortunately you have to manually enable this when running tests from Android Studio. To do so add `-Drobolectric.logging=stdout` to the VM options of the build configuration.
=> Show android logs in robolectric tests

app/res/values/strings.xml, app/res/xml/preferences_developer.xml, app/res/xml/server_preferences.xml, app/src/org/commcare/dalvik/preferences/DeveloperPreferences.java, app/src/org/odk/collect/android/views/media/MediaLayout.java
Creates a developer preference which, if enabled, places images above question text in a question widget, instead of below.
=> Image-above-text configuration option in QuestionWidgets

app/src/org/odk/collect/android/views/ResizingImageView.java
@wpride: https://github.com/dimagi/commcare-odk/pull/695 broke half-size image resizing for ICDS, in that the earlier issues from this ticket http://manage.dimagi.com/default.asp?179788 returned (images that should be half size are taking up the full screen).  Haven't looked closely as to why, but reverting for now. Any new fixes should definitely be tested on ICDS itself to see what things look like there. 
Worth noting that I'm working on a more robust/consistent way of doing image inflation that should render the ResizingImageView stuff unnecessary. But that's not going to be done in time for them to start rolling out next week, so this solution has to work for them for now.
=> Revert resizing change

app/AndroidManifest.xml, app/src/org/commcare/android/fragments/SetupEnterURLFragment.java, app/src/org/commcare/android/fragments/SetupKeepInstallFragment.java, app/src/org/commcare/android/framework/BreadcrumbBarFragment.java, app/src/org/commcare/android/framework/FileServerFragment.java, app/src/org/commcare/android/framework/StateFragment.java, app/src/org/commcare/android/framework/WiFiDirectManagementFragment.java, app/src/org/commcare/dalvik/preferences/CommCarePreferences.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/preferences/FormEntryPreferences.java, app/src/org/odk/collect/android/views/ODKView.java, app/src/org/odk/collect/android/widgets/QuestionWidget.java
- Rename `PreferenceActivity` to `FormEntryPreferences`
- Update fragments to not use deprecated `onAttach(Activity activity)`.
I was going to  update `CommCarePreferences`, `DeveloperPreferences`, and `PreferencesActivity` to stop extending the deprecated `PreferenceActivity`, and instead use `PreferenceFragment`. Turns out `PreferenceFragment` is only API 11 and greater, so I'll leave this fix for another time.
=> Don't use deprecated Fragment.onAttach(Activity)

build.gradle
Requires updating to the latest support library via your sdk manager.
I've performed this update on the jenkins build server already.
=> Update to android support libs to 23.1

app/src/org/commcare/android/framework/EntitySubnodeDetailFragment.java
When using subnode entity screens, this lets the parent screen define variables in the original context that can then be read by the subnode detail screen when it is displaying data. Useful if the two have unrelated nodesets
=> Propogate Subnode Variables to Children

app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/activities/components/ImageCaptureProcessing.java
This is a short-term patch for this bug on ACRA: https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/a75355af7f8fba060f693b6f8eb90128.
It looks like getCurrentWidget() is sometimes returning null, which isn't good, but is gonna be really hard to track down the cause of. For now, this will at least prevent the app from crashing when it does. In theory this means it's possible that we will skip performing scaling of an image capture when we should be, but since it's a very minimally used feature right now, the chances of that are unlikely. More concerned about what's wrong with the implementation of getCurrentWidget(), since it definitely shouldn't be returning null in the place the stack trace is indicating -- if anyone has …
=> prevent null pointer exception if getCurrentWidget() returns null

app/src/org/odk/collect/android/activities/FormEntryActivity.java
I Refactored FormEntryActivity last month to extend CommCareActivity and make use of its framework, but I forgot to make it extend the session aware version. This caused resuming to form entry after the session ended to not redirect to the home screen. Happened often when installing a new app via the app manager while in form entry in another app.
=> Make form entry extend session aware cc activity

app/src/org/commcare/android/resource/AndroidResourceManager.java, unit-tests/src/org/commcare/android/tests/application/AutoUpdateTest.java
Auto-update failures will schedule retries attempts, which launch the update task. The task shouldn't launch if the user is no longer logged in, or is logged into an app that doesn't have a pending retry scheduled.
Also move app setup for a test class into the single test that uses it to prevent strange task timing test failures.
=> Don't retry auto update after logout

app/src/org/commcare/dalvik/activities/UpdateUIState.java
Fix for http://manage.dimagi.com/default.asp?185293
We seem to use this call updateProgressBar(100, 100) throughout this class to accomplish this. Guessing that's because filling the bar dynamically would require adding a lot of callbacks in the ResourceManager upgrade method. @phillipm
=> Make progress bar full after update

app/res/values/strings.xml, app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/android/util/TemplatePrinterUtils.java, app/src/org/commcare/dalvik/activities/AppManagerActivity.java, app/src/org/commcare/dalvik/activities/CommCareFormDumpActivity.java, app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java, app/src/org/commcare/dalvik/activities/CommCareWiFiDirectActivity.java, app/src/org/commcare/dalvik/activities/FormRecordListActivity.java, app/src/org/commcare/dalvik/activities/SingleAppManagerActivity.java, app/src/org/commcare/dalvik/activities/UnrecoverableErrorActivity.java, app/src/org/commcare/dalvik/dialogs/AlertDialogFactory.java, app/src/org/commcare/dalvik/dialogs/AlertDialogFragment.java, app/src/org/commcare/dalvik/dialogs/DialogController.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/activities/components/FormNavigationUI.java, app/src/org/odk/collect/android/utilities/GeoUtils.java
This PR makes it so that all alert dialogs spawned by any CommCareActivity will persist on orientation change. Alert Dialogs spawned by non-CC activities will still disappear on rotation, but this seems ok for now-- none of those instances are things that will break the app in any way or cause confusion. 
This is a partial (but not complete) solution to http://manage.dimagi.com/default.asp?184630. @phillipm is going to make a PR to address the rest of that ticket.
=> Make alert dialogs persist on rotation V.2

app/src/org/commcare/android/adapters/IncompleteFormListAdapter.java, app/src/org/commcare/dalvik/activities/FormRecordListActivity.java
I think this is a fix for [this ticket](http://manage.dimagi.com/default.asp?183564) ([crash report here](https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/2470c26b3312af4adf1fce1ecd49f46d)), though I wasn't able to reproduce it, so I'm unsure.
First commit contains functional changes, which are to call `notifyDataSetChanged()` when the underlying adapter data is changed in any way.
Also fixes bug where deleting an incomplete/saved form entry actually duplicated the entry.
=> IncompleteFormListAdapter bug fixes

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Prevent app from crashing when form load error dialog is shown and the app is rotated.
http://manage.dimagi.com/default.asp?184630
Better approach than the original proposed PR: https://github.com/dimagi/commcare-odk/pull/733
=> Prevent crash when orientation changes after form load fails

app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
Fragment transactions throw `java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState` exceptions if you try to perform them when the activity is paused. This PR prevents that from happening with the CommCareSetupActivity.
[Addresses this ACRA crash report](https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/1ea83dfd44b3bfaa79e788a9bae25560)
=> Don't try to do fragment transaction when paused

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/application/CommCareApplication.java
Pressing back on the install screen caused a crash because the onResultActivity code path was trying to load the commcare session before an app was installed.
http://manage.dimagi.com/default.asp?185291
=> Don't try to get session before cc app is installed

app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/dalvik/dialogs/AlertDialogFactory.java, app/src/org/commcare/dalvik/dialogs/AlertDialogFragment.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/utilities/GeoUtils.java
Pressing back on an alert dialog that has a cancel listener wasn't doing anything.
This fixes that is very unfortunate way.
=> Make alert dialogs cancelable

app/src/org/commcare/android/framework/BreadcrumbBarFragment.java
If you rotate the screen while applying an app update then the breadcrumb bar crashes while trying to localize an installed resource because it isn't available. Wrap the offending line in a try/catch that returns a default title when this happens.
Isn't ideal, but is a minimal change and I suspect hunting down a robust solution would take me hours.
=> Use default title if refreshing breadcrumb title while updating app

app/src/org/commcare/android/database/user/models/FormRecord.java
The value of lastModified was not actually getting set in the constructor if the if value passed in was null. Not sure what the implications of this are or if it could have been causing any bugs -- if it could be, should  probably just put in 2.24.
=> Set FormRecord class field properly

app/res/layout/custom_alert_dialog.xml, app/res/layout/dialog_title.xml, app/res/layout/progress_dialog_cancel_button.xml, app/res/layout/progress_dialog_determinate.xml, app/res/layout/progress_dialog_indeterminate.xml, app/res/values/dimens.xml
So Kriti found a major bug with the new dialogs-- Even though using 'sp' font sizes is the standard recommendation, for some reason in the new dialogs, it was making the font sizes completely wonky on some tablets. This PR changes all the font sizes in all the new dialogs to the same size, but 'dp'. I confirmed that it fixes the appearance on the problematic tablets, and doesn't change the prior appearance on other devices.
=> use dp for font sizes in dialogs

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Deleting form media was using incorrect cursors and columns. This resulted in CommCare crashing, leaving media files around on the phone.
https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/f0d93cc3076bcc0c57c569debab9646a
=> Don't crash when trying to remove attached videos on form discarding 

app/res/layout/progress_dialog_determinate.xml
Fixed progress dialog text cutoff occurring on Tab 2 & 3 devices:
http://manage.dimagi.com/default.asp?184613
=> Ui progress dialog cutoff on tab 2/3 devices

app/src/org/commcare/android/resource/AndroidResourceManager.java, app/src/org/commcare/android/resource/ResourceInstallUtils.java, app/src/org/commcare/android/tasks/PurgeStaleArchivedFormsTask.java, app/src/org/commcare/android/tasks/SingletonTask.java, app/src/org/commcare/android/tasks/UpdateTask.java, app/src/org/commcare/android/tasks/templates/ManagedAsyncTask.java, unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.java, unit-tests/src/org/commcare/android/tests/application/AutoUpdateTest.java
Both UpdateTask and PurgeStaleArchivedFormsTask are examples of singleton tasks that report to some sort of TaskListener. Hence, they share a lot of reporting and tear-down code. This PR consolidates that duplicate code into `SingletonTask`.
=> Consolidate duplicate code in UpdateTask & PurgeStaleArchivedFormsTask

app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/android/util/MediaUtil.java
Remove deprecated calls to `Display.getWidth()` and `Display.getHeight()` in custom banner display code.
=> Remove deprecated size call in banner customization

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/activities/GeoPointActivity.java, app/src/org/odk/collect/android/utilities/GeoUtils.java
dialog.dismiss() wasn't getting called where it should be for the onClickListener in one of the dialogs, making it impossible to close. I also did a quick pass over all of the new dialogs to make sure there weren't any others left with the same problem.
Also makes text capitalization for the no gps dialog consistent, and removes a noop from 1 file.
=> call dialog.dismiss() for no gps dialog

app/res/layout/progress_dialog_determinate.xml
A fix for a different dialog bug changed this layout from a RelativeLayout to LinearLayout, which messed up the alignment of the cancel button. Moving it back to right-aligned
=> Move cancel button back to being right-aligned

app/src/org/commcare/android/adapters/EntitySubnodeDetailAdapter.java
Make data-driven entity detail screens behave like entity selection screens: don't display rows that have no data.
=> In entity subnode details, ignore blank rows

app/res/layout/entity_item_image.xml, app/src/org/commcare/android/view/EntityView.java
So adding this property will scale the image to take up the entire space available to the image (the red in the second picture) without messing with the aspect ratio. I *think* this is more often to be what we want, especially if HQ will continue adding the "13%" default space to icons since this will end up being tiny on small screens.
Long term, I think better HQ case tile support is the correct-er solution here
@orangejenny
=> Case list icon resize

app/src/org/odk/collect/android/activities/FormEntryActivity.java
If you try to quickly swipe twice when the next question launches a repeat dialog, then clicking any entry in the dialog crashes the app. This is happening because the second swipe is being processed even when the dialog is present
http://manage.dimagi.com/default.asp?186334
Fixes this ACRA crash: 
```
java.lang.RuntimeException: Invalid reference while copying itemset answer: Destination already exists!
```
https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/dc4a2588a05c7cff3cc4279bd7562f9d
=> Prevent swipe when repeat dialog is up

app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java
Implemented an adaptive layout technique for shrinking the question group label max size based on the screen dimensions, triggering on any major changes to the screen size (soft keyboard).
Fix for: http://manage.dimagi.com/default.asp?186516
=> Fix for overzealous display of group label data

app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
There was some strange behaviour where [`onQueryTextChange`](https://github.com/dimagi/commcare-odk/blob/bug/case-search-clearing/app/src/org/commcare/dalvik/activities/EntitySelectActivity.java#L685) was getting called multiple times, the last time with an empty string even though the search box wasn't empty. The solution was to not trigger a rebuild of the options menu/action bar.
Fix for this http://manage.dimagi.com/default.asp?186541
Possible that this re-introduces the bug in http://manage.dimagi.com/default.asp?171354 . Clark looked into it and wasn't able to reproduce it, so I think we are good
=> Use current case list search query when loading is complete 

app/src/org/commcare/android/framework/CommCareActivity.java
temporarily disabling case list search caching for 2.24.1 until we can come up with a robust solution.
http://manage.dimagi.com/default.asp?183986
=> Turn case-list query storing/retrieving into no-ops

unit-tests/src/org/commcare/android/tests/application/AutoUpdateTest.java
auto update with daily check frequencies are always pending if the last check time was on another calendar day. This meant that a test I wrote failed if it was executed 0-3 hours after midnight.
=> Fix auto-update test that fails around midnight

app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
Attempt to fix the following error, which I thought was handled in https://github.com/dimagi/commcare-odk/pull/740
```
java.lang.RuntimeException: Unable to resume activity {org.commcare.dalvik/org.commcare.dalvik.activities.CommCareSetupActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState : at org.commcare.dalvik.activities.CommCareSetupActivity.uiStateScreenTransition(CommCareSetupActivity.java:273)
```
https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/4e3e4f36dedf8bc5a84ae6d47e2a0eac
=> Modify fragements after they have resumed

app/src/org/commcare/dalvik/application/CommCareApplication.java, app/src/org/commcare/dalvik/services/CommCareSessionService.java
If you swipe close the android app and then re-open it the current commcare session is still around (used to show up in oldui breadcrumb bar, on new ui you have to inspect the object using the debugger). The user isn't restored to that session's current state, but rather taken to the home screen.
This PR catches the swipe close action via `onTaskRemoved` and resets the session. 
Fixes http://manage.dimagi.com/default.asp?168706
Contains commits from https://github.com/dimagi/commcare-odk/pull/796
=> Clear session on app swipe close

app/src/org/commcare/android/cases/AndroidCaseInstanceTreeElement.java, app/src/org/commcare/android/util/AndroidInstanceInitializer.java
If this is the correct pattern for making the android instance initializer use android version of data instance classes, then I will implement it for ledgers, fixtures, and sessions.
fixes http://manage.dimagi.com/default.asp?186528
cross-requested with https://github.com/dimagi/commcare/pull/192
NOTE: we need to remove `org.commcare.android.util.CommCareInstanceInitializer` because it isn't used any more.
=> Ensure AndroidInstanceInitializer uses the android version of data instance classes

app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/android/models/AndroidSessionWrapper.java, app/src/org/commcare/dalvik/activities/EntitySelectActivity.java, app/src/org/commcare/dalvik/activities/FormRecordListActivity.java
Store the last query for a case list in the current sessions top frame. Hence, if you continue forward in a session, when you back out to the same case list, the query is restored from the session's stack. If you back out past the case list selection view and then forward into it again, the query won't be restored; implementing the desired behavior. 
fixes: http://manage.dimagi.com/default.asp?183986
cross request: https://github.com/dimagi/commcare/pull/191
=> Restore last case list query

app/src/org/commcare/dalvik/activities/HomeActivityUIController.java
We should fix this at some point. Removing the soft assert logging because it is polluting the device logs
=> Remove soft asserts when home screen buttons are null

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Auto-advance questions at the end of form were resulting in the form being saved as incomplete. Instead auto-advancing past the end of form should be the same as pressing the 'next arrow' button 
Should consider hotfixing this.
http://manage.dimagi.com/default.asp?186847
=> Save form as complete if auto-advance question reaches End-of-form

app/res/values/strings.xml, app/src/org/odk/collect/android/tasks/SaveToDiskTask.java
See http://manage.dimagi.com/default.asp?186674
We should be logging this error anyways since we had no visibility. Unclear if we gain anything from percolating the error to the user level but I think not. 
@phillipm I saw you suggested one of your changes might've impacted this behavior (IE failing on form save instead of later) - this seems better to me (IE better than sending to HQ and failing there)
=> Better logging and error message for form save failure

app/src/org/commcare/dalvik/application/CommCareApplication.java
`isPending` had a small bug in its implementation, where if the current time was a different calendar day than the last check time it returned true. It needed to ensure that the last check time was also in the past.
=> Add future time check in pending task diff day logic

app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/widgets/DateTimeWidget.java, app/src/org/odk/collect/android/widgets/TimeWidget.java
If you rotate the a device while in a form that has TimePicker or DateTimePicker widgets then it crashes with `java.lang.IndexOutOfBoundsException: setSpan (2 ... 2) ends beyond length 0`
I was only able to trigger this crash on the [registration form of the mLabour app](https://www.commcarehq.org/a/mlabour/apps/view/6bbf69cec278cff14d152ae8d1a30fe8/modules-1/forms-0/). I tried to rotate on other forms that had TimePickers without success. 
This fix probably only works for devices running Android 3 and up, but that is okay with me, since it seems hard to encounter.
https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/1c3ed844920b9be36e634e2a31ec3933
=> Fix crash when rotating form entry view w/ date/time pickers

app/src/org/commcare/android/resource/AndroidResourceManager.java, app/src/org/commcare/android/resource/analytics/UpdateStats.java
When updates fail a certain number of times they are considered stale and the update table is cleared. When this happens, we should also clear the update stats so that the table doesn't continue to be considered stale.
=> Reset update stats once update is stale

app/assets/graphing/graph.css, app/assets/graphing/graph.js, app/src/org/commcare/android/view/c3/DataConfiguration.java, app/src/org/commcare/android/view/c3/LegendConfiguration.java
C3 re-orders the data in the annotations series, so the `index` passed into `data.labels.format` isn't necessarily the same index that I'm expecting. Deal with this by creating a separate series for each annotation, rather than one series for all annotations.
=> Fix annotations

app/AndroidManifest.xml
Fix variable expansion failure due to missing `$` in manifest file
`Permission Denial: reading org.commcare.dalvik.provider.CaseDataContentProvider uri content://org.commcare.dalvik.case/casedb/case from pid=24687, uid=10244 requires {applicationId}.provider.cases.read, or grantUriPermission(`
=> Add missing $ in manifest

app/assets/graphing/graph.css, app/assets/graphing/graph.js, app/src/org/commcare/android/view/c3/DataConfiguration.java
C3 defaults area below a line to the same color as the line, and it doesn't support user-configured opacity for either line colors or area colors. Deal with this.
=> support fill-below and opacity

app/AndroidManifest.xml, app/assets/graphing/graph.css, app/assets/graphing/graph.js, app/src/org/commcare/android/view/EntityDetailView.java, app/src/org/commcare/android/view/EntityView.java, app/src/org/commcare/android/view/GraphView.java, app/src/org/commcare/android/view/c3/DataConfiguration.java, app/src/org/commcare/dalvik/activities/GraphActivity.java
Support double-tap to see the graph full screen.
In full-screen mode, you can zoom and can touch a point to get a tooltip. This PR adds to series configuration `is-data` (default true) so users can specify that a given series should *not* be included in the tooltip (or the legend) (for example, the fake "series" used to create parto's red and yellow areas, or thresholds in general).
It's a bit finicky; the touch to tooltip isn't always responsive (it's a hover event in C3, so Android is translating the touch event to a mouseover). I'm using the built-in WebView zoom because C3's zoom capabilities are "experimental" (do not work well), but unfortunately that means that you're zooming in on the entire view, not just zooming in on the data while the axes stay put & re-scale themselves.
=> full screen graphs

app/assets/graphing/graph.js, app/src/org/commcare/android/view/c3/DataConfiguration.java
C3 will hide alternate labels if it thinks the axis is too crowded...good for visual breathing room, bad for being able to read bar charts.
Before
After
=> Force all bar labels to show

app/assets/graphing/graph.js, app/src/org/commcare/android/view/c3/DataConfiguration.java
- Accept either 6-digit or 8-digit colors
- Round labels; looks like C3's automatic label calculation doesn't round nicely if you, say, want seven labels ranging from 0 to 1. Might be a problem if someone wants decimal labels, but right now this is an easy bandaid.
=> Accept more color formats, and round axis labels

app/src/org/commcare/android/view/EntityDetailView.java, app/src/org/commcare/android/view/GraphView.java
AChartEngine displayed bar graphs squished unless they were square, so the old graphing code based aspect ratio on graph type. Drop this hackiness, use the same aspect ratio everywhere.
=> Standard aspect ratio for graphs

app/assets/graphing/graph.js, app/src/org/commcare/android/view/c3/DataConfiguration.java
Translucent area graphs (which are desirable because C3 draws its grid lines underneath all of the series, which means you can't see the grid lines through parto's red/yellow zones unless they're translucent) get ugly when the areas overlap. Stack them.
Before
After
=> Stack areas

app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
`EntitySelectActivity` is a session aware activity, but it tries to access session state in `onCreate` which is before the session management can close the activity, which happens in `onResume` 
Similar crash to what https://github.com/dimagi/commcare-odk/pull/803 was trying to address
=> Escape case list early if session ended

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Currently when you try to save and exit a form that has an answer that violates a question constraint, it jumps to that question. Unfortunately it doesn't correctly show the constraint violation message that it used to. This PR ensures that the constraint violation message is shown again.
Fix for http://manage.dimagi.com/default.asp?187237
=> Correctly refresh view on constraint violation during form save

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
I added a dialog to warn users when we needed to restart their session due to some sort of error, but didn't realize that there is one case when we call clearSessionAndExit() that isn't an error state, it's just when we save a form; the user shouldn't see a warning in that case.
=> Don't show warning about restarting session when it was only for saved form

app/src/org/odk/collect/android/tasks/SaveToDiskTask.java
Should probably log when people use a form save feature flag that might not work as expected
=> Log use of save w/o trigger firing

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Tell android to use multiple threads when running async tasks.
Helps slightly when processing form send tasks and form save/load tasks at the same time
=> Launch tasks using executeOnExecutor

app/src/org/commcare/android/database/SqlStorage.java
Months later I'm still trying to figure out how to prevent the following exception trace from popping up: 
```
11-27 14:45:06.627 3606-3614/org.commcare.dalvik E/Cursor: Finalizing a Cursor that has not been deactivated or closed. database = /data/user/0/org.commcare.dalvik/databases/database_app_448082f04dde416e840e4a00d5e793e4, table = user_key_records, query = SELECT commcare_sql_id, commcare_sql_record FROM user_key_records WHERE sandbox_id=? AND username=?
net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
at net.sqlcipher.database.SQLiteCursor.<init>(SQLiteCursor.java:217)
at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:53)
at …
```
=> Wrap cursor ops in finally/close

app/res/xml/preferences_developer.xml, app/src/org/commcare/dalvik/activities/UpdateUIState.java
Fix issue where after performing an update check the progress bar shows partially complete:
Also rename dev setting entry "Enable auto-login during debugging" -> "Auto-login While Debugging"
=> Fix app update progress bar artifact

app/src/org/commcare/android/view/GraphView.java
Graphs in the case list weren't allowing you to actually select an item and proceed to case detail.
=> Support graphs in case lists

app/assets/graphing/graph.js
Two fixes:
1) https://github.com/dimagi/commcare-odk/pull/874 broke tooltips because it caused conflicting variables both named `data`
2) For time-based graphs, display the date in the tooltip with whatever format was specified by x-labels-time-format, rather than the js Date.toString
=> fix tooltips

app/src/org/commcare/dalvik/services/CommCareSessionService.java
Trying to address the ACRA crash below.
From what I can deduce: The log submission task launch on login is trying to access the user session key before it has been setup. Thus wrapping `createNewSymetricKey` in `synchronized (lock)` should hopefully address this.
I might completely off as to when this crash is occurring. If it is happening at a different time then this solution probably doesn't really help.
https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/ab17609d7e49b4bd56f02741c141e937
=> Sync key creation; preventing premature usage

app/res/layout/progress_dialog_indeterminate.xml
On older phones, the bottom of progress dialogs with indeterminate progress bars was getting cut off. In fixing that, the dialog text is no longer centered vertically relative to the progress bar if it is a single line of text, and I can't figure out how to fix that (struggled with it for a while). But this is much better than before and don't want to keep sinking too much time into that for now.
=> Fix progress dialog from being cut off

app/assets/locales/messages_ccodk_default.txt, app/res/layout/screen_login.xml, app/res/values/strings.xml, app/res/xml/preferences_developer.xml, app/src/org/commcare/android/api/ExternalApiReceiver.java, app/src/org/commcare/android/framework/SaveSessionCommCareActivity.java, app/src/org/commcare/android/session/DevSessionRestorer.java, app/src/org/commcare/android/tasks/DataPullTask.java, app/src/org/commcare/android/tasks/ManageKeyRecordTask.java, app/src/org/commcare/dalvik/activities/EntityDetailActivity.java, app/src/org/commcare/dalvik/activities/EntitySelectActivity.java, app/src/org/commcare/dalvik/activities/LoginActivity.java, app/src/org/commcare/dalvik/activities/MenuGrid.java, app/src/org/commcare/dalvik/activities/MenuList.java, app/src/org/commcare/dalvik/application/CommCareApplication.java, app/src/org/commcare/dalvik/preferences/CommCarePreferences.java, app/src/org/commcare/dalvik/preferences/DeveloperPreferences.java, app/src/org/odk/collect/android/activities/FormEntryActivity.java
Added:
-A checkbox on login screen to indicate if you want to restore the saved session (only visible if there is a session currently saved for that app)
-An item in the options menus of EntitySelectActivity, MenuItem, MenuGrid, and FormEntryActivity for saving the current session
-An item in the options menu of CommCarePreferences (very hidden) for clearing the saved session
@phillipm A couple of things:
1. Should we make the "Save Session" items in the menus only visible based on a developer setting flag? I'm loathe to keep it coupled with auto-login, but we could just make it its own flag really quick.
2. From quick testing, it seems like the session restorer can't take you back to an entity detail screen, it just takes you to the Entity Select screen immediately prior to that. That …
=> Augment session restoration

app/src/org/commcare/android/framework/CommCareActivity.java
Pressing the OK button wasn't doing anything when the `shouldExit` param of `CommCareActivity.createErrorDialog` wasn't set.
=> Dismiss error dialog when the okay button is pressed

app/src/org/commcare/dalvik/preferences/DeveloperPreferences.java, app/src/org/odk/collect/android/tasks/SaveToDiskTask.java
Experimental form save feature was on by default. Make it opt-in only
Feature from https://github.com/dimagi/commcare-odk/pull/839
=> Switch form save retriggering to be on by default

app/src/org/odk/collect/android/widgets/DateWidget.java
Fix for: http://manage.dimagi.com/default.asp?188712
TimeZone's have inconsistent offsets for the same region, which is something well encoded in JodaTime, but not Java dates, so we were accidentally applying incorrect offsets for dates which crossed those boundaries.
=> Fix for Dates Shifting on Widget Refresh

app/src/org/commcare/android/view/EntityView.java
http://manage.dimagi.com/default.asp?187729
@ctsims has context, but as explanation seems like there was an issue with view ids not being unique, so when you selected a case in awesome mode (which highlights that row, which triggers a redraw on the view) that row was re-added to the list in the wrong place (namely, as a child of the first row), causing that first row to expand in height and get distorted.
Putting in master because it's been broken since 2.23 and if the fix breaks anything, it'll likely be something obscure. Did some testing with scrolling case lists. Didn't get multimedia in case lists working (at all, not with this code applied), but I'm going to stop sinking time into this and let QA do its thing.
=> Make EntityView child view IDs unique

app/src/org/commcare/android/models/logic/FormRecordProcessor.java
The android code changed to stop firing the android specific model processors, which was preventing indexes from updating correctly. 
Depends on 
https://github.com/dimagi/commcare/pull/224/files
=> Fix for Android Indexes not processing correctly on local forms

app/src/org/commcare/android/view/c3/AxisConfiguration.java
http://manage.dimagi.com/default.asp?189509
Putting in 2.25 after all because the bug turns out to not be specific to case list graphs and it's a tiny graphing-only change. That said, I don't know of anyone actually using `show-axes`.
=> Make secondary y axis respect show-axes configuration

app/res/layout/entity_item_image.xml, app/res/values/dimens.xml, app/res/values/styles.xml
Tested on a few screen sizes and it looked fine. Couldn't find a super super low density screen though
Old:
New
ticket: http://manage.dimagi.com/default.asp?189511#1061324
=> Fix for images providing too much padding in case lists

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/activities/EntitySelectActivity.java
@ctsims 
Not much code, but I don't like having the awesome mode conditional in CommCareHomeActivity. Could simplify this PR by removing the pre-select logic I added to EntitySelectActivity.
Bug was that when CommCareHomeActivity detected the autoselect and launched an EntityDetailActivity, that detail activity would be immediately canceled because of this logic: https://github.com/dimagi/commcare-odk/blob/master/app/src/org/commcare/dalvik/activities/EntityDetailActivity.java#L109-L117
=> Awesome autoselect

app/src/org/commcare/android/framework/CommCareActivity.java
Hopefully fix another `java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState` crash by moving more dialog fragment code into `onResumeFragments` from out of `onResume`
https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/6d03fcbc58994b14d98a425d156d1819
=> Move dialog fragment transition to onResumeFragments

app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/android/tasks/templates/CommCareTask.java, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java
https://github.com/dimagi/commcare-odk/pull/924 introduced a bug where form load progress dialogs were not dismissed upon form load completion. I think this bug was being caused by multiple calls to `startBlockingForTask`, once when the task starts and once on `CommCareActivity.onResumeFragments`.
The fix in this PR is to introduce `syncTaskBlockingWithDialogFragment` and call it in `CommCareActivity.onResumeFragments`. Its behavior performs any progress dialog transactions relating task changes that occurred while the activity was in the background.
=> Only start task progress dialogs once

build.gradle
https://github.com/dimagi/commcare-odk/pull/934 bumped the httpmime version from 4.0 to 4.5.1. Turns out 4.5.1 isn't compatible with android, which was causing CommCare to crash when trying to submit forms.
Downgrade httpmime to 4.3.6, which is android compatible.
=> Downgrade httpmime to android compat version

app/src/org/commcare/android/framework/DeviceDetailFragment.java, app/src/org/commcare/android/framework/DeviceListFragment.java, app/src/org/commcare/android/framework/FileServerFragment.java, app/src/org/commcare/android/framework/WiFiDirectManagementFragment.java, app/src/org/commcare/android/tasks/FormTransferTask.java, app/src/org/commcare/android/tasks/UnzipTask.java, app/src/org/commcare/android/tasks/WipeTask.java, app/src/org/commcare/android/tasks/ZipTask.java, app/src/org/commcare/dalvik/activities/CommCareWiFiDirectActivity.java, app/src/org/commcare/dalvik/services/WiFiDirectBroadcastReceiver.java
A bunch of files were performing debug logs using `CommCareWiFiDirectActivity.TAG` instead of their own `TAG` field. 
I'm assuming it was just a copy-paste mistake and not actually intended.
=> Stop using CommCareWiFiDirectActivity.TAG outside of CommCareWiFiDirectActivity

app/proguard_debug.cfg, build.gradle
Enabling proguard for both debug and release builds, with a separate config file for debug builds that includes the -dontobfuscate flag.
=> Enable proguard

app/src/org/commcare/android/models/AsyncNodeEntityFactory.java
http://manage.dimagi.com/default.asp?184603
Not sure if the entity not being in the cache is itself a bug.
@ctsims
=> Skip setSortData if entity isn't cached

libraries/mapballoons/build.gradle
Eventually we will get rid of mapballoons, so I'm not going to look into the "right way" to do this.
=> Bump mapballoons to api 23 as well to not require 22 for building

app/src/org/commcare/android/framework/Permissions.java, app/src/org/commcare/android/framework/RuntimePermissionRequester.java, app/src/org/commcare/dalvik/activities/CallOutActivity.java, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java, app/src/org/commcare/dalvik/activities/LoginActivity.java, app/src/org/commcare/dalvik/dialogs/DialogCreationHelpers.java
Fixes 2 bugs introduced when we bumped our app to target Android 6 (https://github.com/dimagi/commcare-odk/pull/818)
- We weren't asking for storage permissions at app install time, which meant you couldn't install apps on Android 6 devices. The install activity now asks for all permissions that CommCare might need. We also check for all perms at login time to ensure functionality is smooth once logged in. 
- On devices running API 15 and below, we shouldn't ask for READ_EXTERNAL_STORAGE permissions because it isn't available at those API levels and the compat library seems to always return false when checking if the device has those permissions.
=> Ask for all app permissions at ccz app install time

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java
The DispatchActivity refactor left the home screen dispatch logic such that it was no longer checking for the case where the user has been logged out, which I believe we still want to be doing. This PR fixes this by checking for session expiration in attemptDispatchHomeScreen(), and just calling finish() if so. The specific case that I noticed where this is necessary is clearing user data (the app was crashing whenever you did this because CommCareHomeActivity would try to set up the home screen after returning from the preference activity, when there was no longer any logged in user). But I imagine there are other ways in which this could happen, and we would want to handle those smoothly as well, so went for a catch-all fix.
=> Check for session expiration in home screen dispatch

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/activities/DispatchActivity.java
Prevent re-consumption of one-time intent extras when an activity is launched from history
=> Don't re-consume one-time intent extras

app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java, app/src/org/commcare/dalvik/application/CommCareApplication.java
Android 6 related install issue where the temporary storage directory created in `CommCareApplication` wasn't actually being created because we didn't yet acquire external storage permissions from the user.
This PR simply calls the temp storage setup method again after the perms are acquired from the user.
Other changes are addressing no-opy code
=> Setup temp storage dirs after gaining external write perms 

app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java, app/src/org/commcare/dalvik/activities/CommCareVerificationActivity.java, app/src/org/commcare/dalvik/activities/DispatchActivity.java, app/src/org/commcare/dalvik/activities/LoginActivity.java
Fixes 2 multiple apps-related issues:
1) We should never be explicitly redirecting to DispatchActivity from another activity, since all activities are launched by DispatchActivity anyway and it messes up the back stack. In places where we want to direct back to dispatch for multiple apps navigation purposes, replace an explicit redirect with a call to finish().
2) After the DispatchActivity refactor, it is actually valid to be in the dispatch() method with usableAppsPresent() but no seated app; we should just attempt to seat an available app in this case.
=> Remove explicit redirects to DispatchActivity + fix incorrect invalid state

app/src/org/commcare/dalvik/activities/CrashWarningActivity.java, app/src/org/commcare/dalvik/activities/SingleAppManagerActivity.java, app/src/org/commcare/dalvik/activities/UnrecoverableErrorActivity.java, app/src/org/commcare/dalvik/application/CommCareApplication.java
We had a few different places in the app where we performed a restart of CommCare, and were doing it in slightly different (and in 1 case very different) ways in each. This unifies those instances to use 1 single helper method that does the restart in what (I think) is the most proper way.
@phillipm Also (mostly) fixes http://manage.dimagi.com/default.asp?186379, by performing the reboot after uninstall in a way that actually clears the back stack. This fixes the crash that was happening when you press back after being redirected to the install screen, but does NOT fix the fact that you are redirected to the install screen rather than back to the app manager..at least not entirely. This was previously a known shortcoming of the way I had set up restarting after uninstall, in that …
=> Unify instances of restarting commcare

app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java, app/src/org/commcare/android/tasks/ResourceEngineTask.java
Ticket: http://manage.dimagi.com/default.asp?189554
X-Requested with: https://github.com/dimagi/commcare/pull/233
Pushes checking the install status to its own thread during install (could still be improved) and makes the suite parser skip adding resources to the table during startup, which was unnecessary and wasted an enormous amount of time for apps with lots of resources.
=> Dramatic Performance Improvements during large app install/init

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/activities/DispatchActivity.java, app/src/org/commcare/dalvik/activities/HomeActivityUIController.java
Move over fix for [this bug](https://code.google.com/p/android/issues/detail?id=2373) from the home activity, which used to be the activity launched upon app start, to the dispatch activity, which is now the launched activity.
I didn't test this because I don't really have context on it and it would require deploying to the play store.... @ctsims let me know if you know of a good way to test it, or if it simple enough to expect to work.
=> Move play store launcher bugfix from home to dispatch activity

app/src/org/commcare/android/fragments/SetupEnterURLFragment.java, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java, app/src/org/commcare/dalvik/activities/CommCareVerificationActivity.java, app/src/org/commcare/dalvik/activities/EntitySelectActivity.java, app/src/org/commcare/dalvik/activities/FormRecordListActivity.java, app/src/org/commcare/dalvik/activities/MenuList.java
Better to rely on a Java debugger than asserts and logs wrapped in `if (BuildConfig.DEBUG) { ... }`
=> Remove BuildConfig.DEBUG logging

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Address NPE caused by `onScroll` being called before the ODKView gets setup (not sure how that happens...). 
https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/381ce75a8fa267043e5335130e4c6700
=> Check odk view for null before dispatch in onScroll

app/res/drawable/install_start.xml, app/res/drawable/install_stop.xml, app/res/drawable/update_recheck.xml, app/res/values/colors.xml
The linter is always right...
This PR fixes a small bug where some button graphics appeared black. Was introduced in by https://github.com/dimagi/commcare-odk/pull/922 while trying to address https://github.com/dimagi/commcare-odk/pull/922#discussion_r48736171
The way that these drawables are loaded makes it such that they aren't able to reference color resources. Specifically, gradle will convert the xml vector drawables to PNGs at compile time, which I guess means they don't have access to specific resource references. The linter told me this, I thought I checked that it still worked, but I guess I didn't do a good job of that...
=> Don't use color vars in xml drawables

build.gradle
Somewhere between 2.25 and now version code setting got messed up: probably https://github.com/dimagi/commcare-odk/pull/909 ...
Turns out there is already a method called `getVersionCode` so the one I had defined in the build.gradle file wasn't getting called.
Groovy also likes it when method defs come before method usages.
=> App version code setting wasn't happening; fix that

app/src/org/commcare/android/database/user/DatabaseUserOpenHelper.java, app/src/org/commcare/android/database/user/DemoUserBuilder.java, app/src/org/commcare/android/database/user/UserSandboxUtils.java, app/src/org/commcare/android/db/legacy/LegacyInstallUtils.java, app/src/org/commcare/dalvik/application/CommCareApplication.java, app/src/org/commcare/dalvik/services/CommCareSessionService.java, unit-tests/src/org/commcare/android/util/TestUtils.java
Rename `CommCareUserOpenHelper` to be consistent with other database open helpers like `DatabaseAppOpenHelper` and `DatabaseGlobalOpenHelper`
=> Rename CommCareUserOpenHelper to be consistent w/ other openers

app/src/org/commcare/dalvik/activities/CallOutActivity.java
CallOutActivity was overriding onRequestPermissionsResult(), but not actually extending FragmentActivity, so that method wasn't doing anything.
=> Make CallOutActivity extend FragmentActivity

app/src/org/commcare/android/tasks/templates/CommCareTask.java, app/src/org/odk/collect/android/tasks/SaveToDiskTask.java
Changes in https://github.com/dimagi/commcare-odk/pull/862 seem to have broken form saving upon session expiration. The issue was that the form save task was happening without being connected to an activity but using a non-negative task id, causing it to get cancelled via code in `CommCareTask`
Added logging to the task cancelling code in `CommCareTask` in case it is cancelling other tasks without us wanting it to.
=> Ensure form save task doesn't cancel when headless

app/src/org/commcare/dalvik/activities/LoginActivity.java, app/src/org/odk/collect/android/tasks/SaveToDiskTask.java
Issue worth hotfixing: when the user session expires during form entry the form is supposed to save and the user should immediately be forwarded to the login screen. This broke in 2.25, probably due to a refactor to the task connector logic, https://github.com/dimagi/commcare-odk/pull/862.
Additionally, if you rotate the screen when the login progress dialog is showing then the dialog disappears, while the task continues. This results in the login not occurring in certain cases, because the task result callback launches additional login logic. This broke in 2.25 due to a bug fix that persisted login text, https://github.com/dimagi/commcare-odk/pull/890
Fix for:
http://manage.dimagi.com/default.asp?200782
http://manage.dimagi.com/default.asp?190893
Similar PRs targeting master: …
=> 2.25.3 hotfix: persist login dialog and save form on session expiration

app/src/org/commcare/android/framework/SessionActivityRegistration.java
Using the `FLAG_ACTIVITY_SINGLE_TOP` along with `FLAG_ACTIVITY_CLEAR_TOP` causes the existing `CommCareHomeActivity` to first be finished ([see here](https://developer.android.com/reference/android/content/Intent.html#FLAG_ACTIVITY_CLEAR_TOP)), which routes code through `CommCareHomeActivity.onActivityResult`, in turn launching `processReturnFromFormEntry`, which causes a form save toast message to pop up when it shouldn't.
Tested the backstack by pressing back after being redirected to the logout screen on an Android 6 and 4.4.2 devices. Looked fine.
=> 2nd part of 2.25.3 hotfix: Don't launch login using single top flag

app/src/org/commcare/dalvik/activities/CommCareHomeActivity.java, app/src/org/commcare/dalvik/preferences/CommCarePreferences.java
Small bug where clearing user data causes app to crash due to changes in https://github.com/dimagi/commcare-odk/pull/991
=> Prevent home screen button loading on user data clearing

app/src/org/commcare/android/framework/EntityDetailFragment.java, app/src/org/commcare/android/storage/framework/Persisted.java
Fixed bug where "invalid XPath" was showing up in the detail view.
I wonder if there's a better way in the future to allow activities to use the here() function, without requiring them to addFunctionHandler whenever the evaluationContext is used.
=> Add hereFunctionHandler to entityDetailFragment

app/src/org/commcare/android/framework/SessionActivityRegistration.java, app/src/org/odk/collect/android/listeners/FormSavedListener.java, app/src/org/odk/collect/android/tasks/SaveToDiskTask.java
Looks like form saving wasn't happening anymore when the user session expired.
Solution is to move form save callback code from `deliverResult`, which is only invoked when there is an activity (receiver) attached to the task, into `onPostExecute` which is always called.
Probably caused by refactors to CommCareTask that made it stricter in its behavior (like https://github.com/dimagi/commcare-odk/pull/862)
Also fix the way the login activity is launched when the session expires, which broke when I introduced the `DispatchActivity`
=> Fix form save on session expiration

app/src/org/commcare/android/framework/CommCareActivity.java, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java, app/src/org/commcare/dalvik/activities/LoginActivity.java
Turns out when you don't call `super.onSaveInstanceState` when overriding `onSaveInstanceState`, then none of your fragments get restored :boom:
The result is that rotating the screen while any login task is running detaches the task from the activity, making the progress dialog disappear
Fix for http://manage.dimagi.com/default.asp?200782
=> Round II : Fix LoginActivity fragments not restoring properly

app/proguard.cfg
Was getting a crash during form entry of TDH app linked to methods missing in bypass markup lib.
Blindly telling proguard to keep all code in that lib.
=> Don't proguard Bypass markup lib

unit-tests/src/org/commcare/dalvik/application/CommCareTestApplication.java
Sometimes running tests crashes my local machine because an uncaught exception triggers http log reporting, which somehow freezes my machine... hoping this addresses it.
=> Make test framework use custom uncaught exception handler

app/src/org/odk/collect/android/tasks/SaveToDiskTask.java
Saving a form via "Settings -> Save Form" leaves the save dialog up forever...
Gonna hotfix this, but might as well get it into master/2.26 now
http://manage.dimagi.com/default.asp?210500
=> Call super.onPostExecute to get task connector code

app/src/org/odk/collect/android/tasks/SaveToDiskTask.java
Saving a form via "Settings -> Save Form" leaves the save dialog up forever.
Introduced by 2.25.3 hotfix
http://manage.dimagi.com/default.asp?210500
=> Hotfix 2.25.4: Call super.onPostExecute to get task connector code

app/src/org/commcare/dalvik/services/CommCareSessionService.java
Fix notification compatibility issue where on a pre-honeycomb device commcare crashes when a pinned progress notification is shown, like when a form is submitted.
see https://code.google.com/p/android/issues/detail?id=30495 for details on the
=> Notification compat crash when pinned notification shown on pre-honeycomb

app/proguard.cfg
Release builds are failing due to some proguard warnings
=> Remove mapballoons from proguard, add some includedescriptorclasses

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Move call to saveAnswers() so that old widgets haven't updated yet
=> 2.25.5 hotfix -- Fix dynamic refresh of question list content

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Add call to super so that onPrepareOptionsMenu() in SaveSessionCommCareActivity gets called, hiding the "Save Your Session" menu option when that setting is not on.
=> Fix incorrect appearance of "Save Your Session" in FormEntry

app/src/org/odk/collect/android/activities/FormEntryActivity.java
If location services are off in a form that needs them and the form also has loading errors, the result is that the load error dialog isn't shown. Instead just the "turn on location services" dialog is shown. This puts the form in a state where you can swipe forward and crash the app.
Fix is to show "location service are disabled" dialog only when the form successfully loads, not during form loading.
http://manage.dimagi.com/default.asp?209449
=> Don't show both location disabled & form load error dialogs

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java, app/src/org/commcare/dalvik/activities/SingleAppManagerActivity.java, app/src/org/commcare/dalvik/activities/UpdateActivity.java, app/src/org/commcare/dalvik/activities/UpdateUIController.java
Should have done this a while ago, but better late than never:
Disable the ability to apply an update without logging out; because I guess that is sketch.
Also modified the single app manager code to still work. Now applies any updates in the single app manager activity upon return from the update activity. @amstone326 probably want to check that out.
Removing the ability to apply the update in the update screen fixes this QA ticket http://manage.dimagi.com/default.asp?215637
=> Force logout to apply app update

app/res/layout/screen_login.xml
Phillip noticed that in 2.26, the next and done buttons on the android soft keyboard on the login screen were no longer working properly. This is definitely a regression from 2.25, but I couldn't identify what caused it, because we definitely never used to need the lines I added to make this work. Nevertheless, adding them fixes it, and it seems like a reasonable thing to add since this is what those fields are meant for, so am comfortable with not digging further for the source of the change.
=> Make keyboard next and done buttons work again

app/src/org/commcare/dalvik/activities/UpdateUIController.java
If you localize text when an update is being installed then the translation key may be missing.
Hence perform localizations on demand to avoid most issues with trying to localize while installing an update. For those key places where you can't avoid localizing, use the newly introduced `Localize.getWithDefault`
fix for http://manage.dimagi.com/default.asp?215637
cross-requested with https://github.com/dimagi/javarosa/pull/242
=> Don't localize when installing update, keys might be unstaged

app/assets/locales/messages_ccodk_default.txt, app/res/layout/install_permission_requester.xml, app/res/layout/scrolling_info_dialog.xml, app/src/org/commcare/android/fragments/InstallPermissionsFragment.java, app/src/org/commcare/dalvik/activities/CommCareSetupActivity.java, app/src/org/commcare/dalvik/activities/LoginActivity.java, app/src/org/commcare/dalvik/dialogs/DialogCreationHelpers.java, build.gradle
Install screen entered infinite loop if the user selected 'Never show again' for permission request dialog. Break this loop by taking the user to a dedicated screen that allows them to ask for permissions. If they select 'Never show again', then the platform auto-denies subsequent request attempts, so we instruct the user how to enable the perms manually, which is the only way the app will work. Messy UX, but it is a messy, power-user feature of Android...
Fix for http://manage.dimagi.com/default.asp?215782 and http://manage.dimagi.com/default.asp?215779
=> Dedicated fragment for handling denied permissions

app/src/org/commcare/dalvik/application/CommCareApplication.java
Strangely, on my particular device (Nexus 5x / Android 6) when I uninstall an app in the app manger the call to `CommCareApplication.restartCommCare` trashes my app, freezing everything until I force close it. 
Removing these flags fix it.
Not really sure what they do / why they were put here in the first place. @ctsims, do you know?
=> Remove new doc flags for restart intent

app/assets/locales/messages_ccodk_default.txt, app/res/values-es/strings.xml, app/res/values-fr/strings.xml, app/res/values-lt/strings.xml, app/res/values-no/strings.xml, app/res/values-pt/strings.xml, app/res/values-sw/strings.xml, app/res/values/strings.xml, app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/listeners/FormSavedListener.java, app/src/org/odk/collect/android/tasks/SaveToDiskTask.java
Meryn and the PPIUD team brought up an interesting point that users were getting confused by the fact that when you save a form as incomplete via the drop down menu, you get the same message as when you save a form as complete.
This PR makes it so when you save a form using the drop down menu, you get:
> Form saved as incomplete
And when you complete a form at the end-of-form nav, it shows:
> Form saved and ready for submission
Perhaps the "ready for submission" part is confusing because it makes it seem like the user has something they need to do?
=> Make form save messages distinguish between incomplete/complete saves

app/src/org/commcare/android/view/ResizingTextView.java
Note: doesn't prevent home screen buttons from staggering in a different order when in demo mode, but does prevent button reordering when the home screen is paused and resumed.
Follow up to https://github.com/dimagi/commcare-odk/pull/1040
Issue described in http://manage.dimagi.com/default.asp?215785
=> Prevent reordering of home screen buttons due to text resizing

app/proguard.cfg, app/src/org/commcare/android/util/ACRAUtil.java, build.gradle
Update versions:
- ACRA 4.6.2 -> 4.8.0 ([changelog](https://github.com/ACRA/acra/wiki/ChangeLog))
- com.android.tools.build:gradle 1.5.0 -> 2.0.0-alpha9
Remove ACRA rules from proguard because ACRA now provides proguard defaults
=> Update ACRA & gradle android plugin versions

app/src/org/commcare/dalvik/activities/HomeActivityUIController.java
Fix home screen button reordering that occurs on scrolling after rotating from portrait-landscape-portrait.
http://manage.dimagi.com/default.asp?215785
=> Fix home screen button reordering on rotate/scroll

app/src/org/commcare/dalvik/activities/UpdateActivity.java
Missed a case in https://github.com/dimagi/commcare-odk/pull/1042, where `unappliedUpdateAvailableUiState` was being entered, instead of `applyingUpdateUiState`, while an update was being applied, causing a key to be localized when the app resources were unavailable.
http://manage.dimagi.com/default.asp?215637
=> Remember that update is installing in UpdateActivity

unit-tests/resources/odk_level_ipm_restore.xml, unit-tests/src/org/commcare/android/database/StoreFixturesOnFilesystemTests.java
When you run tests from Android Studio you can reference test resources from other projects, such as referencing a commcare level file in odk. This is not the case when you run tests from the command line (hooray!), so such tests will fail.
Fix that by copying the resource into the odk repo.
An alternative fix would be to manually wire things up in the gradle Gradle file such that the commcare test resources are available to the odk tests. I'm not feeling much motivation to do that at the moment; will reconsider if this is something we need to do more often.
=> ODK-level tests were failing when run from command-line

app/assets/graphing/graph.js
This is a ghastly hack that will hopefully fix intermittent issues with the full-screen graphing activity. Occasionally, for reasons I haven't been able to ascertain, when the graphing javascript runs, document.body has a width and height of zero. This causes the graph to not actually display full screen, and I think it's also what causes extra points to appear on the y axis. Deal with this by delaying graph rendering until the body has dimensions.
=> Retry graph rendering if document.body doesn't yet have size

.gitignore, build.gradle
Fixes windows machines not being able to build introduced from https://github.com/dimagi/commcare-odk/pull/1057
=> Fix for windows issue when copying into a project root directory

app/res/layout/component_entity_detail_item.xml, app/src/org/commcare/android/view/EntityDetailView.java
Fix for: http://manage.dimagi.com/default.asp?216179
Previously, we had both the height and width of image views on an entity detail screen set to `match_parent`. This, in conjunction with `setAdjustViewBounds`, was allowing some images to expand the row height (like in the ticket above). This would occur if the combination of matching the parent's width and maintaining the aspect ratio meant needing to increase the image's height to greater than the row height. 
Changes made to resolve this:
-Set the image view's width to always be `wrap_content`; there is no reason we should ever be stretching to fill the image view's width here
-In normal contexts, leave the image view's height set to `match_parent`; there are likely a lot of people who rely on us sizing up these images to fill that …
=> Fix images in detail view

app/src/org/commcare/android/util/MediaUtil.java, unit-tests/src/org/commcare/android/tests/ImageInflationTest.java
Decided to write this up in hotfix format because it probably should have been one. Since at this point we're releasing 2.26 in a few days, I don't think it makes sense to hotfix 2.25, especially since this has been around since 2.24 and we didn't get any bug reports.. But I am really confused how this didn't cause problems for people.
What is the bug?: If the original size of an image is smaller than its bounding container, the image will in some circumstances get scaled up to fill the container.
How did it get introduced?: Basically, I was using 1 method for 2 very different use cases that I somehow convinced myself were the same thing. In one case - `attemptBoundedScaleUp` - we want to be increasing the original image size as much as possible, without exceeding the bounding dimensions. …
=> Fix incorrect scale-up of images

app/src/org/odk/collect/android/activities/FormEntryActivity.java, app/src/org/odk/collect/android/activities/FormHierarchyActivity.java
@esoergel was encountering xpath arity errors that were crashing commcare instead of showing the user the error, which is user addressable.
https://github.com/dimagi/commcare-odk/commit/3a9ad0004f8fb2e33cb505d04e272b6c67d9ce14 adds additional xpath arity exception checks; I'm unsure if they are necessary...
xpath arity checks caught in the form hierarchy activity show a toast message because that activity doesn't extend `CommCareActivity` (it needs to extend the non-Fragment compatible `ListActivity`).
http://manage.dimagi.com/default.asp?217408
=> Catch arity exceptions in form entry and hierarchy views

app/src/org/odk/collect/android/activities/FormEntryActivity.java
See http://manage.dimagi.com/default.asp?217534#1092375
We shouldn't be considering the inserted '>' chars as part of the label when evaluating if its null
=> Remove > char before testing group label

app/src/org/commcare/android/tasks/ResourceEngineTask.java
Fixes a bug when the db closes at an awkward time during install in multiple apps.
=> Fix for resource install status thread

app/src/org/odk/collect/android/activities/FormEntryActivity.java
Prevent the following stack trace from showing in logcat:
```
02-18 17:16:49.150 28264-28264/org.commcare.dalvik E/WindowManager: android.view.WindowLeaked: Activity org.odk.collect.android.activities.FormEntryActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{4eaa4b5 V.E...... R....... 0,0-1026,573} that was originally added here
...
```
=> Dismiss dialogs before finishing form entry activity

app/src/org/odk/collect/android/views/ShrinkingTextView.java
Long question text hints are semi-collapsed such that when you click them they animate open. 
There was a glitch where when you click them to collapse them, the text height animates up from 0 to the collapsed height instead of animating down from the full text height to the collapsed text height.
This was due to the `mFullHeight` being reset to `-1` and not reset to the correct value before collapsing.
=> Reset height before animating shrinking question hint text

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/dalvik/activities/CallOutActivity.java
- Stop case detail phone number callout from crashing when launched
- Fix permission checking to all the 'Send SMS' option to work. Sending an sms via the messenger doesn't actually require permissions
- Fix failure mode when permissions are denied.
- Add localization texts to allow app builders to localize phone number callout text
fix for https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/941a986da24b6c57417032737cfd4be9
=> Fix case detail phone callout & add localizations

app/src/org/commcare/android/framework/CommCareActivity.java
There was an issue where if you enabled auto-login and session restoration and then launched the app with your device is locked (by way of a computer) you are taken to form entry but the form load dialog doesn't go away (upon unlocking) even though the form loaded.
Also fairly certain this PR addresses: http://manage.dimagi.com/default.asp?218363
=> Dismiss task dialog that begins & completed while activity is paused

app/res/xml/preferences_developer.xml, app/src/org/commcare/android/analytics/GoogleAnalyticsFields.java, app/src/org/commcare/android/cases/CaseUtils.java, app/src/org/commcare/android/models/logic/FormRecordProcessor.java, app/src/org/commcare/android/tasks/DataPullTask.java, app/src/org/commcare/android/tasks/ProcessAndSendTask.java, app/src/org/commcare/dalvik/preferences/DeveloperPreferences.java, app/src/org/commcare/xml/AndroidTransactionParserFactory.java
Adds (as a feature flag for now) the ability to trigger a purge whenever the case xml processor detects that the casedb now has stale cases.
CommCare Field/Dev Announce:
Adds a feature flag (cc-auto-purge: yes) for triggering casedb purges when a form is completed that might result in cases needing to leave the device, for instance because their owner ID was changed.
cross-request: https://github.com/dimagi/commcare/pull/265
=> Purge on Commit for Relevant Cases

app/src/org/commcare/android/tasks/templates/CommCareTask.java
Seeing [some](https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/ba6ff7a32e1a4544ec305bd24954d5dc) [crashes](https://commcare-acralyzer.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/commcare-odk/bug/ac631cd32058b56b78e308299c2f3eb8) that imply that instances of `CommCareTask` are failing. Realized that the only why for us to access those failures is via HQ logs, which are super hard to track down.
This PR ensures we report task failures, such as form save or load failures to our unified crash dashboard for easier triaging and response.
=> Report CommCareTask exceptions to ACRA

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/dalvik/dialogs/CustomProgressDialog.java
Sometimes tasks take forever to cancel because we don't actually check the value of  `AsyncTask.isCancelled()` regularly. This is confusing for me, and probably users, because they think that the button is broken.
This PR changes the blocking task dialog text to signify when the task was cancelled.
Eventually we should do a better job of stopping the process when cancel is pressed, but that is sorta hard.
http://manage.dimagi.com/default.asp?217900
=> Show to user that task is cancelling when the press 'stop'

unit-tests/resources/odk_level_ipm_restore_with_empty_fixture.xml, unit-tests/src/org/commcare/android/database/HybridFileBackedSqlStorageTest.java, unit-tests/src/org/commcare/android/database/StoreFixturesOnFilesystemTests.java, unit-tests/src/org/commcare/android/tests/processing/FixtureLoadingTest.java
ODK-level tests to make sure fixtures were actually loaded from a restore file.
Whenever empty fixtures were encountered they would swallow the rest of the restore file into them.
http://manage.dimagi.com/default.asp?158398
cross-request: https://github.com/dimagi/javarosa/pull/257
cross-request: https://github.com/dimagi/commcare/pull/264
=> Parse empty fixtures correctly: don't swallow subsequent fixtures

app/src/org/commcare/activities/EntitySelectActivity.java, app/src/org/commcare/adapters/EntityListAdapter.java
Bug where incorrect number was being shown in case list search result count
Introduced by https://github.com/dimagi/commcare-odk/pull/1033
=> Fix search result count

app/src/org/commcare/activities/FormEntryActivity.java
Don't show form save warning message at end-of-form when the only issue was that a constraint wasn't satisfied.
http://manage.dimagi.com/default.asp?219803
=> Don't show form save error when constraints aren't satisfied

app/src/org/commcare/android/util/FormUploadUtil.java
revert bump from mime 4.0 to 4.5.1 version bump from https://github.com/dimagi/commcare-odk/pull/934
That version bump caused form attachments to be sent to HQ in a format that HQ can't handle, causing data loss for form attachments.
=> Hotfix: revert mime library version bump

app/src/org/commcare/android/database/user/models/FormRecord.java, app/src/org/commcare/android/tasks/PurgeStaleArchivedFormsTask.java
Retroactively tags data for re-submission which was missed as a result of the 2.26.0-2 bug.
=> CommCare 2.26.4 Hotfix Candidate - Resends forms which are likely to have lost data

app/assets/locales/messages_ccodk_default.txt, app/res/layout/create_pin_view.xml, app/res/layout/pin_auth_view.xml, app/res/layout/pin_prompt_text.xml, app/src/org/commcare/activities/CreatePinActivity.java
When the user was brought to the PIN creation screen by primed mode login (meaning they didn't do anything to get there on their own and are also now forced to create a pin), show a short message explaining what it is they're doing.
=> Show PIN explanatory message in primed mode

app/src/org/commcare/CommCareApplication.java, app/src/org/commcare/activities/CommCareHomeActivity.java, app/src/org/commcare/logging/analytics/GoogleAnalyticsUtils.java, app/src/org/commcare/preferences/CommCarePreferences.java
Kevin said all of the data that's been coming into the test dashboard from 2.26 looks sound, so we're going ahead with moving to the live dashboard (but continuing to use the test dashboard for debug builds). Also makes the opt out button more hidden (per request from @jjackson).
=> Finalize product-level analytics for 2.27

app/src/org/commcare/suite/model/graph/Graph.java, app/src/org/commcare/suite/model/graph/XYSeries.java
ICDS request (in the sense that this should enable more performant graphs).
If the nodeset can't be parsed as an xpath path expression, try parsing and evaluating it as an xpath expression. This requires moving nodeset evaluation from installation time to render time, so nodeset expressions can refer to the current case.
I could optimize this, so nodesets that are paths are evaluated during installation, while nodesets that are expressions aren't evaluated until render time...but that'll make the code more complex and I doubt it's going to make a significant impact on the already-terrible graphing performance.
=> Graphing: allow nodesets to be expressions

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/activities/LoginActivity.java, app/src/org/commcare/views/notifications/NotificationMessageFactory.java
If a login is attempted with an empty password, immediately fail and show a specified error message, instead of going through a whole login attempt.
=> Check for empty password on login

app/src/org/commcare/tasks/ResourceEngineTask.java
Fixes the crash when the app is loading resources in the middle of receiving an update.
=> Broad Catch for Resource Scan Crash

app/res/layout/draw_layout.xml, app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/activities/components/ImageCaptureProcessing.java, app/src/org/commcare/views/QuestionsView.java, app/src/org/commcare/views/widgets/SignatureWidget.java
-Move the 'Reset' and 'Cancel' buttons to the right side of the screen, so that the 'Save and Close' button stands alone
-Automatically navigate forward after signature capture ONLY if: a) a signature was actually captured (e.g. they pressed 'Save and Close' as opposed to cancel), b) the signature question is not on the  last screen, and c) the signature widget isn't in a question list
*(Having now done this and realized all of the conditions I needed to add in order to have this make sense, I'm open to being told that it's not a good idea to have the widget behave differently under different conditions. But wanted to share it and see what others think)*
-Remove some of the more embarrassing comments left in the `SignatureWidget` code from when I worked on it as an intern...
=> Signature widget changes

app/src/org/commcare/activities/LoginActivity.java, app/src/org/commcare/activities/LoginActivityUIController.java
Finally realized that this was a regression caused by multiple apps. For no clear reason, I was calling `refreshForNewApp()` (which calls `restoreLastUsername()`) in `onResume()`, instead of just upon successful completion of a call to `SeatAppActivity`, which was causing the last-entered username to be overridden by the last logged in username whenever `onResume()` was called. Sorry for not catching this sooner!
=> Fix overriding of the last-entered username

app/src/org/commcare/activities/LoginActivityUIController.java
Now that `refreshForNewApp()` doesn't get called every time `onResume()` is called, move check for the restore-session-checkbox's visibility to `refreshView()` so that it gets checked every time LoginActivity resumes.
=> Fix visibility of restore-session checkbox

app/src/org/commcare/android/logging/ReportingUtils.java
Encountered
```
03-18 11:12:50.109 31299-1089/org.commcare.dalvik E/AndroidRuntime: FATAL EXCEPTION: Thread-1104
Process: org.commcare.dalvik, PID: 31299
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.commcare.suite.model.Profile.getVersion()' on a null object reference
at org.commcare.android.logging.ReportingUtils.getAppBuildNumber(ReportingUtils.java:21)
at org.commcare.android.logging.ForceCloseLogEntry.<init>(ForceCloseLogEntry.java:42)
at org.commcare.android.logging.ForceCloseLogger.sendToServerOrStore(ForceCloseLogger.java:60)
at org.commcare.android.logging.ForceCloseLogger.access$000(ForceCloseLogger.java:34)
at org.commcare.android.logging.ForceCloseLogger$1.run(ForceCloseLogger.java:46)
at java.lang.Thread.run(Thread.java:818)
```
When an error was …
=> Fix crash logging NPE while gathering ccz app version

app/src/org/commcare/utils/AndroidShortcuts.java
If you try to use the 'CommCare Action' widget before you have installed a CommCare app, it crashes.
http://manage.dimagi.com/default.asp?221071
=> Check if app installed before showing shortcut options

app/src/org/commcare/activities/AppManagerActivity.java, app/src/org/commcare/activities/CommCareVerificationActivity.java, app/src/org/commcare/activities/DispatchActivity.java, app/src/org/commcare/activities/LoginActivity.java, app/src/org/commcare/activities/SingleAppManagerActivity.java
If you:
- install an app w/o multimedia via multiple apps
- try to validate its multimedia
- select 'skip' when it fails
- switch to the normal CommCare app
Then you get a crash due to the intent passed to `DispatchActivity.onActivityResult` being `null`.
Also make sure to call `super.onActivityResult` in a few methods when no the result code isn't processed in the current `onActivityResult` implementation. This isn't necessary, but is the 'right thing' to do.
=> Fix NPE on multiple apps Multimedia Validation

app/src/org/commcare/activities/CommCareHomeActivity.java, app/src/org/commcare/activities/DispatchActivity.java
Callouts from external apps that launch form entry weren't being returned to correctly upon form completion/exit. The dispatch activity was erroneously relaunching the form entry action instead of finishing.
First commit is the fix
Second commit is some aux cleanup
Fix for http://manage.dimagi.com/default.asp?221691
=> Fix form entry callout return

app/src/org/commcare/activities/LoginActivity.java, app/src/org/commcare/activities/LoginActivityUIController.java
Fix for http://manage.dimagi.com/default.asp?221630#1113023, which was introduced in #1138.
Turns out there was one reason for calling refreshForNewApp() in onResume() that I had forgotten about: if you install an app from the app manager and then return to the login screen, the seated app has changed. This PR introduces a check for that case.
=> fix last username spill-over to newly installed app

app/src/org/commcare/activities/LoginActivity.java
Fix crash that occurs when the following steps are performed (this used to work; I'm guessing the regression has been around since `onResumeFragments()` got added to LoginActivity):
1) User is on the login screen with 1 app installed
2) User navigates to the app manager and uninstalls that 1 app
3) User navigates back to the normal CommCare screen, at which point CommCare crashes for 1 of 2 reasons (when I fixed the first the 2nd manifested itself):
--a) `onCreate()` tries to do something with the seated app (which is actually null) before reaching the code in `onResume()` that finishes the activity
--b) Since `onResumeFragments()` comes after `onResume()` in the activity lifecycle, it seemed like it was actually still getting called after `onResume()` called finish(), resulting in a …
=> Fix check for finish() conditions in LoginActivity

app/res/values/strings.xml, app/src/org/commcare/views/dialogs/DialogCreationHelpers.java
Used a phone with a broken 'back' button the other day and got stuck on the 'About CommCare' button because it didn't have an exit button.
=> Add OK button to 'About CommCare' dialog

app/src/org/commcare/activities/CommCareSetupActivity.java
Every once in a while CommCare crashes during an app install with the following stack trace.
Pretty sure the issue is that we are trying to localize some text while the localization dictionary is being installed, which causes the crash because localization setting/getting isn't synchronized. Saw similar issues during app updating.
Sorta embarrassing that I'm only now taking the time to fix this...
```
org.javarosa.core.util.NoLocalizedTextException: The Localizer could not find a definition for ID: profile.found in the 'default' locale.
at org.javarosa.core.services.locale.Localizer.getText(Localizer.java:457)
at org.javarosa.core.services.locale.Localization.get(Localization.java:22)
at org.commcare.activities.CommCareSetupActivity.updateResourceProgress(CommCareSetupActivity.java:708) …
```
=> Localize safely during app install

app/src/org/commcare/fragments/BreadcrumbBarFragment.java, app/src/org/commcare/utils/CachingAsyncImageLoader.java, app/src/org/commcare/utils/MediaUtil.java
Avoid a division by zero in image scaling code. Not sure if blindly avoiding the division is the correct response to this; for instance, getting a zero width value may signify a deeper issue. I didn't take the time to try to reproduce this.
Potential fix for http://manage.dimagi.com/default.asp?221782
=> Avoid image scaling div by zero

app/src/org/commcare/views/EntityView.java
http://manage.dimagi.com/default.asp?222406
Using an incorrect cache key meant that on scroll down & back up, the wrong graph would get displayed for the re-rendered rows.
=> Properly index graph cache

app/src/org/commcare/android/logging/ForceCloseLogger.java, app/src/org/commcare/network/HttpRequestGenerator.java, app/src/org/commcare/tasks/LogSubmissionTask.java, app/src/org/commcare/utils/FormUploadUtil.java
HQ couldn't previously identify what data in the system was coming from demo users, simply that some submissions were forced to be sent without authentication, preventing it from handling them properly.
Also unifies redundant logic around not using authentication when demo users are logged in.
=> Fix for HQ not being able to distinguish demo data

app/src/org/commcare/activities/FormRecordListActivity.java
Form list loading gets called twice for 'saved' forms activity. This is due to it happening [here](https://github.com/dimagi/commcare-odk/blob/master/app/src/org/commcare/activities/FormRecordListActivity.java#L198-L201) and then again in the place that I removed it in this PR
Ticket: http://manage.dimagi.com/default.asp?222620
=> Prevent double loading of form list

app/src/org/commcare/activities/CommCareVerificationActivity.java, app/src/org/commcare/tasks/VerificationTask.java
Allow user to cancel multimedia verification process if they launched it voluntarily.
This includes via the settings menu, during app install in the app manager (@amstone326, is this okay behavior, if not I'll add more flags into `CommCareVerificationActivity), or during validation check from the app manager.
cross-request: https://github.com/dimagi/commcare/pull/276
ticket: http://manage.dimagi.com/default.asp?222474
=> Allow multimedia verification to be cancelled if launched voluntarily

app/res/xml/preferences_developer.xml, app/src/org/commcare/activities/EntityDetailActivity.java, app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java, app/src/org/commcare/logging/analytics/GoogleAnalyticsUtils.java, app/src/org/commcare/preferences/DeveloperPreferences.java
Feature flag for preventing swipe actions in the case detail tab view from exiting the case detail view.
Can be enabled at the app level or in the devices developer options
Setting it to target 2.27 because it is a small, contained change that I think some FMs would appreciate. 
End goal is to do some sort of UX testing to determine whether this should be the default. 
Follow-up: add documentation to https://confluence.dimagi.com/display/ccinternal/CommCare+Android+Developer+Options
=> Feature flag for disabling swiping out of case detail tabs

app/src/org/commcare/android/nsd/NSDDiscoveryTools.java, app/src/org/commcare/utils/TimeBoundOperation.java
Workaround for NSD Services being a disaster and resulting in many-second blocking calls. Now will abandon the search after a brief window (it won't succeed after it's gotten into the bugged state anyway)
Ticket:
http://manage.dimagi.com/default.asp?222766#1120157
=> Fix for NSD Attachment blocking

app/src/org/commcare/android/logging/ForceCloseLogEntry.java, app/src/org/commcare/android/logging/ForceCloseLogSerializer.java, app/src/org/commcare/logging/XPathErrorSerializer.java
Just chatted with Ethan about the HQ handling of our new log subreports, and he asked me to change the name of 1 field to make it less ambiguous, as well as add a couple of useful fields that were missing from force closes.
=> Minor changes to forceclose/xpatherror log entries

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/utils/SyncDetailCalculations.java
Chatted with Sheel about this ticket http://manage.dimagi.com/default.asp?211211 and determined that the only lingering change necessary was to make the Sync button subtext clearer. That subtext previously read "Sync with Server (x)", where x is the number of unsent forms. It seems silly to duplicate the main text that's already on the button, and not give a good description of what that number actually represents, so changing it to instead read "Unsent Forms: x".
(The other concern on this ticket -- the error text persisting and therefore obfuscating the unsent forms count -- appears to have been resolved at some point since the version the partner was on).
I also noticed while working on this that that somewhere in the process of this code getting refactored, some unreachable code was …
=> Improve unsent forms subtext + fix subtext coloring

app/assets/graphing/graph.js
See https://github.com/dimagi/commcare-odk/pull/1064 for context.
Don't have a fix for the actual bug yet, but the parto team requested removal of the error message, since it startles users and there's nothing they can do about it.
=> Graphing: blank screen instead of error message

app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/tasks/FormLoaderTask.java
Fix for bugs where the itext calculation in xpath was always using the form's default locale, even if the app locale is different.
Needed for ICDS
Fogbugz:
http://manage.dimagi.com/?221785
cross-request: https://github.com/dimagi/javarosa/pull/290
=> Fix for IText Calculations not properly initializing with the app locale

app/src/org/commcare/utils/CommCareExceptionHandler.java
The user-facing error activity was not always being displayed when a crash was caused by a NoLocalizedTextException, because we weren't checking the Throwable's cause(s).
@phillipm Seems like something that could be worth sneaking into 2.27?
=> Fix user notifications for localization exceptions

app/res/drawable/check_update.xml, app/res/layout-land/update_activity.xml, app/res/layout/update_activity.xml
Realized that https://github.com/dimagi/commcare-odk/pull/1170 changed the color of the install check mark to blue, which looks bad.
Fixes the color of:
=> Fix issue where install checkmark was blue instead of green

app/src/org/commcare/activities/components/FormNavigationUI.java
Fix for this crash, which was showing up in the ICDS force close logs:
```java.lang.NullPointerException at org.odk.collect.android.activities.components.FormNavigationUI.updateFloatingLabels(FormNavigationUI.java:157) at org.odk.collect.android.activities.components.FormNavigationUI.updateNavigationCues(FormNavigationUI.java:37) at org.odk.collect.android.activities.FormEntryActivity.handleFormLoadCompletion(FormEntryActivity.java:1942) at org.odk.collect.android.activities.FormEntryActivity.access$1700(FormEntryActivity.java:136) at org.odk.collect.android.activities.FormEntryActivity$15.deliverResult(FormEntryActivity.java:1862) at org.odk.collect.android.activities.FormEntryActivity$15.deliverResult(FormEntryActivity.java:1859) at …
```
=> Prevent crash when an add-repeat dialog is the first thing shown in a form

app/AndroidManifest.xml
Might be causing strange data restoration issues that occur after uninstalling and reinstalling CommCare on my Android 6 device.
So nice that it defaults to `true` when unset... because we all want to opt into new features that change behavior and weren't advertised on the [Android 6 release page](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html)
=> Heed the lint warnings; don't use google data backup feature

app/res/xml/preferences_developer.xml, app/src/org/commcare/preferences/DeveloperPreferences.java
Currently, when you save a form on CommCare for Android, it walks through all questions, re-answering them and firing all associated triggers. So if you have iteration in your form, it will step through everything again, potentially taking a long time. This behavior is a data assurance measure.
We have fixed some bugs that made this refiring required and verified that it is no longer needed. Hence, it is time to enable it by default. I'm leaving the dev option listed in the off chance that someone needs to quickly disable the optimization to check if it is messing with form save behavior.
ICDS and TDH have done QA to check that enabling this optimization is okay in terms of exhibiting the same form save behavior. We have also done a standard round of QA (by accident) with this …
=> Make form save not fire all form triggers the default

app/res/xml/preferences_developer.xml, app/src/org/commcare/activities/components/FormNavigationUI.java, app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java, app/src/org/commcare/preferences/DeveloperPreferences.java
Make form submission button animation disabled by default, but allow it being enabled by the "Animate form submit button" developer option. You can enable at the app level by setting the `cc-animate-form-submit-button` custom property to `yes`
Allows the UI changes in https://github.com/dimagi/commcare-odk/pull/1133 to be field tested before being deployed widely
=> Hide form submit button animation behind feature flag

unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.java, unit-tests/src/org/commcare/android/tests/application/AutoUpdateTest.java, unit-tests/src/org/commcare/android/tests/formnav/EndOfFormTest.java, unit-tests/src/org/commcare/android/tests/formsave/FormRecordProcessingTest.java, unit-tests/src/org/commcare/android/tests/processing/ArchivedFormPurgeTest.java, unit-tests/src/org/commcare/android/util/TestAppInstaller.java, unit-tests/src/org/commcare/models/database/StoreFixturesOnFilesystemTests.java
Removing a lot of duplicate app install code from odk unit tests.
=> Tests: use same entry point for all app install logic

app/src/org/commcare/views/HorizontalMediaView.java
- Break-up method into smaller helpers
- Remove navigation icon code, which is never executed because `int navStyle` is always set to `NAVIGATION_NONE`
perhaps easiest reviewed commit-by-commit
=> Refactor: HorizontalMediaView

app/src/org/commcare/utils/FileUtil.java, app/src/org/commcare/utils/MediaUtil.java
Addresses this crash from the ICDS force-close logs:
```java.lang.OutOfMemoryError at android.graphics.BitmapFactory.nativeDecodeStream(Native Method) at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:709) at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:685) at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:447) at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:486) at org.odk.collect.android.utilities.FileUtils.scaleAndSaveImage(FileUtils.java:128) at org.odk.collect.android.activities.components.ImageCaptureProcessing.moveAndScaleImage(ImageCaptureProcessing.java:36) at org.odk.collect.android.activities.FormEntryActivity.processCaptureResponse(FormEntryActivity.java:484) at …
```
=> prevent OOM error when processing image capture

app/assets/locales/messages_ccodk_default.txt, app/res/values/strings.xml, app/src/org/commcare/views/dialogs/DialogCreationHelpers.java
ICDS feature to allow for adding custom acknowledgement in 'About CommCare' dialog.
Requires setting `custom.acknowledgement` translation key on HQ.
Requires double `\n\n` to do a new line break.
Adds the markdown enabled "Foo bar hello bold?".
When `custom.acknowledgement` is unset the about dialog looks like:
=> Allow for custom acknowledgement in 'about commcare'

app/src/org/commcare/models/database/DbUtil.java
Fix form deserialization bug introduced earlier in 2.27 where classes that start with the `org.odk.collect` package weren't included in the prototype factory class list.
Caused form deserialization to always fail, and revert back to xml form loading, when the form had intent questions in it.
Bug introduced by https://github.com/dimagi/commcare-odk/pull/1050
=> Include odk classes in prototype factory class setup

app/src/org/commcare/activities/CommCareActivity.java
Logs for people who run across dialog issues rapidly log thousands of the same message unnecessarily.  Prevents the logs from getting out of control
=> Fix for overly verbose logging with dialogs

app/src/org/commcare/activities/CommCareHomeActivity.java, app/src/org/commcare/activities/FormAndDataSyncer.java, unit-tests/src/org/commcare/android/mocks/FormAndDataSyncerFake.java, unit-tests/src/org/commcare/android/tests/formnav/EndOfFormTest.java, unit-tests/src/org/commcare/android/tests/formsave/FormRecordProcessingTest.java
If you press the sync button when there are forms to submit, rotate the screen while the form submit task is running, then the sync task will be launched using a stale activity due to the fact that the `FormAndDataSyncer` would using the `activity` field instead of the `receiver` method arg. 
Would cause sync to continue in background without user being aware of it.
=> Start sync task from form submit task using receiver activity

app/AndroidManifest.xml
When I changed the `DispatchActivity` `android:name` in the AndroidManifest.xml file it caused anyone upgrading to 2.27 to loose their CommCare homescreen launcher.
Adding an alias from the old name to the new name prevents that. And if you already replaced the launcher icon on 2.27.0, it doesn't mess with that. 
http://blog.danlew.net/2014/01/16/preserve-your-launchers-use-activity-alias/
=> Add activity alias for old launcher name

app/src/org/commcare/activities/components/FormNavigationUI.java
Add back gray-out / button grow animation for current end of form nav experience
Was broken by https://github.com/dimagi/commcare-odk/pull/1208
=> Restore normal end of form button animation experience

app/src/org/commcare/activities/CommCareActivity.java, app/src/org/commcare/activities/CommCareHomeActivity.java, app/src/org/commcare/activities/FormAndDataSyncer.java, app/src/org/commcare/activities/LoginActivity.java, app/src/org/commcare/fragments/TaskConnectorFragment.java, app/src/org/commcare/network/HttpRequestGenerator.java, app/src/org/commcare/tasks/DataPullTask.java, app/src/org/commcare/tasks/templates/CommCareTask.java, app/src/org/commcare/views/dialogs/CustomProgressDialog.java
Allow user to cancel `DataPullTask` up until point where data has been downloaded and processing begins.
Don't allow user to cancel syncs that have been started automatically.
Avoid synchronization between button hiding and starting the data processing block. We avoid it because it isn't that bad if a user presses the cancel button after data processing has begun. If that happens, the task dialog says it is cancelling, butt the data processing still completes (because we don't check the `AsyncTask.isCancelled()` state in that block). Resulting in the user being slightly annoyed, if the data processing takes a long time.
=> Show cancel button during data download part of sync

app/AndroidManifest.xml
Revert https://github.com/dimagi/commcare-odk/pull/1227 because it introduced another commcare icon in the app list
=> Hotfix: Double launcher icon showing in app list

app/src/org/commcare/tasks/SaveToDiskTask.java
Moves a force close when serializing documents with encoding errors to a visible error, rather than swallowing those errors
cross-requested: https://github.com/dimagi/javarosa/pull/292
=> Don't swallow encoding errors when serializing

app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/activities/FormHierarchyActivity.java
Fix NPE that occurs when opening a saved form.
Coming up because the inline video restore code was running when there were no questions loaded, since the `FormHierarchyActivity` is launched via the `FormEntryActivity`. Issue originated from changes in https://github.com/dimagi/commcare-odk/pull/1234
=> Form Hierarchy NPE fix

app/src/org/commcare/activities/CommCareHomeActivity.java, app/src/org/commcare/activities/LoginActivity.java, app/src/org/commcare/activities/SeatAppActivity.java, app/src/org/commcare/activities/SingleAppManagerActivity.java
Was doing a couple of things carelessly in regards to app seating in the app manager. This PR makes it so that:
-For operations in `SingleAppManagerActivity` that require the current app to be seated (updating and verifying MM), we only try to seat the app if it is not already seated.
-When seating the current app is necessary, use the `SeatAppActivity` rather than just calling 'initializeAppResources()` (for the same reason we decided to use the SeatAppActivity on the login screen -- the seating process can take a while for some apps, and having the screen just go unresponsive with no indication of what's happening is a terrible UX).
=> Handle app seating in app manager properly

app/src/org/commcare/activities/CommCareActivity.java, app/src/org/commcare/activities/CommCareHomeActivity.java, app/src/org/commcare/activities/EntitySelectActivity.java, app/src/org/commcare/fragments/EntitySubnodeDetailFragment.java
While http://manage.dimagi.com/default.asp?225812 turned out to be an HQ issue at its root, it revealed some issues (one very large and one small) with how we were handling an XPathException thrown by `handleCompute()` in `SessionNavigator`. This PR resolves those 2 issues (comments in-line on the PR as to what was fixed).
cross-request: https://github.com/dimagi/commcare/pull/297
=> Handle an XPathException in SessionNavigator properly

app/src/org/commcare/activities/CommCareSetupActivity.java, app/src/org/commcare/utils/Permissions.java
Fix issue where install screen would consistently ask for SMS reading permissions.
Underlying issue was due to the fact that if you ask the user for permissions while the user is already being asked for permissions, the request automatically fails.
=> Correctly ask for SMS reading permissions during app install

app/AndroidManifest.xml, app/src/org/commcare/activities/MenuList.java, build.gradle
https://github.com/dimagi/commcare-odk/pull/1227 introduced the issue where 2 `CommCare` launcher icons show up in the Android app list:
This fixes that.
Also, bump to gradle plugin to 2.1.0 (time to update to Android Studio 2.1 :) )
And update Google support libs from `23.2.1` to `23.3.0`
=> Fix double app icon

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/tasks/SaveToDiskTask.java
cross-request: https://github.com/dimagi/javarosa/pull/295
See description in that PR
=> Tell user when CommCare's unable to save unsupported unicode

app/src/org/commcare/activities/CommCareHomeActivity.java, app/src/org/commcare/activities/FormAndDataSyncer.java, app/src/org/commcare/activities/LoginActivity.java, app/src/org/commcare/tasks/PullTaskReceiver.java, unit-tests/src/org/commcare/android/mocks/FormAndDataSyncerFake.java
Allow all code paths that use `DataPullTask` (from both `LoginActivity` and `HomeActivity`) to utilize the same sync methods (in `FormAndDataSyncer`).
Heads up that this doesn't make a huge difference with the current state of the code, but I'm going to utilize it more in the consumer apps PR.
=> Unify all sync paths

build.gradle, templates/google-services.json
Setup CommCare LTS (Long Term Support) build so that we can have a slower, more stable release cycle for critical projects like ICDS.
Allows one to install CommCare and CommCare LTS side by side on a device:
When inside of the CommCare LTS app, there is no distiction between it and normal CommCare. I hope this is fine.
I will back-port this PR to 2.27 when creating the LTS build for ICDS
=> Enable CommCare LTS build

app/src/org/commcare/views/widgets/GridWidget.java
Fixes issue caused by https://github.com/dimagi/commcare-odk/pull/1233, while retaining the fix that that PR was for.
Since a GridView is intended to be a scrolling container, rather than to wrap all of its contents, we have to explicitly set the height of the GridView based upon how much space we need to fit all of the images.
=> Fix cutting off of images in GridWidget 

app/res/layout/entity_select_layout.xml
Fix bug https://github.com/dimagi/commcare-odk/pull/1119 changes where the search banner would always be shown for Incomplete and Saved form lists
=> By default don't show form list search banner

app/src/org/commcare/utils/SyncDetailCalculations.java
Unsatisfying 'fix' for following exception that has been showing up a lot on ACRA:
```
org.commcare.models.database.UserStorageClosedException
at org.commcare.models.database.SqlStorage.getIDsForValues(SqlStorage.java:91)
at org.commcare.models.database.SqlStorage.getIDsForValue(SqlStorage.java:83)
at org.commcare.utils.SyncDetailCalculations.updateSubText(SyncDetailCalculations.java:35)
at org.commcare.activities.HomeButtons$3.update(HomeButtons.java:122)
at org.commcare.adapters.SquareButtonAdapter.bindCard(SquareButtonAdapter.java:78)
at org.commcare.adapters.SquareButtonAdapter.onBindViewHolder(SquareButtonAdapter.java:63)
at org.commcare.adapters.HomeScreenAdapter.onBindViewHolder(HomeScreenAdapter.java:84)
at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView. …
```
=> Catch UserStorageClosedException thrown on home screen

app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/logging/UserCausedRuntimeException.java, app/src/org/commcare/tasks/FormLoaderTask.java, app/src/org/commcare/tasks/templates/CommCareTask.java, app/src/org/commcare/utils/ACRAUtil.java
When a form load crashes due to an `XPathException`, don't send that crash to ACRA, since it is most likely a app builder misconfiguration made by the user. Still shows the error to the user so they can address it (and logs it to HQ).
Made these changes because we got hundreds of these exceptions reported to ACRA from the 2.27 release.
Also, prevent ACRA from crashing commcare debug builds when it tries to submit to an invalid URL due to bad debug default configs.
=> Don't send XPath errors found during form loading to ACRA

app/src/org/commcare/views/notifications/NotificationMessage.java, unit-tests/src/org/commcare/notifications/NotificationMessageTest.java
Add test coverage to `NotificationMessage` parcel code and fix crash associated with that code.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.commcare.dalvik/org.commcare.activities.MessageActivity}: java.lang.RuntimeException: bad array lengths
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5299)
at java.lang.reflect.Method.invokeNative(Native Method)
at …
```
=> Fix NotificationMessage parcel logic

app/src/org/commcare/CommCareApplication.java, app/src/org/commcare/activities/MenuGrid.java, app/src/org/commcare/activities/MenuList.java, app/src/org/commcare/adapters/MenuAdapter.java
When loading the menu list, fixtures used by suite entries will be loaded. If there is a fixture reference typo in the suite file or the fixture hasn't been pulled down from HQ, CommCare crashes. This PR instead shows the user and lets them back-out of the module list, so that they can try to update the app or sync with HQ.
```
Caused by: org.commcare.core.process.CommCareInstanceInitializer$FixtureInitializationException: Could not find an lookup table for src: jr://fixture/commcare:reports
at org.commcare.core.process.CommCareInstanceInitializer.setupFixtureData(CommCareInstanceInitializer.java:115)
at org.commcare.core.process.CommCareInstanceInitializer.generateRoot(CommCareInstanceInitializer.java:70)
at org.javarosa.core.model.instance.ExternalDataInstance.initialize(ExternalDataInst …
```
=> Tell user about non-existent fixture when loading module list

app/res/layout/component_entity_detail_item.xml
Graphs should take up the full width of the screen.
Before:
=> Adjust padding on entity detail view

app/assets/graphing/graph.js
Allow blank strings for labels. Previously, a blank value would be overwritten with the c3-generated label.
=> Graphing: allow blank labels

app/src/org/commcare/graph/view/c3/DataConfiguration.java
Bar graphs have a beginning and ending fake label. https://github.com/dimagi/commcare-odk/pull/1258 prevents any text from being displayed at these locations, but there's still a tick mark being drawn. Fix that.
=> Don't display extra ticks on bar graphs

app/src/org/commcare/graph/view/GraphView.java, app/src/org/commcare/views/EntityDetailView.java
Revert https://github.com/dimagi/commcare-odk/pull/840
While there are no longer technical reasons that require bar graphs to be square, bar graphs are mostly used for mobile UCR, which looks nicer with taller graphs.
=> Revert "Standard aspect ratio for graphs"

scripts/consumer_apps_builder.py
Don't rely on the ordering of files in app dir, and instead use the expected filenames explicitly.
=> Consumer apps build script update #1

scripts/consumer_apps_builder.py
Add ability to specify debug vs release build
=> Consumer apps build script update #3

app/res/layout/menu_list_item_modern.xml, app/res/values/attrs.xml, app/src/org/commcare/views/ShrinkingLinearLayout.java
The previous audio button behavior has been broken for what appears to be a long time. The audio buttons would drift off the screen if menu text got too long.
Fix for: http://manage.dimagi.com/default.asp?225035
Implementing the new Audio UI to Biyuen's spec was surprisingly not well supported, had to implement a custom layout rule. 
NOTE: I'm going to figure out whether this needs to make it into 2.27, will probably splice in the change if so.
Examples of the new behavior for short and long text, along with the broken behavior, and the pre-new-ui behavior (far right) that is really awkward on larger screens:
=> Fix for Busted Menu Audio Layout

app/src/org/commcare/activities/LoginActivityUIController.java
Fix for http://manage.dimagi.com/default.asp?225005
Reproducible by downloading an app where the default is non-english (icds), logging in and then clearing user data. This will cause the LoginActivity to be started in such a way that the hint isn't localized.
@amstone326 not entirely if this is the correct code change to fix the issue, in that it fixes it but maybe there is a more appropriate approach.
=> Localize login password text hint

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/activities/CommCareHomeActivity.java, build.gradle, templates/google-services.json
| Old | New |
|---|---|
| ![demo-old](https://cloud.githubusercontent.com/assets/94817/15478800/9c48a5dc-20ea-11e6-9f92-7486ec05f5b1.png) | ![demo-new](https://cloud.githubusercontent.com/assets/94817/15478802/a166f280-20ea-11e6-914a-9f14a31e6a0f.png) |
Make demo warning persist across screen rotation
**Additionally**: 
- updates to google-services 9.0, which has no notable changes to maps or analytics: https://developers.google.com/android/guides/releases 
- update from SQLCipher 3.3.1-2 to 3.4.0. I read over the [changelog](https://discuss.zetetic.net/t/sqlcipher-3-4-0-release/1273) and looks like we are good to go, (checked that we don't use the now deprecated `PRAGMA cipher`). Touts something like up to a 20% performance improvement over 3.3.1
=> Redo demo warning dialog

app/src/org/commcare/CommCareApp.java, app/src/org/commcare/CommCareApplication.java, app/src/org/commcare/models/database/AndroidPrototypeFactorySetup.java, app/src/org/commcare/models/database/DbUtil.java, app/src/org/commcare/models/legacy/LegacyDbHelper.java, unit-tests/src/org/commcare/CommCareTestApplication.java, unit-tests/src/org/commcare/android/util/TestUtils.java
- Only print resource tables on debug builds. Takes ~.25 seconds during startup time.
- Move Android prototype factory setup code to its own file for better readability
- Remove unneeded class name `contains` checks for `.test.` and `readystatesoftware`
=> Small startup optimization: don't print tables in prod code

app/src/org/commcare/activities/CommCareSetupActivity.java
When an install failure has a useful error message, include in the toast message a prompt to view notifications for more info.
Before: 
After:
=> Add prompt to view notification when it is available

app/src/org/commcare/activities/components/FormNavigationUI.java
If a user tries to open a form for which they don't have access to any of the entries in a lookup table select question, CommCare used to crash. Instead, show this error box and back out of the form: 
cross-requested: https://github.com/dimagi/javarosa/pull/299
=> Show error message when lookup table for select question missing

scripts/consumer_apps_builder.py, scripts/download_app_into_standalone_asset.sh
Now that Ethan has augmented the endpoint to take additional parameters, have the consumer apps builder script pull down the specified app version.
=> Specify app version for consumer apps

app/src/org/commcare/activities/CommCareSetupActivity.java
Since I had placed the installation code for single app installs after the permissions checks, the install just didn't happen on devices that don't check for permissions... This was dumb, I should have realized this earlier.
=> Make consumer apps work on non-Android 6 devices

app/src/org/commcare/activities/FormRecordListActivity.java, app/src/org/commcare/tasks/PurgeStaleArchivedFormsTask.java
If form purging takes so long that the user launches the saved form list, the user will be blocked by a dialog. This is to prevent the user from selecting a purged form. Once this dialog is dismissed, it is currently the case that purged forms are still shown.
This PR refreshes the saved form list after the purge task completes to prevent the user from selecting a purged form.
Also launches the purge task using the parallel thread pool when available.
=> Refresh saved form list after form purge completes

app/src/org/commcare/android/storage/framework/Persisted.java
Fixes serialization crashes of the following nature that seem to be caused by object serialization synchronization issues when multiple threads are involved. Specifically, since we cache class fields that we do reflection on, issues arise if one thread sets a field to accessible, and before it can access the field another thread sets it to inaccessible.
```
org.commcare.android.adapters.IncompleteFormListAdapter.resetRecords(IncompleteFormListAdapter.java:164)
at org.commcare.dalvik.activities.FormRecordListActivity.refreshView(FormRecordListActivity.java:312)
at org.commcare.dalvik.activities.FormRecordListActivity.onCreate(FormRecordListActivity.java:223)
at android.app.Activity.performCreate(Activity.java:5451)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:109 …
```
=> Synchronize Persisted's Field.setField calls

app/src/org/commcare/CommCareApplication.java, app/src/org/commcare/activities/CrashWarningActivity.java, app/src/org/commcare/activities/SingleAppManagerActivity.java, app/src/org/commcare/activities/UnrecoverableErrorActivity.java, unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.java
@phillipm Embarrassed that it took me so long to figure this out, but here goes: the problem was that the `unredirectedSessionExpiration` getting registered by the app uninstall was getting wiped out by the call to `System.exit()` in `restartCommCare`. I played around a bit and realized that it was fine to remove this in the case of uninstalling, as long as I also made sure that the app that's being uninstalled gets unseated first, if it is the currently seated app.
=> Fix session unavailable crash after uninstall

app/src/org/commcare/adapters/MenuAdapter.java, app/src/org/commcare/utils/AndroidUtil.java
Case loading code was caching a Vector instance, which was then getting modified when it was union'ed with another list. The fix is to make the union code not modify the incoming objects.
Fix for http://manage.dimagi.com/default.asp?229108
=> Don't modify incoming object in list union code

app/src/org/commcare/adapters/IncompleteFormListAdapter.java, app/src/org/commcare/models/AndroidSessionWrapper.java
If you install an app that has a `sync-request` entry in the suite.xml file, CommCare crashes when you open the 'saved forms' view.
Also update `mockEasiestRoute` with the same fix. `mockEasiestRoute` is only a debug method used to load saved forms onto a device manually
=> Fix saved form crash when app has sync-request

app/res/layout/formrecordview.xml, app/res/values/styles.xml, app/src/org/commcare/adapters/IncompleteFormListAdapter.java, app/src/org/commcare/views/IncompleteFormRecordView.java, unit-tests/resources/commcare-apps/form_nav_tests/form_instances_restore.xml, unit-tests/src/org/commcare/android/tests/activities/FormRecordListActivityTest.java
Added a test to open saved form list in Robolectric.
Required moving image resource setup from java class to xml layout due to robolectric resource availability constraints.
Also make white 'Unsent' text darker
| Before | After |
| --- | --- |
| ![screen](https://cloud.githubusercontent.com/assets/94817/15834978/f5571c1e-2bfb-11e6-9ec6-8f43493b5915.png) | ![after](https://cloud.githubusercontent.com/assets/94817/15834980/f9af5178-2bfb-11e6-91a6-8d98c6be5b01.png) |
=> Robolectric tests for Saved Forms view

app/res/xml/preferences_developer.xml, app/src/org/commcare/android/storage/framework/Persisted.java, app/src/org/commcare/models/AndroidSessionWrapper.java, unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
2.28 version of https://github.com/dimagi/commcare-odk/pull/1303
Includes test that fails before the fix is applied and code indentation, so ?w=1
The last commit fixes the debug feature that allows for loading saved forms onto the device from a payload.
=> 2.28 version of Synchronize Persisted's Field.setField calls

app/src/org/commcare/activities/DispatchActivity.java
After a lot of debugging and scratching our heads, Clayton and I finally decided a while back that this was the result of an Android-level bug, in which they are not adhering to the contract that an activity will not resume until the activity that it has called out to with `startActivityForResult()` has in fact returned a result.
The fix is to manually make sure that we don't relaunch the LoginActivity if we are currently waiting for a result from the LoginActivity.
Added the 'don't pull' label until we collectively agree that we want to go this route. @ctsims @phillipm
=> Fix login redirection bug

app/src/org/commcare/utils/SyncDetailCalculations.java
Addresses http://manage.dimagi.com/default.asp?190347. Make warning text on sync button orange (Biyeun's suggestion) instead of red.
=> Remove red text on blue sync button

app/src/org/commcare/utils/AndroidUtil.java, unit-tests/src/org/commcare/utils/StaticInjectionTests.java
As part of performance improvements for ICDS Daily Feeding Form: Use static injection to use the  built-in String.split() method in Android, while retaining our custom implementation for j2me. Also add tests to assert equivalence between the 2 implementations.
A subset of these changes will be included in the 2.27 LTS release as well, but I haven't set that up yet (waiting to talk with @ctsims on the exact right way to do that)
cross-request: https://github.com/dimagi/javarosa/pull/304
=> Use built-in String.split() in Android code

build.gradle, scripts/consumer_apps_builder.py
1. Make generating the package identifier from the app name robust to app names that contain illegal characters
2. Add a mechanism to the build script for building only some of the apps in the consumer_apps directory
=> Consumer apps tweaks

app/src/org/commcare/activities/CommCareHomeActivity.java, app/src/org/commcare/views/dialogs/CommCareAlertDialog.java, app/src/org/commcare/views/dialogs/CustomViewAlertDialog.java
Phillip recently added an OK button to the About CommCare dialog, but pressing it did not contribute to the count for enabling Developer Options. This PR makes it so that either pressing OK or pressing 'back' contribute to the count (canceling a dialog calls both `onCancel` and `onDismiss`, so placing the code in the `OnDismissListener` only is sufficient). 
Also fix a small bug in `CommCareAlertDialog`
=> Fix confusing behavior when enabling developer options

app/assets/locales/messages_ccodk_default.txt, app/res/values-es/strings.xml, app/res/values-fr/strings.xml, app/res/values-lt/strings.xml, app/res/values-no/strings.xml, app/res/values-pt/strings.xml, app/res/values-sw/strings.xml, app/res/values/strings.xml, app/src/org/commcare/activities/FormEntryActivity.java
Allow repeat dialog to be localized in standard fashion.
| Before add first group | After add first group |
| --- | --- |
| ![a_new_repeat](https://cloud.githubusercontent.com/assets/94817/15938576/bb8b45b2-2e41-11e6-8746-aab510930a64.png) | ![b_new_repeat](https://cloud.githubusercontent.com/assets/94817/15938581/c31703b6-2e41-11e6-9ed8-42f2678cd445.png) |
| Before add another group | After add another group |
| --- | --- |
| ![a_another_repeat](https://cloud.githubusercontent.com/assets/94817/15938599/d0fc349c-2e41-11e6-93dc-cca22e9dac30.png) | ![b_another_repeat](https://cloud.githubusercontent.com/assets/94817/15938607/d5f6b800-2e41-11e6-928f-951e0723ecf2.png) | 
Follow-up for http://manage.dimagi.com/default.asp?229190
=> Localize repeat dialog

app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java, app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java, app/src/org/commcare/engine/resource/AndroidResourceManager.java, app/src/org/commcare/engine/resource/AndroidResourceTable.java, app/src/org/commcare/tasks/ResourceEngineTask.java, app/src/org/commcare/tasks/UpdateTask.java, app/src/org/commcare/tasks/VerificationTask.java, app/src/org/commcare/utils/AndroidCommCarePlatform.java, app/src/org/commcare/utils/DummyResourceTable.java
Changes:
- Keep an in-memory set of resources present in a `ResourceTable`. This allows `resourceDoesntExist` calls to avoid hitting storage. Requires overriding additional logic to keep this set fresh.
- Use modern `SqlStorage.getRecordsForValue` in `getResourcesForParent` to avoid intermediate ID reads from storage.
- Implement `TableStateListener`'s `compoundResourceAdded` and `simpleResourceAdded` in `ResourceEngineTask, to keep counts in sync when async progress update threads are running.
cross-request: https://github.com/dimagi/commcare/pull/306
=> Installation and update performance improvements

app/src/org/commcare/android/javarosa/IntentCallout.java
Serialize `type` and `data` fields in `IntentCallout`. Not doing this means that intent callouts that use these fields only work when the form is loaded via xml (1st time) and not when it is loaded from a serialized object.
=> Serialize 'type' and 'data' fields in IntentCallout

app/res/xml/preferences_developer.xml, app/src/org/commcare/activities/components/FormNavigationUI.java, app/src/org/commcare/preferences/DeveloperPreferences.java
Enable @ctsims new end-of-form navigation animation / button by default. Removes the ability to turn it off in the developer options.
Undoes work by https://github.com/dimagi/commcare-android/pull/1208 and https://github.com/dimagi/commcare-android/pull/1228
**Release Notes**: new end-of-form navigation animation
=> Re-enable new end-of-form navigation animation

app/res/layout/component_text.xml, app/src/org/commcare/views/EntityView.java
Case list columns have the ability to set width percentages. On small devices, it might turn out that the width calculated for a column is smaller or super close to the padding size of that column. 
This PR removes the column's horizontal padding when its size is too close to the width allotted for the column.
Before:
After:
Ticket: http://manage.dimagi.com/default.asp?230152
=> Remove padding from case list columns that have small widths

app/src/org/commcare/activities/FormEntryActivity.java
In this PR https://github.com/dimagi/commcare-android/pull/1126, I had made it so that auto-advancing (triggered by the 'quick' attribute on a question) would not work on questions in a question list. My logic at the time was that it would be undesirable for auto-advance to occur if not all questions in the list were answered yet. However, this change caused a regression in functionality for an app of Amy's (reported here http://manage.dimagi.com/default.asp?230383), and I realized that realistically, it seems more than fine to just trust app builders to only use the 'quick' attribute on questions in a question list in contexts that make sense (such as when the auto-advancing question is the last one).
=> Revert change to 'quick' attribute behavior in question list

app/src/org/commcare/activities/FormEntryActivity.java
If you rotate the new repeat dialog during form entry, the `onClick` closures hold a reference to the old activity, while a new activity has been created due to the screen rotation. 
This is usually fine (if you call `finish` on an old activity, it strangely still finishes the new activity). In the case where an error occurs and the `onClick` handler tries to launch a new dialog, it can't because it is pointing to the old activity.
In the long run, we should build up infrastructure similar to how the `CommCareTask.deliverResult` passes around the new activity receiver in. We could do this by recreating the `onClick` closures every time we reshow the dialog in `AlertDialogFragment.onCreateDialog`. Will be big lift given how annoying Java is with closures and how many dialogs we have.
For …
=> Don't persist new repeat dialog

app/src/org/commcare/CommCareApplication.java, app/src/org/commcare/activities/CommCareHomeActivity.java, app/src/org/commcare/activities/DispatchActivity.java, app/src/org/commcare/activities/UpdateActivity.java, app/src/org/commcare/services/CommCareSessionService.java, app/src/org/commcare/utils/SessionActivityRegistration.java
Final changes for consumer apps:
-Show a progress dialog during the update check portion of an update, so that the screen isn't just blank
-Fix an activity navigation bug that was occurring after updating to a new .ccz 
-At least for v1 release, don't do anything with the new restore file on an upgrade
-Don't show the logged in notification for a consumer apps session, and never time out the session
=> 2.28 consumer apps tweaks

app/src/org/commcare/tasks/FormRecordCleanupTask.java, app/src/org/commcare/tasks/ManageKeyRecordTask.java
Been seeing a lot of the `Session ID exists, but with no record (or broken record)` logs on HQ, but we don't actually log the exception, so it isn't very helpful.
=> Log form record wipe exception

app/src/org/commcare/android/database/user/models/SessionStateDescriptor.java, app/src/org/commcare/models/AndroidSessionWrapper.java, app/src/org/commcare/tasks/FormRecordCleanupTask.java, unit-tests/resources/commcare-apps/case_search_and_claim/user_restore.xml, unit-tests/src/org/commcare/android/database/user/models/SessionStateDescriptorTests.java
2.28 version of https://github.com/dimagi/commcare-android/pull/1347
@phillipm I slightly rewrote the continue logic for the sync and query requests
=> Session Serialization fix for 2.28

app/src/org/commcare/tasks/UpdateTask.java
Remove unnecessary sandbox setup in app update task code. Hoping to prevent the following crash:
```
Totally Unexpected Error during form submissionjava.lang.NullPointerException:
Attempt to invoke virtual method 'org.commcare.android.database.global.models.ApplicationRecord
org.commcare.dalvik.application.CommCareApp.getAppRecord()' on a null object reference at
org.commcare.dalvik.odk.provider.ProviderUtils.getSandboxedAppId(ProviderUtils.java:42) at
org.commcare.dalvik.odk.provider.InstanceProvider.init(InstanceProvider.java:108) at
org.commcare.dalvik.odk.provider.InstanceProvider.query(InstanceProvider.java:118) at
android.content.ContentProvider.query(ContentProvider.java:984) at
android.content.ContentProvider$Transport.query(ContentProvider.java:213) at …
```
=> Don't setup sandbox on app update

app/src/org/commcare/activities/CommCareHomeActivity.java, app/src/org/commcare/activities/FormEntryActivity.java
We recently changed `FormEntryActivity` to extend `CommCareActivity`, which means that action bar attachment will be handled by `CommCareActivity`. Hence we don't need to do it explicitly in `FormEntryActivity`
Partial fix for http://manage.dimagi.com/default.asp?221062
=> Don't attach action bar twice in form entry

app/src/org/commcare/models/database/user/UserSandboxUtils.java, app/src/org/commcare/provider/InstanceProvider.java, app/src/org/commcare/provider/InstanceProviderAPI.java, app/src/org/commcare/provider/InstanceProviderInsertType.java, app/src/org/commcare/tasks/ManageKeyRecordTask.java
2.28 version of https://github.com/dimagi/commcare-android/pull/1358 with minimal changes and no tests (since they require more changes, even though all those changes are to test files...)
Should be viewed with ?w=1
Addresses the following crash that happens when a user key record expires on HQ and HQ sends down a new one.
The underlying issue was that a while ago I moved a bunch of instance save logic into the `InstanceProvider` where it should be, but didn't realize that instances were migrated in a very specific way when key records expired. Hence, the instance migration code was handling all its form record upkeep, but the instance insert code was also trying to manage form records by linking it to the session's form record (which in this case doesn't exist).
```
Unexpected error …
```
=> Add migration stragety to InstanceProvider.insert

app/src/org/commcare/CommCareApplication.java
Master version of fix for http://manage.dimagi.com/default.asp?231794, which was committed directly to 2.28 branch. 
The fix is to throw a `SessionUnavailableException` immediately if the UI thread tries to access the session while it is binding, because otherwise that scenario will always lead to a time-out and subsequent throwing of the same exception anyway, so we want to short-circuit the time-out and just do it right away.
=> Session threading fix

app/AndroidManifest.xml, app/src/org/commcare/network/HttpRequestGenerator.java, app/src/org/commcare/provider/DebugControlsReceiver.java, scripts/ccc
`ccc invalidate` will set a fake value for the case DB hash. On the next sync this value will be used (and then removed), such that HQ will send down a 412, triggering a full recovery on the mobile device.
Will be used for integration tests.
cross-request: https://github.com/dimagi/commcare-core/pull/335
=> Extend ccc script to trigger 412 recovery syncs

app/src/org/commcare/android/resource/installers/FileSystemInstaller.java, app/src/org/commcare/tasks/ResourceEngineTask.java
For for issue where the max value in the progress bar during app installs would often get stuck at `3`.
=> Fix app install progress count

app/src/org/commcare/activities/CommCareHomeActivity.java
`onResume` is always called right after `onActivityResult` even when `onActivityResult` has launched a new activity. We don't want to do an UI work in `onResume` if a new activity is going to be launched, because that is slow, especially when we have to build a new case tile for the action bar.
Partial fix for http://manage.dimagi.com/default.asp?221062
=> Prevent UI work if CommCareHomeActivity is stepping forward in session

app/src/org/commcare/views/widgets/SpinnerWidget.java
Fix for bug introduced by https://github.com/dimagi/commcare-android/pull/1322. Issue was that the call to `super` in the `SpinnerAdapter` constructor needs to occur with the augmented choices list (the one that includes an empty first option), not the original one.
=> Fix bug where last option in dropdown list isn't shown

app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/interfaces/WidgetChangedListener.java, app/src/org/commcare/views/QuestionsView.java, app/src/org/commcare/views/widgets/DateTimeWidget.java, app/src/org/commcare/views/widgets/QuestionWidget.java, app/src/org/commcare/views/widgets/SpinnerMultiWidget.java, app/src/org/commcare/views/widgets/SpinnerWidget.java
-After rotating the screen during form entry, restores focus to the most recently updated widget 
-After performing a callout during form entry, restores focus to the widget that the callout was for (i.e.  image/video/sound capture/choose)
=> Recover form view state after rotation or callout

build.gradle
Gradle config changes were introducing unescaped slashes into the config files.
=> Fix for Gradle Builds on Windows

app/src/org/commcare/activities/EntitySelectActivity.java
Fix for ACRA crash below. Not exactly sure when `EntitySelectActivity` is launched without a session command, but there is already some logic that checks for nullity of the command, so I guess this comes up often enough.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.commcare.dalvik/org.commcare.activities.EntitySelectActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
at android.app.ActivityThread.access$800(ActivityThread.java:166)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
at android.os.Looper.loop(Looper.java:136)
at …
```
=> Only hide actions if there is a command to check for 'isSync'

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/tasks/FormLoaderTask.java
Catch lookup table missing errors on form load.
Allow lookup table missing error message to be localized
| Old message (caught in other place) | New message (caught in form load) |
|---|---|
| ![old-message](https://cloud.githubusercontent.com/assets/94817/16964421/5e2ff1f4-4dc9-11e6-8aa2-68d0054b655b.png) | ![screen](https://cloud.githubusercontent.com/assets/94817/16964424/60233228-4dc9-11e6-834b-f46271d86072.png) |
cross-request: https://github.com/dimagi/commcare-core/pull/344
From ACRA crash:
```
org.commcare.core.process.CommCareInstanceInitializer$FixtureInitializationException: Could not find an lookup table for src: jr://fixture/item-list:ML_village
at org.commcare.core.process.CommCareInstanceInitializer.setupFixtureData(CommCareInstanceInitializer.java:117)
at …
```
=> Catch lookup table missing on form open

app/src/org/commcare/activities/MenuBase.java, app/src/org/commcare/activities/MenuGrid.java, app/src/org/commcare/activities/MenuList.java
Fixing ACRA crash that I assume happens when trying to open CommCare at a module/form list after the session has expired.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.commcare.dalvik/org.commcare.activities.MenuList}: org.commcare.utils.SessionUnavailableException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
at android.app.ActivityThread.access$800(ActivityThread.java:155)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5343)
at java.lang.reflect.Method.invoke(Native Method) …
```
=> Make menu list/grid use onCreateSessionSafe

app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/activities/RecoveryActivity.java
Show the user the following form builder error (via ACRA) instead of crashing:
```
org.javarosa.xpath.XPathException: The problem was located in calculate expression for /data/rpt_referral_details/test_type_value
XPath evaluation: Attempting to select element 0 of a list with only 0 elements.
at org.javarosa.xpath.expr.XPathFuncExpr.selectedAt(XPathFuncExpr.java:886)
at org.javarosa.xpath.expr.XPathFuncExpr.evalRaw(XPathFuncExpr.java:244)
at org.javarosa.xpath.expr.XPathExpression.eval(XPathExpression.java:25)
at org.javarosa.xpath.XPathConditional.evalRaw(XPathConditional.java:46)
at org.javarosa.core.model.condition.Recalculate.eval(Recalculate.java:35)
at org.javarosa.core.model.condition.Triggerable.apply(Triggerable.java:143)
at …
```
=> Catch xpath error during update relevancies logic and show user

app/src/org/commcare/activities/EntityDetailActivity.java, app/src/org/commcare/models/FormRecordProcessor.java, app/src/org/commcare/xml/AndroidTransactionParserFactory.java
This is needed so that Simprints knows
- when they should mark fingerprint registration as committed.
- when a case is selected, allowing them to refine their matching algorithm
cross-request: https://github.com/dimagi/commcare-core/pull/329
=> Broadcast case id on case create/update events

app/src/org/commcare/activities/FormEntryActivity.java
Meryn was asking if this was expected behavior.
Follow up to revert done in https://github.com/dimagi/commcare-android/pull/1342 for https://github.com/dimagi/commcare-android/pull/1126
Probably worth including in a hotfix.
=> Don't auto-advance signature widget if in question list

app/src/org/commcare/activities/HomeActivityUIController.java
Fix for an ACRA crash:
```
java.lang.RuntimeException: Unable to resume activity {org.commcare.dalvik/org.commcare.activities.CommCareHomeActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4, result=0, data=null} to activity {org.commcare.dalvik/org.commcare.activities.CommCareHomeActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3056)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3085)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2498)
at android.app.ActivityThread.access$800(ActivityThread.java:166)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
at …
```
=> Null check of HomeActivity's button adapter

app/src/org/commcare/android/database/user/models/SessionStateDescriptor.java, app/src/org/commcare/models/AndroidSessionWrapper.java, app/src/org/commcare/tasks/FormRecordLoaderTask.java
Moves a lot of session descriptor and title loading logic into `commcare-core` so it can be more easily tested and potentially shared with CloudCare (not sure if this is something that is actually useful to CloudCare)
cross-request: https://github.com/dimagi/commcare-core/pull/343
=> Show case name in saved form for registration cases

app/src/org/commcare/views/EntityView.java
Indexing issue with case list column headers where a fingerprint callout result would remove an existing header
Example of the bug: 
| pre-callout | post-callout |
|----|----|
| ![image](https://cloud.githubusercontent.com/assets/94817/17037535/6df4f3cc-4f5f-11e6-8fa9-14945786a1f2.png) | ![image](https://cloud.githubusercontent.com/assets/94817/17037536/70cde7d4-4f5f-11e6-9eae-cb45cee984e6.png) |
=> Don't remove existing header text on callout result

app/res/layout/select_install_mode_fragment.xml, app/src/org/commcare/activities/CommCareSetupActivity.java, app/src/org/commcare/fragments/SelectInstallModeFragment.java
Addresses http://manage.dimagi.com/default.asp?223803.
Instead of using toasts to show error messages during app install, place the error message on the screen itself. (The error text will disappear if you go to any other screen and then return).
Before:
After:
=> Persist install error messages

app/src/org/commcare/tasks/AsyncRestoreHelper.java
handle the case when HQ returns a progress value that is less than the previous one
=> Async restore - handle edge case from server

app/src/org/commcare/activities/CommCareHomeActivity.java
Follow up to https://github.com/dimagi/commcare-android/pull/1403
```
org.commcare.utils.SessionUnavailableException
at org.commcare.CommCareApplication.getSession(CommCareApplication.java:1187)
at org.commcare.CommCareApplication.getRecordForCurrentUser(CommCareApplication.java:1193)
at org.commcare.activities.CommCareHomeActivity.onPrepareOptionsMenu(CommCareHomeActivity.java:1218)
at android.app.Activity.onPreparePanel(Activity.java:2589)
at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:529)
at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:518)
at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:483)
at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:830) …
```
=> Don't crash when session expires and home options menu is being created

app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java, app/src/org/commcare/logging/analytics/GoogleAnalyticsUtils.java
Kevin asked me to sneak this into 2.29 so that the product team can start figuring out what the most commonly-used languages on CommCare are (for purposes of developing default translations).
cross-request: https://github.com/dimagi/commcare-core/pull/355
=> Add language analytics

app/assets/locales/messages_ccodk_default.txt, app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/android/javarosa/IntentCallout.java, app/src/org/commcare/logic/FormController.java, app/src/org/commcare/logic/PendingCalloutInterface.java, app/src/org/commcare/views/QuestionsView.java, app/src/org/commcare/views/widgets/BarcodeWidget.java, app/src/org/commcare/views/widgets/IntentWidget.java, app/src/org/commcare/views/widgets/WidgetFactory.java, unit-tests/resources/commcare-apps/case_search_and_claim/profile.ccpr
Fix for http://manage.dimagi.com/default.asp?234487
Came up due to fixes in https://github.com/dimagi/commcare-android/pull/1372
- Fix `quick` functionality for barcode widget
- Make it so a barcode widget can be `editable` and have other appearance attributes.
- Move intent cancellation flag to outside of `IntentCallout` because the lifecycle of `IntentCallout` doesn't persist past the parent `BarcodeWidget`, so `"quick"` wasn't working
=> Fix BarcodeWidget getAnswer implementation and unify codepath with IntentWidget

app/src/org/commcare/activities/FormEntryActivity.java
A few of the changes in https://github.com/dimagi/commcare-android/pull/1343 where incorrect. 
The repeat dialog can't be persistent due to form entry/controller state restoration limitations, so the dialog must be dismissed directly not via the fragment framework.
fix for http://manage.dimagi.com/default.asp?234496
=> Perform correct dialog dismiss

app/src/org/commcare/adapters/EntityListAdapter.java, app/src/org/commcare/fragments/BreadcrumbBarFragment.java, app/src/org/commcare/views/EntityViewTile.java
Prefactoring for the flexible-width case tiles work for UATBC
I confirmed that the case tiles in parto look identical before and after the refactor.
=> Rename and refactor GridEntityView

app/src/org/commcare/activities/AppManagerAdvancedSettings.java, app/src/org/commcare/activities/ConnectionDiagnosticActivity.java
Don't make activities that can be accessed from the app manager session aware, since they do not require an active session and will cause confusing, unnecessary redirects in certain cases
=> Remove unnecessary extensions of SessionAware activities

app/src/org/commcare/activities/CommCareSetupActivity.java
Not sure if y'all feel like this is a good idea or not, but I think it would be useful to remove the cap of 2 apps installed for debug builds of CommCare. Throughout my dev workflow I often reinstall CommCare and then want to use multiple apps, which requires me to reclaim super user multiple apps privileges every time.
=> Allow more than 2 apps by default in debug builds

app/src/org/commcare/views/QuestionsView.java
Fix for an ACRA crash:
```
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at org.commcare.views.QuestionsView.setFocus(QuestionsView.java:329)
at org.commcare.activities.FormEntryActivity.showView(FormEntryActivity.java:1182)
at org.commcare.activities.FormEntryActivity.refreshCurrentView(FormEntryActivity.java:736)
at org.commcare.activities.FormEntryActivity.onActivityResult(FormEntryActiv
```
@amstone326 I'm just adding a patch to prevent the crash. Not sure if it is worth digging into how this may come up. Maybe something with questions being removed after relevancy condition recalculations?
=> Add list bounds check in QuestionsView.setFocus

app/src/org/commcare/adapters/MenuAdapter.java, app/src/org/commcare/utils/CachingAsyncImageLoader.java, app/src/org/commcare/utils/MediaUtil.java, app/src/org/commcare/views/EntityActionViewUtils.java, app/src/org/commcare/views/EntityView.java, app/src/org/commcare/views/EntityViewTile.java, unit-tests/src/org/commcare/android/tests/ImageInflationTest.java
Add a flag that can indicate to us to scale an image down to more precise dimensions based on the given container dimensions, and set that flag to true in places where we are inflating a display image that should be shown within very specific dimensions. 
Fixes http://manage.dimagi.com/default.asp?235370
=> Add flag to respect exact image bounds

app/src/org/commcare/activities/FormEntryActivity.java
Seeing some of the following crashes on ACRA for 2.29.1
In practice, the receiver in question (`mLocationServiceIssueReceiver`) should always be registered, so I have no idea how this is coming up. Figured it is better to not crash the app though.
```
java.lang.RuntimeException: Unable to pause activity {org.commcare.dalvik/org.commcare.activities.FormEntryActivity}: java.lang.IllegalArgumentException: Receiver not registered: org.commcare.activities.FormEntryActivity$1@43ebef50
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3242)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3193)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3171)
at android.app.ActivityThread.access$1000(ActivityThread.java:151)
at …
```
=> Try/catch around FormEntryActivity unregisterReceiver

app/src/org/commcare/activities/FormEntryActivity.java
Fix for http://manage.dimagi.com/default.asp?235890
@ctsims Duncan from VaxTrac was happy with the workaround so don't think there's any need to hotfix
=> Prevent question save after form completion

app/src/org/commcare/activities/HomeButtons.java
Yet another crash due to home screen button setup code not handling session expiration correctly.
```
org.commcare.utils.SessionUnavailableException
at org.commcare.CommCareApplication.getSession(CommCareApplication.java:1190)
at org.commcare.CommCareApplication.getUserDbHandle(CommCareApplication.java:737)
at org.commcare.CommCareApplication$3.getHandle(CommCareApplication.java:791)
at org.commcare.models.database.SqlStorage.getIDsForValues(SqlStorage.java:87)
at org.commcare.utils.StorageUtils.getNumIncompleteForms(StorageUtils.java:47)
at org.commcare.activities.HomeButtons$6.update(HomeButtons.java:160)
at org.commcare.adapters.SquareButtonAdapter.bindCard(SquareButtonAdapter.java:78)
at org.commcare.adapters.SquareButtonAdapter.onBindViewHolder(SquareButtonAdapter.java:63)
at …
```
=> Catch another session expiration crash in home button logic

app/src/org/commcare/android/javarosa/PollSensorController.java, app/src/org/commcare/preferences/CommCarePreferences.java
Allows one to configure the GPS auto-capture accuracy cutoff by setting the `cc-gps-auto-capture-accuracy` property (to a double) using the ['custom properties' HQ feature flag](https://confluence.dimagi.com/display/ccinternal/CommCare+Android+Developer+Options). If not set, defaults to 10.0 meters.
@dimagi/product Might be nice to consider making this more widely available for configuration on HQ. Like exposing a value box when auto-capture is enabled on HQ that lets you set the accuracy. This configuration is helpful because the desired GPS accuracy varies from project to project and if misconfigured has negative effects on device battery life.
=> Allow configuration of GPS auto-capture accuracy via HQ

app/src/org/commcare/preferences/CommCarePreferences.java, app/src/org/commcare/utils/GeoUtils.java
In 2.29 I changed the `GOOD_ACCURACY` value from `5` to `10` to prevent autocapture from running for a long time. I didn't realize this value was also used by the GPS capture question widget, thus lowering the accuracy of GPS coordinates captured in that way.
This PR adapts that change to make GPS capture questions accurate to `5` meters again.
=> Change max accuracy for GPS question widget

app/src/org/commcare/preferences/DeveloperPreferences.java, app/src/org/commcare/provider/RefreshToLatestBuildReceiver.java
The `ccc update` command is one way to trigger Aliza's 'Update to latest build and restore current location' feature. When called this way it only works if you have already set the 'enable session saving' dev preference. 
Instead of not working when it isn't set, this PR changes the behavior to automatically enable it, saving some setup/keystrokes.
=> Enable session saving when running 'ccc update'

app/src/org/commcare/activities/FormEntryActivity.java
If your select question doesn't have a label, then clearing the answer caused a null pointer exception.
New behavior
=> Fix NPE when removing question answer that doesn't have text

app/res/xml/commcare_preferences.xml, app/res/xml/preferences_developer.xml, app/src/org/commcare/engine/resource/ResourceInstallUtils.java, app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java, app/src/org/commcare/preferences/CommCarePreferences.java, app/src/org/commcare/preferences/DeveloperPreferences.java, app/src/org/commcare/provider/RefreshToLatestBuildReceiver.java
@dimagi/product How do you feel about the text of this feature?  <strike>I feel like 'Use latest HQ build' might be better than 'Use Newest App Version from HQ'. </strike> Went with @amstone326 suggestion of 'Enable Updating to Un-Starred Buildes'.
=> Move 'Enable Updating to Un-Starred Builds' to normal preferences

app/src/org/commcare/activities/HomeActivityUIController.java, app/src/org/commcare/adapters/HomeScreenAdapter.java
When we moved the home button adapter to use `RecycleView` I made use of the `onBindView` payload infrastructure. I either didn't get it working or something changed since then but when sync messages are shown they no longer update the subtext of the sync button (they only show as toast pop-ups). I spent a while trying to get `RecycleView` to properly deliver payloads, but to no avail, so this is my manual work around.
=> Update sync button with new messages

app/src/org/commcare/activities/LoginActivity.java, app/src/org/commcare/activities/SyncUIHandling.java, app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java, app/src/org/commcare/logic/ArchivedFormRemoteRestore.java, app/src/org/commcare/network/HttpRequestEndpointsMock.java, app/src/org/commcare/network/RemoteDataPullResponse.java, app/src/org/commcare/tasks/DataPullTask.java, unit-tests/src/org/commcare/android/tests/DataPullTaskTest.java
Mobile side of https://github.com/dimagi/commcare-hq/pull/12728
Show error message passed down from HQ on `406` http responses.
This will allow us to send custom messages down to our users.
Thanks for the HQ side of this @mkangia 🎉
=> Show 406 error messages to user

app/src/org/commcare/activities/EntitySelectActivity.java
Custom for UATBC adherence calendar, so that when the calendar loads they are automatically brought to today's date, rather than having to scroll all the way down to get there.
cross-request: https://github.com/dimagi/commcare-core/pull/396
=> Allow detail to tell entity list to focus to bottom

app/src/org/commcare/provider/RefreshToLatestBuildReceiver.java
@phillipm Sorry I didn't look closer at this https://github.com/dimagi/commcare-android/pull/1483, but I think it makes sense to turn this on whenever the refresh to latest build utility is being used, whether or not we are also enabling the newest app version flag.
=> Always enable session saving if using update to latest build utility

app/src/org/commcare/android/javarosa/PollSensorController.java, app/src/org/commcare/preferences/CommCarePreferences.java, app/src/org/commcare/utils/GeoUtils.java
@dimagi/product Would make sense to add this in the same place that the configurability for auto-capture accuracy is going to be placed (as per Phillip's comment [here](https://github.com/dimagi/commcare-android/pull/1474))
=> Make auto GPS capture timeout configurable

app/src/org/commcare/activities/CommCareActivity.java, app/src/org/commcare/activities/EntitySelectActivity.java, app/src/org/commcare/activities/FormRecordListActivity.java, app/src/org/commcare/views/ViewUtil.java, unit-tests/src/org/commcare/android/tests/caselist/EntityListCalloutDataTest.java
Currently, any actions that are defined within a `<detail>` block are shown as an item at the end of the entity list, and as an item in the options menu of the entity select screen. This PR makes it so that:
-If the entity list is being shown in grid view, actions are NOT shown as items at the end of the list, since that results in a very poor UI
-To compensate for that, actions are now configurable such that they can show up as an icon in the app bar. If the `<action>` block is defined with an `action-bar-icon` attribute, the specified icon will show up in the app bar of the entity select screen, in place of there being an item hidden in the options menu.
Screenshot below with an example of how this looks.
The last 2 commits also fix a couple of bugs that I found while working on this. …
=> Enable showing actions in the app bar

app/src/org/commcare/graph/view/c3/AxisConfiguration.java
Labels should only be parsed as times when it's a time-based graph *and* they're for the x axis, since the y axis for time-based graphs is still numeric.
http://manage.dimagi.com/default.asp?238840
=> Allow hash-based labels on y axis for time graphs

scripts/ccc
@phillipm 
This should work across systems if you don't have python3 in `bin`
=> Use /usr/bin/env shebang

build.gradle, unit-tests/resources/robolectric.properties
Revert robolectric target sdk bump from https://github.com/dimagi/commcare-android/pull/1498
Add robolectric add-on modules http://robolectric.org/using-add-on-modules/ (not entirely sure if we need these)
Bump android gradle plugin to latest Android Studio release
=> Downgrade Robolectric SDK to 21

app/src/org/commcare/adapters/EntityStringFilterer.java, app/src/org/commcare/models/AsyncEntity.java, app/src/org/commcare/models/AsyncNodeEntityFactory.java
Fix for a bug that was coming up where searching an async case list for the first time would freeze when you typed more than 1 character in quick succession.
The solution is to be stricter about cancelling the existing search process if a new search process is started; like when you type the second character of a query.
=> Async case list search deadlock fix

app/res/layout/pin_text_entry.xml, app/src/org/commcare/activities/CreatePinActivity.java, app/src/org/commcare/activities/PinAuthenticationActivity.java
If you are creating or resetting the login pin, it would be nice to have the keyboard action button do the same thing as pressing the `confirm` / `enter` / `continue` buttons.
Also pop up the keyboard if it has been dismissed between pin set and confirm screens
Fix for http://manage.dimagi.com/default.asp?239780
=> Make pin create/reset keyboard action button proceed through UI

app/src/org/commcare/CommCareApplication.java, app/src/org/commcare/activities/SingleAppManagerActivity.java
App version number on single app manager screen wasn't updating after an app update because the app record object had become stale due to it changing in the underlying storage.
Fix for http://manage.dimagi.com/default.asp?239904
=> Update app version number in app manager

app/src/org/commcare/activities/AdvancedActionsActivity.java
Redirect to home screen instead of returning to the advanced actions menu after reporting a problem.
Fix for http://manage.dimagi.com/default.asp?239844
=> Redirect to home screen after reporting a problem

app/src/org/commcare/activities/CommCareSetupActivity.java, app/src/org/commcare/tasks/RetrieveParseVerifyMessageTask.java
Move cursor code that traverses the SMS inbox into the AsyncTask that processes the SMS body. This prevents the UI thread from blocking while getting SMSs (not that I noticed it blocking, but more on principle)
Yet to be tested because I can't get figure out how to trigger an sms install on HQ (I sent a request but my phone didn't receive it)
=> Perform sms install cursor traversal in AsyncTask

app/src/org/commcare/CommCareApplication.java
Without this change, 'clear user data' crashes.
As [described here](https://github.com/dimagi/commcare-android/pull/1500/files/75a837dabef56b15267c4e7266519c5274d93c7e#r83646913):
> Since the user db was being cleared before this was called I don't think it was doing anything, because the file paths were cleared before this code could remove the files. Hence leaving dangling fixture data (for fixtures over 1mb). Moving it here ensures that files are deleted before the db is cleared.
Here is the stacktrace of the crash:
```
FATAL EXCEPTION: main
Process: org.commcare.dalvik, PID: 14445
net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database
at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
at …
```
=> Clear fixture before wiping wiping user db on 'clear user data'

app/src/org/commcare/activities/AdvancedActionsActivity.java
Go back to home screen after manually validating multimedia from advanced menu screen.
=> Redirect to homescreen after performing manual multimedia validation

app/src/org/commcare/CommCareApplication.java
Fix for http://manage.dimagi.com/default.asp?239910, which came up in 2.31 QA. Since it's not a regression and we're not quite sure what side effects this change may have, we're electing to make the change for 2.32 instead.
=> Remove SINGLE_TOP flag from restartCommCare method

app/src/org/commcare/tasks/SaveToDiskTask.java
Fix for why http://manage.dimagi.com/default.asp?240328 has a confusing error.
Makes it the case that if the form has an XPath error when trying to save that it isn't hidden from the user.
=> Much better visibility of XPath errors which occur during form save

app/assets/locales/messages_ccodk_default.txt, app/res/values/arrays.xml, unit-tests/src/org/commcare/android/tests/formnav/CalendarLocaleTest.java
The Transliteration that was being used for ethiopian dates in english was quite strange and was matching up poorly to the best available sources.
Fix for: http://manage.dimagi.com/default.asp?240253
=> Fix for Ethiopian Month names in English

app/src/org/commcare/utils/MediaUtil.java
Fix for: http://manage.dimagi.com/default.asp?240229
There basically was no OOM protection when _down-sampling_ an image, which was causing problems because it needs to keep both images in memory. 
This approach doesn't try to do anything clever, simply replicates what would happen if we couldn't expand an image which was growing instead of shrinking. For a future release we should revisit what should occur if an image can't be loaded.
=> Fix for Out Of Memory Error when downsampling images

app/assets/locales/android_translatable_strings.txt, app/src/org/commcare/activities/CommCareVerificationActivity.java, app/src/org/commcare/tasks/VerificationTask.java
Fixes 2 problems:
1. Exceptions that occurred during `VerificationTask` were being swallowed, 
2. The way in which they were swallowed actually resulted in the `VerificationTask` _always_ succeeding if there was a swallowed exception, even if there had been media validation failures as well.
Partial fix for http://manage.dimagi.com/default.asp?240552 (Partial because I haven't figured out what's actually causing the underlying exception there)
=> Don't swallow exceptions that occur during media validation

app/src/org/commcare/activities/UpdateActivity.java, app/src/org/commcare/tasks/FormLoaderTask.java, app/src/org/commcare/tasks/UpdateTask.java
Fix for the following stacktrace
```
java.lang.NullPointerException
at org.commcare.activities.UpdateActivity.handleTaskCompletion(UpdateActivity.java:222)
at org.commcare.activities.UpdateActivity.handleTaskCompletion(UpdateActivity.java:37)
at org.commcare.tasks.SingletonTask.onPostExecute(SingletonTask.java:35)
at org.commcare.tasks.UpdateTask.onPostExecute(UpdateTask.java:162)
at org.commcare.tasks.UpdateTask.onPostExecute(UpdateTask.java:33)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5584)
at …
```
=> Fix update error message processing NPE from ACRA

app/src/org/commcare/activities/FormEntryActivity.java
Remove manual prototype factory class registration, should be done automatically by reflection of the classes present in the apk
cross-request: https://github.com/dimagi/commcare-core/pull/442
=> Remove old prototype factory registration code

app/src/org/commcare/activities/CommCareHomeActivity.java
From ACRA
```
Caused by: java.lang.NullPointerException
at org.commcare.activities.CommCareHomeActivity.sessionStateUnchangedSinceCallout(CommCareHomeActivity.java:574)
at org.commcare.activities.CommCareHomeActivity.onActivityResult(CommCareHomeActivity.java:469)
at android.app.Activity.dispatchActivityResult(Activity.java:5634)
```
=> Fix NPE in sessionStateUnchangedSinceCallout

app/assets/locales/android_translatable_strings.txt, app/res/layout/screen_login.xml, app/res/values/strings.xml, app/res/xml/commcare_preferences.xml, app/src/org/commcare/activities/LoginActivityUIController.java, app/src/org/commcare/interfaces/CommCareActivityUIController.java, app/src/org/commcare/preferences/CommCarePreferences.java, app/src/org/commcare/views/PasswordShow.java
login | config
---- | ----
Exposes `cc-password-entry-show-behavior` preference that can be set to either `always_hidden`,`default_show`, or `default_hide`. The default setting is `always_hidden`.
=> Feature flag to allow showing password text

unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Update serialization test to take into account that `DataBinding` no longer extends externalizable (as of https://github.com/dimagi/commcare-core/pull/461)
=> Remove DataBinding from prototypefactory serialization test list

app/res/layout/entity_select_layout.xml, app/src/org/commcare/utils/MarkupUtil.java
Minor tweak to make calendar (grid) entity views be fully framed by the border to improve aesthetics in portrait mode.
Also enabled underlined text, and shifted the background color to match the "Accent" color of text to minimize the number of potentially distracting colors on the screen.
Updated Styles:
=> Calendar Style Update

app/src/org/commcare/CommCareApplication.java, app/src/org/commcare/network/HttpRequestGenerator.java
Adding IMEI as a query parameter into the key fetch url for auditing large deployments .
Feture requested in http://manage.dimagi.com/default.asp?242009
=> Include IMEI in key fetch URL

app/res/layout/geopoint_layout.xml, app/res/values-es/strings.xml, app/res/values-fr/strings.xml, app/res/values-lt/strings.xml, app/res/values-no/strings.xml, app/res/values-pt/strings.xml, app/res/values-sw/strings.xml, app/res/values/strings.xml, app/src/org/commcare/activities/GeoPointActivity.java, app/src/org/commcare/activities/GeoPointMapActivity.java, app/src/org/commcare/views/widgets/GeoPointWidget.java
If a GPS capture question has the appearance attribute `maps`, then you are shown a map where you can select a location independent of your current GPS location. This stopped working when we updated to Google's new map APIs.
Since this feature is not really used, I left some things rough:
- If you tap a location, it selects a new location, but the accuracy is hard-coded to 10 meters. A more robust implementation would scale the accuracy by the current zoom level.
- When your location updates or you tap a new location, the zoom level is scaled by the accuracy. This works but could use some finessing to scale better.
Behavioral changes:
- The activity no longer finishes after a certain accuracy is obtained. From my understanding the whole point of the activity is to not pick your current …
=> Fix map select feature

app/src/org/commcare/CommCareApp.java, app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java, app/src/org/commcare/engine/references/JavaFileRoot.java, app/src/org/commcare/views/widgets/RecordingFragment.java
Audio files captured using the built-in audio capture widget were getting saved as mp40, which meant they weren't getting uploaded to CommCare HQ.
=> Audio recorder widget filename fix: don't save files as mp40

app/res/xml/preferences_developer.xml, app/src/org/commcare/preferences/DeveloperPreferences.java, app/src/org/commcare/tasks/SaveToDiskTask.java
We've gone 3 releases without a save issue related to form save optimization, so I'm removing the feature flag that toggles it. Details in https://github.com/dimagi/commcare-android/pull/1207
=> Remove 'fire triggers on save' feature flag

app/src/org/commcare/tasks/DataPullTask.java, app/src/org/commcare/utils/SyncDetailCalculations.java
If you login with user `a`, sync, logout, login with user `b`, then the last sync time for user `a` is shown. This PR fixes that by adding the userid into the storage key for the last sync time.
Note, when this change is released, everyone's last sync time will be lost, defaulting to a "you've never synced" message. A simple sync should get things back to normal.
=> Use username in last sync date key

unit-tests/src/org/commcare/android/tests/queries/CaseDbQueryTest.java, unit-tests/src/org/commcare/android/tests/queries/LedgerDbQueryTest.java, unit-tests/src/org/commcare/android/util/TestUtils.java
Allow for Android-specific ledger code to be tested. Bumps code coverage of `StorageBackedTreeRoot.tryBatchChildFetch`
=> Add ledger parsing logic and tests to Android code

app/src/org/commcare/views/widgets/CommCareAudioWidget.java, app/src/org/commcare/views/widgets/RecordingFragment.java
As far as I can tell, the only implementation of `getFileExtension()` does not return a file extension, just a unique identifier of sorts, so I'm renaming it to reflect that
=> Change misleading method name

app/src/org/commcare/utils/SyncDetailCalculations.java
tl;dr version: Before this is merged, can either @wpride or @ctsims confirm that the Sync Mode setting on HQ (the actual preference key for which is "server-tether") is only intended to be used on java phones?
Full explanation: I recently asked HQ interrupt to move the Auto-Sync Frequency and Unsynced Time Limit settings from Java Phone General Settings into just General Settings, since they are used in Android code. However, those 2 settings are currently coupled with the Sync Mode setting, the actual preference key for which is "server-tether". My understanding from both looking at our code and prior conversations is that the server-tether setting, unlike the other 2, _is_ only intended to be used on java phones. The only place it is referenced in the Android codebase is the line I …
=> Remove last vestiges of server-tether setting in Android code

app/src/org/commcare/adapters/ImageAdapter.java, app/src/org/commcare/views/widgets/GridWidget.java
Fix for http://manage.dimagi.com/default.asp?244305. `GridWidget` and `ImageAdapter` were not using the new method of inflating image bitmaps, so the "Image Compatibility on Multiple Devices" setting was not being respected. 
There is a small possibility that I will want to do a point release on this for the UPenn app, but not sure yet.
=> Use modern image inflation method in GridWidget

app/src/org/commcare/activities/AppManagerActivity.java, app/src/org/commcare/activities/CommCareActivity.java, app/src/org/commcare/activities/SingleAppManagerActivity.java
The breadcrumb bar is out of place / not useful in the app manager because it ends up just showing the title of 1 of the installed apps. Make it so CommCareActivities can request not to show it at all
=> Don't show breadcrumb bar in app manager 

app/res/values/strings.xml, app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/activities/StandardHomeActivityUIController.java, app/src/org/commcare/utils/ChangeLocaleUtil.java
Make form entry language selection dialog expand the language name.
So that 
Now matches 
Also removed the cancel button from form entry language selection dialog. I can add it people think it is good to keep.
Fix for http://manage.dimagi.com/default.asp?239764
=> Localize language codes in form entry dialog

app/src/org/commcare/activities/CommCareSetupActivity.java, app/src/org/commcare/android/database/global/models/ApplicationRecord.java, app/src/org/commcare/engine/resource/installers/SingleAppInstallation.java
SMS install was running whenever you rotated the device, even if you were in the middle of another install. This was causing the install progress dialog to disappear.
Fix for http://manage.dimagi.com/default.asp?244434
=> Try SMS install only when on 'install method chooser' menu

app/src/org/commcare/activities/GeoPointActivity.java
Fixes http://manage.dimagi.com/default.asp?246312
We were including the location provider in the args even though this wasn't expected in the translation string
I'm not clear from git blame where this got introduced - as far as I can tell neither the translation string nor this line have changed since 2.32. Very odd.
=> Accuracy string fix

app/assets/locales/android_translatable_strings.txt, app/res/values/strings.xml, app/res/xml/commcare_preferences.xml, app/res/xml/preferences_developer.xml, app/src/org/commcare/activities/FormEntryActivityUIController.java, app/src/org/commcare/activities/UpdateActivity.java, app/src/org/commcare/engine/resource/ResourceInstallUtils.java, app/src/org/commcare/logging/analytics/GoogleAnalyticsFields.java, app/src/org/commcare/preferences/CommCarePreferences.java, app/src/org/commcare/preferences/DeveloperPreferences.java, app/src/org/commcare/provider/RefreshToLatestBuildReceiver.java
In follow-up to Cal's hackathon work https://github.com/dimagi/commcare-hq/pull/14737, add the option to update to the latest saved state of an app.
I chatted with @orangejenny for a bit today on the best way to do the UI for this, taking into account the fact that we didn't want to confuse existing workflows but also wanted it to be semi-discoverable. We settled on putting a menu item called "Update Options" in 2 places: one in the main "Settings" menu (as a replacement for the "Enable Updating to Un-Starred Builds" setting that is currently there) and one in the options menu of the Update Activity (since that is the most logical place that someone might look for it). Screenshots of both of these are below. The UIs of the 2 menus are slightly different because 1 is part of a native …
=> Add option to update to latest saved state of an app

app/res/layout/app_manager.xml
As @jjackson rightfully pointed out, I left the "Install An App" button in the app manager looking really shitty for some reason... It could probably be improved more than this but this was quick and 75% better.
Before:
After:
=> Make "Install an App" button in app manager look nicer

app/assets/locales/android_translatable_strings.txt, app/src/org/commcare/activities/UpdateActivity.java, app/src/org/commcare/engine/resource/AndroidResourceManager.java, app/src/org/commcare/engine/resource/AppInstallStatus.java, app/src/org/commcare/tasks/UpdateTask.java, app/unit-tests/src/org/commcare/android/tests/activities/UpdateActivityTest.java
Somehow the error handling for updates had gotten set up such that we were only creating a notification message for certain types of failures, even though the primary error message would always say "(See notification for details)". By moving the exception-handling up the chain from `AndroidResourceManager.checkAndPrepareUpgradeResources` to `UpdateTask.doInBackground`, we can retain access to the exception error messages in order to use them in a notification. 
(There's no ticket for this, Mike O just reported the behavior to me)
=> Show notification message for all update errors

app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/activities/FormEntryActivityUIController.java, app/src/org/commcare/activities/FormHierarchyActivity.java
Updates XPath Arity (incorrect signature) errors to be thrown properly during runtime.
In Android's code this just means handling errors at runtime based on the new behavior (which is identical to the old behavior, but with less code).
Release Note: Fixed issue where functions with the wrong number of arguments would produce a poor error message.
cross-request: https://github.com/dimagi/commcare-core/pull/523
=> Change Arity Parse to be a Syntax Error

app/src/org/commcare/views/QuestionsView.java, app/src/org/commcare/views/ShrinkingTextView.java, app/src/org/commcare/views/widgets/QuestionWidget.java
Fix for http://manage.dimagi.com/default.asp?243134. The issue is a little convoluted and I'm still a little vague on some of the details, but boils down to:
-The hint text for questions is always shown as a `ShrinkingTextView`
-Normally, when hint text is added to a question, `updateMaxHeight()` for the `ShrinkingTextView` is called twice in quick succession: first by the `ShrinkingTextView` constructor with a parameter of `-1` which doesn't do anything meaningful/useful, and then again when the `QuestionsView.onMeasure()` method is called and triggers an update to the hint height for each QuestionWidget it contains, passing a fraction of the newly measured height as the maxHeight.
-The problem comes up _only_ when a question that contains hint text is in a question list _and_ has a …
=> Prevent hint text from getting cut off in conditionally-visible questions in a question list

app/src/org/commcare/views/widgets/GregorianDateWidget.java
Fix for http://manage.dimagi.com/default.asp?247868
getAnswer() shouldn't require getting focus (its frequently called when it should not have focus)
=> Don't request focus when just getting answer

app/src/org/commcare/utils/FileUtil.java, app/src/org/commcare/utils/MediaUtil.java
Created a cache for images which are inflated to match the device's screen. Prevents a massive amount of work resisizing images over and over.
On my (relatively fast) phone it used to be very laggy to scroll with grid menus. It's fairly smooth after this change.
Release Note: Improved performance when scrolling on "grid" menu screens with large icons.
=> Cache "smart" image inflation outputs to disk to prevent needing to perform the interpolation over and over.

app/src/org/commcare/activities/FormEntryActivityUIController.java, app/src/org/commcare/views/QuestionsView.java
Fix for http://manage.dimagi.com/default.asp?247841. 
This was a fun one. The root of this ended up being the fact that `ComboboxWidget` calls `widgetEntryChanged()` when it loses focus: https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/views/widgets/ComboboxWidget.java#L95. `QuestionWidget.widgetEntryChanged()` triggers `FormEntryActivity.updateFormRelevancies()` downstream, which in turn calls `questionsView.removeQuestionsFromIndex()`. In this case, `removeQuestionsFromIndex()` rightfully removes the `ComboboxWidget` for district choice (it will then get added back later in the method), but removing the widget triggers its `onFocusChangedListener` and thus results in `updateFormRelevancies()` effectively recursing in the middle of its first execution. The …
=> Prevent updateFormRelevancies() from calling itself downstream

app/src/org/commcare/views/Combobox.java, app/src/org/commcare/views/widgets/ComboboxWidget.java
Change the rule by which the ComboboxWidget accepts a previous answer value or default value to accept anything that is a "valid user entry" (i.e. anything for which at least 1 answer choice will be present in the dropdown), rather than only anything that is an exact answer choice.
This was a request from Nick Nestle to support the workflow in which they're using the ComboboxWidget for a large nutrition project, so I'd like to get into 2.34 for them since it's a small change and QA has barely started.
=> Change rule for acceptance of previous value in ComboboxWidget

app/res/xml/preferences_developer.xml, app/src/org/commcare/activities/FormAndDataSyncer.java, app/src/org/commcare/activities/HomeScreenBaseActivity.java, app/src/org/commcare/google/services/analytics/GoogleAnalyticsFields.java, app/src/org/commcare/network/LocalReferencePullResponse.java, app/src/org/commcare/network/LocalReferencePullResponseFactory.java, app/src/org/commcare/network/mocks/LocalFilePullResponse.java, app/src/org/commcare/network/mocks/LocalFilePullResponseFactory.java, app/src/org/commcare/preferences/CommCarePreferences.java, app/src/org/commcare/preferences/DeveloperPreferences.java, app/unit-tests/src/org/commcare/CommCareTestApplication.java, app/unit-tests/src/org/commcare/android/tests/DataPullTaskTest.java, app/unit-tests/src/org/commcare/android/tests/activities/PostRequestActivityTest.java
Created a developer option to allow restoring a custom XML file to make it easier to debug/demonstrate certain issues on device without munging files at the APK level.
Adds an option to Developer Options that lets you pick an XML file from the file system and then runs that restore as if it had come from the server.
=> Debug Tool: End-User Offline Data Restore 

app/AndroidManifest.xml, app/res/xml/provider_paths.xml, app/src/org/commcare/CommCareApplication.java, app/src/org/commcare/activities/DrawActivity.java, app/src/org/commcare/activities/components/ImageCaptureProcessing.java, app/src/org/commcare/models/ODKStorage.java, app/src/org/commcare/utils/FileUtil.java, app/src/org/commcare/utils/GlobalConstants.java, app/src/org/commcare/views/widgets/ImageWidget.java, app/src/org/commcare/views/widgets/SignatureWidget.java
Fix for: https://manage.dimagi.com/default.asp?248780
As of SDK 24 and beyond, you are no longer allowed to provide free access to your device's external files (FileUriExposedException).  The camera widget needs to be able to provide a "stub" file to the camera in order to receive correct access to its functionality, so this PR implements a "temporary external" file store location where we can place those files in the short term to allow them to be read.
Release Note:
- Fix for Camera image capture not working on Android 'N' Devices.
=> Camera Widget Fix for Sdk 24+

app/res/xml/preferences_developer.xml, app/src/org/commcare/preferences/DeveloperPreferences.java
Remove update to latest saved from developer preferences, since it is now available in the core app.
=> Remove Update to latest saved from Developer Preferences

app/src/org/commcare/activities/CommCareFormDumpActivity.java, app/src/org/commcare/activities/CommCareWiFiDirectActivity.java, app/src/org/commcare/activities/FormAndDataSyncer.java, app/src/org/commcare/activities/HomeScreenBaseActivity.java, app/src/org/commcare/activities/RecoveryActivity.java, app/src/org/commcare/android/database/user/models/FormRecord.java, app/src/org/commcare/android/database/user/models/FormRecordV2.java, app/src/org/commcare/models/database/SqlStorage.java, app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java, app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java, app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java, app/src/org/commcare/preferences/CommCarePreferences.java, app/src/org/commcare/provider/ExternalApiReceiver.java, app/src/org/commcare/tasks/DumpTask.java, app/src/org/commcare/tasks/FormRecordToFileTask.java, app/src/org/commcare/tasks/ProcessAndSendTask.java, app/src/org/commcare/tasks/SaveToDiskTask.java, app/src/org/commcare/utils/StorageUtils.java, app/src/org/commcare/utils/SyncDetailCalculations.java, app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java, app/unit-tests/src/org/commcare/android/tests/processing/UnsentFormsTest.java
Changes our form submission ordering strategy to use a simple per-app counter. A `FormRecord` is marked with the next sequential `submissionOrderingNumber` only after it has been marked as completed, thus ensuring that forms are submitted in the order that they were completed by the user in. 
The ordering number for a record is also now included in a device log message for both attempting to submit the form and successfully submitting the form, which should make it easy to tell when a form has gone missing (since the submission numbers will always be sequential with no missing numbers).
I haven't yet been able to verify the results of this in the device logs or submitted forms report on HQ due to the current reporting issues, but I did verify that CommCare attempted to submit forms in the …
=> Order form submissions by global counter

app/src/org/commcare/views/media/AudioPlaybackButtonBase.java, app/src/org/commcare/views/media/ExpandedAudioPlaybackView.java, app/src/org/commcare/views/media/MediaLayout.java
Fix for http://manage.dimagi.com/default.asp?249822.
So I'm honestly not sure how this was ever working, because the progress bar animation was just not being paused when the user pressed the pause button. I'm guessing Phillip was trying to work around having to use `ValueAnimator.pause()` in some way because it requires API level 19, but using `cancel()` instead was just not working at all. So I've made it so that an `ExpandedAudioPlaybackView` can only be instantiated on devices running KitKat or higher, which I think is fine since this is just a nice-to-have UI enhancement thing. On earlier OS versions, we just include the normal audio button instead.
=> Fix pause behavior of expanded audio widget

app/src/org/commcare/android/javarosa/IntentCallout.java
After navigating back to CommCare after printing from a form, a toast would always pop up saying "Unable to process callout result". This was misleading and irrelevant for a print question, because there's never a result to process for this type of Intent Callout.
=> Prevent misleading error toast after navigating back from print

app/unit-tests/src/org/commcare/android/tests/queries/LedgerDbQueryTest.java
Tests for https://manage.dimagi.com/default.asp?251635
cross-request: https://github.com/dimagi/commcare-core/pull/546
=> Tests for empty ledger queries

app/res/xml/preferences_developer.xml, app/src/org/commcare/activities/UpdateActivity.java, app/src/org/commcare/preferences/CommCarePreferences.java, app/src/org/commcare/preferences/DeveloperPreferences.java
Addresses https://manage.dimagi.com/default.asp?251402
Updated documentation in https://confluence.dimagi.com/display/commcarepublic/Update+Target+Options to instruction users that they will need to enable this Developer Option in CommCare 2.36 and above.
NOTE: This change means that we are explicitly deciding to make the Developer Options something that is public to non-Dimagi users (I plan to clean up [this page](https://confluence.dimagi.com/display/internal/CommCare+Android+Developer+Options) and then move it to the public wiki, as well as link to it from the public wiki page above). @ctsims and I briefly discussed that we may want to start using the mobile privileges framework to allow us to hide certain more-dangerous settings within the Developer Options.
=> Use Developer Preferences to control visibility of Update Options setting item

app/src/org/commcare/utils/AndroidArrayDataSource.java
Addresses https://manage.dimagi.com/default.asp?252049
This will cause CommCare to use strings from the localization files when they are available. Functionally, this enables the calendar widgets to respect the app language rather than just the phone language.
=> Prefer app localized arrays when available

app/src/org/commcare/activities/FormEntryActivity.java, app/src/org/commcare/utils/FormUploadUtil.java
2 very small improvements to logging:
1. Log UnknownHostException as a network issue -- Because `UnknownHostException` is a subclass of `IOException`, the previous state of exception handling here caused any instances of `UnknownHostException` to be logged as `TYPE_ERROR_STORAGE`, with the message "Error reading form during submission", even though it's just a result of the phone not having a connection. This PR changes that to log it as `TYPE_WARNING_NETWORK` instead.
2. Don't log every time `getPendingWidget()` is called when `getPendingCalloutFormIndex()` is null, because we now call this method speculatively every time `onResume()` is called (it _used to_ only get called when we would expect `getPendingCalloutFormIndex()` to be non-null)
=> Small logging improvements

app/res/layout/custom_alert_dialog.xml
Confirmed that this makes our dialogs look 👍 on all of the following devices/versions:
-Android 7 Moto G
-Android 6 Huawei
-Android 4 Samsung tab
-Android 4 Samsung phone
Feel pretty comfortable that this gives us a good variety of confirmation on this. Thanks @ctsims for the fix!
=> Fix buttons being cut off on dialogs

app/src/org/commcare/views/widgets/GregorianDateWidget.java
The new calendar widget setting an array adapter selection in its creation. "Refreshing" that event gets put  onto the UIThread queue and executed on the _next_ polling cycle, which means that the gregorian widget is guaranteed a second update call.
Long story short that means that no behavior you applied to a GregorianWidget's QuestionView (like validation messages) that you created in one uithead poll would be capable of persisting, which is how we apply validation messages when you are on the final screen of a form.
Fixes: https://manage.dimagi.com/default.asp?252431
=> Calendar on Last Question Fix

app/res/values/strings.xml, app/res/xml/server_preferences.xml, app/src/org/commcare/activities/ReportProblemActivity.java, app/src/org/commcare/google/services/analytics/GoogleAnalyticsFields.java, app/src/org/commcare/preferences/CommCareServerPreferences.java
Added an option to control the support email address on the report issue page
Needed by UATBC
=> Enable submitting issue reports to a custom email address as an app preference

app/res/values/dimens.xml, app/src/org/commcare/adapters/GridMenuAdapter.java, app/src/org/commcare/adapters/MenuAdapter.java
Fix issue where on grid menus the initial scaledown that gets applied to images is the same as for non-grid icons. Made images look terrible.
Before:
After
=> Grid menu density fix

app/assets/locales/android_translatable_strings.txt, app/src/org/commcare/preferences/DeveloperPreferences.java
Ensure that the menu text and title text for preferences match up.
=> Language Consistency for Preferences

app/src/org/commcare/activities/GlobalPrivilegeClaimingActivity.java
This was just bad, I am sorry...
=> Don't require Dimagi email address for enable privileges

app/src/org/commcare/network/AndroidModernHttpRequester.java
Fix for https://manage.dimagi.com/default.asp?254153. This reverts commit bc5f30d99d9ee604b83c366e48c95ded00457a5d, which apparently broke ModernHttpRequester's ability to make requests to HQ successfully. I'm electing to just revert this instead of digging into why right now, because I don't have much time and it wasn't an essential addition (just a nice-to-have for LTS that we can add back later when I figure out the right way to do it).
=> 2.36 fix -- Revert "add auditing params to modern http get requests"

app/src/org/commcare/views/ResizingImageView.java
Fix for: https://manage.dimagi.com/default.asp?253951
Images on Android 7 would crash when double clicked, due to lack of file system permissions
@amstone326 Copied your technique for this from the video work.
=> Fix for image file enlargement on Android 7

app/src/org/commcare/CommCareApplication.java, app/src/org/commcare/preferences/CommCarePreferences.java, app/src/org/commcare/views/CustomBanner.java
Allows user to specify a second custom banner for the home screen, which is displayed to the user when they log in as a "Demo" or practice user.
Needs to be tested (will do tomorrow), but can self-merge after approval
=> Allow users to specify an optional custom banner to display in Demo Mode

app/src/org/commcare/activities/EntitySelectActivity.java, app/src/org/commcare/adapters/EntityListAdapter.java, app/src/org/commcare/adapters/EntitySubnodeDetailAdapter.java, app/src/org/commcare/fragments/EntitySubnodeDetailFragment.java, app/src/org/commcare/interfaces/SortableEntityAdapter.java
cross-request: https://github.com/dimagi/commcare-core/pull/566
I've tested/confirmed that this ensures: 
a) Proper sorting behavior in `EntitySelectActivity` is preserved
b) If a `<sort>` element is added to a `<field>` within a sub-detail that uses a nodeset, the elements of the nodeset get sorted by that field 
~~Holding off on merge until the HQ side has been implemented and I can test with that.~~
Since the timeline and person responsible for the HQ side of this is currently unclear, Jenny and I decided it makes sense to consider this ready and have it merged now. I've tested that it works as long as HQ provides the correct suite formatting, which has been specified to them.
=> Enable detail nodeset sorting

app/src/org/commcare/activities/EntitySelectActivity.java
if domain is icds, set custom callout to assume plain text values unless told otherwise
cross-request: https://github.com/dimagi/commcare-core/pull/571
=> 2.36 icds hotfix

app/src/org/commcare/activities/HomeScreenBaseActivity.java, app/src/org/commcare/preferences/CommCarePreferences.java
Fix for https://manage.dimagi.com/default.asp?256042. When the user selected a locale in the choice dialog on the home screen, we were never saving it in app prefs, meaning that even though we do attempt to pull the locale from app prefs on app startup [here](https://github.com/dimagi/commcare-android/blob/e695007b30796b7311295bb1b9ec47e75207c54c/app/src/org/commcare/CommCareApp.java#L218-L219), it was never doing anything except setting to the default.
=> Actually set chosen locale in app prefs

app/src/org/commcare/activities/FormEntryActivityUIController.java
Fixes: https://manage.dimagi.com/default.asp?255786#1349788
I can't think of any reason we wouldn't want to catch all XPathExceptions here?
=> Catch XPathExceptions and fail gracefully in next()

app/src/org/commcare/tasks/DataPullTask.java, app/src/org/commcare/utils/SyncDetailCalculations.java
Fogbugz link - http://manage.dimagi.com/default.asp?251931
Using username instead of userid for lastSyncKey to set the last sync time indicator correctly on Initial login. Userid is only getting populated in the session after we set the last sync time causing getLastSyncKey() function to return an invalid last sync key.
=> Bugfix: Make initial restore set the last sync time

app/src/org/commcare/activities/CommCareActivity.java, app/src/org/commcare/fragments/BreadcrumbBarFragment.java
Fix for https://manage.dimagi.com/default.asp?256304
This overrides `onBackPressed` in `CommCareActivity` to first check whether the persistent case tile is currently expanded. If it is, we will collapse the tile instead of moving back a screen.
fyi @sheelio
=> Make back button collapse an expanded persistent case tile

app/src/org/commcare/CommCareApplication.java, app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java, app/src/org/commcare/models/AsyncNodeEntityFactory.java
See cross requested PR: Implements hooks which switch async entity list loads to _not_ use bulk optimizations inside of the entity load (since they load one by one no matter what), and allow different amounts of heap memory to be used based on device.
cross-request: https://github.com/dimagi/commcare-core/pull/596
=> Memory Tuning for Optimizations

app/assets/locales/android_translatable_strings.txt, app/src/org/commcare/tasks/EntityLoaderTask.java
Case URL: https://manage.dimagi.com/default.asp?255119#1353059
cross-request: https://github.com/dimagi/commcare-core/pull/600
Since the exception can occur due to sort expression as well saying 'Filtering your list failed with a bad filter expression' is a bit misleading'.
=> Generalize text for entity list exception

app/assets/locales/android_translatable_strings.txt, app/src/org/commcare/activities/FormAndDataSyncer.java, app/src/org/commcare/activities/SyncCapableCommCareActivity.java, app/src/org/commcare/tasks/ProcessAndSendTask.java, app/src/org/commcare/tasks/templates/CommCareTask.java
Case Url: https://manage.dimagi.com/default.asp?252457#1356296
- Feedback from https://github.com/dimagi/commcare-android/pull/1751
- Shows a toast indicating no of forms sent before user presses stop to cancel the task.
=> Show forms sent on stopping the upload sync

app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
In this [ticket](https://manage.dimagi.com/default.asp?257707) we were encountering mismatched parens in the suite file but were only displaying a misleading message about the resource being unable to be found:
This change displays the core error at the UI level:
=> Percolate XPathException to UI in suite parsing
