- app/AndroidManifest.xml
- app/assets/locales/android_translatable_strings.txt
- app/build.gradle
- app/res/values/themes.xml
- app/src/org/commcare/activities/AppManagerActivity.java
- app/src/org/commcare/activities/AppManagerAdvancedPreferences.java
- app/src/org/commcare/activities/CommCareFormDumpActivity.java
- app/src/org/commcare/activities/CommCarePreferenceActivity.java
- app/src/org/commcare/activities/CommCareWiFiDirectActivity.java
- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/GlobalPrivilegeClaimingActivity.java
- app/src/org/commcare/activities/HomeNavDrawerController.java
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
- app/src/org/commcare/activities/SessionAwarePreferenceActivity.java
- app/src/org/commcare/activities/StandardHomeActivity.java
- app/src/org/commcare/fragments/CommCarePreferenceFragment.java
- app/src/org/commcare/google/services/analytics/GoogleAnalyticsUtils.java
- app/src/org/commcare/preferences/AdvancedActionsPreferences.java
- app/src/org/commcare/preferences/CommCarePreferences.java
- app/src/org/commcare/preferences/CommCareServerPreferences.java
- app/src/org/commcare/preferences/DeveloperPreferences.java
- app/src/org/commcare/preferences/FormEntryPreferences.java
Case Url: https://manage.dimagi.com/default.asp?253212#1354692
- All preferences now use the common CommCarePreferenceFragment which serves as a super class and handles the common functionalities.
- We have a single activity called CommCarePreferenceActivity which initialises the respective preference fragment type depending on the intent extra 'extra_pref_type'.
- SessionAwarePreferenceActivity just adds the session listeners on top of CommCarePreferenceActivity and should be used if the preference screen is accessible after login.
> Migrate all instances of PreferenceActivity to use PrferenceFragmentCompat

- app/src/org/commcare/activities/CommCareActivity.java
- app/src/org/commcare/fragments/BreadcrumbBarFragment.java
Fixes bugs introduced in:
https://github.com/dimagi/commcare-android/pull/1738
where all case tiles (regardless of inline/persistent/etc) wouldn't attach correctly and come out empty:
pre (all tiles look like this):
post:
post:
> Fix Case tiles in 2.37 Release

- app/src/org/commcare/tasks/EntityLoaderTask.java
Case: http://manage.dimagi.com/default.asp?258799
- In the list load failure dialogue source was getting duplicated and the actual message was never getting shown. 
cross-request: https://github.com/dimagi/commcare-core/pull/617
> Corrects Error reporting for Case list load failure

- app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
- app/src/org/commcare/models/database/user/models/AndroidCaseIndexTable.java
- app/src/org/commcare/tasks/DataPullTask.java
Fixes issue where 412 syncs don't clear case index table, and rebuild existing index table to ensure any old stale state is corrected
> Hotfix for 412's not cleaning storage properly

- app/src/org/commcare/adapters/EntityStringFilterer.java
- app/src/org/commcare/models/database/HybridFileBackedSqlStorage.java
- app/src/org/commcare/models/database/IndexedFixturePathUtils.java
- app/src/org/commcare/models/database/SqlStorage.java
- app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
- app/src/org/commcare/models/database/global/DatabaseGlobalOpenHelper.java
- app/src/org/commcare/models/database/migration/FixtureSerializationMigration.java
- app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
- app/src/org/commcare/tasks/DataPullTask.java
- app/src/org/commcare/xml/AndroidBulkCaseXmlParser.java
Many of our DB writes were not using safe transaction formatting.
Most of these are trivial changes, but the HybridFileBackedSqlStorage update should get a deeper look, as its transaction format was very dangerously configured.
> Normalize DB Transaction Formats

- app/src/org/commcare/activities/FormEntryActivity.java
Fixes an issue that made it possible for already-sent/saved forms to get into an "Unsent" state and thus be re-submittable: http://manage.dimagi.com/default.asp?232353
Also, Clayton and I both tested and confirmed that if you resubmit a form that is set to "Unsent" in this way, it's form submission ordering # is set to -1, which explains the troubling logs we were seeing
> Don't show save option in read only mode

- app/assets/locales/android_translatable_strings.txt
- app/res/layout/custom_alert_dialog.xml
- app/src/org/commcare/activities/FormRecordListActivity.java
- app/src/org/commcare/android/database/user/models/FormRecord.java
- app/src/org/commcare/tasks/ProcessAndSendTask.java
- app/src/org/commcare/utils/StorageUtils.java
This PR makes the following changes to prevent users from deleting unsent form records:
- The option to delete a form record on long-click doesn't appear for unsent forms:
- In place of the delete option, an option to quarantine a form has been added to the end of the record integrity scan result dialog:
@ctsims As it turns out, the ability to move a quarantined form back into the unsent queue already exists:
> Prevent deleting unsent forms

- app/assets/locales/android_translatable_strings.txt
- app/res/layout/file_pref_dialog.xml
- app/res/values/attrs.xml
- app/res/values/dimens.xml
- app/res/values/strings.xml
- app/res/xml/preferences_developer.xml
- app/res/xml/server_preferences.xml
- app/src/org/commcare/activities/FormRecordListActivity.java
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
- app/src/org/commcare/fragments/CommCarePreferenceFragment.java
- app/src/org/commcare/google/services/analytics/GoogleAnalyticsFields.java
- app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
- app/src/org/commcare/preferences/CommCarePreferences.java
- app/src/org/commcare/preferences/CommCareServerPreferences.java
- app/src/org/commcare/preferences/DeveloperPreferences.java
- app/src/org/commcare/preferences/FilePreference.java
- app/src/org/commcare/preferences/FilePreferenceDialogFragmentCompat.java
- Adds a feature to load forms from a local xml file containing Form Payload. Similar to https://github.com/dimagi/commcare-android/pull/1102/files which is loading forms from a server url.  Sample Payload file - https://gist.github.com/shubham1g5/f22cfd99decc68067190d37a63e0de6b
- No longer removing submission url on saving form payload status from Dev Preferences to allow for sync after we change the payload status
- Adds a custom preference FilePreference to have the ability to trigger file manager along with the file path editText
> Dev Feature: Load forms from a local file

- app/res/xml/preferences_developer.xml
- app/src/org/commcare/activities/AdvancedActionsActivity.java
- app/src/org/commcare/preferences/DeveloperPreferences.java
(I'm only adding this cross request comment so that the PR builder will run with a version of CC that is compatible; the code in these 2 PRs is technically totally independent)
cross-request: https://github.com/dimagi/commcare-core/pull/633
> 2.36.3 - Re-add the logic to hide 'Report Problem'

- app/src/org/commcare/tasks/PurgeStaleArchivedFormsTask.java
Remove this particular `form-deletion` log because it only ever applies to Saved Forms, which are not relevant to the debugging that this log category is being used for, and it is by far the most common instance of this log type, so it creates a lot of clutter when I'm trying to look for real issues.
> remove unhelpful log statement

- app/src/org/commcare/tasks/AsyncRestoreHelper.java
Fix for http://manage.dimagi.com/default.asp?260714, which was previously incompletely addressed by https://github.com/dimagi/commcare-android/pull/1770. The non-positive period issue was still occurring in the async restore timer sometimes because I forgot to account for the wonders of integer division :( Thanks @shubham1g5 for figuring out what was up here.
> Fix for non-positive period (again)

- app/src/org/commcare/activities/FormRecordListActivity.java
We shouldn't be exposing the button to manually quarantine a form after doing a record integrity scan when the record in question is already sent or already quarantined
> Don't allow manual quarantine of Saved or already-quarantined forms

- app/src/org/commcare/activities/FormRecordListActivity.java
@wpride I actually think this should be limited to _just_ `UNSENT` forms. It doesn't make sense to offer for `COMPLETE` forms either because of what Clayton said in that email thread earlier this week-- once a form is quarantined, it has the option to be sent back to the unsent queue, so if it's possible to manually quarantine a form with status `COMPLETE`, it could end up then getting to the unsent queue and skipping over the processing phase entirely.
> Whitelist manual quarantining to UNSENT forms only

- app/src/org/commcare/views/media/MediaLayout.java
- app/src/org/commcare/views/widgets/QuestionWidget.java
Release Note: Expanded audio widget functionality can no longer be used for audio playback
> Bye Bye expanded audio widget

- app/src/org/commcare/activities/CommCareActivity.java
- app/src/org/commcare/activities/EntityDetailActivity.java
- app/src/org/commcare/activities/EntitySelectActivity.java
- app/src/org/commcare/activities/MenuActivity.java
Fixes: https://manage.dimagi.com/default.asp?260852
Not sure if we should add this implementation to the base `CommCareActivity` instead as thats where we are creating `BreadcrumbBarFragment` which has an instance of `TabbedDetailView`  and thus `EntityDetailPagerAdapter` and thus `EntityDetailFragment` which potentially can contain phone numbers etc. as layout fields. So it seems to me from code that every `CommCareActivity` should potentially handle these callouts.
> Makes CommCareActivity implement DetailCalloutListener

- app/src/org/commcare/adapters/MenuAdapter.java
I just tested this out on a phone and 3 characters fits fine, so it was stupid to limit this to only 2, especially when it is very reasonable that people would have expressions that evaluate to > 99 (but much less reasonable to have ones that evaluated to > 999, so this seems like a more correct cut-off point anyway).
> Increase badge text length limit from 2 to 3

- app/src/org/commcare/adapters/EntityStringFilterer.java
fixes https://manage.dimagi.com/default.asp?261687
Not sure if this was a bug or intentional behavior that I'm missing but this change makes more sense to me. Previously, if we weren't using `asyncMode` (which I think we mostly aren't?) then we'd never sort filtered entities based on the edit distance from the search field (IE `score` was never used). This changes the behavior to re-sort the entities whenever we're in fuzzy mode.
> Sort based on edit-distance when fuzzy

- app/src/org/commcare/CommCareApplication.java
Moved ` CrashUtil.init(this)` after ` CommCareApplication.app = this` to fix NPE while getting device id using `CommCareApplication.instance().getPhoneId()`. 
Crash - https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59b6c301be077a4dcc76e597?time=last-seven-days
> Fixes crash on startup introduced by crashlytics changes

- app/src/org/commcare/engine/cases/AndroidLedgerInstanceTreeElement.java
- app/src/org/commcare/engine/cases/CaseUtils.java
- app/src/org/commcare/models/database/HybridFileBackedSqlStorage.java
- app/src/org/commcare/models/database/HybridFileBackedStorageIterator.java
- app/src/org/commcare/models/database/IndexSpanningIterator.java
- app/src/org/commcare/models/database/SqlStorage.java
- app/src/org/commcare/models/database/SqlStorageIterator.java
- app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
- app/src/org/commcare/models/database/user/models/AndroidCaseIndexTable.java
Running a "Case Purge" with large databases was/is quite time consuming. This PR introduces some optimizations to improve the process
Current Performance Improvement on my phone is 8->10 seconds to 1.5-1.75 seconds
* Introduces the idea of metadata iteration for sqlstorage. 
* Add relationship to caseindex table, which can now provide all information about indexes that the casedb can. 
* Refactor purge to optimize for db read structure
cross-request: https://github.com/dimagi/commcare-core/pull/635
> Purge Runtime Optimizations

- app/src/org/commcare/activities/CommCareActivity.java
- app/src/org/commcare/activities/EntityDetailActivity.java
- app/src/org/commcare/activities/EntityMapActivity.java
- app/src/org/commcare/activities/EntitySelectActivity.java
- app/src/org/commcare/fragments/BreadcrumbBarFragment.java
- app/src/org/commcare/fragments/EntityDetailFragment.java
- app/src/org/commcare/fragments/EntitySubnodeDetailFragment.java
Case: https://manage.dimagi.com/default.asp?261358
Catching XPathExceptions that can be thrown from NodeEntityFactory::getEntity
I removed XPathException catch block in this PR - https://github.com/dimagi/commcare-core/pull/617 without looking for all the paths that call `NodeEntityFactory::getEntity` that caused this issue. I am now catching it again at different UI level code blocks where this catch removal can surface.
> Displaying XPathErrors

- app/src/org/commcare/android/logging/ForceCloseLogger.java
Case : https://manage.dimagi.com/default.asp?262186
Crash: https://fabric.io/dimagi/android/apps/org.commcare.lts/issues/59c0ec25be077a4dccdf1c16?time=last-seven-days
Not sure why are we converting response to String just to log it to adb. Also for a successful request  response is just a empty String.
> NPE fix in case of a failed request in ForceCloseLogger

- app/src/org/commcare/CommCareApplication.java
Android 4.4 devices need an explicit hook for enabling multidex. Fixes library linking issues with retrofit
https://manage.dimagi.com/default.asp?262312
> Multidex fix for < Android 5 devices

- app/build.gradle
- app/src/org/commcare/activities/CommCareActivity.java
- app/src/org/commcare/activities/MenuActivity.java
- app/src/org/commcare/activities/RootMenuHomeActivity.java
- app/src/org/commcare/activities/components/MenuList.java
- app/src/org/commcare/adapters/MenuAdapter.java
Most of the actual fix is in commcare-core, but I cleaned up the processing a bit to unify where disposables are tracked.
One specific fix here is that I moved the execution of the badge lambdas into `Schedulers.single()`, since they end up unrolling a ton of state and it's _really_ easy for them to OOM the VM. At some point we may want to revisit whether we can set them up to process concurrently, but it'll take some thinking on how to make sure we're managing the memory pool.
Currently there are still some ~shaky semantics about the scheduler that I'm a bit concerned by (I'm pretty worried about leaving the Observables around and executing until onDestroy if, say, onStop has been fired, but our scope on using the new execution pattern is pretty limited.
cross-request: …
> Cleanups for Asyncronous setup in badge processing

- app/src/org/commcare/activities/RecoveryActivity.java
- app/src/org/commcare/android/database/user/models/FormRecord.java
- app/src/org/commcare/tasks/ProcessAndSendTask.java
Workaround for this - https://manage.dimagi.com/default.asp?261911#1394223
Right now when in recovery mode if for one of the form we could not find any instances, it blocks the whole sending forms task and user gets stuck with the blocking recovery mode screen. Hence in such a case we are now quarantining that form so that forms upload can proceed without sending the buggy form and user can get out of recovery mode.
> Quarantining forms instead of wiping on File not Found

- app/src/org/commcare/engine/cases/AndroidCaseInstanceTreeElement.java
- app/src/org/commcare/models/database/SqlStorage.java
- app/unit-tests/src/org/commcare/android/tests/database/SqlStorageBaseTests.java
- app/unit-tests/src/org/commcare/android/util/TestUtils.java
Move multikey lookups to core, so they can work for indexed fixtures 
cross-request: https://github.com/dimagi/commcare-core/pull/647
> Move Multi-Key storage lookups to core

- app/build.gradle
Not sure when this got changed, but it's breaking the builds on whatever runner Jenkins is now using.
> Ignore missing resource lint errors

- app/src/org/commcare/CommCareApp.java
- app/src/org/commcare/activities/RecoveryActivity.java
Triggers logs submission on Entering Recovery to debug corrupt storage error issues.
Case: https://manage.dimagi.com/default.asp?262385
Targeting 2.39 since there are increasing reports for corrupt-storage issue and users can't do log submission right now after encountering corrupt storage dialogue and it's pretty dark without logs when it comes to corrupt storage bugs. 
Though let me know if this is too late for 2.39 and need to target master instead.
> Submitting logs on hitting Recovery Mode

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
I had been relying on the call to `recordSyncAttempt()` that occurs in `DataPullTask.doTaskBackgroundHelper()` to set this flag back to false after a post-update sync is triggered. But if the form-send step prior to data pull fails, then we never even launch the data pull task at all. This would result in the app continually trying and failing to sync every single time the user comes back to the home screen until whatever is causing the form-send failure is resolved. 
Also switch the order of these 2 checks; in case of the situation where both are true at the same time, we would want the sync-after-update flag to take precedence so that the boolean gets set back to false.
> Set post-update sync flag back to false immediately

- app/src/org/commcare/adapters/MenuAdapter.java
In 2.39, while refactoring for Menu Badges, I also refactored MenuAdapter and GridAdapter to use same getView code and what I didn't realise is there is not audio button in grid menu list item layout. This is causing a crash when we have anyway added a audio file for a Grid menu in HQ since right now mobile code is assuming that if there is a audio file there should also be a audioButton for it. 
https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59cf74adbe077a4dcc831241?time=last-ninety-days
This is impacting only the ICDS AWW app right now and it's causing a crash on clicking Start.
> Fixes NPE for Grid Menu when there is audioFile for a menu

- app/src/org/commcare/models/database/migration/FixtureSerializationMigration.java
- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
Fixes https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59bab3f7be077a4dcca0087b?time=last-seven-days.
The stack trace in the above crash doesn't reveal what was really going on here (thanks @ctsims for getting to the bottom of it). The bug was that for the v20 --> v21 user db migration (which reindexes all cases), the migration was taking longer than 5 seconds, which is the default timeout set in `CommCareApplication` (`MAX_BIND_TIMEOUT`) for binding to the session service. Previously, we would selectively increase this timeout in certain migrations that we expected to take a long time, but this one was missed and is causing issues for a few users (thankfully only 3 so far, all in the same app, so seems quite rare). But since there's really not much harm in increasing this …
> 2.39.2 - Universal timeout increase on upgrades

- app/src/org/commcare/fragments/FileServerFragment.java
A line of the Wi-Fi Direct copy file code could result in the copy going through as successful (and the sender deleting their forms) but also triggering the receiver to delete the received payload (even though it would be, in fact, in tact).
This fix changes that by:
Catching the socket close IOException (which should really be ignored) outside the normal catch
Not deleting the forms in the event of an error (because the folder name is time-based we don't really need to worry about cleaning these up)
> Wi-Fi Direct Bug Fix

- app/src/org/commcare/models/database/AndroidSandbox.java
- app/src/org/commcare/models/database/IndexedFixturePathUtils.java
- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
- app/unit-tests/src/org/commcare/android/tests/database/SqlStorageBaseTests.java
- app/unit-tests/src/org/commcare/android/tests/processing/IndexedFixtureLoadingTest.java
Fixes a bug where the indexed fixture paths table would contain duplicate rows for the same fixture if CommCare processed a transaction containing the same fixture multiple times
cross-request: https://github.com/dimagi/commcare-core/pull/655
> Fix indexed fixture paths table

- app/assets/locales/android_translatable_strings.txt
- app/res/xml/preferences_developer_access_code.xml
- app/src/org/commcare/preferences/CommCarePreferences.java
- app/src/org/commcare/preferences/DeveloperPreferences.java
Addresses concerns laid out in https://manage.dimagi.com/default.asp?262779. This does the same thing as https://github.com/dimagi/commcare-android/pull/1850 but on master.
I've added internal documentation on confluence [here](https://confluence.dimagi.com/display/internal/CommCare+Android+Developer+Options+--+Internal#CommCareAndroidDeveloperOptions--Internal-HowtorestrictaccesstotheDeveloperOptions).
> Set up ability to require PIN for dev options access

- app/src/org/commcare/activities/components/EntitySelectCalloutSetup.java
- app/src/org/commcare/utils/MediaUtil.java
Super small change to use the normal dynamic image inflation strategy for callout icons
> Use Standard Image inflate for Callout Menu Icons 

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/android/nfc/NfcReadActivity.java
CommCare was crashing when scanning NFC tags which didn't support NDEF.
> Fix error handling for non NDEFF NFC tags

- app/src/org/commcare/activities/EntitySelectActivity.java
Apparently if the action bar is being used in an activity, it is possible for `onCreateOptionsMenu` to get called before `onCreate` has finished executing (see https://stackoverflow.com/questions/7705927/android-when-is-oncreateoptionsmenu-called-during-activity-lifecycle/7706597#7706597). Although this definitely doesn't happen on all phones, it's the best explanation I can find for [this crash](https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59caaf16be077a4dcc4b044e/sessions/59E0B141028000014ABF51F37354211A_f3dbf274b01111e7919a56847afe9799_0_v2?) (after determining that the cause I was proposing in https://github.com/dimagi/commcare-android/pull/1853 doesn't seem possible).
> Handle possibility of onCreateOptionsMenu getting called before onCreate finishes

- app/src/org/commcare/views/widgets/AudioWidget.java
- app/src/org/commcare/views/widgets/VideoWidget.java
Fix for https://manage.dimagi.com/default.asp?264387
Makes Audio and Video widget conform to the new File access protocol for Android 7+
Tested on my Alcatel running 7.0
> Use new file access format for Audio and Video Widget

- app/src/org/commcare/activities/CommCareSetupActivity.java
CL: https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59cee64dbe077a4dcc7dc848?time=last-ninety-days
I am not able to reproduce this crash and also not able to really grasp what exactly might be going wrong here. Though looking at some stackoverflow posts it seems like a FragmentActivity bug happening when user presses back before fragment Transaction could finish completing. so I have basically followed the suggestion given here -
https://stackoverflow.com/questions/13745787/fragment-already-added-support-lib/14298328
Though what's really confusing me is how is backstack popping the `SelectInstallModeFragment` when we are not adding the fragment to backstack anywhere in code.
> Potential Fix for Fragment already added crash

- app/src/org/commcare/fragments/CommCarePreferenceFragment.java
The UI tests caught [this bug](https://gist.github.com/wpride/bc47750867cd87ef0ad9208d77898478) on opening Recovery Mode
One of Aliza's recent refactors expected `SharedPreference`s to only be of String type:
https://github.com/dimagi/commcare-android/commit/8f92adfae4226100083e1739e2cbce3c81c2d054#diff-0f317061966a57e0ec9feda1db245a00R174
Meanwhile one of Shubham's refactors added a boolean pref:
https://github.com/dimagi/commcare-android/commit/fd687a256e18acd26a1421e210c19c82fded1395#diff-48d5e471c4e5e4492d24f712bf5d37e9R571
I expect that we want the `onSharedPreferenceUpdated` code to be robust against all setting types,  but unfortunately [there doesn't seem to be a clean way to do this](https://stackoverflow.com/questions/29615920/android-check-sharedpreferences-for-value-type)
I …
> Try to handle boolean and int prefs

- app/src/org/commcare/activities/SessionAwareCommCareActivity.java
This should fix https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59cfab3ebe077a4dcc85c3a7?time=last-seven-days, and probably some other similar issues as well. The idea here is that our implementation of session-aware activities isn't always working, because there are places throughout our code where we respond to a `SessionUnavailableException` by returning `null` for some value (for instance: https://github.com/dimagi/commcare-android/blob/bd67a38fa49845c6c920693d998f38ce985d2b43/app/src/org/commcare/models/database/AndroidSandbox.java#L89-L95). In these situations, CommCare can end up crashing with a NPE, instead of  `SessionAwareCommCareActivity` catching and handling the `SessionUnavailableException`. By adding this call to `getSession()` before we execute …
> Force SessionUnavailableException to happen immediately if it's going to

- app/src/org/commcare/provider/RefreshToLatestBuildReceiver.java
Fix for https://manage.dimagi.com/default.asp?263272
> Prevent npe when there is no seated app during refresh-to-latest-build attempt

- app/src/org/commcare/activities/FormRecordListActivity.java
Fixes crash by UI tests:
https://us-west-2.console.aws.amazon.com/devicefarm/home?#/projects/5aba0e8d-7e3a-4563-a73c-4fc0e5e80b95/runs/0320be9f-d0a2-4853-a900-1311319113e0/jobs/00000/suites/00001/tests/00000
11-05 00:05:13.908  8986  8986 E MessageQueue-JNI: java.util.UnknownFormatConversionException: Conversion: 
11-05 00:05:13.908  8986  8986 E MessageQueue-JNI: 	at java.util.Formatter$FormatSpecifierParser.unknownFormatConversionException(Formatter.java:2321)
11-05 00:05:13.908  8986  8986 E MessageQueue-JNI: 	at java.util.Formatter$FormatSpecifierParser.advance(Formatter.java:2315)
11-05 00:05:13.908  8986  8986 E MessageQueue-JNI: 	at java.util.Formatter$FormatSpecifierParser.parseConversionType(Formatter.java:2394)
11-05 00:05:13.908  8986  8986 E MessageQueue-JNI: 	at …
> Fix String.format for integrity scan log

- app/src/org/commcare/tasks/ProcessAndSendTask.java
Will fix https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59d38d28be077a4dccad737e/sessions/latest?build=65456794
> Prevent npe if `results` hasn't been initialized when task is canceled

- app/src/org/commcare/activities/UpdateActivity.java
- app/src/org/commcare/android/nsd/NSDDiscoveryTools.java
Fix for https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59c55824be077a4dcc126d60?time=last-thirty-days
Change min Android version for NSD to 5.0 to avoid this Android bug: https://issuetracker.google.com/issues/36952181
> Prevent NSD crash in Android 4

- app/src/org/commcare/activities/EntitySelectActivity.java
Fix for https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59fb2ad261b02d480da4d741?time=last-seven-days, which is unfortunately a regression in 2.40 due to the fix I implemented in https://github.com/dimagi/commcare-android/pull/1860 for https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59caaf16be077a4dcc4b044e/sessions/59E0B141028000014ABF51F37354211A_f3dbf274b01111e7919a56847afe9799_0_v2?. I now realize that the fix I implemented basically just pushed off this crash to `onPrepareOptionsMenu` instead of `onCreateOptionsMenu`. This will now prevent it from happening in either. (I don't think a hotfix is necessary since the previous crash was equivalent and around for quite a while).
> Prevent npe in onPrepareOptionsMenu too

- app/src/org/commcare/views/dialogs/AlertDialogFragment.java
Case: https://manage.dimagi.com/default.asp?265664#1422233
Crash: https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59d3443bbe077a4dcca9ffff?time=last-thirty-days
@amstone326 The reason behind this crash wasn't configuration change as it was working properly on rotaion but Android killing the process(Both Activity and Fragment) in case of low memory conditions. I was able to reproduce it by following @ctsims protip on turning the 'Don't keep Activities' developer options on and then leaving the activity when AlertDialog is open and returning to it.  
I am now dismissing these dialogues safely when such a case surfaces so that user can atleast access the corresponding activity. Though if we see value in retaining these dialogues in such cases we will need a way to recreate …
> Fixes NPE in AlertDialog after process kill

- app/src/org/commcare/tasks/ProcessAndSendTask.java
Noticed this missing from the quarantine logs.
> Add FormRecord instanceId to quarantine logs

- app/src/org/commcare/activities/FormEntryActivity.java
I believe this will address https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59db367fbe077a4dccfd06ba?time=last-ninety-days, which I think is just a timing issue in form entry, where if a rotation of the device triggers a call to `onRetainCustomNonConfigurationInstance()` after form loading completes, but before the first view is actually rendered (a very short but presumably real window of time), then we would try to call `saveAnswersForCurrentScreen()` with a null `questionsView`. I wasn't able to replicate the crash based on this guess, but I think it's worth putting in this fix and seeing if that addresses it in the next release before digging much deeper.
> Prevent NPE stemming from onRetainCustomNonConfigurationInstance()

- app/src/org/commcare/utils/FormUploadUtil.java
In https://manage.dimagi.com/default.asp?265905 we're encountering an exception during form processing for submission, but can't see any information on the exception. This case seems worthy of logging the complete exception for.
> Log full exception for form read failures

- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/activities/CommCareSetupActivity.java
- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/HomeButtons.java
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
- app/src/org/commcare/activities/StandardHomeActivity.java
- app/src/org/commcare/activities/components/ImageCaptureProcessing.java
- app/src/org/commcare/fragments/CommCarePreferenceFragment.java
- app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
- app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
- app/src/org/commcare/utils/MediaUtil.java
- app/src/org/commcare/views/widgets/CommCareAudioWidget.java
- app/src/org/commcare/views/widgets/RecordingFragment.java
In the course of doing some research on Firebase analytics before we migrated, 1 of the warnings I read was that while Firebase _will_ queue up events to send later if a device is offline, the amount of storage space that it will devote to that is limited. This means that if you're logging too much while a user is offline for an extended period of time, you may lose data. In retrospect, it seems more than likely that the same was true for Google Analytics, since the storage available to use would be limited no matter what. 
So in the hopes of keeping that storage free for the events that are most important, this PR does 2 things:
1. Removes any events that seem both not particularly important and likely to be happening a lot.
2. Adds a method for rate-limiting the logging of those events …
> Decrease volume of analytics events 

- app/src/org/commcare/models/database/SqlStorage.java
- app/src/org/commcare/models/database/user/models/EntityStorageCache.java
- app/src/org/commcare/tasks/DataPullTask.java
Fixes the issue in https://manage.dimagi.com/default.asp?265905. Specifically, crashes during recovery restore parse could result in the case database being left empty. Accomplish this by doing the wipe and restore parse in one transaction that we simply do not commit unless we fully succeed. A couple supporting refactors.
I tested this by throwing a `RuntimeException` right before the `readInput` call; previously this resulted in an empty user db, now this is successfully rolled back.
I think we should get this into 2.41.
> Transactional Recoveries

- app/src/org/commcare/views/widgets/MediaWidget.java
Cause of the bug here https://manage.dimagi.com/default.asp?267070
For certain URIs (seems exclusive to 7.0 and certain media apps) we would set the path here, which resulted in the bug exposed here and thus the media not being recognized as valid on submission
> Add '.' in MediaWidget

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/views/widgets/ImageWidget.java
- app/src/org/commcare/views/widgets/VideoWidget.java
Fixes crash caused by denied camera permission: https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5a3354338cb3c2fa63e86e28/sessions/5A33536D001E000175226C21CDD3EC02_3f2824c2e15311e7a55656847afe9799_0_v2
> Check for permissions error, show toast

- app/src/org/commcare/provider/InstanceProvider.java
- app/src/org/commcare/tasks/SaveToDiskTask.java
Previously the place where this log was being written would cause it to get logged twice for every completion of form entry, and also when we were just saving a form but not leaving form entry. This fixes both of those issues.
> Prevent 'Form Entry Completed' log from happening twice/incorrectly

- app/src/org/commcare/logging/DeviceReportWriter.java
With help from @emord I confirmed that HQ does treat device log xforms the same way as normal forms in that it checks for a unique id included in a <meta> block on the form. Mobile was previously not including any <meta> block in device log submissions, so adding one now will prevent duplicate logs from being included in device reports on HQ in the future.
I was also able to confirm this theory via manual testing by observing that duplicate logs would previously show up on HQ if we prevented the deletion of a DeviceReportRecord after it was submitted, and observing that this PR fixes that behavior.
> Write a uuid to the log submission XML to prevent duplicate submissions

- app/AndroidManifest.xml
I don't believe we actually need these elements; the `uses-library` tag is for libraries that you require to be on the device *in order to* install, not libraries that you include in your install (such as `javarosa` and `commcare`)
https://stackoverflow.com/questions/9868393/android-requires-unavailable-shared-library-com-google-android-maps-failing
https://stackoverflow.com/a/45357556/2820312
> Remove unneeded uses-library block

- app/res/xml/preferences_developer.xml
- app/src/org/commcare/preferences/DeveloperPreferences.java
- app/src/org/commcare/views/widgets/ComboboxWidget.java
- app/src/org/commcare/views/widgets/GridMultiWidget.java
- app/src/org/commcare/views/widgets/GridWidget.java
- app/src/org/commcare/views/widgets/LabelWidget.java
- app/src/org/commcare/views/widgets/ListMultiWidget.java
- app/src/org/commcare/views/widgets/ListWidget.java
- app/src/org/commcare/views/widgets/QuestionWidget.java
- app/src/org/commcare/views/widgets/SelectMultiWidget.java
- app/src/org/commcare/views/widgets/SelectOneAutoAdvanceWidget.java
- app/src/org/commcare/views/widgets/SelectOneWidget.java
- app/src/org/commcare/views/widgets/SpinnerMultiWidget.java
- app/src/org/commcare/views/widgets/SpinnerWidget.java
Case: https://manage.dimagi.com/default.asp?266292#1427432
Configurable version of https://github.com/dimagi/commcare-core/pull/691
Product Note: Introduces a developer setting 'Allow spaces in Select choices' which if disabled (enabled by default currently) results in an error like 'Select answer option cannot contain spaces in question 'QuestionText' with option 'ChoiceWithSpaceText' ' in case spaces are present in lookup table options used for a lookup table select question's value field. The error occurs when user arrives on the relevant question with spacey choices in a form.
> Throws error in case of space in select choices

- app/src/org/commcare/views/widgets/BarcodeWidget.java
addresses https://manage.dimagi.com/default.asp?268210
Looks like the [refactor](https://github.com/dimagi/commcare-android/commit/f1f8204bc51b85947c51bb00272adcd586967aa2#diff-42be99734c63ffc769073deecabd62ff) to make the `BarcodeWidget` use the ZXing library postponed the instantiation of the `intent` class variable (see comment on line 32) such that this is still null when the `quick` appearance attribute is used. Unfortunate edge case.
> Instantiate BarcodeWidget intent for quick appearance

- app/src/org/commcare/activities/GeoPointActivity.java
- app/src/org/commcare/activities/components/FormEntryDialogs.java
- app/src/org/commcare/utils/GeoUtils.java
- app/src/org/commcare/views/dialogs/LocationNotificationHandler.java
@Ben-Talbot pointed out that when location services are missing, we were previously not always sending users to the proper settings page for them to fix it. This is because there are 2 different situations that can cause location services to be unavailable in CommCare: one is if location services are turned off globally for the device, and one is if they have been disabled (or never granted in the first place) for CommCare specifically. The settings pages on which the user can toggle these 2 things are different, so we should detect which situation the user is in and send them to the proper screen.
> Send users to the proper location settings page for the situation

- app/src/org/commcare/CommCareApp.java
- app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
- app/src/org/commcare/android/resource/installers/LocaleAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/MediaFileAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/OfflineUserRestoreAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
- app/src/org/commcare/engine/resource/AndroidResourceManager.java
- app/src/org/commcare/tasks/VerificationTask.java
- app/src/org/commcare/utils/DummyResourceTable.java
In the same vein as #718, refactor StorageManager to not use a static singleton and instead use CommCarePlatform as the delivery vector
cross-request: https://github.com/dimagi/commcare-core/pull/728
> Refactor StorageManager

- gradle.properties
I know that https://android.jlelse.eu/speeding-up-gradle-builds-619c442113cb suggests putting these changes in your global `gradle.properties` file, but I figured committing them here is the best way to ensure that they continue to get used by other developers in the future. I confirmed that the `gradle.properties` file on the Jenkins mobile agent already has `org.gradle.daemon` set to `false`, so that will override this on the build server.
> gradle.properties changes for build speed

- gradle.properties
Reverts dimagi/commcare-android#1935
Trying this again on @shubham1g5's suggestion that clearing the workspace might solve the build failure
> Revert "Revert "gradle.properties changes for build speed""

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/engine/references/JavaHttpReference.java
Trying to display a better error on getting a 500 from Server during app update. Earlier app was failing with this error message - 
"Attempt to invoke virtual method 'java.io/InputStream okhttp3.ResponseBody.byteStream()' on a null object reference".
> Shows a better error message instead of a NPE

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
Small change to https://github.com/dimagi/commcare-android/pull/1883/ --> When we are automatically resuming an incomplete form after session expiration occurred in the middle of form entry, send the user straight to form entry instead of to the form hierarchy view. (And if they press back from there, don't send them to the form hierarchy view, either).
Also adds a toast message when we drop the user back into form entry to give them a clue as to what just happened.
> Go straight to form entry for automatically-resumed incomplete form

- app/build.gradle
Case: https://manage.dimagi.com/default.asp?268970#1449115
Updates sql-cipher to include fix for https://github.com/sqlcipher/android-database-sqlcipher/issues/313
Product Note: Fixes a crash happening during some DB operations on Commcare caused by a bug in one of the supporting Library Commcare uses.
> Updates sql-cipher

- app/AndroidManifest.xml
https://manage.dimagi.com/default.asp?268446 made me realize that when we added the paradigm of using the `${applicationId}` placeholder in `AndroidManifest`, we went overboard with the switch. There are some places where we don't want to make the action ID for an intent filter dynamic, because they're referenced by some place outside of CommCare that has no notion of switching that request based on which flavor of CommCare it's calling out to. This is definitely true of `TemplatePrinterActivity` because HQ injects the intent ID into the XForm, so it has to be a static value. Note that this means printing has never worked on LTS.
@wpride and @ctsims Aside from printing, I've changed this in all of the other places that I _think_ it should be changed. I confirmed that for all of these, …
> Don't use dynamic action id intent filters that will be set/called from outside CommCare

- app/src/org/commcare/fragments/SelectInstallModeFragment.java
**Product Note**: Fixes a bug where if an incorrect app code was entered for installation, the install would fail but with no error message or indication of what went wrong. 
A very non-obvious fix for https://manage.dimagi.com/default.asp?269826. The reason no error message was showing up was that the `TextView` that contains it is on the `SelectInstallModeFragment`, but after installation by app code failed, we were failing to return to that fragment as we should have been. So that was the actual question here, and the cause turned out to be the following:
The [implementation of `onURLChosen()` in `CommCareSetupActivity`](https://github.com/dimagi/commcare-android/blob/d15686feb4e41f8daa8cd3e0a5441435644f5a0a/app/src/org/commcare/activities/CommCareSetupActivity.java#L293-L297) sets the …
> Do fragment transaction properly when adding app code fragment

- app/src/org/commcare/activities/PromptUpdateActivity.java
Case: https://manage.dimagi.com/default.asp?270185
Crash: https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5a300d4a8cb3c2fa63b92579/sessions/latest?build=69952000
On Rotation, before we could refresh the `updateToPrompt` in `onCreateSessionSafe ` `isBackEnabled`  gets called from `BreadcrumbBarFragment.configureSimpleNav` which results in this NPE.  I am now refreshing the `updateToPrompt` object again if it's null and have added the isNull check in onCreateSessionSafe to avoid duplicate initialization. 
Product Note: Fixes Commcare crash on rotation on the update prompt screen.
> Fixes NPE on rotation for Update Prompts

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
Ran into this while dog fooding, we are always returning `RESULT_CANCELED` for external callouts into CommCare, even when we succeed. Conveniently we already have a boolean corresponding to whether the event succeeded or failing, so we should set the result based on that.
> Return RESULT_OK for external callouts

- app/res/layout-land/update_activity.xml
- app/res/layout/update_activity.xml
Crash: https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5a8dad6d8cb3c2fa6387e5a0/sessions/5A8ED8FF00BC00012D0FE83CC2E3B097_DNE_0_v2?select_key=user
Regression from https://github.com/dimagi/commcare-android/pull/1946, we missed out on adding the new error view to landscape layout causing a NPE in landscape mode. 
Side Note: I stumbled on this while working on integration tests. This was appearing as the infamous `HTTPClient::KeepAliveDisconnected: (HTTPClient::KeepAliveDisconnected` error on device farm with no crash logs in logcat logs. So it seems like logcat provided by device farm is not always complete/accurate.
> Updates landscape layout for update activity with recent changes

- app/src/org/commcare/adapters/EntityStringFilterer.java
Splits out the non-database layer portions of the entity sorting code into the `EntitySorterUtil` class in `commare-core` for usage in Formplayer.
cross-request: https://github.com/dimagi/commcare-core/pull/764
> Split non-DB centric sorting into commcare-core utility

- app/res/layout/select_install_mode_fragment.xml
- app/src/org/commcare/fragments/SelectInstallModeFragment.java
Even when we are making the error button invisible in fragment's onResume in case of no pending notifications, it becomes visible again  in `showOrHideErrorMessage` which gets called later from activity's `onResumeFragments`. I have added the same check in `showOrHideErrorMessage` as well, but let me know if you see a better way to handle it. 
Repro - 
1. An error occurs while install which makes error button visible
2. User clicks on error button to see more details about the error
3. User press back from Error detail screen to come back on Install screen
4. Error button is still visible even though there are no pending notifications
> Error button visibility fix

- app/src/org/commcare/adapters/IncompleteFormListAdapter.java
Reverts dimagi/commcare-android#1939. I realized thanks to https://manage.dimagi.com/default.asp?271707 that this change makes no sense because the submission ordering number resets once forms are submitted successfully, so it can't be relied upon as a global comparator for already-sent forms. Sorting based on ordering number is theoretically still valid for _unsent_ forms, but I don't think it makes sense to make the sort behavior for that one filter different, so let's just revert to the way things were. 
Waiting for input from @ctsims to decide whether this is also hotfix-worthy.
**Product Note**: Undoes the change in dimagi/commcare-android#1939, meaning that we're back to sorting unsent/saved forms by their last-modified date.
> Revert "Sort completed forms in form record list by submission ordering number"

- app/src/org/commcare/activities/LoginActivity.java
The restoration of the last-logged-in username for a given app was getting overridden by the call to `restoreEnteredTextFromRotation()` made by `LoginActivityUIController.refreshView()`. This change solves that by clearing out the saved "before rotation" values if we've just returned from a successful `SeatAppActivity`. The thing that's bothering me is I cannot figure out what changed recently to cause this to break. It definitely worked properly for a long time, but I can't find anywhere in the relevant code that's been touched recently. I already spend a little too long looking for the root cause though so going to be satisfied with just fixing it. If anyone sees what I'm missing, let me know.
**Product Note**: Fixes a small regression where switching between apps on the login screen …
> Fix overriding of last username

- app/src/org/commcare/activities/FormEntryActivity.java
FB: https://manage.dimagi.com/default.asp?272815
Instance path should not be re-initialized on resuming form entry after form Entry session. This results in a buggy behaviour(data loss) where the incomplete form from session expiration doesn't get updated with the data that user enters after resuming session. Moreover this incomplete instance gets uploaded to server since it gets marked as complete on save. 
@ctsims Just realizing that we might want to hotfix this instead. What do you think ?
Product Note: Bug Fix: When a user gets logged out of CommCare while entering data in a form, on login again he gets redirected to the Form he was previously in. This bug was causing any new data entered in this specific form to not get saved resulting in loss of data entered by user for this form.
> Fixes Save in FormEntry after Resuming Session

- app/res/values/strings.xml
Note that I'm not 100% sure how the `update_translations` script in the release process is going to react to a multi-line translations value like this. If we're concerned I could try testing it ahead of time, but I didn't do so right now because it's a pain to run that in isolation without all of the surrounding harnessing.
> Make noun project credit translatable (for CAS)

- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
- app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
Fixes an issue where upgrades which occur from a build after db v20 from a pre v6 build will fail due to the newest (rather than original) definition of the case index table being created in the initial update.
> Bugfix: Update from pre relationship index table when origin db is v5 or below

- app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
Ideally we sould not be catching exceptions at all but for time being just logging the catched exceptions to see if it has any thing to do with profile being null errors.
> Logs resource init failures to Device Logs

- app/src/org/commcare/provider/SimprintsCalloutProcessing.java
Since it's possible/valid in a Simprints callout question specification to only provide a node at which to store the `guid` response (and none of the fingerprint responses themselves), we should define successful processing of the callout response to be getting _either_ the guid or the fingerprints (or both).
This issue was brought to my attention by https://manage.dimagi.com/default.asp?274249. The root issue in that ticket is a bit different than the potential situation I outlined here (there appears to actually be a bug with the returning of the fingerprint values), but nonetheless I think this is the correct thing for us to be doing.
> Change definition of successful Simprints callout processing

- app/AndroidManifest.xml
- app/build.gradle
- app/proguard.cfg
- app/src/org/commcare/utils/MarkupUtil.java
Addresses [this ticket](https://manage.dimagi.com/default.asp?271507) by updating us to a newer, CommonMark-compliant library. It looks like the old `bypass` library has also been abandoned so good to address this tech debt anyways.
Surprisingly there doesn't seem to be a consensus-best markdown library for Android, though this one has the best feedback and is the only one I could find that's CommonMark compliant. Unfortunately it supports only API 16 and above, so once we make our minimum 14 in the next release that will leave the Ice Cream Sandwich builds out in the cold (lol). For that reason we'll need to leave the `bypass` library in for the time being. 
For new APIs, needed to add the `maven.google.com` endpoint to repositories [SO](https://stackoverflow.com/a/45342389/2820312)
> Update Markdown llibrary

- app/src/org/commcare/engine/resource/ResourceInstallUtils.java
ticket: https://manage.dimagi.com/default.asp?275025
If we were setting the `targetParam` then it was impossible to also set the `username` parameter.
> Don't exit before adding url param

- app/src/org/commcare/CommCareApp.java
- app/src/org/commcare/activities/HomeNavDrawerController.java
- app/src/org/commcare/activities/StandardHomeActivityUIController.java
**Question for everyone**: I've created this PR as the easiest way to get input on the soundness of this -- the ICDS team would like to make it so that if an app contains 1 or more training menus, _but_ they all have display conditions which evaluate to false, then the home screen training button does not show up. I explained (in a simplified way) that this is not strictly doable within CommCare's model because at the time the home screen buttons are rendered, the proper evaluation context for the menus isn't present. However, I've realized that technically I can reconstruct it, as I've done in this PR. My question is whether anyone sees any risks associated with doing this that I'm missing, or if it just seems too gross to allow ourselves to do. (I've tested that it works from a desired …
> Hide home screen training button if its menus are hidden

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
This is  a regression from form provider refactor. I mistakenly turned on the warning when saving incomplete forms which shouldn't be the case.
> Reverts to not showing warning when saving Incomplete forms

- app/res/values/strings.xml
Now that this string is translatable, having it span multiple lines in the strings.xml file results in breaking behavior when the update_translations script moves it to the `messages_en-2.txt` file in the commcare-translations repo. These physical newlines weren't actually doing anything except making the string easier to read in the file itself, so we can just get rid of them.
> Don't have a translatable string span multiple lines

- app/build.gradle
- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
- app/src/org/commcare/models/database/AndroidPrototypeFactorySetup.java
- app/src/org/commcare/tasks/LogSubmissionTask.java
- build.gradle
- gradle.properties
Investigating [this ticket](https://manage.dimagi.com/default.asp?276201) we located the crash [here](https://fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5ad5a4cd36c7b23527007bc6?time=last-seven-days) and noticed that the crash reported over 900 open cursors causing an OOM error.
Looking for a way to investigate I found [this](https://stackoverflow.com/a/28155638/2820312) pretty nifty profiling mode that hard-crashes the application whenever you leave a resource unclosed. This turned up a bunch of `File`s and `InputStream`s that we weren't closing which is nice. The only hanging `Cursor` I found seemed to be coming from [firebase](https://github.com/firebase/quickstart-android/issues/176) so I updated the library (and was required to update play services and change this param …
> Close resources

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
- app/src/org/commcare/android/database/app/models/FormDefRecord.java
- app/src/org/commcare/android/database/user/models/FormRecord.java
- app/src/org/commcare/tasks/SaveToDiskTask.java
**Includes https://github.com/dimagi/commcare-android/pull/2004, review + merge that first.**
This will fix http://manage.dimagi.com/default.asp?276261. I realized what was happening here from examining the device logs surrounding submission of the forms that Derek linked in that ticket. Because of where we were previously calling `setFormNumberForSubmissionOrdering()`, a crash that occurred at the end of form entry would result in the `FormRecord` being successfully saved as complete, but never having its submission ordering number set (and therefore having a value of -1). This PR fixes that by setting the submission order number at the same time we update a `FormRecord`'s status to `STATUS_COMPLETE`. (The crashes themselves that were occurring post-form entry were varied and none of …
> Set submission ordering # at same time we mark a form as completed

- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/android/resource/installers/FileSystemUtils.java
- app/src/org/commcare/logging/DataChangeLogger.kt
I saw some instances on Sumo that suggests that this issue starts occurring either after an app auto update. Furthermore, Sachit from Community health got back to us saying that there are users in the field who are facing storage corrupt issue after a playstore update. I am hoping sending data change logs to device logs will help us in determining the exact sequence of events for that particular update and would help us narrow down this bug. 
* Sends data change logs to device logs
* Logs result for auto update. 
cross-request: https://github.com/dimagi/commcare-core/pull/811
> Add more logs to debug missing app files issue

- app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
- app/src/org/commcare/models/database/global/DatabaseGlobalOpenHelper.java
- app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
- gradle.properties
Enables indexed searches by an `external_id` property to be used by (you guessed it) external systems like SimPrints. The implementation uses the existing `external_id` case property as the value if it exists since this is already used by HQ in the same way. 
cross-request: https://github.com/dimagi/commcare-core/pull/814
> Add external_id as indexable case property

- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
- app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
- app/src/org/commcare/models/database/user/models/AndroidCaseIndexTableV1.java
Fixes migration bug due to using new case index definition in old migration.
Case: https://manage.dimagi.com/default.asp?278205
Error Stack - 
```
net.sqlcipher.database.SQLiteException: table case_index_storage has no column named relationship: , while compiling: INSERT INTO case_index_storage(name, relationship, type, case_rec_id, target) VALUES(?, ?, ?, ?, ?);
at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
at …
```
> Fixes User DB v5->6 migration caused by Case Relationship

- app/src/org/commcare/android/database/user/models/ACasePreV24Model.java
- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
- app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
- app/src/org/commcare/models/database/user/models/AndroidCaseIndexTable.java
- app/src/org/commcare/models/database/user/models/AndroidCaseIndexTablePreV21.java
- app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Case: https://manage.dimagi.com/default.asp?278205
Extension of https://github.com/dimagi/commcare-android/pull/2013 to fix more migration bugs. 
Error 1: DB Migration v17->18 (Because of `external_id` addition to case model)
```
net.sqlcipher.database.SQLiteException: no such column: external_id: , while compiling: UPDATE AndroidCase SET external_id=?, case_id=?, owner_id=?, case_type=?, case_status=?, commcare_sql_record=? WHERE commcare_sql_id=?
at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
at …
```
> Corrects External Id Migration for v17-18, Fixes case Relationship migration for v18-19

- app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
- app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
- app/src/org/commcare/utils/AndroidCommCarePlatform.java
CL: https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59dd64f2be077a4dcc14f222?time=last-twenty-four-hours
This issue is happening when apps having entries in update table are getting updated to CommCare 2.44 i.e if a user who have an app update staged but not installed update CommCare to 2.44 and login again his app crashes. I am able to repro it and have verified that this solution fixes the issue for both people updating to potential 2.44.1 from both 2.43 and 2.44 
I am stuck on a weird problem though, putting it as a comment inline.
> Migration fix for Upgrade and Recovery Table

- app/res/layout/screen_recovery.xml
- app/res/values/strings.xml
- app/src/org/commcare/CommCareApp.java
- app/src/org/commcare/activities/RecoveryActivity.java
- app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
- app/src/org/commcare/android/resource/installers/LocaleAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/SuiteAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
- app/src/org/commcare/engine/references/JavaFileReference.java
- app/src/org/commcare/tasks/ProcessAndSendTask.java
- app/src/org/commcare/tasks/ResourceRecoveryTask.java
- app/src/org/commcare/utils/DummyResourceTable.java
* Implements 'Recover App' functionality in `RecoveryActivity` to re-download any missing resources
* `ResourceTable` now maintains a vector for `missingAppResources` which gets set while initializing an app
Screenshots - 
1. Storage Corrupt Warning - @ctsims I don't see any particular benefits of this screen since all this asks is whether to enter recovery screen or exit the app. Instead we can directly make user enter the recovery screen and user can always exit the app by pressing back. 
2. Recovery Screen
3. Recovery in progress
4. Recovery Success
cross-request: https://github.com/dimagi/commcare-core/pull/817
Product Note: Adds functionality to re-download missing app resources from Recovery Screen.
> Re-download missing Resources from Recovery Screen 

- app/src/org/commcare/android/database/user/models/SessionStateDescriptor.java
- app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
- app/src/org/commcare/models/database/user/UserDbUpgradeUtils.java
CL: https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59e2076c61b02d480d8ee18e?time=last-thirty-days
Repro: 
1. Install CommCare 2.43
2. Create 2 Forms A and B in that sequence
3. Delete A
4. Update to CommCare 2.44 or 2.44.1
5. Observe a crash on creating any new form
While migrating FormRecords in v23 migration, we delete the old table and rewrite all entries into a new FormRecord table which results in `id` of FormRecords getting changed to new values. Since `SessionStateDescriptor` records hold references to these ids, these ssd records need to be migrated as well. In a general case new form ids would be same as old causing this bug not to surface except when user or some process deletes a form record from the device which is not the latest. For example, I am …
> Fixes Crash due to SSD records getting detached in FormProvider Migration

- app/src/org/commcare/android/database/app/models/FormDefRecord.java
- app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
- app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
Jira: https://dimagi-dev.atlassian.net/browse/MOB-17
This was silly on my end. Form record path wasn't  getting updated to the  `install` path from `upgrade` path since `updateFilePath` in `FormDefRecord.java` was not actually setting the new filepath value for the form before updating the form record.
This bug doesn't surface in normal cases since generally form records filepath references doesn't change. The bug only gets exposed in cases when namespace of a form changes in between 2 updates since that's the only case where a form record with `upgrade` path gets created and then we later wanna change it to `install` file path.  For installations who have already encountered this scenario, we are applying an one time update which checks for non existent `upgrade` file references in …
> Fixes bug in updating File path for an existing Form with new file path

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
Jira: https://dimagi-dev.atlassian.net/browse/MOB-19
Something that I overlooked during FormProvider refactoring. This warning message was earlier shown when `FormEntryActivity` didn't return any form instance uri. Though since now FormProvider is merged into FormRecord, don't think there is any valid scenario for this error anymore.
> Removes incorrectly shown form lost warning on saving incomplete forms

- app/src/org/commcare/activities/DrawActivity.java
Jira: https://dimagi-dev.atlassian.net/browse/MOB-18
CL: https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59caaf6bbe077a4dcc4b084c?time=last-ninety-days 
https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/59fa5c6561b02d480d9b5247?time=last-ninety-days
Problem: We are hitting OOMs frequently for some users on signature questions which is becoming a operational problem for them. 
Optimisation: RGB_565 uses 2 byte per pixel in comparison to 4 bytes per pixel used by ARG_8888. This results in less memory consumption when creating these bitmaps. In terms of quality, I couldn't see any difference from naked eye when comparing the 2 configs. Maybe since we are only using black and white colors it doesn't make much of a difference.
> Use RGB_565 config for Signature Bitmaps

- app/src/org/commcare/activities/FormEntryActivity.java
CL: https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5b3f408d6007d59fcdc44901?time=last-ninety-days
We no longer use `KEY_FORM_RECORD_ID` in the calling activity to get the instance of form record but directly utilize the CommCare Session to get us the filled form.
> Removes unused intent key

- app/src/org/commcare/views/widgets/SpinnerMultiWidget.java
FB: https://manage.dimagi.com/default.asp?282025
In case SpinnerMultiWidget has readOnly prompt, shows'CANCEL' button in dialog instead of an 'OK' button.
Product Note: Fixes a bug due to which user is able to edit MultiSelect checkbox questions with 'minimal'  appearance when 'readOnly()` is set to true in form xml.
> Makes SpinnerMultiWidget uneditable if readonly

- app/src/org/commcare/tasks/ProcessAndSendTask.java
Jira: https://dimagi-dev.atlassian.net/browse/MOB-31
Throwing FNF for forms with empty paths to eventually quarantine them. Earlier we were doing the same thing when a instance URI was empty for a FormInstance and hence this change is in line with the behaviour before the FormProvider refactor.
> Quarantine Forms with Empty Paths

- app/build.gradle
- app/res/values/strings.xml
- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/CommCareNoficationManager.java
- app/src/org/commcare/provider/DebugControlsReceiver.java
- app/src/org/commcare/services/CommCareSessionService.java
- app/src/org/commcare/views/dialogs/PinnedNotificationWithProgress.java
- scripts/ccc
* Creates 3 Notifications Channels  - Errors, Server Communications, User Session and assigns notifications to one of these channels. 
* Update `ccc` broadcasts to use receiver names
Product Note: Add Support for Android Oreo
> Target Oreo (Android 8.1)

- app/build.gradle
- build.gradle
Reverts dimagi/commcare-android#2044
- Reverting since Roblectric version we are using breaks with AGP 3.2.+
> Revert "Update Gradle dependencies for latest AndroidStudio builds"

- app/src/org/commcare/activities/DrawActivity.java
Context: https://github.com/dimagi/commcare-android/pull/2027
This got left behind in earlier PR where we made the shift from ARGB_8888 to RGB_565 for signature bitmaps
> ARGB_8888 -> RGB_565

- app/src/org/commcare/activities/FormEntryActivityUIController.java
- app/unit-tests/src/org/commcare/android/tests/formnav/EndOfFormTest.java
- app/unit-tests/src/org/commcare/android/tests/formsave/FormRecordProcessingTest.java
Refreshes view to show Finish button on advancing to end of form instead of triggering auto-save. 
Jira: https://dimagi-dev.atlassian.net/browse/MOB-41
Product Note: If there is a required date widget on the last screen in the form, earlier swiping ahead would auto-save the form. We have now changed this behaviour to instead show Finish button on swiping ahead and user needs to click on the Finish button to trigger save on the form.
> Show Finish button on advancing to end of form

- app/src/org/commcare/activities/components/ImageCaptureProcessing.java
Case: https://dimagi-dev.atlassian.net/projects/MOB/issues/MOB-14
We don't end up using the final scaled image currently. So switiching off the scaling code path completely since it deletes the images from gallery today.
> Turns Image scaling code path off

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/FormEntryActivityUIController.java
- app/src/org/commcare/logic/AndroidFormController.java
- app/src/org/commcare/tasks/SaveToDiskTask.java
Jira: https://dimagi-dev.atlassian.net/projects/MOB/issues/MOB-38
There are 3 forms across 3 different users for which users were getting an error like - 
`Error during task execution: XML Syntax Error at Line: 1, Column: 251!]` on opening these forms from Saved Forms and these forms were also causing syncs to fail as well with 500 response code. 
Itnerpreting logs, there exists a loose pattern with all these 3 forms. For two users, Form Entry successfully completes for the respective forms but soon after (~2 mins) we get an error arising from form save code stack. The exact error being - 
`Error during task execution: Attempt to invoke virtual method 'void org.commcare.android.database.user.models.FormRecord.setFilePath(java.lang.String)' on a null object reference]`
This suggests that …
> Disable the finish button after first click

- app/src/org/commcare/activities/LoginActivity.java
Jira: https://dimagi-dev.atlassian.net/browse/MOB-60
Seems like not all phones refreshes menu by default on returning to an activity, so signalling it explicitly to Android to refresh menu.
Product Note: Fixes a bug where Menu translations won't update on switching the apps in CommCare.
> Refreshes menu on app change

- app/res/layout/component_entity_detail_item.xml
- app/res/layout/entity_detail_list.xml
Jira:https://dimagi-dev.atlassian.net/projects/MOB/issues/MOB-65
Setting lisview height to `match_parent` to tackle variable text lengths. This also will make Android to handle listview's children variable heights more gracefully. Currently the `getView()` for `EntityDetailAdapter` ends up getting called multiple times per listview row.
> Fixing Entity Detail View to not cut content

- app/src/org/commcare/utils/UriToFilePath.java
CL: https://www.fabric.io/dimagi/android/apps/org.commcare.lts/issues/5c00cbb4f8b88c2963f67e8b/sessions/5C56BF64035200011BD90A6E255DDF81_DNE_0_v2?
Uses Environment.DIRECTORY_DOWNLOADS instead of hardcoding the downloads path. 
This is Inspired from: https://github.com/flutter/plugins/pull/1089 . I have not been able to repro the issue on my devices to be able to verify this.
> Fixed Crash when selecting a file from Downloads folder

- app/src/org/commcare/activities/UpdateUIController.java
CL: https://www.fabric.io/dimagi/android/apps/org.commcare.lts/issues/5c00a33df8b88c2963f30f9c?time=last-ninety-days
Gets version from app record instead of platform profile to avoid NPEs in case profile is not initialized
> NPE in Update Activity

- app/src/org/commcare/engine/references/JavaHttpReference.java
- app/src/org/commcare/network/HttpUtils.java
- app/src/org/commcare/network/RemoteDataPullResponse.java
- app/src/org/commcare/tasks/DataPullTask.java
- app/src/org/commcare/utils/FormUploadUtil.java
Spec:https://docs.google.com/document/d/1xfOaDsV0gllRwZM2zWigc4BEHarDjPKuwbGYp50-Xt0/edit#heading=h.ty5i7ie0b8sj
This enables the functionality for HQ to pass mobile an error like - "You need to be logged in to do an app update". We are doing this to restrict app updates when user is logged out for Location based App Updates feature. 
PR also moves the common 406 parsing code from various places to `HTTPUtils`.
> Shows 406 error messages from HQ while App update

- app/res/layout/small_audio_playback.xml
- app/res/values/dimens.xml
- app/src/org/commcare/views/media/AudioPlaybackButtonBase.java
- app/src/org/commcare/views/media/MediaLayout.java
The AudioButton was not properly sizing itself in RtL previously on at least some devices, probably because our layout declaration was non-deterministic.
Fixes so that the button has the same layout configuration as in LtR mode
For consistency: this is what the app currently (not with this PR's code) lays out for RtL audio buttons
I'm not really sure whether the placement of the round button in the box model is an issue, but it's consistent now.
> Fix for RtL layouts with audio buttons

- app/src/org/commcare/utils/UriToFilePath.java
Issue: Noticed that on a Lennovo phone, `getDataColumn` returns null for files selected from 'Recent' option in stock file provider. 
Proposed Change: if we are not able to get a non null filePath from a file provider uri, returns the original uri for further processing (making a internal copy of the file using uri which seems to be the best optionto protect against such failures). 
Product Note: Fixes an issue where CommCare won't be able to detect a file selected from Recent folder of Android File Explorer.
> Fix for CommCare not getting filePath for Files selected from File Explorer 'Recent' option

- app/src/org/commcare/activities/FormEntryActivity.java
Jira: https://dimagi-dev.atlassian.net/browse/QA-171
In RTL, form entry menu was not getting aligned to the right on some devices. Moving the menu creation code to `onCreateOptionsMenu` from `onPrepareOptionsMenu` seems to fix the issue.
> Form Entry Menu Alignment Fix for RTL

- app/res/layout/edit_text_question_widget.xml
- app/res/layout/edit_text_question_widget_compact.xml
Jira: https://dimagi-dev.atlassian.net/browse/QA-188
Lots of formatting diff below though the only meaningful change is addition of below 2 properties in both Edittexts - 
```
android:gravity="start"
android:textAlignment="viewStart"
```
> Start Align Text in String widget to support for RTL

- app/src/org/commcare/activities/EntitySelectActivity.java
- app/src/org/commcare/activities/EntitySelectSearchUI.java
Jira: https://dimagi-dev.atlassian.net/browse/MOB-73
Tries to restore the search after setting the adapter.
@ctsims It seems a bit urgent for REACH so getting it in 2.45 for next LTS release even though QA test run is complete. 
Product Note: Fixes a bug causing search results to not be retained on returning back to the case list.
> Restore search on getting back to the Case list

- app/src/org/commcare/views/widgets/DecimalWidget.java
Jira: https://dimagi-dev.atlassian.net/browse/QA-186
When we format numbers in Arabic, they get converted to Arabic numbers which then throws an error on getting parsed as double. 
This PR sets the language to english for formatting the decimals. Moreover, it also removes the ew-conversion from formatted string to Double to avoid showing decimals in scientific/exponential notation.
> Always format Decimal Widget as English 

- app/src/org/commcare/CommCareApp.java
https://dimagi-dev.atlassian.net/browse/MOB-76
we were using eval context for root menu to evaluate relevance condition for the child menu. This PR fixes that by using eval context for child menu.
> Corrects eval context for menu relevance condition

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/logic/AndroidFormController.java
- app/src/org/commcare/tasks/SaveToDiskTask.java
Jira:https://dimagi-dev.atlassian.net/browse/MOB-86
Issue: When we rolled out [this change](https://github.com/dimagi/commcare-android/pull/2041/files) to allow a form to only be saved once we didn't consider that we currently allow incomplete forms to be saved more than once through the "Save" options menu. 
Proposed Change: Only mark forms as "saved" for complete forms so that a incomplete form's save don't get stuck at [the check here](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/activities/FormEntryActivity.java#L737).
Product Note: Fixes a bug due to which saving a form as Incomplete more than once doesn't work
> Bug fix: Saving a form as Incomplete more than once doesn't work

- app/assets/locales/android_translatable_strings.txt
- app/res/values/strings.xml
- Adds missing string "archive.install.error" for showing errors while unzipping
- Removes line breaks (HQ translation update scripts breaks in case of line breaks)
> Corrections in String File

- app/AndroidManifest.xml
Content providers are not exposed to other applications, anymore.
Jira ticket :https://dimagi-dev.atlassian.net/browse/MOB-83
> changed provider exported to false

- app/src/org/commcare/network/CommcareRequestGenerator.java
Looks like practice mode form submission has been broken for a while (since retrofit migration). On submitting any data in practice mode we get 401 from server since we are no longer putting `params.put(AUTH_REQUEST_TYPE, AUTH_REQUEST_TYPE_NO_AUTH);` in the form submission request. 
I am not sure if it's worth a hotfix so just PRing to master. 
Product Note: Fixes form submission in practice mode.
> Fixes form submission in practice mode

- app/src/org/commcare/activities/components/ImageCaptureProcessing.java
Reverts #2019
Jira: https://dimagi-dev.atlassian.net/browse/MOB-103
Hotfixing https://github.com/dimagi/commcare-android/pull/2105
This was a misunderstanding on my part where I thought the scaled image doesn't get used at all. Though it looks like we are using the final scaled image later on. I got confused by not knowing the fact that we always display the original image on screen while the scaled image gets submitted to the server.
Product Note: Fixes a bug where CommCare 2.45 doesn't respect "Image Size" set for image capture questions.
> [HOTFIX] Revert "Turns Image scaling code path off"

- app/src/org/commcare/engine/cases/CaseUtils.java
- app/src/org/commcare/network/CommcareRequestGenerator.java
- app/unit-tests/src/org/commcare/android/tests/processing/ProcessingTest.java
Significantly improves how fast we generate the state hash token for syncs (at least 100% faster with 54k cases, probably faster on slower devices) by using the metadata index coverage method rather than reading the case records raw.
Found this while investigating performance issues identified by Jessica on isth-production
cross-request: https://github.com/dimagi/commcare-core/pull/852
> Improve Sync Request hashing performance

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/components/ImageCaptureProcessing.java
- app/src/org/commcare/views/widgets/ImageWidget.java
2 changes
- Removes the image publishing to MediaStore for CommCare Images
- Don't delete Gallery copies of the images
Jira: https://dimagi-dev.atlassian.net/browse/MOB-14 
Jira: https://dimagi-dev.atlassian.net/browse/MOB-72
Product Note:
- Fixes a bug where Internal CommCare copy of the image will start showing up in Gallery
- Fixes a bug where deleting or replacing the image from CommCare will result in the image getting deleted from Gallery
> Stops Images from getting shown in Gallery

- app/src/org/commcare/activities/components/ImageCaptureProcessing.java
- app/src/org/commcare/engine/cases/AndroidIndexedFixtureInstanceTreeElement.java
- app/src/org/commcare/models/database/AndroidSandbox.java
- app/src/org/commcare/models/database/IndexedFixturePathUtils.java
- app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
- app/src/org/commcare/utils/AndroidInstanceInitializer.java
- app/unit-tests/resources/indexed_fixture_restore.xml
- app/unit-tests/src/org/commcare/android/tests/processing/IndexedFixtureLoadingTest.java
- app/unit-tests/src/org/commcare/android/util/TestUtils.java
- Adds a column for root level attributes in IndexedFixtureIndex user DB table
- Adds `AndroidIndexedFixtureInstanceTreeElement` to support attributes lookup for root attibutes. 
cross-request: https://github.com/dimagi/commcare-core/pull/842
> Adds support for last_sync attribute for Indexed Fixtures

- app/src/org/commcare/activities/FormEntryActivity.java
Jira: https://dimagi-dev.atlassian.net/browse/ICDS-525
CL: https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5b5b918a6007d59fcdfa7535?time=last-thirty-days
I was able to repro this issue on clicking Finish twice for a form who has another form linked to it via EOF navigation. I am not sure why it only happens when we have another form linked to current form. though what seems to be happening is "mFormController" becomes null when the activity is getting destoyed and if user clicks "Finish" around the same time it results in a NPE.
> Protect Form finish when activity is getting destroyed

- app/src/org/commcare/views/widgets/SignatureWidget.java
Jira: https://dimagi-dev.atlassian.net/browse/QA-436
CL: https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5ccabef0f8b88c2963d337c5?time=last-thirty-days
Regression of https://github.com/dimagi/commcare-android/pull/2110/files#diff-7825926c6662bb8827ea6b48aae09b83R174
We are now calling `setBinaryPath` with the path of the image rathr than URI and since we didn't make this change in SignatureWidget and only for ImageWidget, the app was crashing. 
Can someone merge it on approving so that it gets available to QA for testing and also ping on Jira ticket so that QA can test it again.
> Fix Sign Save

- app/src/org/commcare/android/resource/installers/FileSystemUtils.java
While updating a media file when a media resource file path changes folder structure, the update fails because of failure in moving the file to the new folder structure since we don't ensure that fold structure exists beforehand. 
Full Context [here](https://dimagi-dev.atlassian.net/browse/ICDS-578?focusedCommentId=21834&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21834)
This issue happens only for media files that existed in the old version. For ex. in version 1 say we have a media file with path a/b/mf.png and in version 2, we updated it's path to a/c/mf.png.  Mobile fails in updating a resource to this new path `a/c/mf.png` since it doesn't create the folder `c` before copying that file to the new path. It only happens while updating an existing …
> Ensure new file path for media file exists before renaming

- app/src/org/commcare/tasks/AsyncRestoreHelper.java
Jira: https://dimagi-dev.atlassian.net/browse/MOB-113
@ctsims I am not really sure how I can reproduce this behaviour to test this out so just adding additional checks that I think would restrict this issue to happen in future.
> Avoid progress numerator shooting beyond denominator For Async Restore

- app/res/values/strings.xml
- app/src/org/commcare/activities/UpdateActivity.java
- app/src/org/commcare/engine/resource/AndroidResourceManager.java
- app/src/org/commcare/tasks/UpdateTask.java
Jira: https://dimagi-dev.atlassian.net/browse/MOB-108
Issue1: When user stops the current update check, `taskIsCancelling` gets set to `true` which never gets reset to false even after the task is cancelled. So when user triggers an offline update the update task never gets triggered again because of the [check on taskIsCancelling](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/activities/UpdateActivity.java#L128).
Issue2: When user triggers an offline update without stopping the current check, the offline update never takes effect and the update check just continues fetching the resources online. This is because if there is an ongoing update check, we just[ connect to it](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/activities/Up …
> Fixes in Offline Update Workflow

- app/src/org/commcare/android/database/app/models/FormDefRecord.java
- app/src/org/commcare/android/database/app/models/FormDefRecordV12.java
- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
- app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
- app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
- app/src/org/commcare/tasks/SaveToDiskTask.java
- app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Jira: https://dimagi-dev.atlassian.net/browse/ICDS-343
In case of an update containing an existing form with changed resource id, during staging the update table to replace master, we end up giving it the `formid` for the existing entry for existing form with same namespace in `FormDefStorage`. This existing form's xml file gets removed when we uninstall this existing form. Though since the new form is still linked to old form's path,  it results in the "Error Reading XForm" error on opening that form. 
Instead of linking the form resource in update to the existing master form, we wanna treat it as a completely new resource and hence give it a new row in FormDef Storage. So Irrespective of the fact that a form already exists with the same namespace, we add a new form def row (hence new …
> Makes xforminstaller accounts for  form id changes during update

- app/src/org/commcare/tasks/ProcessAndSendTask.java
- app/src/org/commcare/utils/FormUploadResult.java
- app/src/org/commcare/utils/FormUploadUtil.java
Currently when receiving a 503 from the server, the phone immediately tries again a few times. This updates the send task to short circuit back instead to cease further attempts to submit the forms automatically.
This is high priority as our rate limiting is currently getting hit with even higher submission counts after each form due to the automated retry.
> Don't retry form submissions when rate limited

- app/src/org/commcare/engine/cases/AndroidIndexedFixtureInstanceTreeElement.java
Rethrows any exception caught during deserialization for indexed fixtures atrributes
> Correct error handling for Indexed Fixture atrribute lookup

- app/src/org/commcare/activities/components/FormEntryInstanceState.java
- app/src/org/commcare/android/database/app/models/FormDefRecord.java
- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
Issue: https://forum.dimagi.com/t/incomplete-forms-error-more-than-one-xform-present/6705
The duplicate formid issue PR introduced a bug in reading saved/Incomplete forms by creating the possibility of more than one entries in Form Def table for a namespace. On reading such a saved form, we were erroring out with message "More than one XForm definition present for this form". I missed out on this code path earlier while implementing the fix costing this bug.
> [HOTFIX] [commcare_2.47.2] Fixes saved forms reading issue when there are duplicate namespaces in Forms table

- app/src/org/commcare/views/widgets/CommCareAudioWidget.java
- app/src/org/commcare/views/widgets/RecordingFragment.java
Jira: https://dimagi-dev.atlassian.net/browse/MOB-122
The Prototyped widget was using `questionIndexText` for creating the filepath. This causes the widget to show up an already recorded file for all forms for that particular question. This PR fixes the issue by incorporating a more unique file identifier using datestamp.
> Fixes for ProtoType Audio Widget

- app/src/org/commcare/tasks/ProcessAndSendTask.java
On a poor network connection, there can be a gap of 2 mins when the request timeout and another attempt is made. So it only seems fair that we check for task cancellation in between the upload attempts.
> [HOTFIX][2.47.3] Check for task cancellation before making a form upload attempt

- app/src/org/commcare/activities/HomeButtons.java
- app/src/org/commcare/preferences/HiddenPreferences.java
- app/src/org/commcare/utils/SyncDetailCalculations.java
Jira: https://dimagi-dev.atlassian.net/browse/ICDS-795
* Makes Unsent Forms Always Visible
* Adds a custom property "cc-show_unsent_forms_when_zero" to control whether to show unsent forms indicator when there are no unsent forms. 
Product Note: Makes No. of unsent forms always visible on the sync button.
> Makes No. of Unsent Forms always visible

- app/src/org/commcare/utils/SyncDetailCalculations.java
Corrects https://github.com/dimagi/commcare-android/pull/2134 which was causing "unsent forms: 0" to show up in case `notificationText!=null` even if `shouldShowUnsentFormsWhenZero` is set to false.
> Strictly make showing 0 unsent forms dependent on custom setting

- app/src/org/commcare/models/database/app/AppDatabaseUpgrader.java
Jira: https://dimagi-dev.atlassian.net/browse/MOB-135
This issue is breaking updates from any CC versions on or before 2.43 to CC 2.47 , and was introduced in 2.47. 
I am not sure how our QA update test passed on this since this is reproducible for all apps. Going to work with QA to identify what went wrong there.
> [HOTFIX 2.47.4] Form record upgrade fix

- app/src/org/commcare/utils/CommCareExceptionHandler.java
In cases where the nolocatization exception is not the primary exception, the localization error gets hidden by the primary exception leaving user with a non concrete error message.  
Example Exception for which this PR fixes the error message - 
````
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:353)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused …
```
> Fixes localization error message

- app/src/org/commcare/activities/FormRecordListActivity.java
https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/5c82a3dbf8b88c2963632e59?time=last-ninety-days
Moves the adapter based menu visibility logic to OnPrepareOptionsMenu as adapter might not have been initialized by the time onCreateoptionsMenu gets called.
> Fixes NPE in Form List Screen

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
On saving form as incomplete, we end up relaunching the sesssion instance again instead of returning back to the calling application. This can be really confusing if CC was called with a session stack pointing to a form, on saving that form as incomplete, a new intance of the same form gets relaunched automatically. I think the incomplete form save here should follow the same navigation pattern as when we save a complete form. 
Related to: https://dimagi-dev.atlassian.net/browse/MOB-138
> Save as Incomplete Navigation fix for external launch

- app/src/org/commcare/activities/UpdateActivity.java
The new "Require Sync" feature logic was accidentally turned 'on' by default, this reverts it back to being off unless dictated otherwise
> Fix sync condition being default

- app/AndroidManifest.xml
Problem: Starting with Android 9 (API level 28), cleartext support is disabled by default due to which on Android 9 devices, the installation using app code fails due to a security exception - "Cleartext communication to *** not permitted by network security policy."
Solution: Enable cleartext support by default in Manifest.
> Enable cleartext support by default

- app/src/org/commcare/views/widgets/TriggerWidget.java
https://dimagi-dev.atlassian.net/browse/MOB-140
This PR will return an empty string as answer to a label question instead of "OK" text.
> Return empty string as answer instead of OK for a label

- app/src/org/commcare/activities/DispatchActivity.java
- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
- app/src/org/commcare/activities/UpdateActivity.java
- app/src/org/commcare/activities/components/FormEntryConstants.java
- app/src/org/commcare/interfaces/FormSaveCallback.java
- app/src/org/commcare/services/CommCareSessionService.java
- app/src/org/commcare/tasks/SaveToDiskTask.java
- app/src/org/commcare/tasks/templates/CommCareTask.java
Framework for addressing the issues from [MOB-138](https://dimagi-dev.atlassian.net/browse/MOB-138)
External session callouts manipulate the session stack in dangerous ways. This PR extends the "interrupt" mechanism built to capture form entry state when users are logged out due to their session expiring and makes it triggerable from the entry point for external session call-ins.
This should make it possible to safely end and resume a form entry session based on an external intent. It is a future piece of work to do the inverse (make it safe to load a form in CommCare when one is already in progress having been loaded from an intent)
Workflow example:
> Graceful Form Intent Interruption

- app/src/org/commcare/network/CommcareRequestGenerator.java
- app/src/org/commcare/utils/SyncDetailCalculations.java
- app/unit-tests/src/org/commcare/utils/DateUtilTest.java
When performing a sync request, includes the integer days since the last day the device has synced to the URL parameters of the request, ie:
`/a/no-feature-flags/phone/restore/07a82c079ce340a8ae705ef3d66089f7/?device_id=353522096503145&user_id=ce3719da49ef4b4ea8740b2e617ae6b5&days_since_last_sync=34&state=ccsh:ba14c90a2370ecd5778cbdf5d81370ff&version=2.0&items=true&since=2605adb21c2b11eabf720a5180e0c5bc`
The intent here is to allow HQ to create different pooled priorities for rate limiting based on how far behind a user is in syncing data, as such the data needs to be available to the proxy with no downstream processing. 
@shubham1g5 I am thinking that it makes the most sense for me to hotfix this as 2.47.5 as well, otherwise it won't make it out to users fast enough to be usable. Do you …
> Add days since last sync param to sync requests

- app/src/org/commcare/engine/cases/AndroidIndexedFixtureInstanceTreeElement.java
Hotfix version of https://github.com/dimagi/commcare-core/pull/866
Since ICDS plans to release some of the UCR v2 stuff in Feb, we need to include this fix as well in the 2.47 hotfix.
> [HOTFIX] Fixes NPE with UCR v2

- app/src/org/commcare/AppUtils.java
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/UpdateActivity.java
- app/src/org/commcare/utils/SyncDetailCalculations.java
The previous sync calculation was looking for a logged in username which is empty in case of a pre-login update check. This was causing the last sync time to always be 0 (< updateReleaseTime) and was thus resulting in the update install not getting triggered for a ready update even if the user has synced after the update release time.
> Use right username to validate if an update is blocked before login

- app/AndroidManifest.xml
- app/build.gradle
Unfortunately it skipped my mind that 2.47 didn't have Android pie changes. So porting them here to be able to make the release as we can no longer make releases without pie support
Original PR - https://github.com/dimagi/commcare-android/pull/2147
> Port Android Pie changes for LTS

- app/src/org/commcare/views/media/CommCareMediaController.java
- app/src/org/commcare/views/media/CommCareVideoView.java
- app/src/org/commcare/views/media/MediaLayout.java
https://dimagi-dev.atlassian.net/browse/MOB-117
**Problem**: Since The MediaController will create a default set of controls and put them in a window floating above your application., the mediacontroller will not respect parent view's animation or scroll.
**Solution**: Add the mediaController to the view hierarchy to force it always conforms parent view's animation and scroll.
**Extra**: Prevent logging inline video events if the video is never played.
PS: A duplicate of this https://github.com/dimagi/commcare-android/pull/2168, since Jenkins builds gets really messy and produces some weird logs for failure even though there isn't one. 
Product Note: UI improvements for Inline Video
> Fix visibility issue of MediaController while navigation and scrolling

- app/src/org/commcare/activities/components/FormEntryInstanceState.java
- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
Jira: https://dimagi-dev.atlassian.net/browse/ICDS-1264
Issue Repro:
- Install an App and login
- Initiate an update , though don't install it
- Kill CC (to force app re-initialization)
- Open CC again
- Go to a form that's part of the update
- CC Crashes
Explaination: The crash happens when there is an update in progress or there is an update downloaded that’s not been installed and user tries to open a form that’s been updated in the pending update. When a form is installed as part of update, it [creates formDefRecords](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java#L107) into user storage. When an app which has a pending update gets initialized, we loop through forms to find the …
> Fixes form load crash in case of an pending update

- app/src/org/commcare/android/database/app/models/FormDefRecord.java
- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
- app/src/org/commcare/utils/AndroidCommCarePlatform.java
In Continuation to: https://github.com/dimagi/commcare-android/pull/2186
We remove the formDefRecords today from DB while uninstalling a form but don't really remove the particular formid <-> namespace mapping. This causes the code change in the PR above to fail [here](https://github.com/dimagi/commcare-android/blob/commcare_2.47/app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java#L82) as there can be form ids which exists in platform but their respective reports have been deleted.
> Deregisters forms on uninstall

- app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
- app/src/org/commcare/engine/references/JavaHttpReference.java
- app/src/org/commcare/network/RateLimitedException.java
Today when we ecounter a 503 during a resource request during update, we still end up [retrying 4 times](https://github.com/dimagi/commcare-core/blob/master/src/main/java/org/commcare/resources/model/ResourceTable.java#L607) for the same request. 
Getting this in 2.48 to get this fixed sooner for ICDS.
> Disable retries on getting rate limited on individual resource requests

- app/src/org/commcare/utils/PendingCalcs.java
If an organisation has set the new flag "AUTO_SYNC_FREQUENCY" for auto-sync, it should get priority over the old flag "cc-auto-update"
> Changes Sync Pending calculation to give AUTO_SYNC_FREQUENCY priority over cc-auto-update

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/FormEntryActivityUIController.java
- app/src/org/commcare/activities/components/FormRelevancyUpdating.java
- app/src/org/commcare/views/widgets/ImageWidget.java
Fix for: https://dimagi-dev.atlassian.net/browse/SAAS-10659
We will now save the form to disk as soon as there is a change in widgets containing attachments.
> Fix mismatched attachments while editing a saved form 

- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
I didn't see any particular use case of maintaining this var `syncPending` and hence removing it to simplify some code.
> [no op] Removes syncPending 

- app/src/org/commcare/AppUtils.java
- app/src/org/commcare/preferences/HiddenPreferences.java
Jira: https://dimagi-dev.atlassian.net/browse/ICDS-1236
This PR adds an app version tag (`cc-app-version-tag`) defined as a custom app property to the "About CommCare" dialog. 
Product Note: Apps can now define `cc-app-version-tag` as a custom property in app settings to tag a particular app version. This version then become visible in "About CommCare" dialog along with the app version.
> Shows custom App Version Tag in About CommCare

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/FormEntryActivityUIController.java
- app/src/org/commcare/activities/components/FormEntryConstants.java
- app/src/org/commcare/activities/components/FormEntryDialogs.java
https://forum.dimagi.com/t/a-validation-condition-in-the-preview/7333
In case of validation condition on a non-required question, navigation of submitted form gives constraint violation error for validation error
Product Note: Fixes a bug that causes validation errors to appear while navigating saved forms.
> Fix for navigation of saved form

- app/src/org/commcare/views/widgets/GeoPointWidget.java
The feature that lets you see the map while geopoints resolve was broken because it was looking for the old v1 play services element to enable it rather than the new one.
NOTE: This bug is blocking a user workflow on COVID-19 response so I think we should hotfix back into 2.48
> Fix "Choose point on Map" functionality

- app/build.gradle
- build.gradle
Fixes an issue which prevents Fabric API keys present in fabric.properties file from being read by the app. 
Tried using the updated version and the crashes seems to appear just fine in crashlytics with the debug build.
> Update fabric to the latest version

- app/AndroidManifest.xml
[updating fabric]( https://github.com/dimagi/commcare-android/pull/2214) broke the debug builds for me with a crash on application startup - 
`UnmetDependencyException: The Crashlytics build ID is missing.` 
This was only hapening on debug builds and not release due to fabric not properly shutting down fabric based on `ext.enableCrashlytics`
It seems like the [new recommended way](https://stackoverflow.com/a/49836972/3811963) to disable fabric for debug also needs to falsify `firebase_crashlytics_collection_enabled` flag  in manifest. I can confirm that this flag doesn't affect the release builds [here](https://www.fabric.io/dimagi/android/apps/org.commcare.dalvik/issues/f9ee3f15167a7f2bdefb6f49e9bcb97e/sessions/latest) .
> Fabric debug crash - The Crashlytics build ID is missing

- app/src/org/commcare/logging/AndroidLogger.java
Crashlytics provide us a way to add logs to a particular crash report by adding the logs for the particular crash session to the crash report. Adding these device logs to crashlytics will help us in debugging some of the more trickier crashes.
> Assist Crash reports with device logs

- app/src/org/commcare/views/widgets/QuestionWidget.java
If there is a question without label, then `mPrompt.getLongText()` will return null and `builder.append(null);` will cause a NPE.
> Fix NPE while building question label with asterisk

- app/build.gradle
Trying to Speed up the debug builds locally.
> Disable minify, proguard for debug builds

- app/src/org/commcare/heartbeat/UpdatePromptHelper.java
From what I understood, using [this doc](https://confluence.dimagi.com/pages/viewpage.action?spaceKey=ICDS&title=Prompted+Updates), a **FORCED** update should restrict users from using CommCare at all until they update the app. 
Unfortunately, the above flow wasn't happening because of this check `if (!currentSession.apkUpdatePromptWasShown())` which says that if prompt is shown for the current session, then it won't be shown again until user logs out explicitly. So after seeing the popup, if a user kills the app and opens it again, he/she will be able to use the app without any problem. (which is exact opposite of what FORCED update guarantees.) 
There is one catch though, once the prompt is shown, there is no way for a user to get out of it without updating(like not even logout and use …
> Stop users from using app when forced update is required

- app/src/org/commcare/activities/CommCareSetupActivity.java
- app/src/org/commcare/activities/PromptActivity.java
- app/src/org/commcare/activities/PromptApkUpdateActivity.java
Jira: https://dimagi-dev.atlassian.net/browse/SAAS-10748
Using this change, for version mismatch errors, we'll now launch PromptAPKUpdateActivity. 
Product Note: For Version Mismatch errors, CommCare will now launch a new screen with details about the required version and buttons to launch PlayStore to update the app.
> Show PromptAPK activity for version mismatch error

- app/src/org/commcare/fragments/InstallPermissionsFragment.java
Removes the options menu completely when we show the missing permissions fragment. 
The options menu allows for offline installation, which would crash if user has declined storage permissions. 
[StackTrace](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/5ce2e2aaf8b88c2963706428?time=last-seven-days&sessionId=5EB902A003300001382B6A5755CEF623_DNE_0_v2)
> Hide menu options when required permissions are missing

- app/src/org/commcare/activities/FormEntryActivity.java
An attempt to fix [these crashes](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/5c58070df8b88c296399dd45?time=last-seven-days&sessionId=5EB9080901DB00014831E21091E943D1_DNE_0_v2): 
```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@ec645b0 is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
at android.widget.Toast$TN.handleShow(Toast.java:459)
at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
at …
```
> Show form-save-toast before finishing activity

- app/src/org/commcare/activities/FormEntryActivity.java
Adds log statements to provide more information around [these crashes](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/bc08fb56e48a8d482e5c82eb22d6379f?time=last-thirty-days&sessionId=5EB85C23023900017DEED0801F7AA11F_DNE_0_v2)
> Log events when intent.getData returns null and prevent npe

- app/build.gradle
- app/src/org/commcare/CommCareApplication.java
Uses Conscrypt as the security layer for legacy devices to enable support for reasonably secure ciphers
> [hotfix] Introduce Conscrypt security layer for API16-19

- app/src/org/commcare/tasks/SaveToDiskTask.java
The earlier code used to modify the currentFormIndex to loop over all the questions. But if at the same time, some other thread also wants to get hold of the current question in screen, it'll have to use the currentFormIndex which might give wrong value, if this thread has already modified it. And hence may produce NPE in worst cases.
Since, we've to loop over all the questions here, we don't really need to modify the currentFormIndex rather we can simply have another form index to get all the questions. And this will also make sure that the other threads who might be using the currentFormIndex at the same time don't get wrong values.
> Use a separate form index to loop over all questions while saving form

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
- app/src/org/commcare/engine/resource/AndroidResourceManager.java
- app/src/org/commcare/engine/resource/AppInstallStatus.java
- app/src/org/commcare/engine/resource/ResourceInstallUtils.java
- app/src/org/commcare/logging/analytics/UpdateStats.java
- app/src/org/commcare/tasks/UpdateTask.java
* Segregrates update failures to selectively increment update reset counter 
* corrects a bug where `InvalidResourceException` was incorrectly getting logged as `AppInstallStatus.UnknownFailure`
Release Note: Tunes update bheaviour to be more intelligent in resuming update downloads from failures
> [Hotfix] Update resets

- app/build.gradle
- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/network/ForceTLS12BuilderConfig.java
- app/src/org/commcare/network/Tls12SocketFactory.java
- app/unit-tests/src/org/commcare/CommCareTestApplication.java
- app/unit-tests/src/org/commcare/android/tests/activities/CommCareSetupActivityTest.java
For older versions of Android, allow force-enabling TLS 1.2 support
cross-request: https://github.com/dimagi/commcare-core/pull/896
> Permit tls 1.2 on Android 19

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
- app/src/org/commcare/android/resource/installers/OfflineUserRestoreAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/ProfileAndroidInstaller.java
- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
- app/src/org/commcare/engine/resource/AndroidResourceManager.java
- app/src/org/commcare/engine/resource/AppInstallStatus.java
- app/src/org/commcare/engine/resource/ResourceInstallUtils.java
- app/src/org/commcare/logging/analytics/UpdateStats.java
- app/src/org/commcare/update/UpdateHelper.java
- app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.java
Port of https://github.com/dimagi/commcare-android/pull/2244 along with additional error handling -
* Tag parse errors as InvalidResourceException instead of URE
* indentify errors writing incoming resource to a file and throw a `LocalStorageUnavailableException`
cross-request: https://github.com/dimagi/commcare-core/pull/904
> Improvements to Update Error handling

- app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
Logcat shows below error with the current event name. 
```
org.commcare.dalvik.debug E/FA: Name is reserved. Type, name: event, app_install
org.commcare.dalvik.debug E/FA: Invalid public event name. Event will not be logged (FE): app_install
```
> Change APP_install analytics event name

- app/src/org/commcare/network/DataPullResponseFactory.java
- app/src/org/commcare/network/RemoteDataPullResponse.java
- app/src/org/commcare/tasks/DataPullTask.java
A fix for below error: 
```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'end' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:180)
at java.util.zip.Inflater.<init>(Inflater.java:104)
at okio.GzipSource.<init>(GzipSource.java:62)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:103)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at …
```
> Prevent resource leak in datapull response

- app/build.gradle
Defaults to a static version code and sets it from properties only for release builds. 
It seems like setting dynamic manifest properties can have downstream effects on build time. So moving the versionCode computation only for release builds.
> Defaults to a static version code for debug builds

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/activities/CommCareSetupActivity.java
- app/src/org/commcare/engine/resource/AppInstallStatus.java
- app/src/org/commcare/engine/resource/installers/SingleAppInstallation.java
- app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresActivity.java
- app/src/org/commcare/recovery/measures/ExecuteRecoveryMeasuresPresenter.java
- app/src/org/commcare/tasks/ResourceEngineListener.java
- app/src/org/commcare/tasks/ResourceEngineTask.java
- app/unit-tests/src/org/commcare/android/util/TestAppInstaller.java
Jira: https://dimagi-dev.atlassian.net/browse/ICDS-1483
Sentry: https://sentry.io/organizations/dimagi/issues/1216666539/?project=1545828
I don’t have a repro for this issue yet it seems like because of some edge case in state maintenance during install, a case might arise where mobile can incorrectly treat the local location as the remote location and make a request to invalid remote resource locations by infering the http url from the relative local location path for the media. 
For Example,  Mobile seems to be making a request to the url - 
http://cas.commcarehq.org/a/icds-cas/apps/download/c5a8d19d2ebd4ab299444720947f9923/commcare/english/audio/data/bp2/care_of_home.mp3
for a resource which is defined as below in `media_suite.xml` - 
````
<media …
```
> Determines Install Authority based on Profile Reference

- app/build.gradle
The update was causing a crash on app startup [due to this](https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml). Just reverting it right now since it's not worth the time right now to invest in correcting the consumer apps deploy script.
> Reverts firebase-ads to 16.0.1

- app/src/org/commcare/tasks/SaveToDiskTask.java
cross-request: https://github.com/dimagi/commcare-core/pull/908
A fix for this issue: https://dimagi-dev.atlassian.net/browse/QA-1354 caused by [this PR](https://github.com/dimagi/commcare-android/pull/2238). We've changed the SaveToDisk task to use a separate form index to loop over all the questions while saving them. But one of the internal [method call](https://github.com/dimagi/commcare-core/pull/908/files#diff-df805588fd3f80aa4ffb8036e891165aL171) was still using the static formIndex variable in FormModel which was out of bounds causing an NPE.
> Use current form index to check constraints

- app/src/org/commcare/preferences/HiddenPreferences.java
It seems like HQ have different log values [presets](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/static/app_manager/json/commcare-profile-settings.yaml#L32-L39), I had mistakenly [changed these values in 2.48 ](https://github.com/dimagi/commcare-android/pull/2141/files#diff-690b5590c3872f345d2740efb8cc41a5L62) on mobile which would have broke most log submissions on 2.48 on mobile.
> Corrects log setting values

- app/src/org/commcare/heartbeat/HeartbeatRequester.java
This was only getting set currently from the Recovery measures response which is not active for most of the projects. Since we are now using this version info for the udpate prompt's In App Update feature, setting it from the heartbeat response as well so that we have this info set before we prompt for update.
> Set latest CC version from Heartbeat response

- app/src/org/commcare/preferences/HiddenPreferences.java
A last minute fix for https://dimagi-dev.atlassian.net/browse/QA-1359
> Default to current version while getting latestcommcareversion

- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/sync/FormSubmissionHelper.java
[Crash](https://console.firebase.google.com/u/1/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/68ab24bd83e103289e3734a6e8b11dba?time=last-thirty-days&sessionId=5ED64C7800EE000159C6F256D22B44CD_DNE_0_v2)
This happens when somehow the onClick event gets fired after a particular app has been uninstalled. I was able to repro it by rapidly clicking on uninstall after the uninstall dialogue closes for an application. 
This PR adds null safety around cancelling tasks while not compromising with the app being `null` when we schedule a form submission worker.
> NPE fix on cancelling form submission task

- app/AndroidManifest.xml
- app/src/org/commcare/logging/analytics/UpdateStats.java
[Crash](https://console.firebase.google.com/u/1/project/commcare-a57e4/crashlytics/app/android:org.commcare.lts/issues/89eebf691ef96001ffe22811b8033bf6?time=last-thirty-days)
Because of the change we make in 2.48.8 that allows for update resets to happen based on selective errors, the network errors while updates keeps on accumulating in update stats resulting in an OOM crash.
> [2.48.9 LTS Hotifix] OOM protection for writing update stats

- app/src/org/commcare/logging/analytics/UpdateStats.java
removing the writes as well since deserializing a big UpdateStats object can also degrade performance a lot.
> [2.48.9] Removes writes for update install stats

- app/AndroidManifest.xml
[Crash Fix](https://console.firebase.google.com/u/1/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/12e997a8b50eb71f33ec03df4925332a)
This receiver `KujakuNetworkChangeReceiver` starts  `MapboxOfflineDownloaderService` which is giving a lot of crashes. So removing it from here.
> Remove kujaku network change receiver

- app/src/org/commcare/tasks/SaveToDiskTask.java
Fixes side-effect caused by this PR: https://github.com/dimagi/commcare-android/pull/2238. 
When finish button is clicked, and one of the previous questions had a validation error, the form wouldn't go to that failed question, instead it would stay there giving a feeling that the finish button isn't working at all.  
More details here: https://dimagi-dev.atlassian.net/browse/SAAS-11042
> Navigate form to failed question when form finishes

- app/res/values/strings.xml
- app/src/org/commcare/android/database/user/models/FormRecord.java
- app/src/org/commcare/utils/StringUtils.java
This was flagged by the icds team that they want to localize these errors. 
cross-request: https://github.com/dimagi/commcare-core/pull/922
Product Note: Throws an error on saving a form with any of case_name, case_type, owner_id and external_id for a case is greater than 255 chars in length.
> Shows localized error for invalid case property length errors

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/FormRecordListActivity.java
- app/src/org/commcare/android/database/user/models/FormRecord.java
- app/src/org/commcare/models/FormRecordProcessor.java
- app/src/org/commcare/sync/FormSubmissionHelper.java
Earlier Form processing failures was resulting in the form getting saved on phone which used to get quarantined during form submission due to a 422 response to the submission. This PR changes this behaviour to delete such form records as soon as user "finish" the form. 
Product Note: Deletes any erroneous forms on form save by user rather than later quarantining them at the time of form submission.
> Quarantines form records on form processing failures

- app/src/org/commcare/views/widgets/CommCareAudioWidget.java
- app/src/org/commcare/views/widgets/WidgetFactory.java
Product Note:- The audio-record questions will now use CommCare's in-built audio widget by default. And the older UX can still be achieved using `legacy` appearance attribute. The new audio widget won't have the the option to choose audio from file system by default, but it can be achieved using `acquire-or-upload` appearance attribute
> Use in-built audio widget as default to record audio

- app/src/org/commcare/tasks/PurgeStaleArchivedFormsTask.java
[CL Link](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/5b655dc36007d59fcdc38c84?time=last-ninety-days&sessionId=5F0EED230214000118638CE9816680EA_DNE_0_v2)
```
Caused by java.util.NoSuchElementException: No record in table FORMRECORDS for ID 10
at org.commcare.models.database.SqlStorage.getMetaDataFieldForRecord(SqlStorage.java:168)
at org.commcare.tasks.PurgeStaleArchivedFormsTask.getSavedFormsToPurge(PurgeStaleArchivedFormsTask.java:131)
at org.commcare.tasks.PurgeStaleArchivedFormsTask.performArchivedFormPurge(PurgeStaleArchivedFormsTask.java:84)
````
When there are a lot of submitted forms on device, it's possible for the user to delete a form from Saved forms list while [this …
> Not crash when a form record is not found in db during purge

- app/src/org/commcare/activities/LoginActivity.java
https://dimagi-dev.atlassian.net/browse/ICDS-1674
Fixes a bug where Actionable failures were incorrectly getting handled as unknown failures for restore on login screen.
> Handle actionable failures for restore on login screen

- app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
Fix for - 
````
Caused by java.util.NoSuchElementException: No record in table form_def for ID 41
at org.commcare.models.database.SqlStorage.readBytes(SqlStorage.java:458)
at org.commcare.models.database.SqlStorage.read(SqlStorage.java:449)
at org.commcare.android.resource.installers.XFormAndroidInstaller.uninstall(XFormAndroidInstaller.java:129)
at org.commcare.android.resource.installers.XFormAndroidInstaller.uninstall(XFormAndroidInstaller.java:52)
at org.commcare.resources.model.ResourceTable.uninstallResourcesForStatus(ResourceTable.java:877)
at org.commcare.resources.model.ResourceTable.clearUpgrade(ResourceTable.java:852)
````
[CL link](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.lts/issues/5b51ed486007d59fcd2cb39f?time=last-th …
> Don't crash when no form is found in storage while XForm Uninstall

- app/instrumentation-tests/src/org/commcare/CommCareInstrumentationTestApplication.java
- app/instrumentation-tests/src/org/commcare/androidTests/AsyncRestoreTest.java
- app/instrumentation-tests/src/org/commcare/utils/CommCareIdlingResource.kt
- app/instrumentation-tests/src/org/commcare/utils/ProgressIdlingResource.kt
The tests are sometimes failing with `AppNotIdleException`. This PR will add an idling resource to make tests more robust.
> Add idling resource to avoid AppNotIdleExceptions

- app/src/org/commcare/engine/resource/AndroidResourceManager.java
- app/src/org/commcare/engine/resource/AppInstallStatus.java
- app/src/org/commcare/logging/analytics/UpdateStats.java
- Corrects update resumptions to only reset table with specific install codes
- Corrects auto update retries to retry on network failures 
- Clears updateStats anytime we clear upgrade
> [2.49.5 hotfix] Fix Update Resumptions

- app/src/org/commcare/activities/RecoveryActivity.java
[CL](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.lts/issues/c408f602f2c30690c1acda371a4421c1?time=last-ninety-days&sessionId=5F2D51F401D90001244F4B21917F612D_DNE_3_v2)
````
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.commcare.CommCareApp.getAppResourceState()' on a null object reference
at org.commcare.activities.RecoveryActivity.isAppCorrupt(RecoveryActivity.java:236)
at org.commcare.activities.RecoveryActivity.onBackPressed(RecoveryActivity.java:242)
````
Repro -
1. Delete app files from file system
2. launch CommCare
3. Login which should auto-direct to Recovery
4. Make Recovery fail by turning off internet
5. Go to App manager and uninstall the single CommCare app installed 
6. Press …
> Remove recovery activity from backstack on launching app manager

- app/res/values/strings.xml
- app/src/org/commcare/activities/GeoPointMapActivity.java
* Corrects the accuracy check to let the initial location fix go through 
* Don't allow 0,0,0,0 location to be recorded
Produce Notes: 
* Move the maps to user's initial location on start up in case no existing location is set
* Don't allow locatin with values "0.0 0.0 0.0 0.0" to be recorded as a valid location
> [2.49.7 hotfix] Fix to current location for Maps Location Capture

- app/src/org/commcare/activities/FormRecordListActivity.java
[Crashlytics](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.lts/issues/e3110befb09bd58913f9cff4b716f036?time=last-thirty-days&sessionId=5F04A74D038C00010B02783790F45A2E_DNE_0_v2)
Not sure why adapter is `null` in `onPrepareOptionsMenu`. Looks like `onPrepareOptionsMenu` might be getting called out of order but not sure how. I think it's better to show an empty menu which user can possibly correct by going back in menu in these rare cases rather than crashing the app so just putting a null check to solve this.
> null adapter check in menu to avoid NPE

- app/src/org/commcare/activities/UpdateActivity.java
In case an app update is already downloaded and user enters app update screen but doesn't have internet connectivity, we'll show the information of already downloaded update.
> Show downloaded app update info in case of no internet

- app/AndroidManifest.xml
- app/src/org/commcare/engine/resource/AndroidResourceManager.java
Issue: In case `numberOfRestarts` become greater than 15, the long value 17.8^16 overflows and become negative causing the updates to be retried continuously without any delay.
Affects CommCare 2.48.[8-9], prior to this we were resetting the update on every 5 trials causing `numberOfRestarts` to not become greater than 5 ever. 
Also ports https://github.com/dimagi/commcare-android/pull/2219 in 2.48 to fix the debug builds. 
Product Note: Fixes an issue with CommCare 2.48.8 and CommCare 2.48.9 LTS where updates gets retries continuously without any delay.
> [2.48.10 hotfix] Update retry time overflow fix

- app/build.gradle
- build.gradle
This PR updates firebase-crashlytics to latest version. And also removes firebase-core dependency.
As per [docs](https://firebase.google.com/docs/android/setup#available-libraries) firebase-core is no longer a needed dependency.
> Update firebase services dependencies

- app/src/org/commcare/activities/DispatchActivity.java
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
- app/src/org/commcare/heartbeat/UpdatePromptHelper.java
Jira: https://dimagi-dev.atlassian.net/browse/QA-1899
This PR will make sure that the prompt is shown after the login screen and follows the varying frequency custom settings. 
Though, it most probably wouldn't work the first time(since the heartbeat might still be running when we launch the home screen)
> Fix long standing bug with varying update frequency prompt

- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
https://dimagi-dev.atlassian.net/browse/QA-1904
It's a regression of https://github.com/dimagi/commcare-android/pull/2297/files where I am calling `super.uninstall` at a wrong place as we should only remove the associlated XForm files when we remove the corresponding form def entry from the DB.
> Fixes XForm Uninstall

- app/src/org/commcare/activities/UpdateActivity.java
Issue: When user opens up the Update check while a background update is in progress, the update UI fails to transition to update "ready to install" state because of incorrect check on updateStats in case of a success
> fix update completion indicator in case of background update

- app/src/org/commcare/activities/CommCareActivity.java
- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/FormRecordListActivity.java
- app/src/org/commcare/activities/UpdateActivity.java
- app/src/org/commcare/provider/ExternalApiReceiver.java
- app/src/org/commcare/tasks/templates/CommCareTask.java
- app/src/org/commcare/tasks/templates/CommCareTaskConnector.java
- app/src/org/commcare/views/dialogs/DialogController.java
- app/unit-tests/src/org/commcare/activities/DataPullControllerMock.java
- app/unit-tests/src/org/commcare/android/mocks/CommCareTaskConnectorFake.java
https://dimagi-dev.atlassian.net/browse/QA-1893
Because we were using `dialog.show` instead of `dialog.showNow`, it allowed Fragment manager to lazily execute on committed fragment transactions resulting in a state where `dismiss` was called even before the `show` transaction executes resulting in a hanging progress dialog as described in the JIRA linked above. 
This PR changes the `showProgressDialog` to use `dialog.showNow` and then make other supporting changes so that a task only dismisses the progress dialog generated by itself. This is done to avoid incorrect dialog cancellation in case of a task transition. For example in case of sync, if we don't use task specific dialog cancellation the `DataPullTask` new dialog gets cancelled by the concluding `ProcessAndSendTask` dismiss dialog …
> Orphan Progress dialog fix

- app/build.gradle
- app/src/org/commcare/mediadownload/MissingMediaDownloadHelper.kt
- app/src/org/commcare/views/media/MediaLayout.java
- app/unit-tests/src/org/commcare/mediadownload/LazyMediaDownloadTest.kt
- app/unit-tests/src/org/commcare/rules/MainCoroutineRule.kt
* https://dimagi-dev.atlassian.net/browse/QA-1906 - was happening because of a NPE on `mResourceInProgressListener` which was getting set to null on a background thread and later on accessed on UI thread without null check. 
* https://dimagi-dev.atlassian.net/browse/QA-1915 - Error message correction
* Earlier the `recoverResource` which gets fired by both background worker and the foreground download was invoking the UI thread to notify the listener. This logic is now moved to the `downloadResource` which is invoked by foreground download process only to avoid the background worker suspending because of unavailablity of the main thread.
> Lazy Media fixes

- app/res/layout/audio_prototype.xml
Jira: https://dimagi-dev.atlassian.net/browse/QA-1919
With small devices, the `250dp` width of `textView` would push the audio button to the left of the screen(outside of parent `LinearLayout`) causing it to be clipped.
> Fix audio button clipping on small devices

- scripts/browserstack.py
This PR is a temporary workaround for the issue `There is signature mismatch between application APK and test-suite APK. Package org.commcare.dalvik.test does not have a signature matching the target package org.commcare.dalvik. Please fix this, upload your app & test-suite APK and execute the test again` in browserstack.
> Temporarily switch to using apk in browserstack

- app/AndroidManifest.xml
It's really a no-op since both `enabled` and `exported` takes the removed values by default.
> Removes default flags for RefreshToLatestBuildReceiver

- app/src/org/commcare/activities/DataPullController.java
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/tasks/ManageKeyRecordTask.java
- app/unit-tests/src/org/commcare/activities/DataPullControllerMock.java
Jira: https://dimagi-dev.atlassian.net/browse/SUPPORT-4456 (Issue 1)
Repro: 
1. Install App A, Login as user X and set Pin
2. Install App B, Login as same user X and set Pin
3. Uninstall App A (this deleted the User X DB)
4. Login using pin in App B
5. Login fails 
Issue happens because the `DataPullTask` always expects a `password` and [in cases when there is no user in DB for the UKR](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/tasks/ManageKeyRecordTask.java#L121) we were sending a pin as password to the `DataPullTask`
> Fix for login using PIN when no User exists for a UserKeyRecord

- app/src/org/commcare/views/widgets/LabelWidget.java
- app/src/org/commcare/views/widgets/ListMultiWidget.java
- app/src/org/commcare/views/widgets/ListWidget.java
Fixes a bug where changing the form-fonts from the form-entry-preferences, won't have any effects on the texts of these widgets.
> Use flexible font size for label and list widgets

- scripts/browserstack.py
Using this change, we'll now be able to re-run only the failing test classes on browserstack one more time before marking the build as success/failure.
> Add option to re-run failing espresso tests

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/tasks/LogSubmissionTask.java
This PR will break out of log submission loop as soon as we encounter a rate limit error.
> Stop submitting logs if rate limit is reached

- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/DiskUtils.kt
- app/src/org/commcare/activities/components/ImageCaptureProcessing.java
- app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
- app/src/org/commcare/preferences/HiddenPreferences.java
- app/src/org/commcare/tasks/SaveToDiskTask.java
- app/src/org/commcare/utils/StorageUtils.java
- app/src/org/commcare/views/widgets/CleanRawMedia.kt
- app/src/org/commcare/views/widgets/ImageWidget.java
Long term port for [LTS PR](https://github.com/dimagi/commcare-android/pull/2385)
Product Note: CommCare no longer retains original images for a form in order to save disk storage used by CommCare. Smaller sized compressed copies are still retained and shown to the user in "Saved Forms" instead of the original images.
> [2.50.3] Deletes Raw Folder on Form Completion + Free Disk space Analytics

- app/src/org/commcare/activities/FormEntryActivityUIController.java
- app/src/org/commcare/views/widgets/QuestionWidget.java
- app/src/org/commcare/views/widgets/StringWidget.java
Jira: https://dimagi-dev.atlassian.net/browse/SAAS-11370
While working in a question list, when a user enters some text in an edittext and then shifts to a non editText question (like RadioButton or DateWidget), then the last changed editText doesn't clear foucs by itself. 
This results into the screen jumping to this last focused EditText when any change is made to any other question. 
This PR will ask the QuestionWidget to remove focus if it's not the last widget user was interacting with. And only StringWidget will respond to the `removeFocus` call. 
Fixes a bug in the view hierarchy wherein making any change to a question in the questionList will cause the screen to scroll up to the first edittext that has focus.
> Fix form jump issues with edittext

- app/instrumentation-tests/src/org/commcare/androidTests/AppPreferenceSettingsTest.kt
- app/instrumentation-tests/src/org/commcare/androidTests/CaseSharingTest.kt
- app/instrumentation-tests/src/org/commcare/androidTests/MenuTests.kt
- app/instrumentation-tests/src/org/commcare/utils/CustomMatchers.kt
- scripts/browserstack.py
Using auto shard strategy from this doc https://www.browserstack.com/docs/app-automate/espresso/test-sharding
Since we've a limit of 5 parallel tests, so I've configured the `numberOfShards` to 5.
> Optimize android instrumentation test time

- app/src/org/commcare/CommCareApplication.java
Jira: https://dimagi-dev.atlassian.net/browse/QA-2137
https://github.com/dimagi/commcare-android/pull/2409 broke the HTTP requests on Android 4 because I was initializing TLS 2 after adding the ISRG cert. (Took me like 2 days to figure this one line change :( , though happy that our new hotfix QA process caught it)
> Initialize TLS1.2 before adding the isrg cert

- scripts/browserstack.py
Fixes a false positive in test result when number of tests are lower than number of shards and browserstack simply errors out.
> Avoid using 5 shards when number of tests are low

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
In case End of form stack ops fails due to an Xpath error , it crashes the app today. 
Eg - 
````
Caused by: org.javarosa.xpath.XPathException: Cannot evaluate the reference [/true] in the current evaluation context. No default instance has been declared!
at org.javarosa.xpath.expr.XPathPathExpr.evalRaw(XPathPathExpr.java:210)
at org.javarosa.xpath.expr.XPathPathExpr.evalRaw(XPathPathExpr.java:41)
at org.javarosa.xpath.expr.XPathExpression.eval(XPathExpression.java:45)
at org.javarosa.xpath.expr.XPathExpression.eval(XPathExpression.java:24)
at org.commcare.suite.model.StackOperation.isOperationTriggered(StackOperation.java:83)
at org.commcare.session.CommCareSession.createFrame(CommCareSession.java:671)
at org.commcare.session.CommCareSession.processStackOp(CommCareSession.java:652)
at …
```
> Bug Fix: XpathException in End of Form linking crashes CommCare

- app/res/xml/provider_paths.xml
- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/utils/FileUtil.java
- app/src/org/commcare/utils/MarkupUtil.java
Jira Ticket:: https://dimagi-dev.atlassian.net/browse/SAAS-11757
I've added a custom plugin for handling clicks of markdown text. 
While testing it out on Android 10, I found that `ACTION_VIEW` intent won't show the images of external storage.(I modified the paths for the same `<external-path name="external_files" path="." />`). But it would simply show an error in the gallery app `File format isn't supported or file is corrupted`. 
I created an app [here](https://www.commcarehq.org/a/srishti-1/apps/view/e75ca00a7e53385e292049d16c0fa1ac/form/936705e7ee9c4f5bbe77708a795f2b0a/source/#form/total_repeat_count) and only the first question shows the image correctly.
> Fix linking to external files

- app/res/values/themes.xml
Stacktrace: 
```
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
at org.commcare.print.TemplatePrinterActivity.onCreate(TemplatePrinterActivity.java:74)
at android.app.Activity.performCreate(Activity.java:7893)
at android.app.Activity.performCreate(Activity.java:7880)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at …
```
> Fix crash in print activity

- app/src/org/commcare/views/widgets/RecordingFragment.java
This PR will remove the save button from the recording fragment, when it's loaded with a saved recording.
> Hide save button when recorded sound is shown

- app/res/values/strings.xml
- app/src/org/commcare/views/widgets/QuestionWidget.java
Product Note: Attachment oversize warning message will show file size in MBs instead of KBs.
> Improve attachment oversize warning message

- app/src/org/commcare/activities/QueryRequestActivity.java
- app/unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml
- app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
@sravfeyn highlighted that as Web Apps is implementing more case search widgets, it would be a good idea for mobile to skip displaying any widgets it doesn't implement so as not to break searches in case of incompatible input types.
> skip invalid case search prompts

- app/src/org/commcare/views/QuestionsView.java
Fixes an issue caused by https://github.com/dimagi/commcare-android/pull/2417/ where hint text gets hidden always.
> Fix hint text visibility

- app/AndroidManifest.xml
- app/src/org/commcare/activities/EntitySelectSearchUI.java
Jira: https://dimagi-dev.atlassian.net/browse/SUPPORT-8015
This PR fixes a NPE while setting text in searchview after scanning barcode.  
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setText(java.lang.CharSequence)' on a null object reference
at org.commcare.activities.EntitySelectSearchUI.setSearchText(EntitySelectSearchUI.java:124)
at org.commcare.activities.EntitySelectActivity.processBarcodeFetch(EntitySelectActivity.java:642)
at org.commcare.activities.EntitySelectActivity.onActivityResultSessionSafe(EntitySelectActivity.java:574)
at org.commcare.activities.SessionAwareHelper.onActivityResultHelper(SessionAwareHelper.java:49)
at org.commcare.activities.SessionAwareCommCareActivity.onActivityResult(SessionAwareCommCareActi …
```
> Search view fix

- app/src/org/commcare/android/javarosa/IntentCallout.java
Jira https://dimagi-dev.atlassian.net/browse/SAAS-11917
There's an issue with CommCare where we're saving the absolute path to the attachment in the form when the attachment was captured using an external app. 
This PR makes changes this behaviour and sets attachment name in the form def instead of path.
> Store attachment name rather than path in formdef

- app/src/org/commcare/activities/QueryRequestActivity.java
- app/unit-tests/src/org/commcare/android/tests/activities/PostRequestActivityTest.java
1. Before this default values were not getting shown for text intput case prompts on mobile. 
2. Default values for the unsupported prompts were getting passed to search query which was breaking the search. 
cross-request: https://github.com/dimagi/commcare-core/pull/982
> Bug fix: default values are not visibile for free text case prompts

- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/activities/SessionAwareCommCareActivity.java
- app/src/org/commcare/activities/SessionAwareHelper.java
- app/src/org/commcare/activities/SessionAwareListActivity.java
- app/src/org/commcare/activities/SessionAwarePreferenceActivity.java
- app/src/org/commcare/utils/CommCareExceptionHandler.java
- app/src/org/commcare/utils/SessionActivityRegistration.java
- app/src/org/commcare/utils/SessionRegistrationHelper.java
Jira: https://dimagi-dev.atlassian.net/browse/SAAS-11948
`onActivityResultHelper` was calling `SessionActivityRegistration.handleOrListenForSessionExpiration` which was also registering the broadcast receiver, thereby making the activity to register  twice for the same receiver and causing a memory leak.
This PR will seperate the code to register and unregister the broadcast receiver in different methods so that they can be used only in `onResume` and `onPause` of the activity.
> Handle receiver register/unregister calls in onResume and onPause only

- app/src/org/commcare/activities/DrawActivity.java
- app/src/org/commcare/activities/FormEntryActivity.java
Jira: https://dimagi-dev.atlassian.net/browse/SAAS-11641
Some users have reported that they couldn't save the signature. More details on the ticket. 
This PR will add logging to the DrawActivity to grab more information about the issue.
> Add logs to DrawActivity

- Dangerfile
- scripts/run_danger.sh
Added support for Danger https://danger.systems/ruby/
Makes use of `android_lint` plugin to output any lint issues on the PR.
> [SAAS-12009] Add Danger

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/android/javarosa/IntentCallout.java
- app/src/org/commcare/utils/FileUtil.java
- app/unit-tests/src/org/commcare/utils/FileUtilTest.java
Android 11+ Intent RPC requires that files copied between apps uses explicit FileProvider content providers.
This is a proof of concept change which attempts to implement a URI read for files requested if the normal lookup fails. 
Context for a calling app: https://github.com/dimagi/rd-toolkit/pull/40
Release Note:
Fixes failures which could occur in file transfer for binary files returned from Intent Callouts on Android 11+ devices.
> Proof of concept implementation for FileProvider Intent Media copying

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/android/javarosa/IntentCallout.java
- app/src/org/commcare/utils/FileUtil.java
- app/unit-tests/src/org/commcare/utils/FileUtilTest.java
Copies #2460 to commcare_2.51 hotfix. 
Copying the release notes:
Fixes failures which could occur in file transfer for binary files returned from Intent Callouts on Android 11+ devices.
> Backmerge #2460 into hotfix

- app/src/org/commcare/activities/FormRecordListActivity.java
Stack trace 
```
2021-03-22 20:05:04.460 31436-31436/org.commcare.dalvik.debug E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.commcare.dalvik.debug, PID: 31436
java.lang.RuntimeException: Unable to destroy activity {org.commcare.dalvik.debug/org.commcare.activities.FormRecordListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.commcare.adapters.IncompleteFormListAdapter.release()' on a null object reference
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5034)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5063)
at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java …
```
> Fix npe in FormRecordListActivity onDestroy

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/android/javarosa/PollSensorController.java
- app/src/org/commcare/location/CommCareFusedLocationController.kt
- app/src/org/commcare/location/CommCareLocationController.kt
- app/src/org/commcare/location/CommCareProviderLocationController.kt
Fixes an NPE 
```
Fatal Exception: kotlin.KotlinNullPointerException
at org.commcare.location.CommCareFusedLocationController.requestUpdates(CommCareFusedLocationController.java:32)
at org.commcare.location.CommCareFusedLocationController.access$setMCurrentLocation$p(CommCareFusedLocationController.java:10)
at org.commcare.location.CommCareFusedLocationController$start$1.onSuccess(CommCareFusedLocationController.java:48)
at org.commcare.location.CommCareFusedLocationController$start$1.onSuccess(CommCareFusedLocationController.java:10)
at com.google.android.gms.tasks.zzn.run(zzn.java:4)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:216)
at …
```
> Fixes NPE in LocationController

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
Repro:
1. Launch a form using External Launch 
2. Complete and Save the form
3. CommCare should finish itself
4. Open CommCare from the recent apps screen 
After step 4, User is presented with the start screen though the session still remains populated from the stack ops of external launch from step 1. This results in incorrect navigation when the user relaunched CC on step 4
> Clean session before exiting from external launch

- app/src/org/commcare/utils/CommCareUtil.java
**Jira**: https://dimagi-dev.atlassian.net/browse/SAAS-12191
**StackTrace**: 
```
Non-fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
at org.commcare.models.database.SqlStorage.newObject(SqlStorage.java:249)
at org.commcare.models.database.SqlStorage.read(SqlStorage.java:450)
at org.commcare.models.database.SqlStorage.read(SqlStorage.java:43)
at org.commcare.utils.CommCareUtil.loadFixture(CommCareUtil.java:32)
at org.commcare.engine.cases.CaseUtils.purgeCases(CaseUtils.java:93)
at org.commcare.tasks.DataPullTask.doTaskBackgroundHelper(DataPullTask.java:166)
at org.commcare.tasks.DataPullTask.doTaskBackground(DataPullTask.java:139)
at …
```
> Use file backed storage for reading fixture while purging case

- app/instrumentation-tests/src/org/commcare/androidTests/LookupTableTest.kt
- app/instrumentation-tests/src/org/commcare/utils/HQApi.java
- app/instrumentation-tests/src/org/commcare/utils/InputStreamRequestBody.kt
As noted by Amit, the fixture upload api call is failing intermittently with this error on nginx: 
```
[error] 9910#9910: *326082837 client sent invalid chunked body, client: 65.74.184.76, server: www.commcarehq.org, request: ""POST /a/commcare-tests/fixtures/fixapi/ HTTP/1.1"", host: ""www.commcarehq.org""
```
We also noticed that if we retry the upload, it succeeds. 
I'm not really sure about this issue, but it seems like retrofit doesn't know the content-length when the upload starts(although, the network logs suggests that the request has correct `bodySize`, so I might be wrong).
This PR will use the `inputstream#available` method to determine the content length. But since the method doesn't always gives an accurate result, we'll retry the upload call 5 times, before it fails the …
> [SAAS-12119] Fix failures in fixture upload API

- app/src/org/commcare/activities/HomeNavDrawerController.java
https://dimagi-dev.atlassian.net/browse/SC-1494
Somehow the `actionBar.setIcon()` doesn't seem to have an effect with support action bar. So setting the icon by using the `actionBar.setHomeAsUpIndicator`
> [2.51.3 hotfix] Fixes navigation drawer view 

- app/src/org/commcare/views/widgets/RecordingFragment.java
Uses `.mp3` instead of `.mp4` for audios recorded inside commcare.
> Use mp3 codec for audios recorded in commcare

- build.gradle
- commcare-support-library/README.md
- commcare-support-library/build.gradle
- gradle/wrapper/gradle-wrapper.properties
Adds [this plugin](https://github.com/vanniktech/gradle-maven-publish-plugin) to manage upload to Maven Central. 
Followed the usage instructions from [here](https://proandroiddev.com/publishing-your-first-android-library-to-mavencentral-be2c51330b88). This is only locally setup from my computer right now, and next steps would be to set this up on Jenkins. 
There are login credentials for https://oss.sonatype.org/ in the `dimagi_shared` keepass with title `sonatype jira`
> Support Lib Maven Central Changes

- scripts/browserstack.py
The PR marked with `trivial` label will not run android tests. Useful in cases where the changes are too small or are in `ReadMe`
> Skip android tests if PR is trivial

- app/AndroidManifest.xml
**Reason for the change:** 
I was trying to install the release apk, while the debug apk was already installed in the device. And I got this error:
```
➜  adb install release.apk
Performing Streamed Install
adb: failed to install release.apk: Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package org.commcare.dalvik attempting to redeclare permission org.commcare.dalvik.permission.COMMCARE_LOGOUT already owned by org.commcare.dalvik.debug]
```
This PR should fix above error.
> Use applicationId variable for logout permission

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
Fixes a npe with session endpoint error handling
https://dimagi-dev.atlassian.net/browse/QA-3059?focusedCommentId=148906
no coverage
- very minor change in error handling in a specific part of code 
- Tested manually
> NPE fix in error handling for Session Endpoint

- app/src/org/commcare/heartbeat/HeartbeatRequester.java
- app/unit-tests/src/org/commcare/android/tests/HeartbeatAndPromptedUpdateTests.java
Fix for [crash](https://console.firebase.google.com/u/1/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/83958493f023c2da3597b9bb4062c106?time=last-ninety-days&sessionEventKey=60DED19002750001754F3E03A954DA53_1558698498712440908)
Issue would have impacted projects with CC update prompts on in app settings. Crash would have happened after the apk update is finished which is probably the reason we see a limited number of these crashes as one user would have seen this crash at most once for a CC release.
Added a check for the right CC version after parsing the heartbeat response
> bugfix: Latest CC version getting set incorrectly

- app/res/layout/list_gregorian_widget.xml
- app/res/layout/recording_fragment.xml
- app/res/layout/universal_date_widget.xml
Follow up on https://github.com/dimagi/commcare-android/pull/2461#issuecomment-870506640. 
Went over the codebase to look for all the button styles that are defining custom colors and made sure that they work well with the updated colored styles of buttons.
> Ensure button styles doesn't break with custom colors

- app/build.gradle
- app/res/drawable-anydpi/ic_create.xml
- app/res/layout/query_prompt_layout.xml
- app/res/values/themes.xml
- app/src/org/commcare/activities/QueryRequestActivity.java
- app/src/org/commcare/utils/DateRangeUtils.java
- app/unit-tests/resources/commcare-apps/case_search_and_claim/default/app_strings.txt
- app/unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml
- app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
- app/unit-tests/src/org/commcare/utils/DateRangeUtilsTest.java
https://dimagi-dev.atlassian.net/browse/SC-1465
Adds a widget to select a date range in case search
https://www.commcarehq.org/hq/flags/edit/search_claim/
Allows user to search a case property in a date range. 
Clicking edit in the query screen opens up the date picker as shown below - 
HQ changes were merged earlier in https://github.com/dimagi/commcare-hq/pull/29035 
Added test around date conversion utility used for the widget which handles major functionality around the datepicker. Would rely on Manual QA for end to end testing on this as datepicker range is proving to be difficult to test with robolectric. 
Tested locally, would go through manual QA as well,
Impact if any would largely be limited to the apps using the case claim with the daterange widget. To use the datepicker widget …
> Adds daterange picker for case search

- app/assets/graphing/graph.max.js
- app/assets/graphing/graph.min.js
2 commits for 2 issues 
- https://dimagi-dev.atlassian.net/browse/QA-3283?focusedCommentId=156140 In a bubble graph, when we click on a bubble, it expands, and on second click, it collapses to normal state. There is an issue with the update where on clicking the second time, instead of collapsing, the bubble disappears completely. 
The error for the same is: 
```
Error: <circle> attribute r: Expected length, "NaN".
(anonymous) @ d3.js:1211
selection_each @ d3.js:1176
selection_attr @ d3.js:1233
ChartInternal.unexpandCircles @ c3.max.js:9759
mouseout @ c3.max.js:8004
(anonymous) @ c3.max.js:8098
(anonymous) @ d3.js:1526
```
It happens because the `d.index` we expect here https://github.com/dimagi/commcare-android/blob/master/app/assets/graphing/graph.max.js#L75 is undefined. 
When we …
> Graph js fix

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/android/nfc/NfcManager.java
- app/src/org/commcare/android/nfc/NfcWriteActivity.java
https://dimagi-dev.atlassian.net/browse/QA-3294
Changes delimiter to avoid a form save error caused when reading an encrypted payload untagged. The issue happens because of including the null character '/0' in the form. 
Also throws an error when the delimiter is included in the payload itself.
> Nfc delimiter Fix

- app/src/org/commcare/views/widgets/DateTimeWidget.java
Jira: https://dimagi-dev.atlassian.net/browse/SAAS-12035
This PR updates the calendarview height to `WRAP_CONTENT` in the date picker. 
Updated screenshot: 
Fixes an UI issue in date time widget where the last line of calendar wasn't visible fully.
> [SAAS-12035] Fix calendarview UI cut off

- app/AndroidManifest.xml
- app/build.gradle
Reverts https://github.com/dimagi/commcare-android/pull/2456
Reason: 
CommCare is crashing on pre-lollipop devices when user tries to capture a barcode. 
```
Fatal Exception: java.lang.NoClassDefFoundError: android.media.AudioAttributes$Builder
at com.google.zxing.client.android.BeepManager.playBeepSound(BeepManager.java:97)
at com.google.zxing.client.android.BeepManager.playBeepSoundAndVibrate(BeepManager.java:84)
at com.journeyapps.barcodescanner.CaptureManager$1.barcodeResult(CaptureManager.java:80)
at com.journeyapps.barcodescanner.DecoratedBarcodeView$WrappedCallback.barcodeResult(DecoratedBarcodeView.java:50)
at com.journeyapps.barcodescanner.BarcodeView$1.handleMessage(BarcodeView.java:52)
at android.os.Handler.dispatchMessage(Handler.java:98)
at …
```
> Revert zxing library update

- app/res/values/strings.xml
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
[QA-3382](https://dimagi-dev.atlassian.net/browse/QA-3382)
Update exception handling to support https://github.com/dimagi/commcare-core/pull/1026
Also depends on https://github.com/dimagi/commcare-core/pull/1027
Session endpoints
Changes error message for invalid session endpoint links so that it always explains which arguments are missing and which are invalid.
None.
This change has a pretty limited footprint and is in a flagged area of the code.
> Make endpoint args error more user friendly

- app/src/org/commcare/activities/CommCareActivity.java
Fix for NPE crash https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/0eab22845e5c04753d944c94540423b2?time=last-thirty-days&versions=2.52.1%20(464182)&sessionEventKey=6138CA48031E00010D6A09C02D28AADF_1584024537772241884
StackTrace:: 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.MotionEvent.getX()' on a null object reference
at org.commcare.activities.CommCareActivity.isHorizontalSwipe(CommCareActivity.java:825)
at org.commcare.activities.CommCareActivity.onFling(CommCareActivity.java:747)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:745)
at org.commcare.activities.CommCareActivity.dispatchTouchEvent(CommCareActivity.java:736)
at …
```
> Prevent npe for motionEvent in onFling

- app/build.gradle
Removes unused qa beta variant
> remove qa beta flavour 

- app/src/org/commcare/utils/FormUploadUtil.java
- app/src/org/commcare/views/widgets/RecordingFragment.java
In order to support browser playbacks on HQ, we need to shit the audio encoding to AAC. This PR checks if the `he_aac` is available on the device and uses that when so. If not, it falls back to the earlier codec `AMR_NB`. 
This PR also attempts to set the right content types on the files when uploading to HQ. 
Part of this scope of work: https://docs.google.com/document/d/11S0O_PGa90an-7s3fH953eM-OBp1XwvkxuyEpZ6n0AA/edit
Changes the default audio recording codec to `HE_AAC` instead of `AMR_NB`
> Shift audio rec codec to he-aac

- app/src/org/commcare/activities/CommCareActivity.java
[Crash](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/0eab22845e5c04753d944c94540423b2?time=last-ninety-days&sessionEventKey=61DE5C73013800010848A074C6C82659_1630657244017356678)
````
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.MotionEvent.getX()' on a null object reference
at org.commcare.activities.CommCareActivity.isHorizontalSwipe(CommCareActivity.java:825)
at org.commcare.activities.CommCareActivity.onFling(CommCareActivity.java:747)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:812)
````
> NPE fix for motion events

- app/src/org/commcare/views/widgets/MediaWidget.java
Refactors Media widget to modularize the media checks in their own functions.
> No op refactor to modularize mediaWidget

- app/lint.xml
Configure the lint.xml file to disable "Using Log instead of Timber" lint warnings. https://developer.android.com/studio/write/lint#pref
> Disable lint warning for usage of Timber log #trivial

- app/res/layout/screen_permission_request.xml
Adds margin in UI to avoid text getting cut off
> Fixes text cutting off in Key access activity

- app/instrumentation-tests/src/org/commcare/utils/InputStreamRequestBody.kt
- build.gradle
Having some issues with mismatch between Android Studio Kotlin plugin and the one use in gradle scripts. So updating it to latest.
> Kotlin upgrade

- app/instrumentation-tests/src/org/commcare/androidTests/AsyncRestoreTest.java
- app/instrumentation-tests/src/org/commcare/androidTests/CaseClaimTest.java
It seems like sync is taking more time than before on HQ lately causing 60 sec idle timeout to be breached with - `androidx.test.espresso.AppNotIdleException: Looped for 46006 iterations over 60 SECONDS`
> Increase Espresso Idling timeout

- app/src/org/commcare/utils/FormUploadUtil.java
Media Encryption PR broke the mime type handling when uplading the file to server. This PR fixes it by using the non `.aes` filename to deduce the mime type.
> fixes mime type for encrypted files

- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/android/database/global/models/AndroidSharedKeyRecord.java
- app/src/org/commcare/services/CommCareSessionService.java
Couple fixes. 
1. https://github.com/dimagi/commcare-android/commit/3b57a482c81c34c54b6f8068e7d4a9a2dc5bc0a4 to fix
```
E/MethodChannel#io.c4us.sms_forwarder/receiveintent(26449): Failed to handle method call
E/MethodChannel#io.c4us.sms_forwarder/receiveintent(26449): com.android.org.bouncycastle.crypto.DataLengthException: input too large for RSA cipher.
E/MethodChannel#io.c4us.sms_forwarder/receiveintent(26449): 	at com.android.org.bouncycastle.crypto.engines.RSACoreEngine.convertInput(RSACoreEngine.java:117)
E/MethodChannel#io.c4us.sms_forwarder/receiveintent(26449): 	at com.android.org.bouncycastle.crypto.engines.RSABlindedEngine.processBlock(RSABlindedEngine.java:98)
E/MethodChannel#io.c4us.sms_forwarder/receiveintent(26449): 	at …
```
> External callout bug fixes

- app/AndroidManifest.xml
https://dimagi-dev.atlassian.net/browse/SAAS-13334
Callouts to gmaps break on Android 11+ devices due to [package visibility restrictions](https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9) on Android 11
> Fixes interaction with gmaps on Android 11+ devices

- app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Adds `XPathJsonPropertyFunc` from https://github.com/dimagi/commcare-core/pull/1128 to the list of Externalizable classes.
> Adds XPathJsonPropertyFunc to fix test

- .github/dependabot.yml
This PR enables Dependabot version updates. 
- [x ] I have confidence that this PR will not introduce a regression for the reasons below
> Enable Dependabot Version updates

- README.md
- app/AndroidManifest.xml
- app/CommcareAndroidManifest.xml
- app/build.gradle
- app/src/org/commcare/CommCareNoficationManager.java
- app/src/org/commcare/android/nfc/NfcActivity.java
- app/src/org/commcare/services/CommCareSessionService.java
This PR adds support to Android 12 (Android SDK 31). Most of the changes are related to adding the 'exported' attribute to Activities and Receivers and setting the mutability flag of Pending Intents.  
- JIRA ticket: https://dimagi-dev.atlassian.net/browse/SAAS-13635
It passed all 413 Unit Tests and the results of the Instrumentation Tests were satisfactory, the results can be found [here](https://docs.google.com/document/d/14-uYpTs6K0LnLjIPiFVBFwreRwpaNDXw-Mrbs7bYkzw).
> Target android 12

- app/src/org/commcare/CommCareNoficationManager.java
- app/src/org/commcare/views/dialogs/PinnedNotificationWithProgress.java
This PR sets the mutability flag to Pending Intents as [required by applications targeting Android 12](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability).
> Fix mutability flag

- app/AndroidManifest.xml
Considering the restrictions introduced in Android 11 to package visibility, apps have now to register other apps or components from other apps they rely to fulfil some of their requirements. This PR improves CommCare package visibility by adding intent filter signatures for actions SEND and VIEW, making apps with matching capabilities visible to CommCare. 
JIRA tickets: [QA-4487](https://dimagi-dev.atlassian.net/browse/QA-4487) and [QA-4492](https://dimagi-dev.atlassian.net/browse/QA-4492)
> Improve app discoverability

- app/AndroidManifest.xml
This PR is to make the ExternalApiReceiver able to get messages from other apps, one of them being the CommCare Tester App.
JIRA ticket: [QA-4482](https://dimagi-dev.atlassian.net/browse/QA-4482)
> Fix External test app

- app/assets/locales/android_startup_strings.txt
- app/src/org/commcare/activities/CommCareSetupActivity.java
This PR is to resolve a vulnerability that could be exploited to access protected CommCare components. The solution is to check if the source of the intent is CommCare before sharing any data. Note, it doesn't seem necessary to notify the user about when the check fails.
JIRA ticket: [SAAS-13974](https://dimagi-dev.atlassian.net/browse/SAAS-13974)
> Resolve Intent redirection vulnerability

- app/build.gradle
Leak canary is causing the app to crash several times in debug mode due to strict mode violations. I tried updating the dependency to fix these crashes, though it didn't help. I think it's best to remove it for now and add it locally if we are doing any memory leak investigations. 
Only affects debug build.
> remove leak canary due to strict mode violations

- app/src/org/commcare/android/nfc/NfcActivity.java
With Android 12 updates, we marked all Peding Intents immutable, though the nfc pending intent needs to be mutable for Android OS to load tag information in the intent. ([info](https://developer.android.com/guide/topics/connectivity/nfc/advanced-nfc#foreground-dispatch))
Not feasible as it needs additional hardware
Performed all NFC related test cases from [here](https://docs.google.com/spreadsheets/d/1GdbgDbTJbfKQXvBoMzAeyTqygxc9xQkWPC74dNnXPBs/edit#gid=2107518479)  to make sure everything works.
> Fixes Nfc tag always null 

- app/instrumentation-tests/src/org/commcare/androidTests/ApkDependenciesTest.kt
This PR is just to change the method used to install the app for the instrumentation test, instead calling from InstrumentationUtility it's now calling from the parent class which also calls the former but it has additional checks.
> Call installApp from parent class instead of InstrumentationUtility

- app/instrumentation-tests/src/org/commcare/androidTests/LetsEncryptTest.java
- app/instrumentation-tests/src/org/commcare/utils/HQApi.java
- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/activities/InstallFromListActivity.java
- app/src/org/commcare/activities/PostRequestActivity.java
- app/src/org/commcare/activities/QueryRequestActivity.java
- app/src/org/commcare/android/javarosa/AndroidXFormHttpRequester.java
- app/src/org/commcare/android/logging/ForceCloseLogger.java
- app/src/org/commcare/engine/references/JavaHttpReference.java
- app/src/org/commcare/heartbeat/HeartbeatRequester.java
- app/src/org/commcare/interfaces/CommcareRequestEndpoints.java
- app/src/org/commcare/network/CommcareRequestEndpointsMock.java
- app/src/org/commcare/network/CommcareRequestGenerator.java
- app/src/org/commcare/network/GetAndParseActor.java
- app/src/org/commcare/recovery/measures/RecoveryMeasuresRequester.java
- app/src/org/commcare/tasks/ConnectionDiagnosticTask.java
- app/src/org/commcare/tasks/ModernHttpTask.java
- app/src/org/commcare/utils/FormUploadUtil.java
- app/unit-tests/src/org/commcare/CommCareTestApplication.java
- app/unit-tests/src/org/commcare/android/mocks/ModernHttpRequesterMock.java
https://dimagi-dev.atlassian.net/browse/USH-2141
Changes relating to adding query params from a MultiMap to the network requests. 
We have good integration test coverage on all network requests which I am relying to catch any failures on. 
cross-request: https://github.com/dimagi/commcare-core/pull/1151
> Adds support for adding multimap params to network requests

- app/build.gradle
- app/unit-tests/src/org/commcare/CommCareTestApplication.java
- app/unit-tests/src/org/commcare/android/tests/formnav/EndOfFormTest.java
- app/unit-tests/src/org/commcare/android/tests/formsave/FormRecordProcessingTest.java
- app/unit-tests/src/org/commcare/android/tests/processing/XFormUpdateInfoTest.java
- app/unit-tests/src/org/commcare/logging/DataChangeLoggerTest.java
- app/unit-tests/src/org/commcare/recovery/measures/RecoveryMeasuresTest.java
Updates robolectric to 4.8.2 (this also resolves some issues for M1 users in running tests)
commit by commit
> Robolectric 4.8.2

- app/proguard.cfg
- app/src/org/commcare/activities/CommCareActivity.java
1. Since we have changed StackFrameStep.getExtra to thrown [an error](https://github.com/dimagi/commcare-core/blob/formplayer/src/main/java/org/commcare/suite/model/StackFrameStep.java#L167) when multiple extras with same key are present, this ensures that we only save singular value for `LAST_QUERY_STRING` in the stack frame step extras
2.  Adds Proguard config for Guava from [here](https://github.com/google/guava/wiki/UsingProGuardWithGuava)
Changes are motivated from Instrumentation test failures. 
cross-request: https://github.com/dimagi/commcare-core/pull/1163
> ensure singular value for last query string

- README.md
Updated the README in two locations to indicate Java 11 instead of Java 8.
The first is in the Prerequisites section and it a straight-forward change.
The second is in the Common Errors section, but perhaps a larger change is necessary here. There are instructions for upgrading the JCE policy files for JDK 8, but starting with JDK 9 that is apparently no longer necessary. I added text specifying that this fix should no longer apply, but otherwise left the fix in. Would it be better for me to remove the text about the JCE fix entirely?
(none)
Directs user to install Java 11, as the Android build will no longer work with Java 8.
- [x ] I have confidence that this PR will not introduce a regression for the reasons below
No related tests.
Documentation only. No risk of breaking build.
> Updated README to specify Java 11 instead of Java 8.

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/tasks/UnzipTask.java
This PR is to fix a vulnerability that can be exploited to gain unauthorized access to system or even private folders by using ZIP entries with path traversal characters, more info can be found [here](https://support.google.com/faqs/answer/9294009). The fix is basically to check whether each Zip entry path matches the destination folder, if it doesn't, then the decompression process is interrupted.
> Fix Zip path traversal vulnerability

- .github/workflows/commcare-android-pr-workflow.yml
The [Github action for cURL](https://github.com/marketplace/actions/github-action-for-curl) doesn't support MacOS, this PR drops the action and replaces it with a command call.
> Drop Github action for cURL

- app/res/layout/query_prompt_layout.xml
- app/src/org/commcare/activities/QueryRequestActivity.java
- app/src/org/commcare/activities/QueryRequestUiController.kt
- app/unit-tests/resources/commcare-apps/case_search_and_claim/suite.xml
- app/unit-tests/resources/commcare-apps/case_search_and_claim/user_restore.xml
- app/unit-tests/src/org/commcare/android/mocks/ModernHttpRequesterMock.java
- app/unit-tests/src/org/commcare/android/tests/activities/QueryRequestActivityTest.java
Implements `checkbox` input type for `query` prompts 
HQ UI for this is currently feature flagged by `USH_CASE_CLAIM_UPDATES` [See](https://github.com/dimagi/commcare-hq/pull/32290)
PR adds robolectric tests to check for right state of checkbox views. We have [Instrumentation tests](https://github.com/dimagi/commcare-android/blob/master/app/instrumentation-tests/src/org/commcare/androidTests/CaseClaimTest.java) for checking basic navigation on this screen as well. 
Relying on tests and manual testing plus labeled as `QA Note` for QA to do a pass as part of 2.54 release testing
You can use [this app](https://staging.commcarehq.org/a/shubhamgoyaltest/apps/view/200afa70734685b604075e8b721068fa/module/b2e7db65daff4fcaa47cd427b72176c6/#case-detail-screen-config-tab) to see how it's configured …
> Add checkbox support in Case Search

- app/src/org/commcare/CommCareApplication.java
Strict mode crashes is making it impossible today to debug application without crashing. I am disabling it for now and we should turn it back on once we are able to solve for existing violations. 
NA
Only affect debug apk.
> disbaling death on strict mode violations

- app/src/org/commcare/views/widgets/GridWidget.java
Basic fix for [this issue](https://dimagi-dev.atlassian.net/browse/SUPPORT-16630). Essentially, forms will crash if the image for a grid select view is wider in pixels than the native display. 
Release Note:
* Fix for a crash which could occur with compact image selection widgets on small screens with large images
It is specific to an uncommon pattern involving the use of the `compact` attribute on `<select>` and `<select1>` questions with images on the select items, which displays a grid of images to choose from. 
N/A
I think we should consider seeing if we could usefully automate some tests around the image grid selection if we don't have them currently, as the project reporting this issue is quite high-value and high-impact, and they use the 'grid' pattern images in multiple places. …
> Fix for crashes when grid images are wider than the screen

- app/src/org/commcare/activities/CommCareActivity.java
- app/src/org/commcare/preferences/HiddenPreferences.java
This PR addresses an issue raised by the ABDM auditors in which sensitive data could be accessible to attackers in certain parts of the Android OS, such as in the Recent Apps. This PR enables the FLAG_SECURE flag, which enforces security features of the window, this includes blanking the window when the application goes to the background and preventing screenshots.
This feature is behind a CommCare custom property called `cc-enable-secure-flag`
When this flag is enabled, here's what the user sees when they see the app in the Recent apps.
> Enable secure flag

- app/src/org/commcare/views/widgets/RecordingFragment.java
Some users have reported having trouble recording audio, CommCare simple crashes with the following exception being thrown:
```
Fatal Exception: java.lang.IllegalStateException:
at android.media.MediaRecorder.start(MediaRecorder.java)
at org.commcare.views.widgets.RecordingFragment.startRecording(RecordingFragment.java:168)
at org.commcare.views.widgets.RecordingFragment.lambda$prepareButtons$3(RecordingFragment.java:135)
at org.commcare.views.widgets.RecordingFragment.$r8$lambda$_f4gpgcFmBpYAjMTw-zPR52rFnE(RecordingFragment.java)
at org.commcare.views.widgets.RecordingFragment$$InternalSyntheticLambda$0$cc1961f5746e23f7491a3d6e1f5a06d308627bd6d301c3274e25a58d59953a04$1.onClick(RecordingFragment.java:2)
at android.view.View.performClick(View.java:7522)
at …
```
> Set audio recorder sample rate

- app/AndroidManifest.xml
- app/build.gradle
- app/res/values/strings.xml
- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/heartbeat/HeartbeatRequester.java
- app/src/org/commcare/preferences/HiddenPreferences.java
- app/src/org/commcare/services/CommCareFirebaseMessagingService.java
- app/src/org/commcare/utils/FirebaseMessagingUtil.java
This is the first PR related with the implementation of the [Referral Notification feature](https://docs.google.com/document/d/1JRKWF8Pe_LE1cr51UnTPaZPpT2gwgCV_ZAoZqe7jhV8). This part is responsible for the integration of CommCare with Firebase Cloud Message (FCM) as the channel to be used when sending [Push Notifications to CommCare apps](https://docs.google.com/document/d/1m-atLS7gcPRKWWdPd_pW62JLfrW122hAxCkIVurWeyQ). The Push Notifications are supposed to trigger syncs in CommCare, when certain conditions are met, allowing the user access to newly created referrals.
In order to test the service, follow the steps below:
1. Once CommCare is running, Firebase SDK will generate a FCM registration token, if there isn’t one yet, that will be shared with HQ via Heartbeat requests;
1. For …
> Referral Notifications - FCM Push Notifications

- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/LoginActivityUIController.java
- app/src/org/commcare/activities/connect/ConnectIDLoginActivity.java
- app/src/org/commcare/activities/connect/ConnectIDManager.java
- app/src/org/commcare/activities/connect/ConnectIDPasswordVerificationActivity.java
- app/src/org/commcare/activities/connect/ConnectIDPhoneVerificationActivity.java
- app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
- app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
- app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
Adds analytics events for CC connect sign in and recovery attempts. 
Refer to the [doc](https://docs.google.com/document/d/1viwUKgGsVfwaP2fJPMpJr2Ma7ymn9IRVsO3zkjEaCM8/edit) for requirements.
> Connect analytics

- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/activities/EntitySelectActivity.java
- app/src/org/commcare/models/AndroidSessionWrapper.java
- app/src/org/commcare/preferences/DevSessionRestorer.java
- app/src/org/commcare/utils/AndroidInstanceInitializer.java
- app/unit-tests/src/org/commcare/android/database/user/models/SessionStateDescriptorTests.java
- app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Changes for https://github.com/dimagi/commcare-core/pull/1322 
Changes `CommCareSession` to `SessionWrapper` in a few places to align with the [core commit](https://github.com/dimagi/commcare-core/pull/1322/commits/4880a84783e7b1222e02c76b91263e373d70731a)
No functional change
Ensuring through existing tests. 
cross-request: https://github.com/dimagi/commcare-core/pull/1322
> Test fix and API changes 

- app/build.gradle
Remove dependency on conscrypt-android as it's no longer used with us having dropped support for Android 4 devices
No Op
> Remove conscrypt-android

- app/src/org/commcare/activities/DispatchActivity.java
This PR fixes an issue affecting the Reminders app where an already dispatched Session Endpoint request would be resubmitted in subsequent logins.
> Remove dispatched Session Endpoint request

- app/AndroidManifest.xml
- app/assets/locales/android_translatable_strings.txt
- app/build.gradle
- app/src/org/commcare/CommCareNoficationManager.java
- app/src/org/commcare/activities/CommCareWiFiDirectActivity.java
- app/src/org/commcare/activities/FormAndDataSyncer.java
- app/src/org/commcare/activities/RecoveryActivity.java
- app/src/org/commcare/activities/UpdateActivity.java
- app/src/org/commcare/activities/components/EntitySelectCalloutSetup.java
- app/src/org/commcare/activities/components/EntitySelectViewSetup.java
- app/src/org/commcare/activities/components/FormNavigationUI.java
- app/src/org/commcare/gis/DrawingBoundaryActivity.kt
- app/src/org/commcare/logic/FormHierarchyBuilder.java
- app/src/org/commcare/mediadownload/MissingMediaDownloadHelper.kt
- app/src/org/commcare/preferences/AdvancedActionsPreferences.java
- app/src/org/commcare/provider/ExternalApiReceiver.java
- app/src/org/commcare/services/CommCareSessionService.java
- app/src/org/commcare/sync/FormSubmissionWorker.kt
- app/src/org/commcare/tasks/LogSubmissionTask.java
- app/src/org/commcare/update/UpdateHelper.java
- app/src/org/commcare/update/UpdateWorker.kt
- app/src/org/commcare/utils/CommCareUtil.java
- app/src/org/commcare/utils/Permissions.java
- commcare-support-library/build.gradle
- commcare-support-library/src/main/res/layout/activity_main.xml
This PR implements the changes required to support Android 13. The most relevant are:
- Nearby Wi-Fi devices permission - from Android 13, access to devices via Wi-Fi are no longer through the `ACCESS_FINE_LOCATION` permission. Apps that call any of [these Wi-Fi APIs](https://developer.android.com/guide/topics/connectivity/wifi-permissions#check-for-apis-that-require-permission) need to request the `NEARBY_WIFI_PERMISSION`;
- `POST_NOTIFICATION` permission - Google is invested in making sure users' wishes around notifications are respected, this means that users can now very easily revoke permissions around notifications. This motivated changes in places where notifications are triggered to skip them when the permission is not granted; 
- Stop Foreground services - this feature causes the …
> Android 13 update

- app/instrumentation-tests/src/org/commcare/androidTests/BaseTest.kt
- app/instrumentation-tests/src/org/commcare/androidTests/DateWidgetsTests.kt
- commcare-support-library/build.gradle
This PR brings a few changes needed to our Instrumentation Tests to successfully run on Android 13.
> Android 13 Tests Updates

- app/res/values/strings.xml
- app/src/org/commcare/activities/DispatchActivity.java
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/LoginActivityUIController.java
- app/unit-tests/src/org/commcare/android/tests/navigation/ExternalLaunchTests.kt
- app/unit-tests/src/org/commcare/android/util/TestAppInstaller.java
- commcare-support-library/README.md
- commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/CommCareLauncher.java
Adds a way to launch a particular CC app using an intent as - 
````
val intent = Intent("org.commcare.dalvik.action.CommCareSession")
intent.putExtra(DispatchActivity.SESSION_ENDPOINT_APP_ID, appId)
startActivity(intent)
````
commit by commit
coverage for new functionality is in PR, installs and logins have ample tests. 
Tests should cover for any regressions on the dipatch and login pages.
> Intent for launching a specific App In CommCare 

- app/res/navigation/nav_graph_connect.xml
- app/res/values/strings.xml
- app/src/org/commcare/activities/CommCareSetupActivity.java
- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/engine/resource/ResourceInstallUtils.java
- app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
- app/src/org/commcare/fragments/connect/ConnectDownloadingFragment.java
- app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
Implements Download CC App from Connect Fragment
No coverage for Connect UI but all our tests run through normal CC app installs to protect against any regressions. 
Tests and QA
Best reviewed commit by commit.
> Connect: Download CC App 

- app/res/values/strings.xml
- app/src/org/commcare/activities/SettingsHelper.java
- app/src/org/commcare/activities/connect/ConnectIdConstants.java
- app/src/org/commcare/activities/connect/ConnectIdManager.java
- app/src/org/commcare/activities/connect/ConnectIdTask.java
- app/src/org/commcare/activities/connect/ConnectIdVerificationActivity.java
- app/src/org/commcare/utils/BiometricsHelper.java
Added checks for the API level when the user chooses to enroll in a biometric (fingerprint or PIN). When the API is less than 30, there's one additional check to see if it is >=28 and if so the fingerprint enrollment can still be launched. Otherwise, a message is shown to the user indicating that they will need to configure the biometric manually in Android settings, and a button is shown that will take them directly to the Security page in Android settings.
For users with API 28 or 29, a new fingerprint enrollment will now appear. Otherwise, any enrollment with API <30 now exhibits the behavior described above.
New enrollment when user chooses to enroll fingerprint using API 28 or 29:
New message shown when app can't auto-direct user all the way to Android enrollment:
> Improved biometric enrollment for Android versions before API 30

- app/res/layout/screen_connect_verify.xml
- app/res/values/strings.xml
- app/src/org/commcare/activities/connect/ConnectIdVerificationActivity.java
- app/src/org/commcare/activities/connect/ConnectIdVerificationActivityUiController.java
On  some small Android devices, the link to choose password-only workflow in the biometric configuration page would fall off the bottom of the screen, making it unreachable for the user. I removed a couple unnecessary labels and reduced some white space to make the page take up less vertical space, and now everything is visible on the smaller screen size (1080x1920).
The UI now looks like this (screenshot on 1080x1920 device):
> Rearranged UI for biometric configuration to save vertical space

- app/AndroidManifest.xml
There is no reason for us to use different action names depending on the build types as we only expect one CC build type to be installed on a device. The change is prompted by the fact that we don't need to use different intent action while developing locally with CC debug builds. 
Not needed 
Safe as there is no change for release builds
> Use a fixed CC launch action for all CC build types

- app/src/org/commcare/activities/CommCareVerificationActivity.java
- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/fragments/connect/ConnectDownloadingFragment.java
Verifies Connect App after installing it and move to next sceeen only if verification is successful
None
Changes only touch connect screens, CC impact is limited to verification activity which adds a variable `fromConnect` to handle launch from connect but looks like a minimal safe change.
> Connect App verification

- app/src/org/commcare/activities/DispatchActivity.java
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
- app/src/org/commcare/activities/connect/ConnectActivity.java
Shows back button on Connect Workflow Screens plus Home Screen for Connect Launches
None
Home Screen uses the connect launch flag to enable the back screen button to not affect normal CC workflow, other changes are limited to connect
> Enable back button on connect activity

- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/LoginActivityUiController.java
- app/src/org/commcare/activities/connect/ConnectManager.java
This is to address [CCPC-141](https://dimagi-dev.atlassian.net/browse/CCPC-141). Hiding apps that are managed by Connect in the selector on the login page, so there's no way for the user to access those apps from there.
"Apps managed by Connect" are identified as having a stored ConnectLinkedAppRecord with a username equal to the ConnectID username (a long random alphanumeric string).
The code allows the presetAppId to remain in the list (i.e. when launched from Connect), since it needs to be included in order for the traditional login functionality to work.
I also renamed the presetAppID and getter to Id since the linter doesn't like acronyms to be in all caps.
> Not showing apps managed by Connect in LoginActivity selector

- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/connect/ConnectManager.java
Once the user chooses to unlock ConnectID on the login page, we'll go straight to the jobs list instead of back to the login page. This is a user request.
> Going directly to Connect jobs list after user unlocks CID

- app/src/org/commcare/activities/SyncCapableCommCareActivity.java
Step 6 [here](https://dimagi-dev.atlassian.net/browse/CCPC-184), the crash. The error-handling code for rate limiting was calling handleFormUploadResult when it should have called handleFormSendResult. Fixed the error and renamed the latter method to avoid future confusion.
- [x ] I have confidence that this PR will not introduce a regression for the reasons below
> Fixed bug when trying to show rate limiting error message.

- app/src/org/commcare/activities/connect/ConnectManager.java
- app/src/org/commcare/connect/network/ConnectNetworkService.kt
- app/src/org/commcare/connect/network/ConnectNetworkServiceFactory.kt
- app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt
Adds a heartbeat request to connect server that communicates the fcm_token to connect server to be used in push notifications. 
[HQ PR](https://github.com/dimagi/connect-id/pull/7)
None
Changes are isolated to Connect
Tested locally to make sure the request goes through to HQ with a 200 code
> Implements heartbeat for Connect

- app/res/values/strings.xml
- app/src/org/commcare/CommCareNoficationManager.java
- app/src/org/commcare/services/CommCareFirebaseMessagingService.java
Simple change to direct firebase notifications to a new notification channel with default priority (instead of non obstructive min priority for server notifications) 
Small change, almost no-op. Should be tested by QA before release.
> Adds a new notification channel for push notifications

- app/src/org/commcare/utils/SyncDetailCalculations.java
Currently, the minimum frequency for CommCare to warn users that a sync is needed is daily, this PR allows setting time limits shorter than that. The property `Unsynced Time Limit` is expressed in days, so this change makes it possible to pass down a decimal number resulting in frequencies lower than 24 hours, when the value is lower than `1`.
Ticket: https://dimagi.atlassian.net/browse/SC-3223
Unit tests don't cover this logic. I was tempted to add some, but this code lives in a private method so I would need to broaden the scope of the test.
> Allow Unsynced Time Limit to be set in hours

- app/res/layout/screen_connect_message.xml
- app/res/values/strings.xml
- app/src/org/commcare/activities/connect/ConnectConstants.java
- app/src/org/commcare/activities/connect/ConnectIdMessageActivity.java
- app/src/org/commcare/activities/connect/ConnectIdMessageActivityUiController.java
- app/src/org/commcare/activities/connect/ConnectIdWorkflows.java
- app/src/org/commcare/activities/connect/ConnectTask.java
Added functionality for user to change secondary phone during validation warning period. When the user attempts to perform secondary phone validation, a new button is shown with the initial message giving them the option to change the phone number. This additional option is not visible when the same message is shown during recovery (i.e. a user can't change their secondary phone number during recovery).
> Change secondary phone

- app/src/org/commcare/activities/DispatchActivity.java
- app/src/org/commcare/activities/HomeButtons.java
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
- app/src/org/commcare/connect/ConnectManager.java
- app/src/org/commcare/connect/network/ConnectNetworkHelper.java
- app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
- app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
Auto-syncing job status when logging into any app related to Connect.
Redirecting to Learn Progress page (showing learning certificate) when user attempts to login to learn app and ready to transition to delivery.
> Better UX for transitioning from learn to deliver

- app/res/layout-land/home_screen.xml
- app/res/layout/home_screen.xml
- app/src/org/commcare/activities/StandardHomeActivity.java
- app/src/org/commcare/activities/StandardHomeActivityUIController.java
Ticket
https://dimagi.atlassian.net/browse/CCCT-336?atlOrigin=eyJpIjoiNjhkZjE3MjYyYTBiNGVmNWIxY2Y2NjAzNWQyYjA5NmIiLCJwIjoiaiJ9
Combined two sync button of connect id into one
> CCCT-336 combine two sync button to 1

- app/res/values/strings.xml
- app/src/org/commcare/activities/connect/ConnectIdPasswordVerificationActivity.java
- app/src/org/commcare/activities/connect/ConnectIdPhoneVerificationActivity.java
- app/src/org/commcare/activities/connect/ConnectIdPinActivity.java
- app/src/org/commcare/activities/connect/ConnectIdRegistrationActivity.java
- app/src/org/commcare/android/database/global/models/ConnectKeyRecord.java
- app/src/org/commcare/android/database/global/models/ConnectKeyRecordV6.java
- app/src/org/commcare/connect/ConnectDatabaseHelper.java
- app/src/org/commcare/connect/ConnectManager.java
- app/src/org/commcare/connect/network/ApiConnect.java
- app/src/org/commcare/connect/network/ApiConnectId.java
- app/src/org/commcare/connect/network/ConnectNetworkHelper.java
- app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
- app/src/org/commcare/models/database/global/DatabaseGlobalOpenHelper.java
- app/src/org/commcare/models/database/global/GlobalDatabaseUpgrader.java
Several improvements to support having the database passphrase be issues by the ConnectID server, rather than generating a random passphrase locally.
Changes include:
-Not creating the DB until user registers/recovers account
-Deleting DB when forgetting user (and on corrupted DB)
-Retrieving the passphrase and rekeying the DB for existing users
-Supporting background network calls (with concurrent calls allowed)
> Connect DB passphrase managed by ConnectID server

- app/src/org/commcare/engine/resource/AndroidResourceManager.java
https://dimagi.atlassian.net/browse/SC-3427
Logs update failures to get more insight while debugging update resets
None
Not needed
Just adds a null safe simple log statement
> Logs update failures to get more insight while debugging update resets

- app/src/org/commcare/CommCareApplication.java
RxJava 2.x brought changes to the way Throwable errors are handled, causing them to not be swallowed. This means that when any exception that is not being handled occurs, RxJava now bubbles it up through the current thread's uncaught exception handler, which causes CommCare to crash. This PR overrides RxJava Global error handler to offer a more controlled behaviour.  
This is only to swallow RxJava RequestAbandonedException exceptions, other exceptions should continue being handled the same way.
> Override RxJava Global Error Handler

- app/src/org/commcare/activities/HomeNavDrawerController.java
The current logic doesn't consider the `Training` menu item causing the creation of an extra item, which is `null` and when pressed causes CommCare to crash.
Custom property `cc-use-root-menu-as-home-screen`
> Fix the number of Nav drawer items 

- app/src/org/commcare/CommCareApplication.java
This PR fixes an issue that is causing the `app_id` in the response body of the Recovery Measures GET request to be `null`. 
```
{
"latest_apk_version": "2.53.1",
"latest_ccz_version": 127,
"app_id": null,
"recovery_measures": [
{
"sequence_number": 9,
"type": "app_reinstall_and_update",
"app_version_min": 128,
"app_version_max": 131
}
]
}
```
In CommCareHQ, the `app_id` is added to the [response body from the GET request itself](https://github.com/dimagi/commcare-hq/blob/33fc0df006a54e57bfe23a204155dd5a8d5ea33a/corehq/apps/ota/views.py#L485), from a query param, and because the existing logic that builds HTTP requests for requests that don't need authentication is ignoring any params that have been passed, the `app_id` is not part of the request, causing it to be `null` in the response …
> Pass query params to HTTP requests that don't require authentication

- app/AndroidManifest.xml
Adds common Android apps packages CC may depend on for [App depndency](https://dimagi.atlassian.net/wiki/spaces/GS/pages/2374238277/Set+Android+app+dependencies+that+must+be+installed+before+using+a+CommCare+app).
NA
No business logic change. A build pass should confirm the safety here.
> Apk dependencies additions

- app/src/org/commcare/activities/InstallFromListActivity.java
- app/src/org/commcare/activities/PostRequestActivity.java
- app/src/org/commcare/activities/QueryRequestActivity.java
- app/src/org/commcare/network/GetAndParseActor.java
- app/src/org/commcare/tasks/ModernHttpTask.java
Attempts to safely retrieve the x-api-current-version header from API response payloads so calling code can do version checking.
https://dimagi.atlassian.net/browse/CCCT-239
cross-request: https://github.com/dimagi/commcare-core/pull/1409
> Providing API version header from server to caller when available.

- app/src/org/commcare/CommCareNoficationManager.java
- app/src/org/commcare/services/CommCareSessionService.java
- app/src/org/commcare/sync/ExternalDataUpdateHelper.java
- app/src/org/commcare/sync/FirebaseMessagingDataSyncer.java
[Fix for Crash](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/fafe874f6870be2706f26d75856dd3ce)
````
Attempt to read from field 'java.lang.String com.transsion.griffin.lib.app.AppInfo.processName' on a null object reference in method 'boolean b.c.b(java.lang.String)'
at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
at android.os.Parcel.createException(Parcel.java:2410)
at android.os.Parcel.readException(Parcel.java:2393)
at android.os.Parcel.readException(Parcel.java:2335)
at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:6273)
at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1198)
at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:479)
at …
```
> Safeguard sendBroadcast calls to not crash

- app/build.gradle
- app/src/org/commcare/CommCareApplication.java
Fix NPE when logging memory when there are no app processes running. Here's the stacktrace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
at org.commcare.CommCareApplication.logMemoryInfo(CommCareApplication.java:1299)
at org.commcare.CommCareApplication.onStateChanged(CommCareApplication.java:1247)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:290)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:308)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
at …
```
> Fix NPE when logging app process memory info 

- app/res/xml/main_preferences.xml
- app/res/xml/preferences_developer.xml
- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/preferences/DeveloperPreferences.java
- app/src/org/commcare/preferences/MainConfigurablePreferences.java
Allow all users to manually configure form autosaving.
Shift the location of autosave from a developer preference into a user facing preference, to allow all users to access.
This both will make it easier to access, and allow configuration of this setting by any end user until this feature is the default. This is more appropriate for this feature because unlike other developer settings, which are only relevant in tandem with the program or administrator, this setting could positively impact a user based on their specific device or usage profile.
This is a pre-release feature, I have tested this change locally, and this code area has minimal surface area.
> Move autosave preference from developer options to user settings

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/services/CommCareSessionService.java
Adds logging when a form session recovery was triggered. 
Logging only change, tested locally and confirmed appropriate conditions are logged / not logged
> Add logging when session recovery is identified

- app/src/org/commcare/activities/FormEntryActivity.java
https://dimagi.atlassian.net/browse/QA-6984
Bug Fix: If user switches app while working on a form and then come back, exits the form (By clicking on either "Exit without Saving" or "Save Incomplete") and logout. On logging in again, user is redirected again to the form they were working on.
Using method calls already used in other places to clear the state, small changes. Locally tested that the feature doesn't break due to this.
> Clear state on user exiting/saving the form

- app/src/org/commcare/activities/FormRecordListActivity.java
There are some edge cases when local processing errors while form processing are not necessarily due to bad form xml and can be recoverable. As such, this PR makes a change to show the button to "Add Record Back to Unsent Queue" for all quarantined forms. 
Think long term we can potentially categorize the error modes here better (bad form payload vs all others) and hide this button only for errors related to bad form payload. 
Very small surface area for the change, tested locally.
> Show button to "Add Record Back to Unsent Queue" for forms quarantined even due to local processing errors

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/logic/AndroidFormController.java
- app/src/org/commcare/preferences/HiddenPreferences.java
This is to remove some unused methods and outdated comments. In addition to that, a small change to when the stored form index is cleared, this is now at the top of the [handledFormLoadCompletion(...)](https://github.com/dimagi/commcare-android/blob/755913bfaf583c2960c36bf5d5de1d457c2d7c71/app/src/org/commcare/activities/FormEntryActivity.java#L1124) method for visibility.
> Minor cleanup after adding InterruptedFormState model

- app/src/org/commcare/activities/connect/ConnectActivity.java
Solved notification redirection issue for inactive learn/delivery notification
https://dimagi.atlassian.net/browse/QA-6911
> QA-6911 || User Redirection Issue

- app/src/org/commcare/activities/CommCareSetupActivity.java
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/LoginActivityUiController.java
- app/src/org/commcare/android/database/connect/models/ConnectLinkedAppRecord.java
- app/src/org/commcare/android/database/connect/models/ConnectLinkedAppRecordV8.java
- app/src/org/commcare/connect/ConnectDatabaseHelper.java
- app/src/org/commcare/connect/ConnectManager.java
- app/src/org/commcare/connect/network/ConnectSsoHelper.java
- app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt
- app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
- app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
- app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
- app/src/org/commcare/models/database/connect/ConnectDatabaseUpgrader.java
- app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
- app/src/org/commcare/utils/CrashUtil.java
- app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Changed code so when logging into a Connect app for the first time, a random DB passphrase is no longer generated locally. Instead, the standard HQ login call is made (using token auth instead of password), and the returned server-managed DB passphrase is used for encrypting the app database.
Note that a random local password is still generated to encrypt the DB passphrase so it can be stored in the unencrypted global database.
> UKRs managed by server for Connect apps

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/views/widgets/CommCareAudioWidget.java
- app/src/org/commcare/views/widgets/MediaWidget.java
- app/src/org/commcare/views/widgets/RecordingFragment.java
Some users reported crashes during long audio recordings, more concretely when starting or stopping a recording. From the crash reports, we could see that these are related with what seems to be OS runtime errors, probably related to the allocation of the microphone or its state, here are some examples:
```
Fatal Exception: java.lang.IllegalStateException:
at android.media.MediaRecorder.native_start(MediaRecorder.java)
at android.media.MediaRecorder.start(MediaRecorder.java:1409)
at org.commcare.views.widgets.RecordingFragment.startRecording(RecordingFragment.java:171)
at org.commcare.views.widgets.RecordingFragment.lambda$prepareButtons$3(RecordingFragment.java:138)
at org.commcare.views.widgets.RecordingFragment.$r8$lambda$_f4gpgcFmBpYAjMTw-zPR52rFnE(RecordingFragment.java)
at …
```
> Improve logging around audio recording events

- app/build.gradle
- app/instrumentation-tests/src/org/commcare/androidTests/InstallFromListTest.kt
- app/instrumentation-tests/src/org/commcare/utils/HQApi.java
Our release `BuildConfig` class contains test credentials that are used by instrumentation tests. This PR makes these credentials only available to the Instrumentation tests `BuildConfig` class. 
After this change, here are the fields available in the release `BuildConfig` class
```
.field public static final ANALYTICS_TRACKING_ID_DEV:Ljava/lang/String; = ""
.field public static final ANALYTICS_TRACKING_ID_LIVE:Ljava/lang/String; = ""
.field public static final APPLICATION_ID:Ljava/lang/String; = "org.commcare.dalvik"
.field public static final BUILD_DATE:Ljava/lang/String; = "2024-08-13"
.field public static final BUILD_NUMBER:Ljava/lang/String; = "..."
.field public static final BUILD_TYPE:Ljava/lang/String; = "release"
.field public static final CCC_HOST:Ljava/lang/String; = …
```
> Remove test credentials from release build

- app/src/org/commcare/android/database/global/models/ConnectKeyRecord.java
- app/src/org/commcare/models/database/global/DatabaseGlobalOpenHelper.java
- app/src/org/commcare/models/database/global/GlobalDatabaseUpgrader.java
- app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
This PR is to copy Global DB changes that were done as part of the CCC work. The goal with bringing these changes is to ensure a healthy update from that version to production. Changes included here are:
- Addition of table to global DB for storing ConnectKeyRecords (changed DB version to 6)
I believe this is safe as we are only adding a new table to the Global DB that is used by CCC. 
cross-request: https://github.com/dimagi/commcare-core/pull/1416
> Copy CCC Global database changes - Version 6

- app/src/org/commcare/activities/HomeButtons.java
- app/src/org/commcare/services/CommCareSessionService.java
- Handles SessionExpiration in the home button view setup, this escapes the default session expiration and causes the app to crash when resuming after a session expiration event.  Other buttons already have this safety implemented and sync was the only one remaining. 
- Adds some helpful logs around session expiration
> Fixes Crash on App Resume after Session Expiration + Logs

- app/src/org/commcare/android/database/global/models/ConnectKeyRecord.java
- app/src/org/commcare/android/database/global/models/ConnectKeyRecordV6.java
- app/src/org/commcare/models/database/global/DatabaseGlobalOpenHelper.java
- app/src/org/commcare/models/database/global/GlobalDatabaseUpgrader.java
- app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
This PR is to copy Global DB changes that were done as part of the CCC work. The goal with bringing these changes is to ensure a healthy update from that version to production. Changes included here are:
- Added is_local column to ConnectKeyRecord table in global DB
These changes have already been released in the beta stream, the risk is in the update itself and there are plans to test that update before releasing this to production users.
> Copy connect v7 global database upgrades

- app/build.gradle
Makes test credentials available for debug builds to fix "Build->Make Project" which otherwise fails with no field found for `HQ_API_USERNAME` and `HQ_API_PASSWORD`
Build Only change
> Fixes AS make project Function

- app/res/values/dimens.xml
- app/src/org/commcare/adapters/MenuAdapter.java
https://dimagi.atlassian.net/browse/SC-3315
Custom Icon Badges for modules and forms 
Correctly display an overflow of text for Badge View. 
Feature has coverage around normal use case in MenuBadgeTests without testing for overflow of characters. I can add it but feels like an overdo for a small thing. Happy to reconsider. 
tested locally.
> Badge size to correctly display Overflow of characters

- app/src/org/commcare/CommCareApplication.java
This PR adjusts the `onTrimMemory` level options that trigger an output of the state of the memory. There is a level that haven been consistently seen before app kills and with this change we expect to get a better sense of how low the available memory can get before the low memory killer is triggered.
> Print memory info for critical level

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/preferences/HiddenPreferences.java
This is a potential fix for some of the issues we are seeing where user gets restored to a saved session state even after saving the form as complete. Today [we clear this state after the Form Saved ](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/activities/FormEntryActivity.java#L1237) async task has been finished successfully but that may cause issues in scenarios when the activity get deattached from the async task itself.
I have not been able to reproduce these issues but the change is harmless and would love to see if that fixes the issue for users.  If not, also added some helpful logs to get more info on if we are managing the interrupted state correctly. 
Small code change with all code pathways already in usage
> Potential fix for incorrect session recovery

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/FormEntryActivityUIController.java
Makes 2 changes in context of completed/read only forms -
1. Do not allow re-saving completed forms 
2. Reword Form's "FINISH" button to say "EXIT" for completed forms
Tested locally and verified that we are able to save non-completed forms as usual.
> Do not save read only forms

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
This PR adds temporary logging around the Form Entry initiation, this is to help troubleshooting an issue with re-submitting a previously saved session state by the auto-save feature.
> Add extra logging during form entry start

- app/build.gradle
Upgrading the Google maps SDK from version 17.0.0 to 19.0.0
https://github.com/dimagi/commcare-android/issues/2821
- PR may introduce a regression for the reasons below.
- The map should work fine and similar to what it was working before this version upgrade.
- Testing should cover each areas like Registration form, Followup form, etc.
- Attaching an SS of testing of map in follow up form testing from my end:
**QA Note**: Test maps related functionality
> Google map SDK version upgrade from 17.0.0 to 19.0.0

- app/src/org/commcare/CommCareApplication.java
This is to remove extra logging information related to memory, battery and app events added during the GD investigation.
> Remove GD extra logging 

- app/src/org/commcare/heartbeat/HeartbeatWorker.kt
- app/src/org/commcare/update/UpdateHelper.java
- app/src/org/commcare/update/UpdateWorker.kt
- app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.kt
- app/unit-tests/src/org/commcare/update/UpdateWorkerTest.kt
https://dimagi.atlassian.net/browse/SC-3923
Bug Fix for App updates. 
Background updates were failing due to SessionNotAvailable exception due to us unneccesarily checking for user session being active in the Update Worker. This PR makes 2 important changes to eliminate this - 
1. Remove the check for user session from UpdateWrapper, we already perform user updates outside user sessions. 
2. If the error is caused by the wrapper code in UpdateWorker, we can simply result a task failure instead of handling it as an update code error and resetting the update downloads. 
Covered in [UpdateWorkerTests](https://github.com/dimagi/commcare-android/blob/master/app/unit-tests/src/org/commcare/update/UpdateWorkerTest.kt)
Mostly relying on tests coverage here plus the change not affecting any …
> Fixes a bug causing Updates to get stale

- README.md
Documentation update to point new developers to the README for setting up HQ.
> Add end to end dev guide to README

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/FormRecordListActivity.java
- app/src/org/commcare/tasks/SaveToDiskTask.java
Errors that occur when saving the forms to disk are categorized under a single umbrella status [SAVE_ERROR](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/tasks/SaveToDiskTask.java#L60), which causes forms to be quarantined due to [LOCAL_PROCESSING_ERROR](https://github.com/dimagi/commcare-android/blob/7b57114e32f2e5a878b73eebb47546179abbea3c/app/src/org/commcare/android/database/user/models/FormRecord.java#L106) motive, which in turn prevents forms from being sent back to the queue for reprocessing. This PR adds a new `SaveStatus`, `SAVE_UNRECOVERABLE_ERROR`, to be used when quarantining forms due to malformed or corrupted form XML, leaving `SAVE_ERROR` to any other errors that are deemed recoverable. These forms are …
> Quarantine forms due to malformed xml as unrecoverable

- app/res/layout/fragment_phone_available_bottom_sheet.xml
- app/res/layout/screen_connect_message.xml
- app/res/layout/screen_connect_phone_verify.xml
- app/res/layout/select_install_mode_fragment.xml
- app/res/navigation/nav_graph_connectid.xml
- app/res/values-fr/strings.xml
- app/res/values-pt/strings.xml
- app/res/values/strings.xml
- app/res/values/themes.xml
- app/src/org/commcare/activities/connect/ConnectIdActivity.java
- app/src/org/commcare/connect/ConnectConstants.java
- app/src/org/commcare/connect/network/ApiConnectId.java
- app/src/org/commcare/fragments/connectId/ConnectIDSecondaryPhoneNumber.java
- app/src/org/commcare/fragments/connectId/ConnectIDSignupFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdMessageFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdPasswordVerificationFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdPhoneAvailableBottomSheet.java
- app/src/org/commcare/fragments/connectId/ConnectIdPhoneFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdPhoneVerificationFragmnet.java
- app/src/org/commcare/fragments/connectId/ConnectIdPinFragment.java
https://dimagi.atlassian.net/browse/CCCT-483
> CCCT-483 || User Deactivate Flow (New Revamp)

- app/res/navigation/nav_graph_connect.xml
- app/src/org/commcare/adapters/ConnectJobAdapter.java
- app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
- app/src/org/commcare/fragments/connect/ConnectDeliveryProgressDeliveryFragment.java
- app/src/org/commcare/fragments/connect/ConnectDownloadingFragment.java
- app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
- app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
We no longer ever want to go to the learn/deliver progress page after downloading the corresponding learn/deliver app, and should always immediately launch and auto-login to the app. This PR removes the functionality that supported going to the progress pages.
> Always launching learn/deliver app immediately after downloading

- README.md
- app/build.gradle
- app/proguard-multidex.pro
- app/src/org/commcare/CommCareApplication.java
Since the min SDK is 21, it is no longer necessary to use the Multidex library.
See the following for more info: https://developer.android.com/build/multidex#mdex-on-l
> Remove Multidex usages

- app/instrumentation-tests/src/org/commcare/androidTests/DateWidgetsTests.kt
Temporary removing `DateWidgetTest` due to consistent timezone related to failures.
> Muting DateWidgetTest due to failures

- app/src/org/commcare/activities/FormEntryActivity.java
This PR fixes an issue when unregistering the Pending Sync alerts receiver, it seems that for some reason the registration of the receiver failed. Here's the stacktrace:
```
Fatal Exception: java.lang.RuntimeException: Unable to pause activity {org.commcare.dalvik/org.commcare.activities.FormEntryActivity}: java.lang.IllegalArgumentException: Receiver not registered: org.commcare.services.PendingSyncAlertBroadcastReceiver@3592b8b
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5266)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5217)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5168)
at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
at …
```
> Fix an issue when unregistering Pending Sync Alerts receiver

- app/src/org/commcare/adapters/EntityListAdapter.java
https://dimagi.atlassian.net/browse/SUPPORT-22243
Bug fix: Fixes form navigation error due to multiple search callout extras 
Repro:
1. Use case search list callout to search and filter the case list
2. Make a case selection to enter into a form
3. Exit the form without saving and go back to the case list
4. Select the case again from filtered case list and go into the form again
5. Form errors with an error -"_Multiple Extras found with key entity-list-data_"
On making a case selection from the case list filtered with a callout, we [add an extra](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/adapters/EntityListAdapter.java#L432) called `entity-list-data` to the top frame step. On re-selecting the case from case list, this extra ends up getting added again to …
> Fixes form navigation error due to multiple search callout extras 

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/interfaces/FormSaveCallback.java
- app/src/org/commcare/interfaces/FormSavedListener.java
- app/src/org/commcare/logic/AndroidFormController.java
- app/src/org/commcare/models/AndroidSessionWrapper.java
- app/src/org/commcare/models/database/InterruptedFormState.java
- app/src/org/commcare/services/CommCareSessionService.java
- app/src/org/commcare/tasks/FormLoaderTask.java
- app/src/org/commcare/tasks/SaveToDiskTask.java
Copy of https://github.com/dimagi/commcare-android/pull/2851
cross-request: cross-request: https://github.com/dimagi/commcare-core/pull/1437
> Adjust user messages around the Session Pause feature

- app/src/org/commcare/views/widgets/RecordingFragment.java
This PR removes logic used to assess the status of the microphone after a recording configuration change on Android 9 and earlier versions. While this logic passed previous rounds of QA, there are instances in which it unexpectedly pauses the recording at the beginning  of the beginning.
Ticket: https://dimagi.atlassian.net/browse/SAAS-15417?focusedCommentId=341302
Note: I park this an issue for future investigation.
No need.
> Remove microphone status check for Android 9 and lower

- app/src/org/commcare/android/database/user/models/FormRecord.java
`InvalidStateException` is thrown when reparsing a saved form and there are errors/inconsistencies with the form XML. This PR makes the original exception to bubble up and with it the original stack-trace, this is to improve future troubleshooting efforts.
Ticket: https://dimagi.atlassian.net/browse/SAAS-15947?focusedCommentId=346141
No need.
> Include original exception in wrapper InvalidStateException

- app/src/org/commcare/preferences/DeveloperPreferences.java
This PR corrects a minor issue when removing the custom log submission URL. After removing the preference, there shouldn't be any editing as it will add the preference again.
No need
> Don't recreate preference when blanking custom URL

- app/src/org/commcare/models/database/user/models/CommCareEntityStorageCache.java
There is no 1 MB limitaion on data we can can query in sql queries, the only limitaion is that a single sql row can't be more than 1 mb
NA
No code changes
> Remove misleading comment reg. 1 MB Sql Limitation

- app/src/org/commcare/activities/components/ImageCaptureProcessing.java
> logs exceptions encountered while saving image

- .github/workflows/linter.yml
Run lint check only on the changed files to reduce the noise.
NA
Tooling change
> Lint only changed files in the PR

- app/src/org/commcare/activities/CommCareGraphActivity.java
- app/src/org/commcare/android/javarosa/IntentCallout.java
- app/src/org/commcare/appupdate/CommcareFlexibleAppUpdateManager.java
- app/src/org/commcare/graph/view/GraphView.java
- app/src/org/commcare/preferences/HiddenPreferences.java
- app/src/org/commcare/tasks/DataPullTask.java
- app/src/org/commcare/tasks/LogSubmissionTask.java
- app/src/org/commcare/utils/FormUploadUtil.java
Cleaning some not so useful logs which makes up for almost half of the log entries in sumologic in hopes to reduce our sumo usage by a good factor. 
NA
Logs only
> Removes some logs which are killing our sumo usage

- gradle.properties
Enables [configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) for build performance
NA
Only affects project building.
Tried and tested on my end to make sure nothing breaks in our project setup
> enable gradle configuration cache

- app/build.gradle
Updates work manager, test libs and desugaring lib
We have some unit test coverage for [Updates worker](https://github.com/dimagi/commcare-android/blob/master/app/unit-tests/src/org/commcare/update/UpdateWorkerTest.kt)
Test and desugaring libs should not affect anything runtime
Work Manager update will get tested during auto updates test as part of Manual QA tests
> Update test libs and work manager

- app/src/org/commcare/logging/AndroidLogger.java
- app/src/org/commcare/logging/PreInitLogger.java
- app/src/org/commcare/tasks/templates/CommCareTask.java
Reports all non fatals to Firebase Crashlytics
NA
Minor logs handling. 
cross-request: https://github.com/dimagi/commcare-core/pull/1453
> Report all non fatals to firebase

- app/build.gradle
After the JCenter sunsetting we had to exclude some group dependencies from _Kujaku_ as they were not resolving, and we added the dependecies `aars` and `jars` to the project structure. It seems that we missed one, ReLinker, a native libraries loader used by Mapbox SDK, causing CommCare to crash whenever a feature that uses that SDK is used. This PR adds that to the project.
Here's a stackstrace of one of the crashes:
```
FATAL EXCEPTION: main
Process: org.commcare.dalvik, PID: 14448
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/getkeepsafe/relinker/ReLinker;
at io.realm.internal.RealmCore.loadLibrary(SourceFile:60)
at io.realm.Realm.init(SourceFile:247)
at io.ona.kujaku.data.realm.RealmDatabase.<init>(SourceFile:34)
at …
```
> Fix Mapbox SDK dependency issue

- app/src/org/commcare/activities/HomeButtons.java
- app/src/org/commcare/activities/StandardHomeActivityUIController.java
- app/src/org/commcare/connect/ConnectManager.java
https://dimagi.atlassian.net/browse/CCCT-567
> CCCT-567 || Home Screen UI Fixes

- app/res/navigation/nav_graph_connectid.xml
- app/src/org/commcare/fragments/connectId/ConnectIdMessageFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdUserDeactivateOTPVerificationFragment.java
- app/src/org/commcare/logging/AndroidLogger.java
- app/src/org/commcare/logging/PreInitLogger.java
Secondary phone redirection issue and deactivate account issue
[](https://dimagi.atlassian.net/browse/QA-7325)
> QA_7325- secondry phone issue

- app/res/layout/progress_dialog_cancel_button.xml
This PR reverts a change that appears to have been made by mistake during the UI revamping work, which caused a `Stop` button to be visible during app installations.
Ticket: https://dimagi.atlassian.net/browse/QA-7351
> Change progress dialog cancel button visibility state

- app/AndroidManifest.xml
- app/res/values/strings.xml
[Android 14 brought new restrictions around implicit intents](https://developer.android.com/about/versions/14/behavior-changes-14#safer-intents) and CC app callouts are based on implicit intents, this PR reviews the `exported` attribute of activities targeted by predefined app callout options.
Ticket: https://dimagi.atlassian.net/browse/QA-7356
> Update component exported attribute

- app/src/org/commcare/gis/EntityMapActivity.java
- app/src/org/commcare/preferences/HiddenPreferences.java
Applies a custom map marker on the "Map" Case list view when a detail field with template `image` is defined for the case list when the property `cc-enable-custom-map-marker` is set to `yes` in app settings. 
Image with default icon:
Image with a custom icon applied:
None
Tested locally for scenarios when an icon is defined for the case list and when it's not. 
**QA Note**: View on Map case list view now supports a custom map marker and an appropriate test case should be added to verify it. 
**Release Note**: Custom map marker support for Case list's "View on Map" feature. 
Best reviewed commit by commit.
> Add support for a custom Map marker for the Case List

- app/res/layout/fragment_connect_unlock.xml
- app/res/navigation/nav_graph_connect.xml
- app/src/org/commcare/activities/CommCareSetupActivity.java
- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/connect/ConnectConstants.java
- app/src/org/commcare/fragments/connect/ConnectUnlockFragment.java
- app/src/org/commcare/services/CommCareFirebaseMessagingService.java
This addresses an issue where the user would be directed to the Connect activity on clicking a push notification, and while unlocking ConnectID the opportunity list fragment would already appear in the background and begin updating. Now instead, a blank fragment is shown when the user enters the app this way while the user is prompted to unlock ConnectID. This also addresses a bug where the wait dialog (shown while updating the opportunity list from the API) would sometimes fail to dismiss when the call completed.
Users will not see the opportunity list behind the Connect biometric unlock popup. Instead, the screen behind will be blank during this time.
No automated tests for Connect code yet...
This increases safety …
> Handling CID unlock in ConnectActivity

- app/src/org/commcare/adapters/ConnectMessageAdapter.java
- app/src/org/commcare/fragments/connectMessaging/ConnectMessageChannelListFragment.java
- app/src/org/commcare/fragments/connectMessaging/ConnectMessageFragment.java
- app/src/org/commcare/services/CommCareFirebaseMessagingService.java
Simple change to support markdown in the messaging page
[Jira ticket](https://dimagi.atlassian.net/browse/CCCT-650)
ConnectID Messaging
When messages contain markdown, it will be rendered appropriately in the messaging page.
No automated tests for Connect code yet.
Very small change, simply changes how the text is displayed and relies on existing code to render the markdown.
> Markdown in messaging

- app/src/org/commcare/fragments/connectMessaging/ConnectMessageChannelListFragment.java
- app/src/org/commcare/fragments/connectMessaging/ConnectMessageFragment.java
- app/src/org/commcare/services/CommCareFirebaseMessagingService.java
This change allows the CommCareFirebaseMessagingService to send a broadcast instead of issuing a push notification when the received FCM message is related to messaging and one of the messaging pages is active either the channel list or the message page with the corresponding channel).
[Jira ticket](https://dimagi.atlassian.net/browse/CCCT-649)
The two related fragments use static variables to indicate their active state easily to the service, and register/unregister for the broadcasts when the fragment resumes/pauses.
ConnectID Messaging
When the user is on the channel list page or messaging page (for the channel indicated in the FCM message), they will no longer see a push notification for the received message. Instead, …
> Update messaging pages when active instead of showing push notification

- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/activities/FormEntryActivityUIController.java
- app/src/org/commcare/activities/HomeButtons.java
- app/src/org/commcare/activities/components/MenuList.java
- app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
- app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
- app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
- app/src/org/commcare/sync/FormSubmissionHelper.java
- app/src/org/commcare/utils/FormUploadResult.java
Makes following changes to Analytics - 
-  Send Start and Logut button clicks as part of `home_button_click` event
- Adds form xmlns to form related analytics events (same ashttps://github.com/dimagi/commcare-android/pull/2951 but for `master`)
- Adds following new events 
1. `form_finish_attempt`: Logs a form save attempt with the save `result` and `method` (user_triggered save vs system_triggered) event params
2. `menu_screen_item_click`:  Whenever a menu/form is selected from the menu screen with menu id as `item_id` event param
3. `form_upload_attempt` : Whenever we do a form upload process to the server with `result` and `value` as 2 event params representing the result of the form upload process and # of forms uploaded as part of the form upload attempt. 
N/A
Analytics only, …
> Adds New Analytics event

- app/res/layout/view_job_card.xml
- app/res/layout/view_progress_job_card.xml
- app/src/org/commcare/activities/StandardHomeActivityUIController.java
- app/src/org/commcare/fragments/connect/ConnectDeliveryDetailsFragment.java
- app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
- app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
- app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
https://dimagi.atlassian.net/browse/CCCT-606
Removes the pay-per-visit text from the job summary card that is shown on several Connect pages.
The concept increasingly does not make sense since opportunities often involve several visits with different pay amounts.
So if a user gets $10 for an initial visit and $5 for a follow-up visit, an overall "pay per visit" isn't meaningful.
View on most pages:
View on app home (with daily progress):
Removes the pay-per-visit UI fields from the two related cards, and code on related pages that updated the value of the pay-per-visit text.
Connect
Relatively simple change, just removing some UI fields and the code that updates them. I also viewed the tiles on each of the related pages to …
> Remove pay-per-visit text from job summary cards

- app/build.gradle
- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
- app/src/org/commcare/activities/SyncCapableCommCareActivity.java
- app/src/org/commcare/engine/cases/CaseUtils.java
- app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
- app/src/org/commcare/models/database/user/UserDatabaseUpgrader.java
- app/src/org/commcare/models/database/user/models/CommCareEntityStorageCache.java
- app/src/org/commcare/tasks/DataPullTask.java
- app/src/org/commcare/tasks/EntityCacheInvalidationWorker.kt
- app/src/org/commcare/xml/AndroidBulkCaseXmlParser.java
- app/src/org/commcare/xml/AndroidCaseXmlParser.java
- app/unit-tests/resources/commcare-apps/case_list_lookup/restore.xml
- app/unit-tests/resources/commcare-apps/index_and_cache_test/incremental_restore.xml
- app/unit-tests/resources/commcare-apps/index_and_cache_test/suite.xml
- app/unit-tests/src/org/commcare/CommCareTestApplication.java
- app/unit-tests/src/org/commcare/android/tests/DataPullTaskTest.java
- app/unit-tests/src/org/commcare/android/tests/DemoUserRestoreTest.java
- app/unit-tests/src/org/commcare/android/tests/activities/PostRequestActivityTest.java
- app/unit-tests/src/org/commcare/android/tests/activities/UpdateActivityTest.java
- app/unit-tests/src/org/commcare/android/tests/caselist/EntityListCacheIndexTest.java
- app/unit-tests/src/org/commcare/android/tests/formnav/EndOfFormTest.java
[Spec](https://docs.google.com/document/d/1VE6yjo-yOfhnwpHMRZWavgJmbmbRhsoVvWS3Kq3yh2g/edit?tab=t.0#heading=h.ivv3e8sh6t45)
https://dimagi.atlassian.net/browse/SC-4279
Expires cache for all related cases in order to support caching xpath calculation results for related cases like instance('casedb')/casedb/case[@case_type='mother'][@case_id=current()/index/parent]/case_name. Without expiring related cases from cache, these kind of expressions may result in obsolete data to the user.
Alternate approach to https://github.com/dimagi/commcare-android/pull/2944
Adds a new field `is_shallow` in the entity cache to signify any cases that have changed from the last time the cache was primed. These shallow records are then further processed by a background worker after form submission and restores …
> Expires entity cache for related cases

- app/AndroidManifest.xml
- app/build.gradle
- app/instrumentation-tests/src/org/commcare/androidTests/BaseTest.kt
- app/src/org/commcare/utils/Permissions.java
- app/src/org/commcare/views/widgets/ImageWidget.java
- app/src/org/commcare/views/widgets/VideoWidget.java
- app/src/org/commcare/views/widgets/WidgetUtils.java
Google issued a new policy that states that [READ_MEDIA_IMAGES](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_IMAGES) and [READ_MEDIA_VIDEO](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_VIDEO) permissions can only be used by apps whose core functionality requires broad access to images and videos stored in the device. These permissions were introduced in Android 13 and as such, this policy mostly affects that version and later. For apps that don't require this level of access, the recommended approach is to use a system picker, like the [Android photo picker](https://developer.android.com/training/data-storage/shared/photopicker), which is available in Android 13 onward. Additionally, Google is committed to making the …
> Remove media permissions

- app/src/org/commcare/adapters/EntityDetailPagerAdapter.java
- app/src/org/commcare/views/TabbedDetailView.java
This PR fixes an issue in the Case details which causes a mismatch between tab items and their respective content when a display condition is set. The fix is basically to restore a method that was removed during the migration to ViewPager2 that retrieves the title of the page from the visible tabs.
Ticket: https://dimagi.atlassian.net/browse/SAAS-16528
This was tested locally and with different configurations, all seems fine.
> Fix Case detail tab title

- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/fragments/connect/ConnectDownloadingFragment.java
Menu items of connect page are disabled while downloading the application
https://dimagi.atlassian.net/browse/CCCT-721
For better user experience and fixing the bugs by pressing back/menu items while downloading the app
This is small change and test on staging variant
General QA
> Disable menu items while downloading the applications

- app/src/org/commcare/android/database/connect/models/ConnectJobAssessmentRecord.java
- app/src/org/commcare/android/database/connect/models/ConnectJobDeliveryRecord.java
- app/src/org/commcare/android/database/connect/models/ConnectJobLearningRecord.java
- app/src/org/commcare/android/database/connect/models/ConnectJobPaymentRecord.java
- app/src/org/commcare/android/database/connect/models/ConnectJobPaymentRecordV3.java
- app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
- app/src/org/commcare/android/database/connect/models/ConnectLinkedAppRecord.java
- app/src/org/commcare/android/database/connect/models/ConnectUserRecord.java
- app/src/org/commcare/connect/ConnectManager.java
- app/src/org/commcare/connect/network/ApiConnectId.java
- app/src/org/commcare/connect/network/ConnectNetworkHelper.java
- app/src/org/commcare/connect/network/ConnectSsoHelper.java
- app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIDSignupFragment.java
- app/src/org/commcare/network/CommcareRequestGenerator.java
https://dimagi.atlassian.net/browse/CCCT-666
When an API call fails due to a 401 error while using TokenAuth, we should delete the token from local storage.
This is most likely to occur due to a clock error (drift or time zone mismatch) on the device.
For whatever reason the token failed, it should be discarded so a new token is retrieved the next time an API call is made.
This code addresses token failures for both HQ and ConnectID tokens in several places:
- [Checking response for HQ calls](https://github.com/dimagi/commcare-android/blob/5113bd1950004148398a740c04add1016ceb242c/app/src/org/commcare/network/CommcareRequestGenerator.java#L215)
- [ResponseProcessor for Connect calls using ConnectID token](https://github.com/dimagi/commcare-android/blob/5113bd1950004148398a740c04add1016ceb24 …
> Delete SSO token storage when token auth fails

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/network/HttpCalloutTask.java
- app/src/org/commcare/tasks/ManageKeyRecordTask.java
- app/src/org/commcare/views/notifications/NotificationMessageFactory.java
This PR improves the user message for login failures because the user's role doesn't have the `Mobile App Access` right. Right now, whenever such user tries to log in, they receive a generic a `Bad Server Response` message, which provides no guidance on how to address the issue.
This properly handle a `403` HTTP response and shows to the user a more appropriate message.
<table><tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Ticket: https://dimagi.atlassian.net/browse/SAAS-16077
Tested this locally as per the results in the images above.
> Handle failed logins due to insufficient permission

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/activities/FormEntryActivity.java
- app/src/org/commcare/location/CommCareLocationControllerFactory.kt
This PR addresses an issue with the GPS widget when the device is in Airplane Mode. Upon pressing the `Record Location` button, the screen flashes and the user returns to the previous screen. 
<video src="https://github.com/user-attachments/assets/2f3579c9-73ea-43c1-958f-b5c01028b05b" width="200px"></video>
There is an exception being thrown and here's the stack trace:
```
com.google.android.gms.common.api.ApiException: 8502: SETTINGS_CHANGE_UNAVAILABLE
13:43:05.638  W  	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.4.0:3)
13:43:05.638  W  	at com.google.android.gms.common.internal.zap.onComplete(com.google.android.gms:play-services-base@@18.4.0:4)
13:43:05.638  W  	at …
```
> Fix location capture in Airplane mode

- app/src/org/commcare/android/database/connect/models/ConnectMessagingChannelRecord.java
- app/src/org/commcare/connect/ConnectDatabaseHelper.java
- app/src/org/commcare/utils/DimensionUtils.kt
- app/src/org/commcare/utils/StringUtils.java
For Outgoing message: read/unread icon + message body
For incoming message: message body
When last message was outgoing:
When last message was incoming:
https://dimagi.atlassian.net/browse/CCCT-711
This is kind of feature where display of message preview changed
Limited effect on safety, UI change
Need general review for message preview
> Preview of message in messages channel changed

- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/activities/connect/ConnectIdActivity.java
- app/src/org/commcare/connect/ConnectConstants.java
- app/src/org/commcare/connect/ConnectManager.java
- commcare-support-library/src/main/java/org/commcare/commcaresupportlibrary/CommCareLauncher.java
https://dimagi.atlassian.net/browse/CCCT-800
https://dimagi.atlassian.net/browse/CCCT-730
Previously, there was a bug. After downloading the app from connect screen, app was showing empty list of opportunities. Even though code was pointing out that it should redirect to auto login but it was not happening due to bug. This is rectified in this PR.
Not a feature, its a bug
I have tested in staging variant
Now, after downloading the app, user should be automatically logged in.
> Auto login app after its downloaded 

- app/src/org/commcare/services/CommCareFirebaseMessagingService.java
https://dimagi.atlassian.net/browse/CCCT-786
As shown in the ticket, users are sometimes shown "empty" push notifications, i.e. with no title or text. It seems this is possible if the server sends certain payloads, so this PR adds some logging to help us better understand more about when it happens.
ConnectID Messaging
Simple under-the-hood logging, very little risk
No automated tests for ConnectID yet.
No testing required or useful.
> Logging empty push notifications

- app/src/org/commcare/fragments/connectId/ConnectIdPhoneVerificationFragmnet.java
- app/src/org/commcare/fragments/connectId/ConnectIdUserDeactivateOTPVerificationFragment.java
https://dimagi.atlassian.net/browse/CCCT-840
This PR fixes a crash experienced on some Android versions when the user attempts to deactivate their account. The issue is described more [here](https://stackoverflow.com/questions/77235063/one-of-receiver-exported-or-receiver-not-exported-should-be-specified-when-a-rec), and the fix is to simply check the Android version when registering a receiver and pass in the RECEIVER_NOT_EXPORTED flag if necessary.
ConnectID
I found other places in existing code that perform the check on Tiramisu and call the registerReceiver function differently depending.
No automated tests for ConnectID yet.
Attempt to deactivate a ConnectID account (already covered in the test plan), using a device …
> Register broadcast receivers with proper security

- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/SyncCapableCommCareActivity.java
- app/src/org/commcare/connect/ConnectManager.java
- app/src/org/commcare/network/CommcareRequestGenerator.java
https://dimagi.atlassian.net/browse/CCCT-668
Some additional logging to help capture the failed token auths related to ConnectID-managed apps.
We're already logging the case where we're unable to get an HQ token just before making an HQ call.
But currently we still make the call anyway, which is guaranteed to fail.
Even once that's fixed, we still may get surprise failures due to tokens we thought were good actually not being good.
So this PR adds logging after HQ calls fail (key record or data pull requests) due to bad authorization when they should be managed by ConnectID via tokens.
ConnectID
Simple addition that silently logs a condition, and checks happen in a try-catch in case something goes wrong.
No automated tests …
> Additional logging for failed HQ token auth in ConnectID-managed apps.

- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
- app/src/org/commcare/fragments/connect/ConnectJobsListsFragment.java
- app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
https://dimagi.atlassian.net/browse/CCCT-839
Sync button in top-right corner now functional in Learn Progress and Delivery Progress pages.
The two fragments needed to override the onMenuItemSelected function and, when the sync action was selected by the user, initiate a data refresh.
Connect
The added code is similar to what's already in the opportunity list page to do a refresh there.
To add to the test plan if not already there:
- Learning progress: Click the sync button in the top-right corner and verify that the page performs a sync with the server
- Delivery progress: Repeat the above test
> Fix sync buttons in learn and delivery progress pages

- app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
https://dimagi.atlassian.net/browse/CCCT-838
Delivery progress tabs no longer squished vertically when changing between tabs.
This PR fixes a bug in which part of the UI would sometimes be sized too short (matching a different UI), such that elements were squished. Also while working in this code, I cleaned things up slightly so as not to hold static references to the two fragments (which equated to holding static references to Context objects).
Showing the error:
Connect
Tested the code out to verify things size correctly now and nothing got broken in my cleanup.
Otherwise this is mostly just about updating the height of a UI element, pretty simple change.
See steps to reproduce in the …
> Delivery Progress UI fix

- app/res/layout/fragment_connect_delivery_details.xml
- app/res/layout/fragment_signup.xml
- app/src/org/commcare/connect/ConnectManager.java
- app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
- app/src/org/commcare/utils/BiometricsHelper.java
Solve small screen UI issues in 
Login 
Delivery app download screen
Biometric and PIN/Pattern unlock screen
https://dimagi.atlassian.net/browse/CCCT-829
It is bug
Mentioned changes are verified on small and large screen
Mentioned screen UI to be verified
> Solved smaller screens UI issues

- app/src/org/commcare/connect/ConnectDatabaseHelper.java
No ticket, fixing a quick bug for Jon.
Fixes a special case where the user has transitioned to learning but hasn't completed a learn module yet. This ensures that the status stays in "learning" and doesn't revert to "available".
The underlying issue is that the server doesn't send a status along with each job when we retrieve the jobs. So when parsing and storing the job data, we use a [couple checks](https://github.com/dimagi/commcare-android/blob/489b81a863d341b500b1170d6ce690a0368a9a4f/app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java#L270) to determine the current status. Unfortunately, the check to determine whether we're in learning state is whether the user has >0 learn completion (i.e. they've completed at least one learn module).
When the user starts …
> Job status fix for learning

- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/activities/SyncCapableCommCareActivity.java
- app/src/org/commcare/tasks/DataPullTask.java
- app/src/org/commcare/tasks/EntityCacheInvalidationWorker.kt
- app/src/org/commcare/tasks/EntityLoaderHelper.kt
- app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
A few minor tweaks and pending feedback for cache and lazy load feature. Review commit by commit. 
cross-request: https://github.com/dimagi/commcare-core/pull/1463
> MInor Tweaks for Cache and Lazy Load

- app/build.gradle
This PR fixes an issue with instrumentation tests failing locally due to missing HQ credentials in the BuildConfig class, which are required by some of the tests.
Ticket: https://dimagi.atlassian.net/browse/SAAS-16708
Successfully tested locally.
> Add HQ credentials to build configuration when running AGP connected tasks

- app/res/values/strings.xml
- app/src/org/commcare/activities/EntitySelectActivity.java
- app/src/org/commcare/tasks/EntityLoaderHelper.kt
- app/src/org/commcare/tasks/PrimeEntityCache.kt
- app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
- app/unit-tests/src/org/commcare/android/tests/DemoUserRestoreTest.java
This PR makes following changes for cache and index work - 
- Nullability corrections https://github.com/dimagi/commcare-android/pull/2998/commits/cdd44e260f78f3bbec749843effcd9ff7a5079ed
- Instead of showing a progress indictor for 3 phases that each goes from 0 to 100 , shows a weighted progress by giving all possible phases equal ewightage. https://github.com/dimagi/commcare-android/pull/2998/commits/980fcad76c288866dbee3756b74ceeedd26e9f81
- Fixes a bug where a normal case list loading gets blocked on background cache work priming work due to [user db being locked ](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/models/database/user/models/CommCareEntityStorageCache.java#L91)by the background work. This is fixed by explicitly calling cancel on the …
> Fixes for Entity Cache and Lazy loading work

- app/build.gradle
This PR is to update Firebase Analytics and Crashlytics to 20.1.2 and 18.3.7, respectively. The main motivation is to make ANRs available in Crashlytics, this will give better insight into the affected users and domains. Crashlytics started supporting ANR collection in 18.4.2. The Firebase Analytics bump is more opportunistic, the current version is from 2020 and from the release notes, this bump seems safe to make.
Caused a crash and was able to confirm its report in `Crashlytics` as well as the Analytics events.
> Update Firebase dependencies

- app/src/org/commcare/activities/LoginActivity.java
Fixes a bug where the app would attempt to navigate the user to the Connect menu if they select the first app in the dropdown list, instead of the selected app. This code should have been removed when we removed the "Go to Connect Menu" option as the first item in the dropdown list.
Removed obsolete code that redirects to Connect menu when first item in app selector is selected.
ConnectID
Discovered via local testing, and fix verifide the same way.
No automated tests for ConnectID yet.
This was a pretty specific bug, but generally QA might be able to improve the testing by trying more single- and multi-app configurations from the login page.
> Fixing obsolete app selector code

- app/src/org/commcare/fragments/connect/ConnectDeliveryProgressDeliveryFragment.java
https://dimagi.atlassian.net/browse/CCCT-897
Small improvements to the text displayed for each payment unit in the delivery progress page, to only count progress based on approved visits (not including pending visits).
Simple change to the values that go into the text field and progress bar
Connect
Simple change to UI inputs. Tested manually.
Verify the delivery progress bar and text for each payment unit are displayed as specified in Sankalp's comment in the Jira ticket.
> Changes to delivery progress text for each payment unit

- app/res/layout/fragment_connect_delivery_progress.xml
https://dimagi.atlassian.net/browse/CCCT-729
Replaced complex scrolling in the delivery progress page with simple whole page scrolling. The previous implementation tried to have the top cards scroll away separately than the bottom sections of the page, but users found the experience confusing.
Replaced the more complex UI elements that supported the additional scrolling behavior with one big NestedScrollView.
Connect
Tested manually by scrolling the page from various points with my finger and verifying that it always worked as expected.
Scrolling on the page should not do anything fancy, just scroll all the contents up and down together.
> Delivery progress scrolling fix

- app/src/org/commcare/android/database/connect/models/ConnectPaymentUnitRecord.java
Repairs an issue with the key used to identify the payment unit ID. The server sends the info under the "id" key, but legacy mobile code has been using the "unit_id" for local storage for quite a while. Rather than force a DB upgrade just to rename the column, the existing code used the two different keys for their perspective uses.
Restored definition of two keys for the payment unit ID, one for the server and one for local storage.
[Commit that broke this](https://github.com/dimagi/commcare-android/commit/b1e4eff4e615744ebfeb8c7626713d9f5f83cf9f#diff-888501c47960fffa9c0b837558400f5cfe1dc3dc149596a8b9de5084ee331ef6)
Connect
Discovered while working on a different ticket.
Once the problem was identified, I traced back to see it was introduced as part of the merge work back in late …
> Payment id key bug fix

- app/res/layout/view_job_card.xml
- app/res/layout/view_progress_job_card.xml
- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values-ti/strings.xml
- app/res/values/strings.xml
- app/src/org/commcare/activities/StandardHomeActivityUIController.java
- app/src/org/commcare/adapters/ConnectDeliveryProgressReportAdapter.java
- app/src/org/commcare/fragments/connect/ConnectDeliveryProgressFragment.java
- app/src/org/commcare/fragments/connect/ConnectJobIntroFragment.java
- app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
https://dimagi.atlassian.net/browse/CCCT-897
Changed the displayed text in payment unit progress cards for special situations:
- Final 2 days of delivery: showing "by today" and "by tomorrow"
- Delivery ended: showing "Days Over"
- All visits completed: showing "All Visits Done"
Some additional logic and new strings to handle the additional displays.
Also saw a misidentified class that I should have change in a commit yesterday.
It was low-risk since all we call is setText and both classes implement the method the same way, but good to fix.
Connect
Tested display manually.
Verify the text is displayed correctly for each of the scenarios described above.
> Additional tweaks to delivery progress text

- app/src/org/commcare/connect/database/ConnectUserDatabaseUtil.java
Fixed the crash for the second time recovery or signup for connectid 
The user is getting crash when he signup or recover account every alternative time the db was not getting cleared 
StackTrace 
Caused by net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database
at net.sqlcipher.database.SQLiteStatement.native_execute(SQLiteStatement.java)
at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:61)
at net.sqlcipher.database.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:2227)
at net.sqlcipher.database.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:2103)
at org.commcare.models.database.SqlStorage.write(SqlStorage.java:633)
at org.commcare.connect.database.ConnectUserDatabaseUtil.storeUser(ConnectUserDatabaseUtil.java:46)
at …
> PM QA 7620

- app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
https://dimagi.atlassian.net/browse/QA-7609?linkSource=email
Small additional change to make sure "today" and "tomorrow" are used properly when reporting time remaining near the end of the opportunity.
This change is about making sure we report 0 days remaining when the end date has passed, 1 day remaining when today is the last day, and 2 days remaining when tomorrow is the last day. Mostly, it's about dealing with the fact that the end date doesn't include a time (so it defaults to 00:00).
Connect
Simple math change.
None
QA already aware of and testing for this.
> Additional delivery progress tweak

- app/src/org/commcare/views/dialogs/AlertDialogFragment.java
- app/unit-tests/src/org/commcare/android/tests/formsave/CyclicCasesPurgeTest.java
Noticing quite a lot of  Jenkins failures with `CyclicPurgeTest` recently and trying to see if this will make a difference. The current test on Jenkins fails with a NPE on `formEntryActivity.getCurrentAlertDialog()` and it only happens some times which strongly suggests it's a timing issue and test runner is not waiting for dialog to be shown.  Use of `ShadowDialog` should bypass these issues. 
Test Fix only
> Potential Fix for CyclicPurgeTest

- app/build.gradle
- app/src/org/commcare/utils/FileUtil.java
/claim #2689
This PR ensures that EXIF metadata (like orientation, timestamp, GPS, etc.) is preserved when an image is scaled down in the CommCare Android app. This improves user experience in workflows that rely on image metadata.
[Passthrough EXIF metadata while scaling images](https://github.com/dimagi/commcare-android/issues/2689)
Modified the image scaling logic to preserve EXIF metadata by copying it from the original image to the scaled-down version as can be seen in the following screenshot
Values on the left side of `->` are coming from original image and those on the right side are coming from the scaled image.
Not behind a feature flag.
- The changes were tested locally with various images containing different EXIF metadata.
- Verified that the metadata is retained correctly …
> Passthrough EXIF properties while scaling image

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/AppUtils.java
This is a small change to ensure that the CommCare versions that appear in the form submission `appVersion` metadata follow the SemVer format. They are currently being computed differently but from the same source, resulting in values such as:
```
<n1:appVersion xmlns:n1="http://commcarehq.org/xforms">CommCare Android, version "2.56"(1). App v16. CommCare Version 2.56.0. Build 1, built on: 2025-03-05</n1:appVersion>
```
These differences are causing discrepancies in the Enterprise Dashboard, more info [here](https://dimagi.atlassian.net/browse/SAAS-16383).
It seems that in the past, one used to be sourced from the `PackageManager` and the other from the `BuildConfig.VERSION_NAME`, the latter is the current source for both. The change was done …
> Set CC version in form metadata in SemVer format

- app/src/org/commcare/android/logging/ForceCloseLogEntry.java
- app/src/org/commcare/android/logging/ForceCloseLogSerializer.java
- app/src/org/commcare/logging/DeviceReportWriter.java
This small PR includes two more pieces of data to the normal device logs, `Device model` and `Android version`. These are already included in the forced close logs, and this is just to make them standard across the different types of logs.
Note: This will require HQ work to parse these new data elements, store and forward them to the necessary cloud storages (if applicable).
Tickets: https://dimagi.atlassian.net/browse/SAAS-16657
HQ PR: https://github.com/dimagi/commcare-hq/pull/35956
Deployed the HQ branch on Staging and was able to test this there, there are 2 scenarios:
Log message from CommCare versions with this change (2.57+):
```
[log_date=2025-04-02T17:19:26.999000Z] [log_submission_date=2025-04-02 17:19:28.961561] [log_type=user] 
[domain=test-65] [username=bio_test] …
```
> Add device model and android version to device logs

- app/src/org/commcare/entity/AndroidAsyncNodeEntityFactory.kt
- app/src/org/commcare/tasks/EntityLoaderHelper.kt
- app/src/org/commcare/tasks/EntityLoaderTask.java
- app/src/org/commcare/tasks/PrimeEntityCacheHelper.kt
https://dimagi.atlassian.net/browse/SC-4402
This is necessary to be able to populate cache correctly in primeCache as otherwise we don't have values like [mTemplateIsCachable and mCacheHost correctly initialized](https://github.com/dimagi/commcare-core/blob/master/src/main/java/org/commcare/cases/entity/AsyncNodeEntityFactory.java#L94) which results into the  `primeCache` method to exit early and not populate cache into memory resulting into a performance hit. 
Cache and Lazy Load 
The change allows us to reuse the factory class which should be harmless for normal use cases that doesn't involve entity caching. The pass on integration test should confirm this further. 
None
> Cache Prime Fix: Reuse entity factory for cache prime

- app/src/org/commcare/fragments/connectMessaging/ConnectMessageChannelListFragment.java
Back button on message channel list will be present while coming back from message screen
https://dimagi.atlassian.net/browse/CCCT-924
No
This has been tested on local setup
QE team should be able to view the back button whenever coming from message screen to message channel list
> Solved back button issue while coming back to message channel list from message screen

- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values-ti/strings.xml
- app/res/values/strings.xml
- app/src/org/commcare/activities/connect/ConnectIdActivity.java
- app/src/org/commcare/connect/ConnectManager.java
- app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
- app/src/org/commcare/utils/BiometricsHelper.java
https://dimagi.atlassian.net/browse/CCCT-941
Better error handling and reporting for issues encountered during biometric configuration (during registration/recovery)
Deleted some obsolete code (uncalled functions).
Added non-fatal exceptions for error-cases (like an option isn't available as we start trying to configure it).
Added a couple toast messages to give the user an indication of certain problems  (along with reporting a non-fatal exception).
ConnectID
Tested locally in various situations
No automated tests for ConnectID yet.
- Test various options in the biometric configuration page during registration or recovery workflow
- Include testing on device without fingerprint reader
- Test PIN config/unlock on SDKs <23, …
> Biometric config cleanup and error handling

- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values-ti/strings.xml
- app/res/values/strings.xml
- app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
Quick change to include the error string returned by the OS when the user fails fingerprint authentication, both in the reported non-fatal exception and the toast message shown to the user.
> Show fingerprint failure error string

- app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
https://dimagi.atlassian.net/browse/CCCT-971
Bug fix
Tested on Android 6 and 7
To test on Android 6 and 7
> Solved crash for older Android versions

- app/src/org/commcare/connect/database/ConnectDatabaseHelper.java
- app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
https://dimagi.atlassian.net/browse/CCCT-950
Fixes a bug where the app would sometimes crash during registration.
Fixed handling for received remote passphrase to properly rekey when necessary, and then store the local passphrase.
Added analytics event when database is rekeyed with new passphrase.
More notes about the crash that caused this [here](https://docs.google.com/document/d/1PvTgJPVidjmaqy4d-kWJKfhPIRan60gmQ8C9RqzF02M/edit?tab=t.0#heading=h.rbd0yudtyzqb)
ConnectID
Tested several scenarios locally.
QA plan should make sure to include the testing described below.
None
Tests that need to be performed around this, all should not crash:
- Register an account
- Recover an account
- Reg/recover on published beta (build …
> Fixed logic around receiving and storing Connect DB passphrases.

- app/res/layout/home_screen.xml
- app/src/org/commcare/activities/DispatchActivity.java
- app/src/org/commcare/activities/HomeButtons.java
- app/src/org/commcare/activities/HomeScreenBaseActivity.java
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/LoginActivityUIController.java
- app/src/org/commcare/activities/StandardHomeActivity.java
- app/src/org/commcare/activities/StandardHomeActivityUIController.java
- app/src/org/commcare/connect/ConnectIDManager.java
Some final set of fixes/refactor before we merge the phase 2 connect code into `master`.  A bunch of commits are just to bring missing code from latest `connect_qa` branch to here. 
Best reviewed commit by commit. 
I have tried to make some calls here to what makes best sense to me and might introduce a regression with a special case handling on Login Screen that I am unaware of. I am mostly relying on review to spot any such edge case handling. I would like reviewer to pay special attention to login inputs visibility and connect app state management. 
Will be QA'ed with phase 2 QA
> Phase 2 Connect Merge Fixes

- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
Using CommCare BuildConfig instead of Firebase for reporting build number in analytics events.
Old code was reporting -1, and then broke the build recently.
None
Simple change, not visible to user but will improve our reporting
None
None
> Using CommCare BuildConfig

- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
Wrapped the function in analytics that packs parameters into a bundle in a try-catch.
This was causing an occasional crash when code tried to log a form entry event with a null form ID.
[Firebase crash](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/72de9c0c2770c333cdb78585fd00bd41?time=last-seven-days&types=crash&sessionEventKey=68091A4C0218000175CF2159E44778BF_2075003108423650723)
None
Simple try-catch with logging, pretty safe stuff.
None
> Safety try-catch in analytics

- app/src/org/commcare/activities/HomeScreenBaseActivity.java
- app/src/org/commcare/activities/connect/ConnectIdActivity.java
- app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
- app/src/org/commcare/connect/ConnectConstants.java
https://dimagi.atlassian.net/browse/QA-7705
bug  fix for connect landing page 
https://dimagi.atlassian.net/browse/CCCT-988
In this the impact will be time shown as working hours on the connect job screens 
we have to show the time n local time zone 
I have manually checked the times it showing correct on all job screen
> Pm-fixed bug for job status button click and landing page for connect

- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/android/logging/ReportingUtils.java
- app/src/org/commcare/connect/ConnectIDManager.java
- app/src/org/commcare/utils/CrashUtil.java
No visible change
When a ConnectID user is logged in, override the Crashlytics user to the user's ConnectID
ConnectID
Crash logging change, only gets run when user is logged in.
None
None
> Set Crashlytics user to ConnectID

- app/res/layout/fragment_signup.xml
- app/res/layout/screen_connect_primary_phone.xml
- app/res/navigation/nav_graph_connectid.xml
- app/res/values/strings.xml
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/connect/ConnectIdActivity.java
- app/src/org/commcare/connect/ConnectConstants.java
- app/src/org/commcare/connect/ConnectIDManager.java
- app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdPhoneFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdPhoneVerificationFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdPinFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdUserDeactivateOTPVerificationFragment.java
- app/src/org/commcare/utils/BiometricsHelper.java
Cherry picked the commits based on regression testing in phase 2
> Pm qa regression

- app/res/navigation/nav_graph_connectid.xml
- app/src/org/commcare/fragments/connectId/ConnectIdMessageFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdPasswordVerificationFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdPinFragment.java
- app/src/org/commcare/utils/BiometricsHelper.java
Make Biometric available for version less than 28 
https://dimagi.atlassian.net/browse/QA-7707
Till now we have configure till android 28 but we support till android 21 so we have placed the check for that
Tested on android 7 , 12 and 14
> make biometric available for api version less than 28

- app/res/layout/fragment_recovery_code.xml
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/android/database/connect/models/ConnectJobRecord.java
- app/src/org/commcare/connect/ConnectIDManager.java
- app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
- app/src/org/commcare/utils/JsonExtensions.kt
- app/src/org/commcare/views/connect/CustomOtpView.java
- app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Bug fixes 
https://dimagi.atlassian.net/browse/QA-7728
[QA-7729](https://dimagi.atlassian.net/browse/QA-7729)
[QA-7730](https://dimagi.atlassian.net/browse/QA-7730)
[QA-7727](https://dimagi.atlassian.net/browse/QA-7727)
[QA-7707](https://dimagi.atlassian.net/browse/QA-7707)
cross-request:https://github.com/dimagi/commcare-core/pull/1475
> Pm-bug fixes for connect, and biometric fix

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/LoginActivityUIController.java
- app/src/org/commcare/activities/NavigationHostCommCareActivity.java
- app/src/org/commcare/activities/SyncCapableCommCareActivity.java
- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/activities/connect/ConnectIdActivity.java
- app/src/org/commcare/activities/connect/ConnectMessagingActivity.java
- app/src/org/commcare/connect/ConnectIDManager.java
- app/src/org/commcare/connect/MessageManager.java
- app/src/org/commcare/connect/network/ApiConnectId.java
- app/src/org/commcare/connect/network/ConnectSsoHelper.java
- app/src/org/commcare/connect/network/TokenDeniedException.kt
- app/src/org/commcare/google/services/analytics/AnalyticsParamValue.java
- app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
- app/src/org/commcare/logic/ArchivedFormRemoteRestore.java
- app/src/org/commcare/network/CommcareRequestGenerator.java
- app/src/org/commcare/network/HttpCalloutTask.java
- app/src/org/commcare/tasks/DataPullTask.java
- app/src/org/commcare/tasks/ManageKeyRecordTask.java
- app/src/org/commcare/views/notifications/NotificationMessageFactory.java
- Make some lint changes and logs cleanup
- Adds missing analytics code that was PR'ed before in https://github.com/dimagi/commcare-android/pull/2687/files
> Brings back missing analytics events And Token Exceptions Handling

- app/res/xml/app_manager_developer_preferences.xml
- app/src/org/commcare/connect/ConnectIDManager.java
- app/src/org/commcare/preferences/AppManagerDeveloperPreferences.java
Removes pref setting to enable connect ID as with GA we want it to be enabled by default.
> Remove connect enable setting

- app/src/org/commcare/android/resource/installers/XFormAndroidInstaller.java
Instead of showing "unknown error while installing app", show a detailed user message on Xpath errors while installing apps. Below is a screenshot on how this change results in more error details on the install page -
> Show Xpath error details while installing app

- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/StandardHomeActivityUIController.java
- app/src/org/commcare/activities/connect/ConnectIdActivity.java
- app/src/org/commcare/android/database/connect/models/ConnectJobDeliveryRecord.java
- app/src/org/commcare/connect/ConnectIDManager.java
- app/src/org/commcare/connect/ConnectManager.java
- app/src/org/commcare/fragments/connectId/ConnectIdPasswordVerificationFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdPhoneVerificationFragment.java
Fixed qa bugs
[QA-7735](https://dimagi.atlassian.net/browse/QA-7735)
https://dimagi.atlassian.net/browse/CCCT-607
https://dimagi.atlassian.net/browse/QA-7738
> Pm-fix direction issue with password , "null" issue,

- app/res/layout/fragment_connect_delivery_progress.xml
- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/connect/ConnectManager.java
Fixed the crash when clicking on the message icon
https://dimagi.atlassian.net/browse/QA-7742
cross-request: https://github.com/dimagi/commcare-core/pull/1475
[QA-7745](https://dimagi.atlassian.net/browse/QA-7745)
New bug 
[firebase stacktrace](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/e62bab888624c5a05b82bbef57f8ae9e?time=last-twelve-hours&types=crash&sessionEventKey=681D9BD2033E00013CAE743B820520FD_2080769885259634272)
> PM-fixing crash on click message icon

- app/AndroidManifest.xml
- app/assets/locales/android_translatable_strings.txt
- app/instrumentation-tests/src/org/commcare/androidTests/MenuTests.kt
- app/src/org/commcare/views/widgets/AudioRecordingHelper.java
- app/src/org/commcare/views/widgets/AudioRecordingService.java
- app/src/org/commcare/views/widgets/RecordingFragment.java
https://dimagi.atlassian.net/browse/SAAS-16641
This PR adds a bounded foreground service to the Audio recording feature. This service will ensure that the recording will continue when the device enters sleep or doze mode.
Users will now see a notification when the recording is in progress and another when it gets paused:
<video src="https://github.com/user-attachments/assets/c03c4729-453c-4584-8f03-3e3ea322c450" width="200px"/>
Successfully tested locally.
I've requested QA to run regression tests around this feature. 
QA ticket: https://dimagi.atlassian.net/browse/QA-7692
cross-request: https://github.com/dimagi/commcare-core/pull/1477
> Add audio recording foreground service

- app/res/layout/fragment_connect_delivery_progress.xml
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/StandardHomeActivityUIController.java
- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/activities/connect/ConnectIdActivity.java
- app/src/org/commcare/connect/ConnectIDManager.java
- app/src/org/commcare/connect/ConnectManager.java
- app/src/org/commcare/connect/database/ConnectJobUtils.java
- app/src/org/commcare/fragments/connect/ConnectDeliveryListFragment.java
- app/src/org/commcare/fragments/connectId/ConnectIdBiometricConfigFragment.java
- app/src/org/commcare/views/connect/CustomOtpView.java
Regression testing qa bug fixes 
https://dimagi.atlassian.net/browse/QA-7662?linkSource=email
cross-request: https://github.com/dimagi/commcare-core/pull/1475
> -fixes from regression qa fixes

- app/src/org/commcare/activities/NavigationHostCommCareActivity.java
Earlier we were cleaning the listener in onDestroy by which time there is no guarantee that the fragment will be alive or not. It's anyway better for UI listeners to be tied to onResume and onPause instead which is what this PR does to correct this behavior.
> Fixes a NPE with Connect ID Flow

- app/src/org/commcare/utils/FileUtil.java
/claim #2742
Improves image downscaling quality in CommCare by implementing a progressive step-wise scaling approach. This reduces visual artifacts like amplifying light patterns when resizing large images.
Ticket: #2742 
•	The original implementation of direct downscaling introduced visual artifacts in images with fine patterns. This change introduces progressive halving to preserve image quality.
•	DownScaling is done  in multiple halving steps followed by a final scale, instead of a single step.
> Improve image downscaling using progressive steps to reduce artifacts. 

- app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Fixed formstoragetest case with changing the new Xpath function name
I have tested this locally on my device 
We have covered the test cases to test these functions 
Release Note: Adds two new Xpath methods [closest-point-on-polygon](https://dimagi.atlassian.net/wiki/spaces/commcarepublic/pages/2143957589/CommCare+Functions#is-point-inside-polygon) and [is-point-inside-polygon](https://dimagi.atlassian.net/wiki/spaces/commcarepublic/pages/2143957589/CommCare+Functions#is-point-inside-polygon)
> -updated formStorageTest file with latest Xpath functions

- app/AndroidManifest.xml
- app/res/values/strings.xml
- app/src/org/commcare/activities/connect/ConnectMessagingActivity.java
- app/src/org/commcare/adapters/ChannelAdapter.java
- app/src/org/commcare/connect/MessageManager.java
- app/src/org/commcare/connect/database/ConnectMessagingDatabaseHelper.java
- app/src/org/commcare/fragments/connectMessaging/ConnectMessageChannelConsentBottomSheet.java
- app/src/org/commcare/fragments/connectMessaging/ConnectMessageFragment.java
- app/src/org/commcare/services/CommCareFirebaseMessagingService.java
> Connect Message review

- app/src/org/commcare/android/database/connect/models/ConnectUserRecord.java
- app/src/org/commcare/android/database/connect/models/ConnectUserRecordV13.java
- app/src/org/commcare/models/database/connect/ConnectDatabaseUpgrader.java
- app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
- app/unit-tests/src/org/commcare/android/tests/processing/FormStorageTest.java
Add photo and isDemo fields to Connect User Record. These are to be used to store base 64 encoded photo String and whether a user is a demo user.
> Add photo and isDemo fields to Connect User Record

- app/src/org/commcare/android/integrity/IntegrityTokenViewModel.kt
Fixes `Caused by: java.lang.NoSuchMethodException: org.commcare.android.integrity.IntegrityTokenViewModel.<init> [class android.app.Application]`
> Fixes a crash on Connect ID signup due to incorrect View Model constructor

- app/src/org/commcare/utils/HashUtils.kt
Fixes request hash for integrity token by not removing padding `=`
> request hash for integrity token needs padding

- app/src/org/commcare/connect/PersonalIdManager.java
- app/src/org/commcare/network/CommcareRequestGenerator.java
https://dimagi.atlassian.net/browse/CI-76
as a part of this we found an issue 
There's a bug in the mobile code such that the app will attempt to use token auth when syncing forms from a trad’l app after the user declines to link the app login to ConnectID. In other words, this happens when they press “No thanks” in the dialog that offers to link their app login to ConnectID. 
I have tested this code locally and was working fine
> -put extra check for getHq token

- app/src/org/commcare/connect/network/ApiPersonalId.java
- app/src/org/commcare/connect/network/PersonalIdApiHandler.java
- app/src/org/commcare/connect/network/parser/CompleteProfileResponseParser.java
- app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java
- app/src/org/commcare/fragments/personalId/PersonalIdNameFragment.java
- app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
- app/src/org/commcare/fragments/personalId/PersonalIdPhotoCaptureFragment.java
Refactored the complete profile page on the following
- API call as per the common way
- removed connect userecord take the data from session 
- created the data base after success from the server
> Complete profile refactor

- app/res/layout/screen_personalid_message.xml
- app/res/layout/screen_personalid_name.xml
- app/res/navigation/nav_graph_personalid.xml
- app/res/values/strings.xml
- app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java
- app/src/org/commcare/fragments/personalId/PersonalIdMessageFragment.java
- app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
- app/src/org/commcare/fragments/personalId/PersonalIdPhoneVerificationFragment.java
- app/src/org/commcare/fragments/personalId/PersonalIdPhotoCaptureFragment.java
- app/src/org/commcare/utils/FirebaseAuthService.java
Fixed work flow issue raised by Dave
End of workflow: Button shouldn't say “Back”
Name page: Each word should auto-capitalize in name input
Phone page: Keyboard dismissed when I cancel phone picker dialog
Removed brodcast reciever for sms autofill for this relase
>  fixed workflow issues

- app/src/org/commcare/CommCareApplication.java
- app/src/org/commcare/logging/analytics/TimedStatsTracker.java
- app/src/org/commcare/tasks/DataPullTask.java
- app/src/org/commcare/tasks/ManageKeyRecordTask.java
Reverts dimagi/commcare-android#2993
> Revert "Additional logging to troubleshoot the repeated login issue"

- app/src/org/commcare/fragments/personalId/PersonalIdPhoneVerificationFragment.java
https://dimagi.atlassian.net/browse/QA-7823
> Timer stopping after activity is paused issue solved

- app/AndroidManifest.xml
- app/res/values/strings.xml
- app/src/org/commcare/activities/CommCareSetupActivity.java
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/connect/PersonalIdManager.java
- app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
Check the version of the app and set the min version for personal iD is android N
> Pm device compatiblity

- app/src/org/commcare/activities/GeoPointMapActivity.java
https://dimagi.atlassian.net/browse/QA-7829
Fixes crash: 
````
Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:549)
at android.app.Activity.requestWindowFeature(Activity.java:5675)
at org.commcare.activities.GeoPointMapActivity.onCreate(SourceFile:72)
````
> fix crash requestFeature() must be called before adding content

- app/AndroidManifest.xml
https://dimagi.atlassian.net/browse/QA-7835
Screen rotation locked to portrait while user is taking a photo
Added it to the manifest for MicroImageActivity.
None
Tested, screen doesn't rotate
None
Try to rotate the screen during photo capture
> Lock screen to portrait during photo activity

- app/src/org/commcare/fragments/personalId/PersonalIdBiometricConfigFragment.java
https://dimagi.atlassian.net/browse/QA-7836
User will see an error message if biometric config fails or is aborted (instead of incorrectly proceeding to the next step in the device configuration workflow).
We were ignoring the result code that came back from the biometric config activity.
Passing the result code through so it can be handled properly now.
PersonalID
Tested the change out and I see the on-screen error message now.
None
This is in the QA plan already, the bug came from QA testing
> Handling failed biometric config properly

- app/res/values/strings.xml
- app/src/org/commcare/connect/network/PersonalIdApiErrorHandler.java
- app/src/org/commcare/connect/network/PersonalIdApiHandler.java
Improved user messaging for several HTTP error codes.
Added messages for unauthorized, server error, cooldown, and unknown.
Parsing errors (JSONException, IOException) during failure scenario handling now treated as unknown errors
PersonalID
No special testing, these are just different strings to show
> More API error messages

- app/assets/locales/android_translatable_strings.txt
- app/src/org/commcare/AppUtils.java
In a previous work (#2978), the formatted string used to populate the `appVersion` metadata in form submissions was optimized to eliminate repetition, the number of parameters was reduced to 5. So from:
- `CommCare Android, version "${0}"(${1}). App v${5}. CommCare Version ${2}. Build ${3}, built on: ${4}` - **6 params**
to
- `CommCare Android, version "${0}"(${1}). App v${4}. CommCare Version ${0}. Build ${2}, built on: ${3}` -  **5 params**
Since only the english version is in the codebase, the change was not applied the formatted string in other languages. These are stored separately and injected into the CommCare app via HQ when a language is added. For the change to work correctly, we would need to update the string in all supported languages so that they all expect 5 parameters …
> Revert format of appVersion metadata string

- app/res/layout/screen_personalid_phone_verify.xml
- app/res/values-fr/strings.xml
- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values-ti/strings.xml
Addressing observations 2, 3, 4, and 5 here:
https://dimagi.atlassian.net/browse/QA-7847
Arranged "change phone" link below phone text (to avoid overflow when text is wide).
Added some missing translations.
Shortened one French translation.
> Fixes for French

- app/res/layout/fragment_connect_delivery_details.xml
- app/res/layout/fragment_connect_job_intro.xml
- app/res/layout/fragment_connect_learning_progress.xml
- app/res/layout/fragment_connect_progress_delivery.xml
- app/res/layout/screen_personalid_phone_verify.xml
https://dimagi.atlassian.net/browse/QA-7848
https://dimagi.atlassian.net/browse/QA-7847
On the Job Intro and Job Details pages, the button to proceed was to the right of some text.
On the Learning/Delivery Progress pages, the sync button was similar
On the Phone Verification page, similar again with the Change link
When translated to French it all gets bigger, and causes strange overflows.
I rearranged these components vertically to allow room for them to expand horizontally, such that rollover will be isolated to each component rather than squishing other components.
Example of the new look:
> Fixed button spacing issue

- app/src/org/commcare/connect/network/ApiPersonalId.java
https://dimagi.atlassian.net/browse/QA-7849
Fixes an issue that could occur after failed PersonalID API calls.
Fixed a corner-case where a PersonalID API call fails and returns an error body, and the mobile code would erroneously call the processFailure callback twice.
PersonalID
Tested locally. Crashed before on failed device configuration (i.e. bad integrity token), now it doesn't
None
Already tested (bug identified by QA)
> Fixed double callback in after PersonalID API failure

- app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java
https://dimagi.atlassian.net/browse/QA-7850
Added key handlers for the Next and Done keys when showing the numeric keypad in the backup code fragment.
When pressed:
-If in recovery: submits the code
-If new registration, first input: proceeds to second input
-If new registration, second input: proceeds to next page
> Handling Next and Done keys in Backup Code Fragment

- app/src/org/commcare/fragments/CommCarePreferenceFragment.java
- app/src/org/commcare/preferences/AdvancedActionsPreferences.java
- app/src/org/commcare/preferences/AppManagerAdvancedPreferences.java
This PR hides/shows the Clear User Data preference of the AppManager according to the user session status. This also accounts for when the session status changes (see video below).
<video src="https://github.com/user-attachments/assets/714b86c6-7e44-4973-8a53-98d7635b59fa" width="300px" />
Ticket: https://dimagi.atlassian.net/browse/SAAS-16440
Tested locally.
> Make 'Clear user data' visibility depend on session status

- app/res/values-fr/strings.xml
- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values-ti/strings.xml
- app/res/values/strings.xml
- app/src/org/commcare/android/integrity/IntegrityTokenApiRequestHelper.kt
- app/src/org/commcare/android/integrity/IntegrityTokenViewModel.kt
- app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
https://dimagi.atlassian.net/browse/CI-115
Noticing a few [Firebase logs](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/fe3e2cba48b5449d7dcaa780c5e2c780) that implies that the integrity token provider is getting stale and we need to re-prepare in response for [this error](https://developer.android.com/google/play/integrity/reference/com/google/android/play/core/integrity/model/StandardIntegrityErrorCode#INTEGRITY_TOKEN_PROVIDER_INVALID)
Failure Logs: 
````
Non-fatal Exception: com.google.android.play.core.integrity.StandardIntegrityException: -19: Standard Integrity API error (-19): The StandardIntegrityTokenProvider is invalid (e.g. it is outdated).
Request a new integrity token provider by calling …
```
> Better error handling and retry mechanism for integrity token provider

- app/src/org/commcare/activities/LoginActivity.java
This PR enforces a restriction in CC mobile to block login attempts from Web users. With this change, Web users will now see a message as follows:
Web users are identified by their email address, so this change checks for the presence of an '@' symbol in the username. Access is allowed if the '@' symbol is not found, or it it's found and the username ends with the project space domain name.
Successfully tested locally.
> Restrict Web users from logging into CC mobile

- app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
https://dimagi.atlassian.net/browse/CCCT-1464
No user visible change
Added a method to retrieve the Firebase "user pseudo ID" when available (else empty string).
Calling the method in the PersonalID phone fragment and attaching result to start_configuration call.
PersonalID
> Send Firebase user ID to PersonalID

- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/connect/ConnectAppUtils.kt
https://dimagi.atlassian.net/browse/QA-7905
Fix encryption error when clicking on login with personal id
This issue was the login was checking that it was ConnectBasedLogin not the PersonalIdmanged login because appId and primedId both was null and it should not be the case if primedId is null it should be the PersonalId managed login  and earlier this check was there it was removed in refactoring
>  fix encryption sync error

- app/res/values-es/strings.xml
- app/res/values-fr/strings.xml
- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values-ti/strings.xml
- app/res/values/strings.xml
Facing bug with bellow stack trace
```
FATAL EXCEPTION: main
Process: org.commcare.dalvik.debug, PID: 28757
java.util.IllegalFormatConversionException: d != java.lang.String
at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4608)
at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:3123)
at java.util.Formatter$FormatSpecifier.print(Formatter.java:3078)
at java.util.Formatter.format(Formatter.java:2710)
at java.util.Formatter.format(Formatter.java:2640)
at java.lang.String.format(String.java:4068)
at android.content.res.Resources.getString(Resources.java:562)
at android.content.Context.getString(Context.java:730)
at org.commcare.utils.StringUtils.getStringRobust(StringUtils.java:26)
at org.commcare.activities.RecoveryActivity$1.deliverResult(RecoveryActivity …
```
> Reverted to accept string value in strings file of all languages

- app/res/values-es/strings.xml
- app/res/values-fr/strings.xml
- app/res/values-hi/strings.xml
- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values-ti/strings.xml
https://dimagi.atlassian.net/browse/QA-7924
https://dimagi.atlassian.net/browse/QA-7922
-Corrected translation of get start with personal id  string in other languages
> Translation changed for start registration string

- app/res/layout/fragment_connect_progress_delivery.xml
- app/res/menu/menu_connect.xml
- app/src/org/commcare/fragments/connect/ConnectDeliveryListFragment.java
- app/src/org/commcare/fragments/connect/ConnectLearningProgressFragment.java
[QA-7927](https://dimagi.atlassian.net/browse/QA-7927)
Fix-> put the visibility condition
https://dimagi.atlassian.net/browse/QA-7929
Fix-> there was no code for this put the appropiate code
[QA-7921](https://dimagi.atlassian.net/browse/QA-7921)
Fix_ called sync code which was not present earlier
[QA-7926](https://dimagi.atlassian.net/browse/QA-7926)
Fix-> There was a return statement in if else condition removed that in updateButtons function
> Pm beta bug fixes

- app/src/org/commcare/fragments/connect/ConnectDeliveryProgressDeliveryFragment.java
https://dimagi.atlassian.net/browse/QA-7923
> Solved progress display error while navigating from payment tab in delivery progress screen

- app/res/values-es/strings.xml
- app/res/values-fr/strings.xml
- app/res/values-hi/strings.xml
- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values/strings.xml
- app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
This is to check if the play store is not updated or missing 
Reference doc is here:https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability?utm_source=chatgpt.com
Not able to test this as 2 of my device is updated with the service
> Play store service check

- app/src/org/commcare/activities/DispatchActivity.java
- app/src/org/commcare/connect/ConnectAppUtils.kt
Fixes a recent breaking change to auto-login code
We pass a flag back to Dispatch when launching a Connect app indicating that the app was launched from Connect.
Dispatch then launches the LoginActivity, which should auto-login.
But Dispatch wasn't passing the IS_LAUNCH_FROM_CONNECT flag through from one intent to the other.
Connect
Tested manually to verify that auto-login works again
> Auto login fix for Connect apps

- app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
https://play.google.com/console/u/0/developers/5365112617688783256/app/4975059684389568433/pre-launch-report/details?tab=stability&artifactId=4860086507315319379&expandFirstIssue=true
fix this issue reported by play console
And repatidly showing location service dialog
> Pm beta fix mainline

- app/res/values-es/strings.xml
- app/res/values-fr/strings.xml
- app/res/values-hi/strings.xml
- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values/strings.xml
- app/src/org/commcare/adapters/ConnectProgressJobSummaryAdapter.java
Ticket -> https://dimagi.atlassian.net/browse/CCCT-844
Updated msg for all languages and updated color of progressbar to green when daily visits >= max daily limit
> Updated warning message and color of progress bar for user visit

- app/res/values-es/strings.xml
- app/res/values-fr/strings.xml
- app/res/values-hi/strings.xml
- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values/strings.xml
- app/src/org/commcare/fragments/personalId/PersonalIdPhoneFragment.java
- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
for these change in Beta release pointing to master 
related to this PR
https://github.com/dimagi/commcare-android/pull/3269/files
it has Play Store version checks 
and user property to analytics
All thisngs are QA verified just doing the back merge
> Beta release changes to master

- app/src/org/commcare/activities/DispatchActivity.java
Fixes a bug where once the user logs in to an app from the Connect menu and log out, they won't be prompted to unlock when trying to login to any app from the login page.
Consuming the intent that gets passed to DispatchActivity when launching an app from Connect.
We only want that flag to apply once, the next time Dispatch launches the LoginActivity.
On subsequent launches of LoginActivity after that, we don't want to indicate that it was launched from Connect.
Connect
Discovered this during local testing and tested the fix once applied.
This was introduced in a recent phase 4 PR and is not part of the latest released beta.
None
Test to run: Login to an app from the Connect menu, then logout. On the Login page, try to login into any installed app (both managed by PersonalID and not …
> Connect Login fix

- app/res/layout/nav_drawer_footer.xml
- app/res/layout/nav_drawer_header.xml
- app/res/values/styles.xml
- app/src/org/commcare/activities/CommCareSetupActivity.java
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/navdrawer/BaseDrawerActivity.kt
- app/src/org/commcare/navdrawer/NavDrawerAdapter.kt
Extending the nav_drawer to CommCareSetupActivity
figma :- https://www.figma.com/design/YDgUWZJ9DZPNA6XCZCyO8i/Sidebar-Nav--CCC-PID---DRAFT-?node-id=355-1143&t=u7BaGnGDsZdyxboM-0 
Tech Design :- https://docs.google.com/document/d/1UXgjCAB8H_33YDJTZ0QN9z5f3-WDdHeyWeMiGJlSPsE/edit?tab=t.azvmq4einwjp#heading=h.ipgou4bu0qoj
Show commcare app option when it is login activity
Show app version
Expanded view of commcare apps when there is less than 2 apps
change of arrow icon
Handle the commcare click
Replaced the close icon with the back icon in the actionbar and remoced close from inside the nav drawer
> Nav Drawer Enhacements

- app/build.gradle
- app/res/values/themes.xml
- commcare-support-library/build.gradle
This PR makes the necessary changes to ensure compatibility with Android 15. The changes were mainly to:
- Ensure that all native libraries used by CommCare support the 16KB page requirement - there are 3 libraries that required updates: SQLCipher, RootBeer and Kujaku. Kujaku doesn't have a suitable option so we decided to remove it from CommCare and kill all related feature;
- Edge-to-Edge mode handling for devices running Android 15 - we've decided to opt out for now and thoroughly test the related changed outside the scope of a release;
These changes will have to go through regression testing.
> Android 15 compatibility changes

- app/src/org/commcare/navdrawer/BaseDrawerActivity.kt
https://dimagi.atlassian.net/browse/QA-7982
Fix for [Crash](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/7bdcbc6f90552403fcf7f7446fbb2350)
````
Caused by java.lang.NullPointerException: rootView.findViewById(R.id.drawer_layout) must not be null
at org.commcare.navdrawer.DrawerViewRefs.<init>(DrawerViewRefs.kt:14)
at org.commcare.navdrawer.BaseDrawerActivity.setupDrawerController(BaseDrawerActivity.kt:33)
at org.commcare.navdrawer.BaseDrawerActivity.onCreate(BaseDrawerActivity.kt:17)
at org.commcare.activities.SessionAwareCommCareActivity.onCreate(SessionAwareCommCareActivity.java:20)
````
Not all activities have their view set when we were calling drawing init. I therefore decided to move drawer setup to `onResume` …
> Drawer Init NPE Fix

- app/res/layout/nav_drawer_sublist_item.xml
- app/src/org/commcare/activities/CommCareActivity.java
- app/src/org/commcare/activities/CommCareSetupActivity.java
- app/src/org/commcare/activities/DispatchActivity.java
- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/activities/StandardHomeActivity.java
- app/src/org/commcare/connect/ConnectConstants.java
- app/src/org/commcare/navdrawer/BaseDrawerActivity.kt
- app/src/org/commcare/navdrawer/BaseDrawerController.kt
- app/src/org/commcare/navdrawer/NavDrawerAdapter.kt
- app/src/org/commcare/navdrawer/NavDrawerParentItem.kt
https://dimagi.atlassian.net/browse/CCCT-1614
Showing the side navigation drawer in the App Home page when PersonalID is configured on the device.
Seated app highlighted in side nav menu on Login and App Home pages.
Navigating to Opportunities/Messages from App Home only requires unlock if it wasn't performed to access the current app.
PersonalID, Side Navigation Drawer
Dev tested
None
- Verify the side navigation drawer appears on App Home whenever PersonalID is configured (otherwise does not appear)
- Verify clicking Opportunities/Messages from App Home requires unlock when app was logged in via username/password
- Verify clicking Opportunities/Messages from App Home does not require unlock when app was logged in via PersonalID unlock (including access to Connect apps from opportunity …
> Side nav drawer in App Home page

- app/src/org/commcare/activities/LoginActivity.java
- app/src/org/commcare/navdrawer/NavDrawerHelper.kt
https://dimagi.atlassian.net/browse/CCCT-1615
Once the user is shown the sidenav drawer on the Login page, the app will never stop showing it (specifically if user forgets their PersonalID account on the device).
Added a SharedPreference to track once we start showing the sidenav drawer on Login page
Checking for the new pref to automatically show the drawer.
Setting the pre the first time the drawer is shown.
PersonalID, side navigation drawer
Simple change, easy to test.
Nonce
- Verify that the sidenav drawer is not enabled on Login before configuring PersonalID
- Verify that the sidenav drawer is enabled on Login after configuring PersonalID
- Verify that the sidenav drawer is still enabled on Login after forgetting PersonalID
- Restart app after forgetting PersonalID and verify again
> Keep showing sidenav drawer on Login once shown

- app/src/org/commcare/views/widgets/WidgetUtils.java
Android 15 brought new restrictions around implicit intents, requiring now an exact match with the component's manifest filters. This PR adds the DEFAULT category to the scan intent, allowing it to resolve correctly to more scanner apps. 
Ticket: https://dimagi.atlassian.net/browse/QA-7995
Successfully tested locally.
QA will test this as part of the regression testing for `2.59`.
> Fix intent callout for scanner

- app/unit-tests/src/org/commcare/android/tests/caselist/EntityListCalloutDataTest.java
This PR fixes two unit tests failing with the following error:
```
logger> resources: Tearing down sandbox: 82716c8a55944bae99331152b39b2330
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.base/java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
at java.base/java.util.concurrent.FutureTask.setException(FutureTask.java:250)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: WorkManager is …
```
> Fix EntityListCalloutDataTest unit tests

- app/AndroidManifest.xml
Manually bumping app version to 2.60 after 2.59 release (I think a script was supposed to do this?)
> Changed app version to 2.60 in manifest

- app/src/org/commcare/activities/StandardHomeActivity.java
- app/src/org/commcare/activities/StandardHomeActivityUIController.java
- app/src/org/commcare/navdrawer/BaseDrawerActivity.kt
https://dimagi.atlassian.net/browse/CCCT-1632
Whenever user trying to login into learning / delivery app, StandardHomeActivity was processing the sessions related stuff and than was adding the activity's view from home_screen.xml. BaseDrawerActivity is trying to add the drawer before root view of this activity is created. Now, with fix, after the root view is created from home_screen.xml, drawer is added to the root view.
> Solved crash while showing drawer in delivery / learning app

- app/src/org/commcare/google/services/analytics/CCAnalyticsParam.java
- app/src/org/commcare/google/services/analytics/CCPerfMonitoring.kt
- app/src/org/commcare/tasks/EntityLoaderHelper.kt
- app/src/org/commcare/tasks/EntityLoaderTask.java
This PR implements a performance custom trace for synchronous case list loading. This is part of an effort to collect performance data related key events in CommCare.
Ticket: https://dimagi.atlassian.net/browse/SAAS-18089
This is supposed to be a lightweight, null-safe operation that has no impact on the user experience.
> Add perf monitoring trace for case list loading time

- app/src/org/commcare/connect/workers/ConnectHeartbeatWorker.kt
https://dimagi.atlassian.net/browse/CCCT-1657
If `isloggedIn()` is false, we were immediately calling `continuation.resume(Result.failure())` without exiting the code which in turn call heartbeatRequest, and will eventually invoke onSuccess or onFailure resulting into another call to `continuation.resume` and hence the exception `java.lang.IllegalStateException: Already resumed`
> fix issue with connect hearbeat due to incorrect sequencing

- app/src/org/commcare/fragments/connect/ConnectJobsListsFragment.java
Application was failing to load the opportunities from local DB incase of internet issue. Now, it will load from local DB
https://dimagi.atlassian.net/browse/CI-132
> Shown opportunities from local DB in case internet connectivity issue

- app/src/org/commcare/android/resource/installers/FileSystemInstaller.java
- app/unit-tests/src/org/commcare/android/tests/application/AppUpdateTest.kt
- app/unit-tests/src/org/commcare/update/UpdateWorkerTest.kt
Potential Fix for https://dimagi.atlassian.net/browse/CCCT-1595
[Crashlytics](https://console.firebase.google.com/u/0/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/2e54aefeb20fd192ea86ee2a42f5324d?time=last-ninety-days&sessionEventKey=6891DC700155000161FCDC7344BCFF82_2113493200062635819&sessionTab=data&userInfoQuery=IO7T02HPCDQFBPQTMDJO)
My theory is that somehow device ends up in a state where the `temp` file directory is no longer there and results in the crash below.  This PR makes sure that temp file path is created on the device before accessing it. 
````
Non-fatal Exception: org.commcare.engine.resource.installers.LocalStorageUnavailableException: Couldn't create temp file for file system installation
at …
```
> fix FNF by ensuring the parent folder exists

- app/res/menu/menu_connect.xml
- app/res/values-es/strings.xml
- app/res/values-fr/strings.xml
- app/res/values-hi/strings.xml
- app/res/values-pt/strings.xml
- app/res/values-sw/strings.xml
- app/res/values-ti/strings.xml
- app/res/values/strings.xml
- app/src/org/commcare/activities/connect/ConnectActivity.java
- app/src/org/commcare/connect/ConnectNavHelper.kt
- app/src/org/commcare/navdrawer/BaseDrawerActivity.kt
- app/src/org/commcare/navdrawer/BaseDrawerController.kt
- app/src/org/commcare/personalId/PersonalIdFeatureFlagChecker.kt
https://dimagi.atlassian.net/browse/CCCT-1660
> Adds Credential in Left Side Drawer

- app/src/org/commcare/connect/PersonalIdManager.java
- app/src/org/commcare/connect/database/ConnectDatabaseHelper.java
- app/src/org/commcare/connect/database/ConnectDatabaseUtils.java
- app/src/org/commcare/models/database/app/DatabaseAppOpenHelper.java
- app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
- app/src/org/commcare/models/database/global/DatabaseGlobalOpenHelper.java
- app/src/org/commcare/models/database/user/DatabaseUserOpenHelper.java
- app/src/org/commcare/utils/GlobalErrors.java
No visible user changes
Removed ambiguous logging about not finding DB passphrase (often false-alarms)
Removed redundant non-fatal exceptions just before DB crashes (which cause fatal exceptions)
Added a new check and crash to prevent unencrypted Connect DB
Added non-fatal exception when error encountered opening any DB (before trySqlCipherDbUpdate)
Improved exception logging when crashing Connect DB to indicate source
PersonalID
Should be no noticeable changes to user, but simply reduced/improved logging when errors occur.
The new crash before opening an unencrypted DB is the biggest risk and could cause users to crash on upgrade.
If so, they would simply be prompted to reconfigure PersonalID when restarting the app.
None
Basic regression testing around PersonalID configuration and …
> Improved Connect DB error handling

- app/res/layout/fragment_recovery_code.xml
- app/src/org/commcare/fragments/personalId/PersonalIdBackupCodeFragment.java
https://dimagi.atlassian.net/browse/CCCT-1731
Release/QA Note: Remove "This is Not me" button from Personal ID sign up flow
> Hide "this is not me" Button

- app/res/values/strings.xml
- app/src/org/commcare/android/database/global/models/ConnectKeyRecord.java
- app/src/org/commcare/connect/PersonalIdManager.java
- app/src/org/commcare/connect/database/ConnectDatabaseHelper.java
- app/src/org/commcare/connect/database/ConnectDatabaseUtils.java
- app/src/org/commcare/connect/network/ApiPersonalId.java
- app/src/org/commcare/google/services/analytics/CCAnalyticsEvent.java
- app/src/org/commcare/google/services/analytics/FirebaseAnalyticsUtil.java
- app/src/org/commcare/models/database/connect/DatabaseConnectOpenHelper.java
https://dimagi.atlassian.net/browse/CCCT-1574
No user-facing changes
This PR cleans up the migration code that was introduced earlier this year when we changed the Connect DB to start using a passphrase managed by PersonalID for encryption, instead of a locally-generated passphrase.
Brief description of the migration flow:
-Added an isLocal flag to ConnectKeyRecord
-All existing passphrases became "local" passphrases (isLocal=true) during the upgrade
-At app startup, we would issue a special API call if we detected the user didn't have the remote passphrase yet (isLocal=false)
-Once the remote passphrase was received, we would:
-Store it as remote
-Rekey the database if necessary (local != remote)
-Store it as local
One additional caveat:
During the change described above we realized …
> Cleaned up local DB passphrase code

- app/src/org/commcare/utils/FirebaseMessagingUtil.java
Additional logs to investigate if fcm tokens are getting set to empty.
> Improved logging on fcm token nullability

- app/AndroidManifest.xml
https://dimagi.atlassian.net/browse/CI-197
https://dimagi.atlassian.net/browse/CCCT-1659
All Connect screens will only be shown in portrait mode.
Simple change to manifest, to avoid state issues when the screen downloads.
This was causing a crash when downloading a learn/deliver app if the user rotated the screen.
The job being passed via the intent got lost, and the ConnectJobFragment would crash.
This error could technically happen with any job-depended fragment.
Connect
Easy to test, screen no longer adjusts to landscape when rotated.
None
Verify the device will not display any Connect pages in landscape mode.
> Locking ConnectActivity to portrait screen orientation

- app/src/org/commcare/google/services/analytics/CCPerfMonitoring.kt
- app/src/org/commcare/tasks/FormLoaderTask.java
This PR implements a performance custom trace to measure form loading times. This is part of an effort to collect performance data related key events in CommCare.
Ticket: https://dimagi.atlassian.net/browse/SAAS-18091
This is supposed to be a lightweight, null-safe operation that has no impact on the user experience.
> Add perf monitoring trace for form loading time

- app/src/org/commcare/activities/connect/ConnectActivity.java
https://dimagi.atlassian.net/browse/QA-8141
[crash](https://console.firebase.google.com/u/1/project/commcare-a57e4/crashlytics/app/android:org.commcare.dalvik/issues/2453761d848f4bb7f52a49ae1554ea26?time=60m&sessionEventKey=68E4E50E033C000132D6FCAEBF1E4D76_2136864156345115017)
We were using incorrect data type for opportunity id which was resulting in the job to be set as null for `connectActivity` 
[This is where](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/connect/ConnectNavHelper.kt#L76) we add opportunity id to the extras as Integer
> Fixes crash on clicking View Job Status
